function Cutscene(owner)
  cutscenes = owner
  SetInvulnerable(flag.TYPE_WFRONTIER, 1)
  StartIntro()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam1Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam1Spline)
  WaitFor(1)
  PhoneMessage(0, 0, 0, 6, SpriteID.CO_WF_Herman_Happy)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.2)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam2Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam2Spline)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.2)
  PhoneMessage(1, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(6, 0, 0, 3, SpriteID.CO_WF_Herman_Happy)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.2)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam3Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam3Spline)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.2)
  PhoneMessage(2, 0, 0, 8, SpriteID.CO_WF_Herman_Happy)
  WaitFor(3)
  Teleport(Ground_Vehicle.WFHeavyTank1, 206, -284, 0, 2)
  Teleport(Ground_Vehicle.WFHeavyTank2, 207, -297, 0, 2)
  Teleport(Ground_Vehicle.WFHeavyTank3, 221, -287, 45, 2)
  GoToArea(Ground_Vehicle.WFHeavyTank3, 191, -92, 5)
  WaitFor(1)
  GoToArea(Ground_Vehicle.WFHeavyTank1, 180, -51, 5)
  GoToArea(Ground_Vehicle.WFHeavyTank2, 180, -51, 5)
  tanksonbridge = 1
  WaitFor(4)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.2)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam4Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam4Spline)
  CameraSetFOV(Camera.Cam1, 70, constant.IMMEDIATE, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.2)
  PhoneMessage(26, 0, 0, 9.5, SpriteID.CO_WF_Herman_Sad)
  WaitFor(3.5)
  CameraSetFOV(Camera.Cam1, 90, constant.SMOOTH, 40, constant.NO_WAIT)
  WaitFor(3)
  Kill(Destroyable_Object.EastBridge1ExplosiveCentre)
  Kill(Destroyable_Object.EastBridge1Piece3)
  Kill(Destroyable_Object.EastBridge1Piece4)
  Teleport(Ground_Vehicle.WFHeavyTank1, 10, -355, 0, 2)
  Teleport(Ground_Vehicle.WFHeavyTank2, 23, -355, 0, 2)
  Teleport(Ground_Vehicle.WFHeavyTank3, 2, -367, 0, 2)
  StopAndGuard(Ground_Vehicle.WFHeavyTank1)
  StopAndGuard(Ground_Vehicle.WFHeavyTank2)
  StopAndGuard(Ground_Vehicle.WFHeavyTank3)
  tanksonbridge = 0
  WaitFor(0.7)
  Kill(Destroyable_Object.EastBridge1ExplosiveStart)
  Kill(Destroyable_Object.EastBridge1ExplosiveEnd)
  Kill(Destroyable_Object.EastBridge1Piece2)
  Kill(Destroyable_Object.EastBridge1Piece5)
  WaitFor(0.7)
  Kill(Destroyable_Object.EastBridge1Piece1)
  Kill(Destroyable_Object.EastBridge1Piece6)
  WaitFor(1.6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.2)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam5Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam5Spline)
  CameraSetFOV(Camera.Cam1, 45, constant.IMMEDIATE, 15, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.2)
  PhoneMessage(27, 0, 0, 6, SpriteID.CO_WF_Herman_Happy)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.2)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam6Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam6Spline)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.2)
  PhoneMessage(25, 0, 0, 9, SpriteID.CO_WF_Herman_Happy)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscene = 1
end
