function Gambit_Part_1_Cutscene_INTRO_Skip(owner)
  WaitFor(1)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO)) then
      DebugOut("Killed cutscene", cutsceneStart)
      if cutsceneStart > 0 then
        Kill(cutsceneStart)
      end
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      EndIntro()
      StoreSummaryMessage(constant.PLAYER_ONE, 1, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 2, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 3, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 5, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
      FollowWaypoint(Ground_Vehicle.ILtank03, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
      FollowWaypoint(Ground_Vehicle.ILtank02, Waypoint.Entity550035569, 5, 5, constant.ORDER_FORCED)
      FollowWaypoint(Troop.Entity550035617, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
      FollowWaypoint(Troop.Entity550035618, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
      FollowWaypoint(Troop.Entity550035619, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
      Despawn(Troop.Sstrikebazooka01, false)
      Despawn(Troop.Sstrikebazooka02, false)
      Despawn(Troop.Sstrikebazooka03, false)
      Despawn(Troop.Sstrikehose01, false)
      Despawn(Troop.Sstrikehose02, false)
      Despawn(Troop.Sstrikemissile01, false)
      Despawn(Troop.Sstrikemissile02, false)
      Despawn(Ground_Vehicle.SEtankbattle01, false)
      Despawn(Ground_Vehicle.ILtankCutscene01)
      Despawn(Ground_Vehicle.ILtankCutscene02)
      Despawn(Ground_Vehicle.ILtankCutscene03)
      Despawn(Troop.ILgrunt01)
      Despawn(Troop.ILgrunt02)
      Despawn(Troop.ILgrunt03)
      Despawn(Troop.ILgrunt14)
      Despawn(Troop.ILgrunt15)
      Despawn(Troop.ILgrunt16)
      Despawn(Troop.ILbazooka03)
      Despawn(Troop.ILbazooka04)
      Despawn(Troop.Entity550035617)
      Despawn(Troop.Entity550035618)
      Despawn(Troop.Entity550035619)
      Despawn(Ground_Vehicle.ILtank01)
      Despawn(Ground_Vehicle.ILtank02)
      Despawn(Ground_Vehicle.ILtank03)
      Despawn(Ground_Vehicle.ILbattlestation02)
      Spawn(Air_Vehicle.ILbomberSTART01)
      Spawn(Air_Vehicle.ILbomberSTART02)
      Spawn(Air_Vehicle.ILbomberSTART03)
      Spawn(Air_Vehicle.ILbomberSTART04)
      SetObjectiveData(Objective_Marker.StaffBearer01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      SetCamera(Camera.Player0001, constant.PLAYER_ONE)
      ForceUnitTransfer(constant.PLAYER_ONE, Troop.Sgrunt01, true, true)
      Spawn(Troop.Sstaffbearer02)
      Despawn(Troop.Sstaffbearer03)
      WaitFor(0.5)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      cutsceneStart = 1
      WaitFor(0.5)
      UnfreezePlayer(constant.PLAYER_ONE)
      ResetCommandBar()
      StartScoringTimer()
    end
    EndFrame()
  until cutsceneStart == 1
end
