function Gambit_Part_1_Cutscene_INTRO(owner)
  cutsceneStart = owner
  DebugOut("Cutscene Start ID", cutsceneStart)
  SetActive(Ground_Vehicle.ILtank01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILtank02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILtank03, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILbattlestation02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.Sstaffbearer03, constant.INACTIVE, constant.DONT_ADJUST_WEAPON)
  Despawn(Troop.Sstaffbearer02)
  Despawn(Ground_Vehicle.ILtankCutscene01)
  Despawn(Ground_Vehicle.ILtankCutscene02)
  Despawn(Ground_Vehicle.ILtankCutscene03)
  StartIntro()
  FreezePlayer(constant.PLAYER_ONE)
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.Sstaffbearer03, true, true)
  SetCamera(Camera.Cutscene0002, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene0002, Waypoint.Cutscene0002)
  CameraSetTarget(Camera.Cutscene0002, Waypoint.Cutscene0002Target)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0003, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene0003, Waypoint.Cutscene0003)
  CameraSetTarget(Camera.Cutscene0003, Waypoint.Cutscene0003Target)
  CameraSetFOV(Camera.Cutscene0003, 70, constant.SMOOTH, 2, constant.NO_WAIT)
  SetUnitInvulnerable(Troop.Sstrikebazooka02, true)
  FollowWaypoint(Troop.Sstrikebazooka01, Waypoint.WP01, 15, 15, constant.ORDER_FORCED)
  FollowWaypoint(Troop.Sstrikebazooka03, Waypoint.WP01b, 15, 15, constant.ORDER_FORCED)
  Spawn(Ground_Vehicle.ILtankCutscene01)
  Spawn(Ground_Vehicle.ILtankCutscene02)
  Spawn(Ground_Vehicle.ILtankCutscene03)
  SetUnitInvulnerable(Ground_Vehicle.ILtankCutscene01, true)
  SetUnitInvulnerable(Ground_Vehicle.ILtankCutscene02, true)
  SetUnitInvulnerable(Ground_Vehicle.ILtankCutscene03, true)
  FollowWaypoint(Ground_Vehicle.ILtankCutscene01, Waypoint.Entity550041006, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Ground_Vehicle.ILtankCutscene02, Waypoint.Entity550041015, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Ground_Vehicle.ILtankCutscene03, Waypoint.Entity550041012, 0, 0, constant.ORDER_FORCED)
  SetHealthPercent(Troop.Sstrikebazooka01, 5)
  SetHealthPercent(Troop.Sstrikebazooka03, 15)
  SetHealthPercent(Troop.Sstrikebazooka04, 15)
  SetHealthPercent(Troop.Sstrikebazooka05, 15)
  SetHealthPercent(Troop.Sstrikehose01, 15)
  SetHealthPercent(Troop.Sstrikehose02, 15)
  SetHealthPercent(Troop.Sstrikemissile01, 15)
  SetHealthPercent(Troop.Sstrikemissile02, 15)
  SetHealthPercent(Ground_Vehicle.SEtankbattle01, 15)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  WaitFor(0.5)
  FollowWaypoint(Troop.Sstrikebazooka02, Waypoint.WP01c, 15, 15, constant.ORDER_FORCED)
  WaitFor(0.5)
  Kill(Building.AmmoDump21)
  FollowWaypoint(Troop.Sstrikemissile01, Waypoint.WP02, 5, 5, constant.ORDER_FORCED)
  WaitFor(1)
  GoToArea(Ground_Vehicle.SEtankbattle01, 38, 78, 5, 0, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  FollowWaypoint(Troop.Sstrikehose01, Waypoint.WP03, 5, 5, constant.ORDER_FORCED)
  WaitFor(0.25)
  Kill(Building.AmmoDump10)
  FollowWaypoint(Troop.Sstrikehose02, Waypoint.WP03b, 5, 5, constant.ORDER_FORCED)
  WaitFor(0.5)
  FollowWaypoint(Troop.Sstrikemissile02, Waypoint.WP02b, 5, 5, constant.ORDER_FORCED)
  WaitFor(0.25)
  FollowWaypoint(Troop.Sstaffbearer01, Waypoint.WP04, 5, 5, constant.ORDER_FORCED)
  WaitFor(2)
  Kill(Building.AmmoDump23)
  WaitFor(2)
  Kill(Building.AmmoDump22)
  WaitFor(1)
  Kill(Building.AmmoDump11)
  SetUnitInvulnerable(Troop.Sstrikebazooka02, false)
  SetHealthPercent(Troop.Sstrikebazooka02, 20)
  WaitFor(0.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.Sstrikebazooka01, false)
  Despawn(Troop.Sstrikebazooka02, false)
  Despawn(Troop.Sstrikebazooka03, false)
  Despawn(Troop.Sstrikehose01, false)
  Despawn(Troop.Sstrikehose02, false)
  Despawn(Troop.Sstrikemissile01, false)
  Despawn(Troop.Sstrikemissile02, false)
  Despawn(Ground_Vehicle.SEtankbattle01, false)
  Despawn(Ground_Vehicle.ILtankCutscene01)
  Despawn(Ground_Vehicle.ILtankCutscene02)
  Despawn(Ground_Vehicle.ILtankCutscene03)
  SetCamera(Camera.Cutscene0004, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene0004, Waypoint.Cutscene0004)
  CameraSetTarget(Camera.Cutscene0004, Waypoint.Cutscene0004Target)
  CameraSetFOV(Camera.Cutscene0004, 70, constant.IMMEDIATE, 10, constant.NO_WAIT)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  CameraSetFOV(Camera.Cutscene0004, 45, constant.SMOOTH, 4, constant.NO_WAIT)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0006, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene0006, Waypoint.Cutscene0006)
  CameraSetTarget(Camera.Cutscene0006, Waypoint.Cutscene0006Target)
  FollowWaypoint(Ground_Vehicle.ILtank03, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.Entity550035617, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.Entity550035618, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.Entity550035619, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt01, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt02, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt03, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt14, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt15, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILgrunt16, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILbazooka03, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Troop.ILbazooka04, Waypoint.Entity550035565, 5, 5, constant.ORDER_FORCED)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(5, constant.ID_NONE, constant.ARMY_UNDERWORLD, 8, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  FollowWaypoint(Ground_Vehicle.ILbattlestation02, Waypoint.Entity550040160, 5, 5, constant.ORDER_FORCED)
  FollowWaypoint(Ground_Vehicle.ILtank02, Waypoint.Entity550035569, 5, 5, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  EndIntro()
  SetCamera(Camera.Player0001, constant.PLAYER_ONE)
  ClearMessageQueue(constant.PLAYER_ONE)
  Despawn(Troop.ILgrunt01)
  Despawn(Troop.ILgrunt02)
  Despawn(Troop.ILgrunt03)
  Despawn(Troop.ILgrunt14)
  Despawn(Troop.ILgrunt15)
  Despawn(Troop.ILgrunt16)
  Despawn(Troop.ILbazooka03)
  Despawn(Troop.ILbazooka04)
  Despawn(Troop.Entity550035617)
  Despawn(Troop.Entity550035618)
  Despawn(Troop.Entity550035619)
  Despawn(Ground_Vehicle.ILtank01)
  Despawn(Ground_Vehicle.ILtank02)
  Despawn(Ground_Vehicle.ILtank03)
  Despawn(Ground_Vehicle.ILbattlestation02)
  Spawn(Air_Vehicle.ILbomberSTART01)
  Spawn(Air_Vehicle.ILbomberSTART02)
  Spawn(Air_Vehicle.ILbomberSTART03)
  Spawn(Air_Vehicle.ILbomberSTART04)
  SetObjectiveData(Objective_Marker.StaffBearer01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.Sgrunt01, true, true)
  Spawn(Troop.Sstaffbearer02)
  Despawn(Troop.Sstaffbearer03)
  WaitFor(0.5)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  cutsceneStart = 1
  StartScoringTimer()
  WaitFor(0.5)
  UnfreezePlayer(constant.PLAYER_ONE)
  ResetCommandBar()
  EndFrame()
  return
end
