function Gambit_Part_1_Cutscene_MidGame_2_Infantry(owner)
  cutsceneMidGameInfantry = owner
  DebugOut("Cutscene Mid Game Infantry = ", cutsceneMidGameInfantry)
  while true do
    if cutsceneMidGameInfantryBegin == 1 then
      cutsceneMidGameInfantryBegin = 2
      StartIntro()
      FreezePlayer(constant.PLAYER_ONE)
      PauseTimerActive = 1
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Teleport(Ground_Vehicle.SEtankbattle01, 15, 230, 75, 0)
      StopAndGuard(Troop.Sstrikehose01)
      Teleport(Troop.Sstrikehose01, 12, 235, 0, 0)
      StopAndGuard(Troop.Sstrikehose01)
      GoToArea(Troop.Sstrikehose01, 12, 235, 0, 0, constant.ORDER_NORMAL)
      StopAndGuard(Troop.Sstrikehose02)
      Teleport(Troop.Sstrikehose02, 20, 225, 0, 0)
      StopAndGuard(Troop.Sstrikehose02)
      GoToArea(Troop.Sstrikehose02, 20, 225, 0, 0, constant.ORDER_NORMAL)
      Spawn(Troop.ILbazooka01)
      Spawn(Troop.ILbazooka02)
      Spawn(Troop.ILgrunt07)
      Spawn(Troop.ILgrunt08)
      AttackTarget(Troop.Sstrikehose02, Troop.ILbazooka01, constant.ORDER_FORCED)
      AttackTarget(Troop.Sstrikehose01, Troop.ILbazooka02, constant.ORDER_FORCED)
      FollowWaypoint(Troop.ILbazooka01, Waypoint.ILbazooka01, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Troop.ILbazooka02, Waypoint.ILbazooka02, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Troop.ILgrunt07, Waypoint.ILbazooka01, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Troop.ILgrunt08, Waypoint.ILbazooka02, 5, 5, constant.ORDER_NORMAL)
      SetCamera(Camera.CutsceneMidGame0001, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneMidGame0001, Waypoint.cutsceneMidGameInfantry0001)
      CameraSetTarget(Camera.CutsceneMidGame0001, Waypoint.cutsceneMidGameInfantry0001Target)
      GoToArea(Ground_Vehicle.SEtankbattle01, 50, 330, 10, 0, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(30, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Sad, constant.PLAYER_ONE)
      WaitFor(2)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetCamera(Camera.Player0001, constant.PLAYER_ONE)
      EndIntro()
      AttackTarget(Troop.ILbazooka01, Troop.Sstrikehose02, constant.ORDER_FORCED)
      AttackTarget(Troop.ILbazooka02, Troop.Sstrikehose01, constant.ORDER_FORCED)
      AttackTarget(Troop.ILgrunt07, Troop.Sstrikehose01, constant.ORDER_FORCED)
      AttackTarget(Troop.ILgrunt08, Troop.Sstrikehose02, constant.ORDER_FORCED)
      ClearMessageQueue(constant.PLAYER_ONE)
      PhoneMessage(31, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
      PhoneMessage(39, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      WaitFor(1)
      UnfreezePlayer(constant.PLAYER_ONE)
      PauseTimerActive = 0
      SetObjectiveData(Objective.Trench02, constant.OBJECTIVE_DATA_VISIBLE, 0)
      SetObjectiveData(Objective_Marker.Trench02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      SetObjectiveData(Objective.Trench07, constant.OBJECTIVE_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.Trench07, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
    end
    EndFrame()
  end
end
