function Gambit_Part_1_Cutscene_Bombed(owner)
  cutsceneBombed = owner
  DebugOut("Cutscene Bombed = ", cutsceneBombed)
  Despawn(Building.DeadStaffGuy)
  repeat
    EndFrame()
  until cutsceneStart == 1
  Kill(Destroyable_Object.SolarTent01)
  while true do
    if cutsceneBombedBegin == 1 then
      FreezePlayer(constant.PLAYER_ONE)
      SetUnitInvulnerable(GetPlayerUnit(), true)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      StartIntro()
      SetObjectiveData(Objective.SquadJoin01, constant.OBJECTIVE_DATA_STATE, 1)
      SetObjectiveData(Objective.SquadJoin01, constant.OBJECTIVE_DATA_VISIBLE, 0)
      Despawn(Air_Vehicle.ILbomberSTART01)
      Despawn(Air_Vehicle.ILbomberSTART02)
      Despawn(Air_Vehicle.ILbomberSTART03)
      Despawn(Air_Vehicle.ILbomberSTART04)
      Spawn(Air_Vehicle.ILbomber01)
      SetUnitInvulnerable(Air_Vehicle.ILbomber01, true)
      WaitFor(1)
      Teleport(Air_Vehicle.ILbomber01, 18, 151.8, 158.2, 0)
      AttackTarget(Air_Vehicle.ILbomber01, Building.AmmoDump07, constant.ORDER_FORCED)
      SetCamera(Camera.CutsceneMidGame0001, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneMidGame0001, Waypoint.cutsceneBombed0001)
      CameraSetTarget(Camera.CutsceneMidGame0001, Waypoint.cutsceneBombed0001Target)
      CameraSetFOV(Camera.CutsceneMidGame0001, 50, constant.IMMEDIATE, 10, constant.NO_WAIT)
      CameraSetFOV(Camera.CutsceneMidGame0001, 70, constant.SMOOTH, 3, constant.NO_WAIT)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(14, constant.ID_NONE, constant.ARMY_UNDERWORLD, 8, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
      WaitFor(4)
      AttackTarget(Troop.Entity550035415, Air_Vehicle.ILbomber01, constant.ORDER_FORCED)
      AttackTarget(Troop.Entity550035416, Air_Vehicle.ILbomber01, constant.ORDER_FORCED)
      WaitFor(5)
      Kill(Troop.Sstaffbearer02)
      Kill(Troop.Sgruntsquad01)
      Kill(Troop.Sgruntsquad02)
      Kill(Troop.Entity550035413)
      Kill(Building.AmmoDump06)
      Kill(Building.AmmoDump08)
      WaitFor(0.75)
      SetHealthPercent(Ground_Vehicle.SEtankbattle02, 5)
      Kill(Building.AmmoDump07)
      Kill(Troop.Sgruntsquad03)
      Kill(Troop.Sgruntsquad04)
      Kill(Troop.Entity550035414)
      WaitFor(0.75)
      Kill(Building.AmmoDump09)
      Kill(Troop.Entity550035415)
      Kill(Troop.Entity550035416)
      Kill(Ground_Vehicle.SEtankbattle02)
      WaitFor(0.5)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Despawn(Troop.Sstaffbearer02)
      Teleport(GetPlayerUnit(), GetObjectXPosition(GetPlayerUnit()), GetObjectZPosition(GetPlayerUnit()), 0, 0)
      SetCamera(Camera.CutsceneMidGame0001, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneMidGame0001, Waypoint.cutsceneBombed0002)
      CameraSetTarget(Camera.CutsceneMidGame0001, Waypoint.cutsceneBombed0002aTarget)
      CameraSetFOV(Camera.CutsceneMidGame0001, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
      Spawn(Building.DeadStaffGuy)
      Spawn(Building.StaffOfPower)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(13, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Sad, constant.PLAYER_ONE)
      WaitFor(2)
      Kill(Building.DeadStaffGuy)
      repeat
        EndFrame()
      until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetCamera(Camera.Player0001, constant.PLAYER_ONE)
      cutsceneBombedBegin = 2
      EndIntro()
      SetObjectiveData(Objective.PickupStaff, constant.OBJECTIVE_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.PickupStaff, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessageWithObjective(19, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
      WaitFor(0.5)
      UnfreezePlayer(constant.PLAYER_ONE)
      SetUnitInvulnerable(GetPlayerUnit(), false)
    end
    EndFrame()
  end
end
