function Gambit_Part_1_Cutscene_Bombed_Skip(owner)
  repeat
    EndFrame()
  until cutsceneBombedBegin == 1
  WaitFor(2)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO)) then
      DebugOut("Killed cutscene", cutsceneBombed)
      Kill(cutsceneBombed)
      SetUnitInvulnerable(GetPlayerUnit(), true)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Spawn(Building.DeadStaffGuy)
      Teleport(GetPlayerUnit(), GetObjectXPosition(GetPlayerUnit()), GetObjectZPosition(GetPlayerUnit()), 0, 0)
      SetCamera(Camera.Player0001, constant.PLAYER_ONE)
      WaitFor(0.5)
      Kill(Building.DeadStaffGuy)
      Despawn(Air_Vehicle.ILbomberSTART01)
      Despawn(Air_Vehicle.ILbomberSTART02)
      Despawn(Air_Vehicle.ILbomberSTART03)
      Despawn(Air_Vehicle.ILbomberSTART04)
      Spawn(Air_Vehicle.ILbomber01)
      SetUnitInvulnerable(Air_Vehicle.ILbomber01, true)
      StoreSummaryMessage(constant.PLAYER_ONE, 14, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 13, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      GoToArea(Air_Vehicle.ILbomber01, 1000, -100, 25, 0, constant.ORDER_FORCED)
      SetActive(Air_Vehicle.ILbomber01, constant.INACTIVE, constant.DONT_ADJUST_WEAPON)
      Kill(Troop.Sstaffbearer02)
      Kill(Troop.Sgruntsquad01)
      Kill(Troop.Sgruntsquad02)
      Kill(Troop.Entity550035413)
      Kill(Troop.Sgruntsquad03)
      Kill(Troop.Sgruntsquad04)
      Kill(Troop.Entity550035414)
      Kill(Troop.Entity550035415)
      Kill(Troop.Entity550035416)
      Kill(Ground_Vehicle.SEtankbattle02)
      Despawn(Building.AmmoDump06)
      Despawn(Building.AmmoDump08)
      Despawn(Building.AmmoDump09)
      WaitFor(0.5)
      Despawn(Troop.Sstaffbearer02)
      Spawn(Building.StaffOfPower)
      EndIntro()
      SetObjectiveData(Objective.SquadJoin01, constant.OBJECTIVE_DATA_STATE, 1)
      SetObjectiveData(Objective.SquadJoin01, constant.OBJECTIVE_DATA_VISIBLE, 0)
      SetObjectiveData(Objective.PickupStaff, constant.OBJECTIVE_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.PickupStaff, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessageWithObjective(19, constant.ID_NONE, constant.ARMY_SOLAR, 8, SpriteID.CO_SE_Leiqo_Helmet_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
      WaitFor(0.5)
      UnfreezePlayer(constant.PLAYER_ONE)
      SetUnitInvulnerable(GetPlayerUnit(), false)
      PauseTimerActive = 0
      cutsceneBombedBegin = 2
    end
    EndFrame()
  until cutsceneBombedBegin == 2
end
