function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.CutsceneCam1)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.cutscene2SEtarget)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.cutscene2SE)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, constant.WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(1, constant.ID_NONE, CO01_DialogBoxColour, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    PhoneMessage(3, constant.ID_NONE, CO01_DialogBoxColour, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(9)
    ReviveDeadUnit(Troop.CutsceneSolarTroop1, 387, 12, 270, 10)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop2, 385, 8, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop1, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop3, 391, 10, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop2, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop4, 391, 13, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop3, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop5, 385, 14, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop4, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop6, 383, 6, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop5, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop7, 386, 4, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop6, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop8, 391, 5, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop7, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop9, 388, 8, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop8, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop10, 389, 12, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop9, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop11, 393, 10, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop10, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneSolarTroop12, 384, 9, 270, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop11, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    FollowWaypoint(Troop.CutsceneSolarTroop12, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(2)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  end
  Despawn(Troop.CutsceneSolarTroop1)
  Despawn(Troop.CutsceneSolarTroop2)
  Despawn(Troop.CutsceneSolarTroop3)
  Despawn(Troop.CutsceneSolarTroop4)
  Despawn(Troop.CutsceneSolarTroop5)
  Despawn(Troop.CutsceneSolarTroop6)
  Despawn(Troop.CutsceneSolarTroop7)
  Despawn(Troop.CutsceneSolarTroop8)
  Despawn(Troop.CutsceneSolarTroop9)
  Despawn(Troop.CutsceneSolarTroop10)
  Despawn(Troop.CutsceneSolarTroop11)
  Despawn(Troop.CutsceneSolarTroop12)
  Spawn(Troop.SEAntiAir1)
  Spawn(Troop.SEGrunt1)
  Spawn(Troop.SEGrunt2)
  Spawn(Troop.SEGrunt3)
  Spawn(Troop.SEGrunt4)
  Spawn(Troop.SE_Player)
  Spawn(Troop.SEHose1)
  Spawn(Troop.SEHose2)
  Spawn(Troop.SEBazooka1)
  Spawn(Troop.SEBazooka2)
  Spawn(Troop.SEBazooka3)
  Spawn(Troop.SEBazooka4)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.CutsceneCam1)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.cutscene3SEtarget)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.cutscene3SE)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, constant.WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(5, constant.ID_NONE, CO01_DialogBoxColour, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.cutscene4target)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.cutscene4SE)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, constant.WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    ClearMessageQueue(constant.PLAYER_ONE)
    PhoneMessage(7, constant.ID_NONE, CO01_DialogBoxColour, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.CutsceneCam2)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.cutscene2ILtarget)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.cutscene2IL)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, constant.WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(2, constant.ID_NONE, CO02_DialogBoxColour, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    PhoneMessage(4, constant.ID_NONE, CO02_DialogBoxColour, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(9)
    ReviveDeadUnit(Troop.CutsceneLegionTroop1, -388, 12, 90, 10)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop2, -386, 15, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop1, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop3, -385, 9, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop2, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop4, -390, 15, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop3, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop5, -384, 15, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop4, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop6, -386, 8, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop5, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop7, -392, 11, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop6, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop8, -384, 13, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop7, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop9, -383, 7, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop8, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop10, -388, 6, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop9, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop11, -385, 16, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop10, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneLegionTroop12, -385, 7, 90, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop11, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    FollowWaypoint(Troop.CutsceneLegionTroop12, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(2)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  end
  Despawn(Troop.CutsceneLegionTroop1)
  Despawn(Troop.CutsceneLegionTroop2)
  Despawn(Troop.CutsceneLegionTroop3)
  Despawn(Troop.CutsceneLegionTroop4)
  Despawn(Troop.CutsceneLegionTroop5)
  Despawn(Troop.CutsceneLegionTroop6)
  Despawn(Troop.CutsceneLegionTroop7)
  Despawn(Troop.CutsceneLegionTroop8)
  Despawn(Troop.CutsceneLegionTroop9)
  Despawn(Troop.CutsceneLegionTroop10)
  Despawn(Troop.CutsceneLegionTroop11)
  Despawn(Troop.CutsceneLegionTroop12)
  Spawn(Troop.ILAntiAir1)
  Spawn(Troop.ILGrunt1)
  Spawn(Troop.ILGrunt2)
  Spawn(Troop.ILGrunt3)
  Spawn(Troop.ILGrunt4)
  Spawn(Troop.IL_Player)
  Spawn(Troop.ILHose1)
  Spawn(Troop.ILHose2)
  Spawn(Troop.ILBazooka1)
  Spawn(Troop.ILBazooka2)
  Spawn(Troop.ILBazooka3)
  Spawn(Troop.ILBazooka4)
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.CutsceneCam2)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.cutscene3ILtarget)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.cutscene3IL)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, constant.WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(6, constant.ID_NONE, CO02_DialogBoxColour, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.cutscene4target)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.cutscene4IL)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, constant.WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(8, constant.ID_NONE, CO02_DialogBoxColour, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
