function ALL_UNITS_DEAD_AND_UNIT_KILLING_AND_UNIT_GROUP_SETUP(owner)
  Despawn(Ground_Vehicle.WFartillery1)
  Despawn(Ground_Vehicle.WFartillery2)
  Despawn(Troop.WFaa1)
  Despawn(Troop.WFaa2)
  Despawn(Troop.WFaa3)
  Despawn(Air_Vehicle.WFtransport1)
  Despawn(Air_Vehicle.WFtransport2)
  Despawn(Air_Vehicle.Tgunship01)
  Despawn(Air_Vehicle.Tgunship02)
  Despawn(Air_Vehicle.Ttransport1)
  Despawn(Ground_Vehicle.Tltank01)
  Despawn(Ground_Vehicle.Tltank02)
  Despawn(Troop.Tgrunt01)
  Despawn(Troop.Tgrunt02)
  Despawn(Troop.Tgrunt03)
  Despawn(Troop.Tgrunt04)
  Despawn(Troop.Tgrunt05)
  Despawn(Troop.Tgrunt06)
  Despawn(Troop.Tgrunt07)
  Despawn(Troop.Tgrunt10)
  Despawn(Troop.Tgrunt11)
  Despawn(Troop.Tgrunt12)
  Despawn(Troop.Tgrunt13)
  Despawn(Troop.Tgrunt14)
  Despawn(Troop.Tgrunt15)
  Despawn(Troop.Tgrunt16)
  Despawn(Troop.Tbazooka01)
  Despawn(Troop.Tbazooka02)
  Kill(Troop.WFAA1cutscene)
  Kill(Troop.WFAA2cutscene)
  Kill(Troop.WFAA3cutscene)
  Kill(Ground_Vehicle.WFcutsceneArtillery1)
  Kill(Ground_Vehicle.WFcutsceneArtillery2)
  Kill(Air_Vehicle.WFcutscenegunship1)
  Kill(Air_Vehicle.WFcutscenegunship2)
  Kill(Air_Vehicle.WFcutscenegunship3)
  EndFrame()
  ResetHealthAndScoreTotals()
  AddToGroup(Unit_Group.WFUnits, Troop.WFassault01)
  AddToGroup(Unit_Group.WFUnits, Troop.WFassault02)
  AddToGroup(Unit_Group.WFUnits, Troop.WFassault03)
  AddToGroup(Unit_Group.WFUnits, Troop.WFassault04)
  AddToGroup(Unit_Group.WFUnits, Troop.WFbazooka01)
  AddToGroup(Unit_Group.WFUnits, Troop.WFbazooka02)
  AddToGroup(Unit_Group.WFUnits, Troop.WFbazooka03)
  AddToGroup(Unit_Group.WFUnits, Troop.WFbazooka04)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt01)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt02)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt03)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt04)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt05)
  AddToGroup(Unit_Group.WFUnits, Troop.WFgrunt06)
  AddToGroup(Unit_Group.WFUnits, Ground_Vehicle.WFrecon1)
  repeat
    WaitFor(0.1)
    if AllPlayerUnitsDead(constant.PLAYER_ONE) == true then
      WaitFor(2)
      if ForceSpawningStopped == false then
        ReviveDeadUnit(Troop.WFgrunt01, GetObjectXPosition(Waypoint.WFDeadSpawn), GetObjectZPosition(Waypoint.WFDeadSpawn), 90, 5)
      end
    end
    EndFrame()
  until GetMissionEnded()
end
