function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PlayEffect(Scripted_Effect.SepiaC2, 3, 0, 0, 0)
  SetCamera(Camera.cutscenecam)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene1target)
  FollowWaypoint(Ground_Vehicle.tank1intro, Waypoint.IntroWestTundransTank, 0, 0, constant.ORDER_NORMAL)
  FollowWaypoint(Ground_Vehicle.tank2intro, Waypoint.IntroEastTundrans, 0, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.Tgrunt1intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt2intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt3intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt4intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt5intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt6intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt7intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt8intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt9intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt10intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt11intro, 110, -335, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Tgrunt12intro, 110, -335, 5, constant.ORDER_FORCED)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
  WaitFor(11)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene2)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene2target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Happy, constant.PLAYER_ONE)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene3)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene3target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
  WaitFor(9.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene4)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene4target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  GoToArea(Ground_Vehicle.Tltank07, -150, -119, 5, constant.ORDER_FORCED)
  PhoneMessage(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene5)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene5target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(1)
  PhoneMessage(6, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
  WaitFor(2)
  PutUnitInVehicle(Troop.Tgunship03pilot, Air_Vehicle.Tgunship03, 0)
  WaitFor(4)
  PutUnitInVehicle(Troop.Tgunship04pilot, Air_Vehicle.Tgunship04, 0)
  WaitFor(3.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene6)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene6target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(7, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Happy, constant.PLAYER_ONE)
  WaitFor(8.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.IntroCutscene7)
  CameraSetTarget(Camera.cutscenecam, Waypoint.IntroCutscene7target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(8, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(8.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CutsceneEnded = true
end
