function CUTSCENE_SKIP(owner)
  WaitFor(1)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      DebugOut("cutscene skipped")
      CutsceneEnded = true
    else
    end
    EndFrame()
  until CutsceneEnded == true
  EndIntro()
  Kill(cutscene)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.Tgrunt1intro)
  Despawn(Troop.Tgrunt2intro)
  Despawn(Troop.Tgrunt3intro)
  Despawn(Troop.Tgrunt4intro)
  Despawn(Troop.Tgrunt5intro)
  Despawn(Troop.Tgrunt6intro)
  Despawn(Troop.Tgrunt7intro)
  Despawn(Troop.Tgrunt8intro)
  Despawn(Troop.Tgrunt9intro)
  Despawn(Troop.Tgrunt10intro)
  Despawn(Troop.Tgrunt11intro)
  Despawn(Troop.Tgrunt12intro)
  Despawn(Ground_Vehicle.tank1intro)
  Despawn(Ground_Vehicle.tank2intro)
  EndFrame()
  Spawn(Ground_Vehicle.Tltank01)
  Spawn(Ground_Vehicle.Tltank02)
  Spawn(Troop.Tgrunt01)
  Spawn(Troop.Tgrunt02)
  Spawn(Troop.Tgrunt03)
  Spawn(Troop.Tgrunt04)
  Spawn(Troop.Tgrunt05)
  Spawn(Troop.Tgrunt06)
  Spawn(Troop.Tgrunt07)
  Spawn(Troop.Tgrunt10)
  Spawn(Troop.Tgrunt11)
  Spawn(Troop.Tgrunt12)
  Spawn(Troop.Tgrunt13)
  Spawn(Troop.Tgrunt14)
  Spawn(Troop.Tgrunt15)
  Spawn(Troop.Tgrunt16)
  Spawn(Troop.Tbazooka01)
  Spawn(Troop.Tbazooka02)
  if IsPassengerInUnit(Troop.Tgunship03pilot) == false then
    PutUnitInVehicle(Troop.Tgunship03pilot, Air_Vehicle.Tgunship03, 0)
  end
  if IsPassengerInUnit(Troop.Tgunship04pilot) == false then
    PutUnitInVehicle(Troop.Tgunship04pilot, Air_Vehicle.Tgunship04, 0)
  end
  StoreSummaryMessage(constant.PLAYER_ONE, 2, constant.ARMY_WF, SpriteID.CO_WF_Herman_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 3, constant.ARMY_WF, SpriteID.CO_WF_Betty_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 4, constant.ARMY_WF, SpriteID.CO_WF_Herman_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 5, constant.ARMY_WF, SpriteID.CO_WF_Herman_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 6, constant.ARMY_WF, SpriteID.CO_WF_Herman_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 7, constant.ARMY_WF, SpriteID.CO_WF_Betty_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 8, constant.ARMY_WF, SpriteID.CO_WF_Herman_Happy)
  StartScoringTimer()
  SepiaFade = true
  PlayEffect(Scripted_Effect.SepiaFade, 3, 0, 0, 0)
  SetCamera(Camera.playercam)
  EndFrame()
  ResetCommandBar()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  UnfreezePlayer(constant.PLAYER_ONE)
  PhoneMessageWithObjective(17, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  PhoneMessage(20, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  PhoneMessage(19, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
end
