function C1Bonus_Cutscene(owner)
  cutsceneStart = owner
  DebugOut("Cutscene Start ID", cutsceneStart)
  StartIntro()
  FreezePlayer()
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0026)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0030)
  PhoneMessage(0, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Sad)
  WaitFor(4)
  FollowWaypoint(Ground_Vehicle.WFheavyTank0001, Waypoint.Entity0247, 5, 5, constant.ORDER_NORMAL)
  FollowWaypoint(Ground_Vehicle.WFheavyTank0003, Waypoint.Entity0240, 5, 5, constant.ORDER_NORMAL)
  WaitFor(2)
  FollowWaypoint(Ground_Vehicle.WFheavyTank0002, Waypoint.Entity0247, 5, 5, constant.ORDER_NORMAL)
  FollowWaypoint(Ground_Vehicle.WFheavyTank0004, Waypoint.Entity0240, 5, 5, constant.ORDER_NORMAL)
  WaitFor(2)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0318)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0090)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  FollowWaypoint(Troop.WFgrunt0001, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0002, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0003, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0004, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0005, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0006, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0007, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0008, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0009, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0010, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0011, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFgrunt0012, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0001, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0002, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0003, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0004, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0005, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  FollowWaypoint(Troop.WFbazooka0006, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  PhoneMessage(1, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Sad)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0051)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0128)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Happy)
  WaitFor(4)
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0037)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0048)
  WaitFor(4)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0131)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0126)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, 0, 6, SpriteID.CO_Herman_Happy)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0068)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0086)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Happy)
  WaitFor(7)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Camera0001)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(5, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Happy)
  cutsceneStart = 1
  UnfreezePlayer()
  StartScoringTimer()
  EndFrame()
  return
end
