function C1Bonus_Kill_Cutscene(owner)
  WaitFor(1)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED)) then
      DebugOut("Killed cutscene", cutsceneStart)
      Kill(cutsceneStart)
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetCamera(Camera.Camera0001)
      FollowWaypoint(Ground_Vehicle.WFheavyTank0001, Waypoint.Entity0247, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Ground_Vehicle.WFheavyTank0002, Waypoint.Entity0247, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Ground_Vehicle.WFheavyTank0003, Waypoint.Entity0240, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Ground_Vehicle.WFheavyTank0004, Waypoint.Entity0240, 5, 5, constant.ORDER_NORMAL)
      FollowWaypoint(Troop.WFgrunt0001, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0002, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0003, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0004, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0005, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0006, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0007, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0008, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0009, Waypoint.Entity0237, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0010, Waypoint.Entity0234, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0011, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFgrunt0012, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0001, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0002, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0003, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0004, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0005, Waypoint.Entity0254, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      FollowWaypoint(Troop.WFbazooka0006, Waypoint.Entity0287, 5, 5, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      cutsceneStart = 1
      StoreSummaryMessage(0, 2, SpriteID.CO_Nova_Sad)
      StoreSummaryMessage(1, 2, SpriteID.CO_Nova_Sad)
      StoreSummaryMessage(2, 2, SpriteID.CO_Nova_Happy)
      StoreSummaryMessage(3, 0, SpriteID.CO_Herman_Happy)
      StoreSummaryMessage(4, 2, SpriteID.CO_Nova_Happy)
      ClearMessageQueue()
      PhoneMessage(5, constant.ID_NONE, 2, 6, SpriteID.CO_Nova_Happy)
      UnfreezePlayer()
      StartScoringTimer()
    end
    EndFrame()
  until cutsceneStart == 1
  EndFrame()
  return
end
