function Activate_Base(owner)
  WaitFor(5)
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.Base_Zone)
  SetObjectiveData(Objective.GetToBase, constant.OBJECTIVE_DATA_STATE, 1)
  SetActive(Troop.WF_Bazooka1, constant.ACTIVE)
  SetActive(Troop.WF_Bazooka2, constant.ACTIVE)
  SetActive(Troop.WF_Bazooka3, constant.ACTIVE)
  SetActive(Troop.WF_Chain1, constant.ACTIVE)
  SetActive(Troop.WF_Chain2, constant.ACTIVE)
  SetActive(Troop.WF_Chain3, constant.ACTIVE)
  SetActive(Troop.WF_Rifle1, constant.ACTIVE)
  SetActive(Troop.WF_Rifle2, constant.ACTIVE)
  SetActive(Troop.WF_Rifle3, constant.ACTIVE)
  SetActive(Troop.WF_Rifle4, constant.ACTIVE)
  SetActive(Troop.WF_Rifle5, constant.ACTIVE)
  SetActive(Troop.WF_Rifle6, constant.ACTIVE)
  SetActive(Troop.WF_Rifle7, constant.ACTIVE)
  SetActive(Troop.WF_Rifle8, constant.ACTIVE)
  SetActive(Troop.WF_Rifle9, constant.ACTIVE)
  SetActive(Troop.WF_Rifle10, constant.ACTIVE)
  SetActive(Ground_Vehicle.WF_Artillery1, constant.ACTIVE)
  SetActive(Ground_Vehicle.WF_Artillery2, constant.ACTIVE)
end
