function C2M1_Game_Flow(owner)
  LevelState = 0
  PrintState()
  SetActive(Ground_Vehicle.WF_Artillery1, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.WF_Artillery2, constant.INACTIVE, constant.ADJUST_WEAPON)
  Despawn(Ground_Vehicle.XLTank0)
  Despawn(Air_Vehicle.XAirTransOpen)
  Despawn(Air_Vehicle.XAirTrans2)
  Despawn(Air_Vehicle.XAirTrans3)
  Despawn(Air_Vehicle.XAirTrans4)
  Despawn(Air_Vehicle.XAirTrans5)
  Despawn(Air_Vehicle.XAirTrans6)
  Despawn(Air_Vehicle.XAirTrans7)
  Despawn(Air_Vehicle.XAirTrans8)
  Despawn(Air_Vehicle.XAirTrans9)
  Despawn(Air_Vehicle.WF_Transport1)
  Despawn(Air_Vehicle.WF_Transport2)
  Despawn(Air_Vehicle.Bomber1)
  Despawn(Air_Vehicle.Bomber2)
  Despawn(Air_Vehicle.Bomber3)
  Despawn(Air_Vehicle.Bomber4)
  LevelState = 1
  PrintState()
  repeat
    EndFrame()
  until LevelState == 2
  WaitFor(2)
  PhoneMessage(5, 0, 0, 5, SpriteID.CO_WF_Herman_Sad)
  PhoneMessage(58, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(35)
  PhoneMessage(19, 0, 1, 4, SpriteID.CO_X_Ubel_Happy)
  PhoneMessage(20, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(21, 0, 1, 4, SpriteID.CO_X_Ubel_Happy)
  repeat
    EndFrame()
  until 0 >= GetHealthPercent(Troop.Trans0Dude1) and 0 >= GetHealthPercent(Troop.Trans0Dude2) and 0 >= GetHealthPercent(Troop.Trans0Dude3) and 0 >= GetHealthPercent(Troop.Trans0Dude4) and 0 >= GetHealthPercent(Troop.Trans0Dude5) and 0 >= GetHealthPercent(Troop.Trans1Dude1) and 0 >= GetHealthPercent(Troop.Trans1Dude2) and 0 >= GetHealthPercent(Troop.Trans1Dude3) and 0 >= GetHealthPercent(Troop.Trans1Dude4) and 0 >= GetHealthPercent(Troop.Trans1Dude5)
  LevelState = 3
  PrintState()
  SetObjectiveData(Objective.Setup, constant.OBJECTIVE_DATA_STATE, 0)
  PhoneMessage(8, 0, 0, 5, SpriteID.CO_WF_Herman_Sad)
  PhoneMessage(9, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(10, 0, 0, 5, SpriteID.CO_WF_Austin_Happy)
  PhoneMessage(11, 0, 0, 4, SpriteID.CO_WF_Herman_Sad)
  PhoneMessage(12, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  PhoneMessage(13, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  PhoneMessage(61, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  PhoneMessage(14, 0, 0, 5, SpriteID.CO_WF_Herman_Sad)
  WaitFor(50)
  LevelState = 4
  PrintState()
  SetObjectiveData(Objective.Setup, constant.OBJECTIVE_DATA_STATE, 1)
  PhoneMessage(22, 0, 1, 4, SpriteID.CO_X_Ubel_Happy)
  PhoneMessage(16, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  WaitFor(18)
  PhoneMessage(18, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  repeat
    EndFrame()
  until IsDead(Ground_Vehicle.XLTank1) and IsDead(Ground_Vehicle.XLTank2)
  PhoneMessage(26, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(27, 0, 1, 4, SpriteID.CO_X_Ubel_Sad)
  PhoneMessage(28, 0, 1, 3, SpriteID.CO_X_Ingrid_Happy)
  PhoneMessage(29, 0, 1, 4, SpriteID.CO_X_Ubel_Happy)
  PhoneMessage(30, 0, 1, 5, SpriteID.CO_X_Ingrid_Happy)
  PhoneMessage(31, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(35)
  Spawn(Air_Vehicle.WF_Transport1)
  Spawn(Air_Vehicle.WF_Transport2)
  TransWF1Go = 1
  TransWF2Go = 1
  PhoneMessage(33, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  repeat
    EndFrame()
  until 4 > NumPassengersInUnit(Air_Vehicle.WF_Transport1)
  PhoneMessage(34, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  repeat
    EndFrame()
  until BombGo == 1
  DebugOut("Bombers Go?", BombGo)
  WaitFor(10)
  PhoneMessage(32, 0, 1, 5, SpriteID.CO_X_Ingrid_Happy)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.Bomber1) and IsDead(Air_Vehicle.Bomber2) and IsDead(Air_Vehicle.Bomber3) and IsDead(Air_Vehicle.Bomber4)
  Kill(Air_Vehicle.Bomber1)
  Kill(Air_Vehicle.Bomber2)
  Kill(Air_Vehicle.Bomber3)
  Kill(Air_Vehicle.Bomber4)
  while GetPlayerUnit() == nil do
    EndFrame()
  end
  FreezePlayer()
  DeclareVictory(constant.ARMY_WF)
  PhoneMessage(44, 0, 0, 5, SpriteID.CO_WF_Austin_Happy)
  PhoneMessage(39, 0, 1, 5, SpriteID.CO_X_Ubel_Sad)
  PhoneMessage(45, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(23.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  WinMission()
end
