function Cutscene_Intro(owner)
  cutscenes = owner
  repeat
    EndFrame()
  until LevelState == 1
  StartIntro()
  FreezePlayer()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Entity0106)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Entity0105)
  FollowWaypoint(Troop.WF_Bazooka1, Waypoint.Entity0107, 0, 0)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(1)
  PhoneMessage(0, 0, 0, 3, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(1, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(11)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam2)
  CameraSetTarget(Camera.Cam2, Waypoint.Entity0121)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Entity0122)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(5)
  Spawn(Air_Vehicle.XAirTransOpen)
  Teleport(Air_Vehicle.XAirTransOpen, 0, 630, 140, 10)
  Teleport(Air_Vehicle.XAirTrans0, -100, 630, 140, 10)
  Teleport(Air_Vehicle.XAirTrans1, -100, 730, 140, 10)
  WaitFor(1)
  FollowWaypoint(Air_Vehicle.XAirTransOpen, Waypoint.ToMe, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Air_Vehicle.XAirTrans0, Waypoint.ToMe, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Air_Vehicle.XAirTrans1, Waypoint.ToMe, 0, 0, constant.ORDER_FORCED)
  PhoneMessage(3, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  GoToArea(Air_Vehicle.XAirTransOpen, 230.075, 272.443, 20, nil, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.XAirTrans0, 173.377, 812.23, 20, nil, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.XAirTrans1, 59.882, 854.378, 20, nil, constant.ORDER_FORCED)
  SetCamera(Camera.Cam3)
  CameraSetTarget(Camera.Cam3, Waypoint.Entity0115)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Entity0103)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, 0, 0, 7, SpriteID.CO_WF_Herman_Happy)
  WaitFor(12)
  LevelState = 2
  PrintState()
  cutscene = 1
end
