function DespawnUnits(owner)
  scriptDespawnUnits = owner
  Despawn(Ground_Vehicle.XLightAttack7)
  AddToGroup(Unit_Group.Player_Army, Troop.Grenadier1)
  AddToGroup(Unit_Group.Player_Army, Troop.Grenadier2)
  AddToGroup(Unit_Group.Player_Army, Troop.Grenadier3)
  AddToGroup(Unit_Group.Player_Army, Troop.Grenadier4)
  AddToGroup(Unit_Group.Player_Army, Troop.Grenadier5)
  AddToGroup(Unit_Group.Player_Army, Troop.WFGrunt1)
  AddToGroup(Unit_Group.Player_Army, Troop.WFGrunt2)
  AddToGroup(Unit_Group.Player_Army, Troop.WFGrunt3)
  AddToGroup(Unit_Group.Player_Army, Troop.WFGrunt4)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarHoseVet1)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarHoseVet2)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarHoseVet3)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarHoseVet4)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarHoseVet5)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarGrunt1)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarGrunt2)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarGrunt3)
  AddToGroup(Unit_Group.Player_Army, Troop.SolarGrunt4)
  Despawn(Building.FuelRefineryBuilding1)
  Despawn(Building.FuelRefineryBuilding4)
  Despawn(Building.FuelRefineryBuilding5)
  Despawn(Building.FuelRefineryBuilding6)
end
