function Cutscene_Intro_Skip(owner)
  WaitFor(3)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      Kill(IntroCutscene)
      DebugOut("Intro Cutscene skipped")
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      IntroCutsceneEnd = 1
      EndFrame()
    else
    end
    EndFrame()
  until IntroCutsceneEnd == 1
  Kill(IntroCutscene)
  ClearMessageQueue()
  StoreSummaryMessage(5, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
  StoreSummaryMessage(6, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Sad)
  StoreSummaryMessage(1, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
  StoreSummaryMessage(2, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
  StoreSummaryMessage(3, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
  StoreSummaryMessage(4, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
  if IsDead(Water_Vehicle.SEBattleship01) then
    repeat
      EndFrame()
    until IsReadyToRevive(Water_Vehicle.SEBattleship01)
    ReviveDeadUnit(Water_Vehicle.SEBattleship01, GetObjectXPosition(Waypoint.SEBattleship01Teleport), GetObjectZPosition(Waypoint.SEBattleship01Teleport), 0, 0)
  end
  EndFrame()
  if IsDead(Water_Vehicle.SEBattleship02) then
    repeat
      EndFrame()
    until IsReadyToRevive(Water_Vehicle.SEBattleship02)
    ReviveDeadUnit(Water_Vehicle.SEBattleship02, GetObjectXPosition(Waypoint.SEBattleship02Teleport), GetObjectZPosition(Waypoint.SEBattleship02Teleport), 0, 0)
  end
  EndFrame()
  EnableWeapon(Water_Vehicle.SEBattleship01, 1)
  EnableWeapon(Water_Vehicle.SEBattleship02, 1)
  EnableWeapon(Building.NavalGun01, 1)
  EnableWeapon(Building.NavalGun02, 1)
  Teleport(Water_Vehicle.SEBattleship01, GetObjectXPosition(Waypoint.SEBattleship01Teleport), GetObjectZPosition(Waypoint.SEBattleship01Teleport), 0, 0)
  Teleport(Water_Vehicle.SEBattleship02, GetObjectXPosition(Waypoint.SEBattleship02Teleport), GetObjectZPosition(Waypoint.SEBattleship02Teleport), 0, 0)
  Teleport(Water_Vehicle.SENavalTransport01, GetObjectXPosition(Waypoint.NavalTransport01Start), GetObjectZPosition(Waypoint.NavalTransport01Start), 0, 0)
  Teleport(Water_Vehicle.SENavalTransport02, GetObjectXPosition(Waypoint.NavalTransport02Start), GetObjectZPosition(Waypoint.NavalTransport02Start), 0, 0)
  Teleport(Water_Vehicle.SENavalTransport03, GetObjectXPosition(Waypoint.NavalTransport03Start), GetObjectZPosition(Waypoint.NavalTransport03Start), 0, 0)
  Teleport(Water_Vehicle.SENavalTransport04, GetObjectXPosition(Waypoint.NavalTransport04Start), GetObjectZPosition(Waypoint.NavalTransport04Start), 0, 0)
  EndFrame()
  Despawn(Water_Vehicle.SEBattleship01)
  Despawn(Water_Vehicle.SEBattleship02)
  Despawn(Water_Vehicle.SENavalTransport01)
  Despawn(Water_Vehicle.SENavalTransport02)
  Despawn(Water_Vehicle.SENavalTransport03)
  Despawn(Water_Vehicle.SENavalTransport04)
  Despawn(Building.CutsceneBattleship01Target)
  Despawn(Building.CutsceneBattleship02Target)
  Despawn(Building.CutsceneAirTransport01)
  Despawn(Air_Vehicle.SEAirTransport02)
  SetCapturePointHeight(Capture_Point.ILairbase, constant.ARMY_SOLAR, 100)
  SetInstallationOwner(Strategic_Installation.ILairbase, constant.ARMY_SOLAR)
  Spawn(Troop.SEGrunt16)
  Spawn(Troop.SEGrunt17)
  Spawn(Troop.SEGrunt18)
  Spawn(Troop.SEGrunt19)
  ExitVehicle(Troop.SEGrunt03, Capture_Point.ILairbase)
  ExitVehicle(Troop.SEGrunt16, Capture_Point.ILairbase)
  ExitVehicle(Troop.SEGrunt17, Capture_Point.ILairbase)
  ExitVehicle(Troop.SEGrunt18, Capture_Point.ILairbase)
  ExitVehicle(Troop.SEGrunt19, Capture_Point.ILairbase)
  EndFrame()
  Teleport(Troop.SEGrunt03, -235.77, 312.545, 45, 5)
  Teleport(Troop.SEGrunt16, -82, -4, 45, 5)
  Teleport(Troop.SEGrunt17, -82, -4, 45, 5)
  Teleport(Troop.SEGrunt18, -73, -13, 45, 5)
  Teleport(Troop.SEGrunt19, -73, -13, 45, 5)
  StopAndGuard(Troop.SEGrunt16)
  StopAndGuard(Troop.SEGrunt17)
  StopAndGuard(Troop.SEGrunt18)
  StopAndGuard(Troop.SEGrunt19)
  Spawn(Air_Vehicle.SEGunship01)
  Spawn(Air_Vehicle.SEGunship02)
  Kill(Air_Vehicle.ILBomber01)
  Kill(Air_Vehicle.ILFighter01)
  EndFrame()
  SetCamera(Camera.PlayerCam, constant.PLAYER_ONE)
  EndFrame()
  ResetCommandBar()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  EndIntro()
  WaitFor(UnfreezeDelay)
  UnfreezePlayer(constant.PLAYER_ONE)
  SetInvulnerable(flag.TYPE_SOLAR, 0)
  SetInvulnerable(flag.TYPE_UNDERWORLD, 0)
  PauseTimerActive = 0
  ResetHealthAndScoreTotals()
  EndFrame()
  StartScoringTimer()
  ListScoringUnits()
end
