function Cutscene_Outro(owner)
  OutroCutscene = owner
  Despawn(Troop.CutsceneDummy)
  Despawn(Troop.CutsceneSEStaffBearer01)
  Despawn(Troop.CutsceneSEStaffBearer02)
  Despawn(Troop.CutsceneSEGrunt01)
  Despawn(Troop.CutsceneSEGrunt02)
  Despawn(Troop.CutsceneSEGrunt03)
  Despawn(Troop.CutsceneSEGrunt04)
  Despawn(Troop.CutsceneSEGrunt05)
  Despawn(Troop.CutsceneSEGrunt06)
  Despawn(Troop.CutsceneSEGrunt07)
  Despawn(Troop.CutsceneSEGrunt08)
  Despawn(Troop.CutsceneSEGrunt09)
  Despawn(Troop.CutsceneSEGrunt10)
  Despawn(Troop.CutsceneSEGrunt11)
  Despawn(Troop.CutsceneSEGrunt12)
  Despawn(Troop.CutsceneSEGrunt13)
  Despawn(Ground_Vehicle.CutsceneSELightTank01)
  Despawn(Air_Vehicle.CutsceneSEAirTransport01)
  Kill(Air_Vehicle.CutsceneBomber01)
  Despawn(Building.StaffOfPower)
  Kill(Water_Vehicle.SE_Battleship01_Cutscene)
  Kill(Water_Vehicle.SE_Battleship02_Cutscene)
  Kill(Air_Vehicle.SE_Gunship01_Cutscene)
  Kill(Air_Vehicle.SE_Gunship02_Cutscene)
  Kill(Air_Vehicle.IL_Fighter01_Cutscene)
  Kill(Air_Vehicle.IL_Bomber01_Cutscene)
  repeat
    EndFrame()
  until OutroCutsceneStart == 1
  CutsceneIsPlaying = 1
  StartOutro()
  SetWaterRenderEnable(true)
  Spawn(Troop.CutsceneDummy)
  EndFrame()
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.CutsceneDummy, true, true)
  EndFrame()
  FreezePlayer(constant.PLAYER_ONE)
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  SetInvulnerable(flag.TYPE_UNDERWORLD, 1)
  Despawn(Building.MGTower01)
  Despawn(Building.MGTower02)
  Despawn(Building.MGTower05)
  Despawn(Building.MGTower06)
  Despawn(Troop.SEGrunt16)
  Despawn(Troop.SEGrunt17)
  Despawn(Troop.SEGrunt18)
  Despawn(Troop.SEGrunt19)
  Despawn(Troop.SEMortar09)
  Despawn(Troop.SEMortar10)
  Despawn(Troop.SEAssault22)
  Despawn(Troop.SEAssault23)
  Despawn(Ground_Vehicle.SELightTank09)
  repeat
    EndFrame()
  until IsReadyToRevive(Air_Vehicle.IL_Fighter01_Cutscene)
  ReviveDeadUnit(Air_Vehicle.IL_Fighter01_Cutscene, -410, 25, 200, 0)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.IL_Fighter01_Cutscene) == false
  EndFrame()
  ReviveDeadUnit(Air_Vehicle.SE_Gunship01_Cutscene, GetObjectXPosition(Waypoint.BattleshipPath02), GetObjectZPosition(Waypoint.BattleshipPath02), 0, 10)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.SE_Gunship01_Cutscene) == false
  EndFrame()
  EndFrame()
  ReviveDeadUnit(Air_Vehicle.SE_Gunship02_Cutscene, GetObjectXPosition(Waypoint.BattleshipPath02), GetObjectZPosition(Waypoint.BattleshipPath02), 0, 10)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.SE_Gunship02_Cutscene) == false
  EndFrame()
  EndFrame()
  Spawn(Building.CutsceneBattleship01Target)
  Spawn(Building.CutsceneBattleship02Target)
  GoToArea(Air_Vehicle.SE_Gunship01_Cutscene, -425, -160, 0, 0, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.SE_Gunship02_Cutscene, Building.CutsceneBattleship02Target, constant.ORDER_FORCED)
  EnableWeapon(Air_Vehicle.IL_Fighter01_Cutscene, 1)
  AttackTarget(Air_Vehicle.IL_Fighter01_Cutscene, Air_Vehicle.SE_Gunship01_Cutscene, constant.ORDER_FORCED)
  ReviveDeadUnit(Water_Vehicle.SE_Battleship01_Cutscene, GetObjectXPosition(Waypoint.BattleshipPath01), GetObjectZPosition(Waypoint.BattleshipPath01), 0, 0)
  ReviveDeadUnit(Water_Vehicle.SE_Battleship02_Cutscene, GetObjectXPosition(Waypoint.BattleshipPath02), GetObjectZPosition(Waypoint.BattleshipPath02), 0, 0)
  EnableWeapon(Water_Vehicle.SE_Battleship01_Cutscene, 0)
  EnableWeapon(Water_Vehicle.SE_Battleship02_Cutscene, 0)
  SetCamera(Camera.CutsceneCamSepia, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot01Spline)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot01Target)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(20, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until IsReadyToRevive(Air_Vehicle.IL_Bomber01_Cutscene)
  ReviveDeadUnit(Air_Vehicle.IL_Bomber01_Cutscene, -600, -300, 90, 0)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.IL_Bomber01_Cutscene) == false
  EndFrame()
  EnableWeapon(Air_Vehicle.IL_Bomber01_Cutscene, 1)
  AttackTarget(Air_Vehicle.IL_Bomber01_Cutscene, Water_Vehicle.SE_Battleship02_Cutscene, constant.ORDER_FORCED)
  WaitFor(4)
  Kill(Air_Vehicle.SE_Gunship01_Cutscene)
  AttackTarget(Air_Vehicle.IL_Fighter01_Cutscene, Air_Vehicle.SE_Gunship01_Cutscene, constant.ORDER_FORCED)
  WaitFor(3)
  Kill(Air_Vehicle.SE_Gunship02_Cutscene)
  WaitFor(2)
  Kill(Water_Vehicle.SE_Battleship02_Cutscene)
  WaitFor(1)
  Kill(Water_Vehicle.SE_Battleship01_Cutscene)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.IL_Bomber01_Cutscene)
  Despawn(Air_Vehicle.IL_Fighter01_Cutscene)
  Spawn(Air_Vehicle.CutsceneSEAirTransport01)
  Spawn(Troop.CutsceneSEStaffBearer01)
  PutUnitInVehicle(Troop.CutsceneSEStaffBearer01, Air_Vehicle.CutsceneSEAirTransport01, 3)
  LandAirUnit(Air_Vehicle.CutsceneSEAirTransport01, GetObjectXPosition(Waypoint.OutroCutsceneAirTransportLand), GetObjectZPosition(Waypoint.OutroCutsceneAirTransportLand), constant.ORDER_FORCED, 0, 20, 180)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot05Spline)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot05Target)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(24, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetMovementState(Air_Vehicle.CutsceneSEAirTransport01) == constant.MOVEMENT_STATE_ON_GROUND
  Spawn(Troop.CutsceneSEGrunt06)
  PutUnitInVehicle(Troop.CutsceneSEGrunt06, Air_Vehicle.CutsceneSEAirTransport01, 4)
  ExitVehicle(Troop.CutsceneSEStaffBearer01, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEStaffBearer01, GetObjectXPosition(Waypoint.CutsceneSEStaffBearer01Teleport01), GetObjectZPosition(Waypoint.CutsceneSEStaffBearer01Teleport01), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  Spawn(Troop.CutsceneSEGrunt07)
  PutUnitInVehicle(Troop.CutsceneSEGrunt07, Air_Vehicle.CutsceneSEAirTransport01, 5)
  ExitVehicle(Troop.CutsceneSEGrunt06, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt06, GetObjectXPosition(Waypoint.CutsceneGrunt02Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt02Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  Spawn(Troop.CutsceneSEGrunt08)
  PutUnitInVehicle(Troop.CutsceneSEGrunt08, Air_Vehicle.CutsceneSEAirTransport01, 3)
  ExitVehicle(Troop.CutsceneSEGrunt07, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt07, GetObjectXPosition(Waypoint.CutsceneGrunt03Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt03Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.75)
  Spawn(Troop.CutsceneSEGrunt09)
  PutUnitInVehicle(Troop.CutsceneSEGrunt09, Air_Vehicle.CutsceneSEAirTransport01, 4)
  ExitVehicle(Troop.CutsceneSEGrunt08, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt08, GetObjectXPosition(Waypoint.CutsceneGrunt04Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt04Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(1)
  Spawn(Troop.CutsceneSEGrunt10)
  PutUnitInVehicle(Troop.CutsceneSEGrunt10, Air_Vehicle.CutsceneSEAirTransport01, 5)
  ExitVehicle(Troop.CutsceneSEGrunt09, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt09, GetObjectXPosition(Waypoint.CutsceneGrunt05Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt05Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.75)
  Spawn(Troop.CutsceneSEGrunt11)
  PutUnitInVehicle(Troop.CutsceneSEGrunt11, Air_Vehicle.CutsceneSEAirTransport01, 3)
  ExitVehicle(Troop.CutsceneSEGrunt10, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt10, GetObjectXPosition(Waypoint.CutsceneGrunt06Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt06Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  Spawn(Troop.CutsceneSEGrunt12)
  PutUnitInVehicle(Troop.CutsceneSEGrunt12, Air_Vehicle.CutsceneSEAirTransport01, 4)
  ExitVehicle(Troop.CutsceneSEGrunt11, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt11, GetObjectXPosition(Waypoint.CutsceneGrunt07Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt07Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(0.75)
  Spawn(Troop.CutsceneSEGrunt13)
  PutUnitInVehicle(Troop.CutsceneSEGrunt13, Air_Vehicle.CutsceneSEAirTransport01, 5)
  ExitVehicle(Troop.CutsceneSEGrunt12, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt12, GetObjectXPosition(Waypoint.CutsceneGrunt08Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt08Teleport), 1, 0, constant.ORDER_FORCED)
  WaitFor(1)
  ExitVehicle(Troop.CutsceneSEGrunt13, Air_Vehicle.CutsceneSEAirTransport01)
  GoToArea(Troop.CutsceneSEGrunt13, GetObjectXPosition(Waypoint.CutsceneGrunt09Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt09Teleport), 1, 0, constant.ORDER_FORCED)
  Spawn(Ground_Vehicle.CutsceneSELightTank01)
  GoToArea(Ground_Vehicle.CutsceneSELightTank01, 85, -100, 1, 1, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ReviveDeadUnit(Air_Vehicle.CutsceneBomber01, -33.495, 27.8, 135, 0)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.CutsceneSEAirTransport01)
  Teleport(Troop.CutsceneSEStaffBearer01, GetObjectXPosition(Waypoint.CutsceneSEStaffBearer01Teleport01), GetObjectZPosition(Waypoint.CutsceneSEStaffBearer01Teleport01), 0, 0)
  Teleport(Troop.CutsceneSEGrunt06, GetObjectXPosition(Waypoint.CutsceneGrunt02Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt02Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt07, GetObjectXPosition(Waypoint.CutsceneGrunt03Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt03Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt08, GetObjectXPosition(Waypoint.CutsceneGrunt04Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt04Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt09, GetObjectXPosition(Waypoint.CutsceneGrunt05Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt05Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt10, GetObjectXPosition(Waypoint.CutsceneGrunt06Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt06Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt11, GetObjectXPosition(Waypoint.CutsceneGrunt07Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt07Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt12, GetObjectXPosition(Waypoint.CutsceneGrunt08Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt08Teleport), 0, 0)
  Teleport(Troop.CutsceneSEGrunt13, GetObjectXPosition(Waypoint.CutsceneGrunt09Teleport), GetObjectZPosition(Waypoint.CutsceneGrunt09Teleport), 0, 0)
  EnableWeapon(Troop.CutsceneSEStaffBearer01, 0)
  EnableWeapon(Troop.CutsceneSEGrunt06, 0)
  EnableWeapon(Troop.CutsceneSEGrunt07, 0)
  EnableWeapon(Troop.CutsceneSEGrunt08, 0)
  EnableWeapon(Troop.CutsceneSEGrunt09, 0)
  EnableWeapon(Troop.CutsceneSEGrunt10, 0)
  EnableWeapon(Troop.CutsceneSEGrunt11, 0)
  EnableWeapon(Troop.CutsceneSEGrunt12, 0)
  EnableWeapon(Troop.CutsceneSEGrunt13, 0)
  Teleport(Ground_Vehicle.CutsceneSELightTank01, 75, -65, 0, 0)
  EnableWeapon(Ground_Vehicle.CutsceneSELightTank01, 0)
  AttackTarget(Air_Vehicle.CutsceneBomber01, Building.AmmoDump07, constant.ORDER_FORCED)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot06Spline)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot06Target)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.NO_WAIT, 1)
  WaitFor(1)
  PhoneMessage(19, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  WaitFor(5.75)
  Kill(Ground_Vehicle.CutsceneSELightTank01)
  WaitFor(0.25)
  Kill(Troop.CutsceneSEStaffBearer01)
  Kill(Troop.CutsceneSEGrunt06)
  Kill(Troop.CutsceneSEGrunt07)
  Kill(Troop.CutsceneSEGrunt08)
  Kill(Building.AmmoDump06)
  Kill(Building.AmmoDump08)
  WaitFor(0.75)
  Spawn(Building.StaffOfPower)
  Kill(Building.AmmoDump07)
  Kill(Troop.CutsceneSEGrunt09)
  Kill(Troop.CutsceneSEGrunt10)
  Kill(Troop.CutsceneSEGrunt11)
  WaitFor(0.75)
  Kill(Building.AmmoDump09)
  Kill(Troop.CutsceneSEGrunt12)
  Kill(Troop.CutsceneSEGrunt13)
  WaitFor(0.5)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.CutsceneBomber01)
  Spawn(Troop.CutsceneSEGrunt01)
  EndFrame()
  Teleport(Troop.CutsceneSEGrunt01, 62.882, -277.051, 90, 0)
  EndFrame()
  FollowWaypoint(Troop.CutsceneSEGrunt01, Waypoint.OutroCutsceneGrunt01Path02, 0, 0, constant.ORDER_FORCED)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot02SplineC)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot02TargetC)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(18, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  PhoneMessage(21, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.CutsceneSEGrunt01)
  Spawn(Troop.CutsceneSEGrunt02)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot03Spline)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot03Target)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(22, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
  FollowWaypoint(Troop.CutsceneSEGrunt02, Waypoint.OutroCutsceneGrunt01Path03, 0, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  Spawn(Troop.CutsceneSEStaffBearer02)
  Spawn(Troop.CutsceneSEGrunt03)
  Spawn(Troop.CutsceneSEGrunt04)
  Spawn(Troop.CutsceneSEGrunt05)
  FollowWaypoint(Troop.CutsceneSEStaffBearer02, Waypoint.EnterTower, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Troop.CutsceneSEGrunt03, Waypoint.EnterTower2, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Troop.CutsceneSEGrunt04, Waypoint.EnterTower, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Troop.CutsceneSEGrunt05, Waypoint.EnterTower2, 0, 0, constant.ORDER_FORCED)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.CutsceneSEGrunt02)
  CameraSetWaypoint(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot04SplineA)
  CameraSetTarget(Camera.CutsceneCamSepia, Waypoint.CutsceneOutroShot04TargetA)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(23, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
  PhoneMessage(26, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  OutroCutsceneEnd = 1
end
