function Gameflow(owner)
  GameflowScript = owner
  local AirbaseCounterAttackTriggered = 0
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt01)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt02)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt03)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt04)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt05)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt06)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt07)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt08)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt09)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILGrunt10)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILBazooka01)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILBazooka02)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILBazooka03)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILBazooka04)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILBazooka05)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILAntiAir01)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILAntiAir02)
  AddToGroup(Unit_Group.PlayerUnits, Troop.ILAntiAir03)
  Despawn(Air_Vehicle.SEAirTransport01)
  Despawn(Air_Vehicle.SEAirTransport02)
  Despawn(Air_Vehicle.SEAirTransport03)
  Despawn(Air_Vehicle.SEAirTransport04)
  Despawn(Troop.SEGrunt04)
  Despawn(Troop.SEGrunt07)
  Despawn(Troop.SEGrunt08)
  Despawn(Troop.SEGrunt50)
  Despawn(Troop.SEGrunt51)
  Despawn(Troop.SEGrunt52)
  Despawn(Troop.SEGrunt53)
  Despawn(Troop.SEGrunt54)
  Despawn(Troop.SEGrunt55)
  Despawn(Water_Vehicle.SENavalTransport05)
  Despawn(Water_Vehicle.SENavalTransport06)
  Despawn(Water_Vehicle.SENavalTransport07)
  Despawn(Water_Vehicle.SENavalTransport08)
  Despawn(Water_Vehicle.SEBattleship03)
  Despawn(Water_Vehicle.SEBattleship04)
  Despawn(Water_Vehicle.SEBattleship05)
  Despawn(Water_Vehicle.SEBattleship06)
  Despawn(Air_Vehicle.SEGunship01)
  Despawn(Air_Vehicle.SEGunship02)
  SetUnitInvulnerable(Ground_Vehicle.ILArtillery01, true)
  SetUnitInvulnerable(Ground_Vehicle.ILArtillery02, true)
  SetActive(Ground_Vehicle.ILArtillery01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILArtillery02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.SELightTank02, constant.INACTIVE)
  SetActive(Ground_Vehicle.SELightTank09, constant.INACTIVE)
  SetActive(Ground_Vehicle.SELightTank11, constant.INACTIVE)
  SetActive(Troop.SEGrunt09, constant.INACTIVE)
  SetActive(Troop.SEGrunt10, constant.INACTIVE)
  SetActive(Troop.SEGrunt11, constant.INACTIVE)
  SetActive(Morphing_Building.ILairbase, constant.INACTIVE)
  SetActive(Capture_Point.ILairbase, constant.INACTIVE)
  FollowWaypoint(Troop.SEGrunt09, Waypoint.SEGrunt09Path, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Troop.SEGrunt10, Waypoint.SEGrunt10Path, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Troop.SEGrunt11, Waypoint.SEGrunt11Path, 0, 0, constant.ORDER_FORCED)
  SetUnitAI(Troop.SEGrunt03, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_DEFENSIVE)
  SetUnitAI(Troop.SEGrunt03, constant.AI_MOVE_STYLE, constant.MOVESTYLE_RESPOND_TO_ATTACK)
  repeat
    EndFrame()
  until IntroCutsceneEnd == 1
  WaitFor(3)
  DebugOut("GAMEFLOW SCRIPT DEBUG ONE - MISSION STARTED")
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.TriggerGunships, flag.TYPE_UNDERWORLD)
  TriggerGunships = 1
  DebugOut("GAMEFLOW SCRIPT DEBUG TWO - TRIGGER GUNSHIPS")
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.TriggerSEAirTransport01)
  DebugOut("GAMEFLOW SCRIPT DEBUG THREE - TRIGGER AIR TRANSPORTS")
  Spawn(Air_Vehicle.SEAirTransport01)
  Spawn(Troop.SEGrunt04)
  Spawn(Troop.SEGrunt07)
  Spawn(Troop.SEGrunt08)
  PutUnitInVehicle(Troop.SEGrunt04, Air_Vehicle.SEAirTransport01, 3)
  PutUnitInVehicle(Troop.SEGrunt07, Air_Vehicle.SEAirTransport01, 4)
  PutUnitInVehicle(Troop.SEGrunt08, Air_Vehicle.SEAirTransport01, 5)
  LandAirUnit(Air_Vehicle.SEAirTransport01, GetObjectXPosition(Waypoint.SEAirTransport01Land), GetObjectZPosition(Waypoint.SEAirTransport01Land), constant.ORDER_FORCED, true, 10, 100)
  SetUnitAI(Troop.SEGrunt04, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEGrunt07, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEGrunt08, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.TriggerAttackWave02)
  DebugOut("GAMEFLOW SCRIPT DEBUG FOUR - SENT SOLAR GRUNTS IN OVER BRIDGE")
  EndFrame()
  SendGunshipsAway = 1
  PhoneMessageWithObjective(50, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE, false, constant.NEW_SECONDARY_OBJECTIVE)
  SetObjectiveData(Objective.POWArtillery, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.POWArtillery, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  GoToArea(Troop.SEGrunt09, GetObjectXPosition(Waypoint.AttackWave02Path01), GetObjectZPosition(Waypoint.AttackWave02Path01), 5, 0, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  GoToArea(Troop.SEGrunt10, GetObjectXPosition(Waypoint.AttackWave02Path01), GetObjectZPosition(Waypoint.AttackWave02Path01), 5, 0, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  GoToArea(Troop.SEGrunt11, GetObjectXPosition(Waypoint.AttackWave02Path02), GetObjectZPosition(Waypoint.AttackWave02Path02), 0, 0, constant.ORDER_NORMAL, constant.FORMATION_ALLOWED)
  WaitFor(1)
  SetActive(Troop.SEGrunt09, constant.ACTIVE)
  SetActive(Troop.SEGrunt10, constant.ACTIVE)
  SetActive(Troop.SEGrunt11, constant.ACTIVE)
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.TriggerTankAmbush) or IsInArea(GetPlayerUnit(), Map_Zone.TriggerArtilleryCutscene) or IsInArea(Ground_Vehicle.SELightTank02, Map_Zone.SetAmbushTankActive) == false
  DebugOut("GAMEFLOW SCRIPT DEBUG FIVE - TRIGGER TANK TO APPROACH BRIDGE END")
  SetActive(Capture_Point.ILairbase, constant.ACTIVE)
  FollowWaypoint(Ground_Vehicle.SELightTank02, Waypoint.SELightTank02Path, 0, 0, constant.ORDER_NORMAL)
  SetUnitAI(Ground_Vehicle.SELightTank02, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  WaitFor(2.75)
  SetActive(Ground_Vehicle.SELightTank02, constant.ACTIVE)
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.TriggerAttackWave03, flag.TYPE_UNDERWORLD) or 100 > GetHealthPercent(Building.MGNest06) or 100 > GetHealthPercent(Building.MGNest07)
  DebugOut("GAMEFLOW SCRIPT DEBUG SIX - TRIGGER ATTACKS ON BRIDGE BEFORE AIRBASE")
  TriggerGunships = 2
  StopWrongWayMessage = 1
  if IsDead(Air_Vehicle.SEAirTransport01) == false then
    Kill(Air_Vehicle.SEAirTransport01, false)
    EndFrame()
  end
  Spawn(Air_Vehicle.SEAirTransport03)
  Spawn(Troop.SEGrunt50)
  Spawn(Troop.SEGrunt51)
  Spawn(Troop.SEGrunt52)
  PutUnitInVehicle(Troop.SEGrunt50, Air_Vehicle.SEAirTransport03, 3)
  PutUnitInVehicle(Troop.SEGrunt51, Air_Vehicle.SEAirTransport03, 4)
  PutUnitInVehicle(Troop.SEGrunt52, Air_Vehicle.SEAirTransport03, 5)
  EndFrame()
  SetActive(Ground_Vehicle.SELightTank11, constant.ACTIVE)
  GoToArea(Ground_Vehicle.SELightTank11, GetObjectXPosition(Waypoint.AttackWave03Path), GetObjectZPosition(Waypoint.AttackWave03Path), 10, 0, constant.ORDER_NORMAL)
  LandAirUnit(Air_Vehicle.SEAirTransport03, GetObjectXPosition(Waypoint.SEAirTransport03Land), GetObjectZPosition(Waypoint.SEAirTransport03Land), constant.ORDER_FORCED, true, 10, 225)
  SetUnitAI(Troop.SEGrunt50, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEGrunt51, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEGrunt52, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.TriggerAttackWave04, flag.TYPE_UNDERWORLD)
  DebugOut("GAMEFLOW SCRIPT DEBUG EIGHT - SEND IN SOLARS AT END OF BRIDGE BEFORE AIRBASE")
  SpawnAirbaseTroops = 1
  EndFrame()
  EndFrame()
  DebugOut("Attack Wave 04 Triggered")
  PhoneMessage(31, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  PhoneMessage(32, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  PhoneMessage(33, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  SetActive(Morphing_Building.ILairbase, constant.ACTIVE)
  GoToArea(Troop.SEMortar09, GetObjectXPosition(Waypoint.AttackWave03Path), GetObjectZPosition(Waypoint.AttackWave03Path), 100, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.SEMortar10, GetObjectXPosition(Waypoint.AttackWave03Path), GetObjectZPosition(Waypoint.AttackWave03Path), 100, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.SEAssault22, GetObjectXPosition(Waypoint.AttackWave03Path), GetObjectZPosition(Waypoint.AttackWave03Path), 80, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.SEAssault23, GetObjectXPosition(Waypoint.AttackWave03Path), GetObjectZPosition(Waypoint.AttackWave03Path), 80, 0, constant.ORDER_NORMAL)
  SetUnitAI(Troop.SEMortar09, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEMortar10, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEAssault22, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  SetUnitAI(Troop.SEAssault23, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.TriggerTankAmbush2, flag.TYPE_UNDERWORLD) or IsInArea(Ground_Vehicle.SELightTank09, Map_Zone.SetAmbushTank2Active) == false
  DebugOut("GAMEFLOW SCRIPT DEBUG NINE - SEND IN TANKS")
  POWReadyToBeTriggered = 1
  GoToArea(Ground_Vehicle.SELightTank09, GetObjectXPosition(Waypoint.SELightTank09PathEnd), GetObjectZPosition(Waypoint.SELightTank09PathEnd), 0, 0, constant.ORDER_NORMAL)
  SetUnitAI(Ground_Vehicle.SELightTank09, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
  WaitFor(2)
  SetActive(Ground_Vehicle.SELightTank09, constant.ACTIVE)
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.Airbase, flag.TYPE_UNDERWORLD)
  DebugOut("GAMEFLOW SCRIPT DEBUG TEN - SPAWN IN REST OF ENEMIES AFTER THE AIRBASE")
  SpawnEndTroops = 1
  while true do
    if GetInstallationOwner(Strategic_Installation.ILairbase) == constant.ARMY_UNDERWORLD and AirbaseCounterAttackTriggered == 0 then
      AirbaseCapturedByLegion = 1
      AirbaseCounterAttackTriggered = 1
      TechniqueObjectivesCompleted = TechniqueObjectivesCompleted + 1
      if IsDead(Air_Vehicle.SEAirTransport03) == false then
        Kill(Air_Vehicle.SEAirTransport03, false)
        EndFrame()
      end
      Spawn(Air_Vehicle.SEAirTransport04)
      Spawn(Troop.SEGrunt53)
      Spawn(Troop.SEGrunt54)
      Spawn(Troop.SEGrunt55)
      PutUnitInVehicle(Troop.SEGrunt53, Air_Vehicle.SEAirTransport04, 3)
      PutUnitInVehicle(Troop.SEGrunt54, Air_Vehicle.SEAirTransport04, 4)
      PutUnitInVehicle(Troop.SEGrunt55, Air_Vehicle.SEAirTransport04, 5)
      EndFrame()
      ClearMessageQueue()
      PhoneMessageWithObjective(34, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE, false, constant.SECONDARY_OBJECTIVE_COMPLETE)
      PhoneMessage(35, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Sad, constant.PLAYER_ONE)
      PhoneMessage(36, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Sad, constant.PLAYER_ONE)
      LandAirUnit(Air_Vehicle.SEAirTransport04, GetObjectXPosition(Waypoint.SEAirTransport04Land), GetObjectZPosition(Waypoint.SEAirTransport04Land), constant.ORDER_FORCED, true, 10, 250)
      SetUnitAI(Troop.SEGrunt53, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
      SetUnitAI(Troop.SEGrunt54, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
      SetUnitAI(Troop.SEGrunt55, constant.AI_ATTACK_STYLE, constant.ATTACKSTYLE_AGGRESSIVE)
      Spawn(Air_Vehicle.SEAirTransport02)
      Teleport(Air_Vehicle.SEAirTransport02, -350, -490, 40, 10)
      LandAirUnit(Air_Vehicle.SEAirTransport02, GetObjectXPosition(Waypoint.SEAirTransport02Land), GetObjectZPosition(Waypoint.SEAirTransport02Land), constant.ORDER_FORCED, true, 10, 315)
      EndFrame()
    end
    EndFrame()
  end
end
