function POW_Artillery(owner)
  POWArtilleryScript = owner
  SetActive(Troop.ILArtillery01Pilot01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.ILArtillery01Pilot02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.ILArtillery02Pilot01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.ILArtillery02Pilot02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILArtillery01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILArtillery02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetUnitInvulnerable(Troop.ILArtillery01Pilot01, true)
  SetUnitInvulnerable(Troop.ILArtillery01Pilot02, true)
  SetUnitInvulnerable(Troop.ILArtillery02Pilot01, true)
  SetUnitInvulnerable(Troop.ILArtillery02Pilot02, true)
  SetUnitInvulnerable(Ground_Vehicle.ILArtillery01, true)
  SetUnitInvulnerable(Ground_Vehicle.ILArtillery02, true)
  SetUnitInvulnerable(Destroyable_Object.POW02a, true)
  SetUnitInvulnerable(Destroyable_Object.POW02b, true)
  SetUnitInvulnerable(Destroyable_Object.POW02c, true)
  SetUnitInvulnerable(Destroyable_Object.POW02d, true)
  SetUnitInvulnerable(Destroyable_Object.POW02e, true)
  SetUnitInvulnerable(Destroyable_Object.POW02f, true)
  SetUnitInvulnerable(Destroyable_Object.POW02g, true)
  SetUnitInvulnerable(Destroyable_Object.POW02h, true)
  SetUnitInvulnerable(Destroyable_Object.POW02i, true)
  SetUnitInvulnerable(Destroyable_Object.POW02j, true)
  SetUnitInvulnerable(Destroyable_Object.POW02k, true)
  SetUnitInvulnerable(Destroyable_Object.POW02l, true)
  SetUnitInvulnerable(Destroyable_Object.POW02m, true)
  SetUnitInvulnerable(Destroyable_Object.POW02n, true)
  repeat
    EndFrame()
  until IntroCutsceneEnd == 1
  WaitFor(10)
  repeat
    EndFrame()
  until IsDead(Destroyable_Object.POW02a) or IsDead(Destroyable_Object.POW02b) or IsDead(Destroyable_Object.POW02c) or IsDead(Destroyable_Object.POW02d) or IsDead(Destroyable_Object.POW02e) or IsDead(Destroyable_Object.POW02f) or IsDead(Destroyable_Object.POW02g) or IsDead(Destroyable_Object.POW02h) or IsDead(Destroyable_Object.POW02i) or IsDead(Destroyable_Object.POW02j) or IsDead(Destroyable_Object.POW02k) or IsDead(Destroyable_Object.POW02l) or IsDead(Destroyable_Object.POW02m) or IsDead(Destroyable_Object.POW02n) or IsDead(Building.AmmoDump02)
  TechniqueObjectivesCompleted = TechniqueObjectivesCompleted + 1
  Kill(Destroyable_Object.POW02a)
  Kill(Destroyable_Object.POW02b)
  Kill(Destroyable_Object.POW02c)
  Kill(Destroyable_Object.POW02d)
  Kill(Destroyable_Object.POW02e)
  Kill(Destroyable_Object.POW02f)
  Kill(Destroyable_Object.POW02g)
  Kill(Destroyable_Object.POW02h)
  Kill(Destroyable_Object.POW02i)
  Kill(Destroyable_Object.POW02j)
  Kill(Destroyable_Object.POW02k)
  Kill(Destroyable_Object.POW02l)
  Kill(Destroyable_Object.POW02m)
  Kill(Destroyable_Object.POW02n)
  Kill(Building.AmmoDump02)
  EndFrame()
  ArtilleryJoined = 1
  Kill(Troop.SEGrunt13)
  Kill(Troop.SEGrunt14)
  SetObjectiveData(Objective.POWArtillery, constant.OBJECTIVE_DATA_STATE, 1)
  EnterVehicle(Troop.ILArtillery01Pilot01, Ground_Vehicle.ILArtillery01, 0)
  EnterVehicle(Troop.ILArtillery01Pilot02, Ground_Vehicle.ILArtillery01, 1)
  EnterVehicle(Troop.ILArtillery02Pilot01, Ground_Vehicle.ILArtillery02, 0)
  EnterVehicle(Troop.ILArtillery02Pilot02, Ground_Vehicle.ILArtillery02, 1)
  repeat
    EndFrame()
  until GetNumSeatsFree(Ground_Vehicle.ILArtillery01) == 0 and GetNumSeatsFree(Ground_Vehicle.ILArtillery02) == 0
  WaitFor(1)
  SetActive(Ground_Vehicle.ILArtillery01, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.ILArtillery02, constant.ACTIVE, constant.ADJUST_WEAPON)
  AddToGroup(Unit_Group.PlayerUnits, Ground_Vehicle.ILArtillery01)
  AddToGroup(Unit_Group.PlayerUnits, Ground_Vehicle.ILArtillery02)
end
