function JW_Cutscene_02_Naval_Landings(owner)
  TransportLandingCutsceneGlobal = owner
  Despawn(Ground_Vehicle.NavalCutsceneTank01)
  Despawn(Ground_Vehicle.NavalCutsceneTank02)
  repeat
    EndFrame()
  until transports == 2
  TransportLandingCutsceneStarted = 1
  SetObjectiveData(Objective_Marker.PrimaryObjectEscortTransport01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.PrimaryObjectEscortTransport02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.PrimaryObjectEscortTransport03, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  Teleport(Water_Vehicle.SEBattleship01, -1400, -250, 90)
  Teleport(Water_Vehicle.SEBattleship02, -1300, -250, 90)
  Teleport(Water_Vehicle.SEFrigate01, -1200, -250, 90)
  Teleport(Water_Vehicle.SEFrigate02, -1100, -250, 90)
  StopAndGuard(Water_Vehicle.SEBattleship01)
  StopAndGuard(Water_Vehicle.SEBattleship02)
  StopAndGuard(Water_Vehicle.SEFrigate01)
  StopAndGuard(Water_Vehicle.SEFrigate02)
  EnableWeapon(Water_Vehicle.SEBattleship01, 0)
  EnableWeapon(Water_Vehicle.SEBattleship02, 0)
  EnableWeapon(Water_Vehicle.SEFrigate01, 0)
  EnableWeapon(Water_Vehicle.SEFrigate02, 0)
  Teleport(Water_Vehicle.SEBattleship01, LandingTeleport04X, LandingTeleport04Z, 90)
  Teleport(Water_Vehicle.SEBattleship02, LandingTeleport05X, LandingTeleport05Z, 90)
  Teleport(Water_Vehicle.SEFrigate01, LandingTeleport06X, LandingTeleport06Z, 90)
  Teleport(Water_Vehicle.SEFrigate02, LandingTeleport07X, LandingTeleport07Z, 90)
  Spawn(Ground_Vehicle.NavalCutsceneTank01)
  Spawn(Ground_Vehicle.NavalCutsceneTank02)
  EnableWeapon(Ground_Vehicle.NavalCutsceneTank01, 0)
  EnableWeapon(Ground_Vehicle.NavalCutsceneTank02, 0)
  SetCamera(Camera.CutsceneCamera)
  CameraSetWaypoint(Camera.CutsceneCamera, Waypoint.WesternFrontierLandingCutsceneWaypoint01)
  CameraSetTarget(Camera.CutsceneCamera, Waypoint.WesternFrontierLandingCutsceneTarget01)
  CameraSetFOV(Camera.CutsceneCamera, 70, constant.IMMEDIATE, 100, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(3)
  PhoneMessageWithObjective(22, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE, 0, constant.NEW_PRIMARY_OBJECTIVE)
  PhoneMessage(39, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
  WaitFor(1.1)
  GoToArea(Troop.WesternFrontierGrunt07, -445, -40, 15, constant.ORDER_FORCED)
  GoToArea(Troop.WesternFrontierGrunt08, -445, -40, 15, constant.ORDER_FORCED)
  GoToArea(Troop.WesternFrontierGrunt09, -445, -40, 15, constant.ORDER_FORCED)
  GoToArea(Troop.WesternFrontierGrunt10, -445, -40, 15, constant.ORDER_FORCED)
  GoToArea(Troop.WesternFrontierGrunt11, -445, -40, 15, constant.ORDER_FORCED)
  GoToArea(Troop.WesternFrontierGrunt12, -445, -40, 15, constant.ORDER_FORCED)
  WaitFor(2.9)
  GoToArea(Ground_Vehicle.NavalCutsceneTank01, GetObjectXPosition(Waypoint.NavalTankWaypoint), GetObjectZPosition(Waypoint.NavalTankWaypoint), 1, constant.ORDER_FORCED)
  GoToArea(Ground_Vehicle.NavalCutsceneTank02, GetObjectXPosition(Waypoint.NavalTankWaypoint), GetObjectZPosition(Waypoint.NavalTankWaypoint), 1, constant.ORDER_FORCED)
  CameraSetFOV(Camera.CutsceneCamera, 40, constant.SMOOTH, 1, constant.NO_WAIT)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  TransportLandingCutsceneEnd = 1
end
