function JW_Despawn_Units(owner)
  SetFunctionIndicatorState(true)
  Despawn(Water_Vehicle.SEBattleship03)
  Despawn(Building.WesternFrontierSeaTransportBeached01)
  Despawn(Building.WesternFrontierSeaTransportBeached02)
  Kill(Air_Vehicle.AngloAirTransport01)
  Despawn(Air_Vehicle.AngloAirTransport02)
  Despawn(Air_Vehicle.SolarAirTransport01)
  Despawn(Air_Vehicle.SolarAirTransport02)
  Despawn(Air_Vehicle.AngloBomber06)
  SetUnitInvulnerable(Troop.AngloGrunt01, true)
  SetUnitInvulnerable(Troop.AngloGrunt02, true)
  SetUnitInvulnerable(Troop.AngloGrunt03, true)
  Despawn(Troop.AngloGrunt01)
  Despawn(Troop.AngloGrunt02)
  Despawn(Troop.AngloGrunt03)
  Despawn(Troop.SolarGrunt01)
  Despawn(Troop.SolarGrunt02)
  Despawn(Troop.SolarGrunt03)
  Despawn(Troop.SolarGrunt04)
  Despawn(Troop.SolarGrunt05)
  Despawn(Troop.SE_Grunt_06)
  Despawn(Troop.SE_Grunt_07)
  Despawn(Troop.SE_Grunt_08)
  Despawn(Troop.SE_Grunt_09)
  Despawn(Troop.SE_Grunt_10)
  Despawn(Ground_Vehicle.SolarAntiAirTank01)
  Despawn(Ground_Vehicle.SolarLightTank01)
  Despawn(Ground_Vehicle.AngloLightTank03)
  Despawn(Air_Vehicle.AngloBomber07)
  Despawn(Air_Vehicle.AngloBomber08)
  Despawn(Air_Vehicle.AngloBomber09)
  Despawn(Air_Vehicle.AngloBomber10)
  Despawn(Troop.AngloFlamer10)
  Despawn(Troop.AngloFlamer11)
  Despawn(Troop.AngloFlamer07)
  Despawn(Troop.AngloFlamer08)
  Despawn(Troop.AngloFlamer09)
  Despawn(Ground_Vehicle.AngloLightTank05)
  Despawn(Building.Entity270050152)
  Despawn(Building.Entity270050153)
  Despawn(Ground_Vehicle.AngloLightTank06, true)
  Despawn(Troop.AngloFlamer12, true)
  Despawn(Troop.AngloFlamer13, true)
  Despawn(Troop.AngloFlamer14, true)
  Despawn(Troop.AngloFlamer15, true)
  Despawn(Troop.AngloBazookaVet06, true)
  Despawn(Troop.AngloBazookaVet07, true)
  Despawn(Troop.AngloBazookaVet08, true)
  Despawn(Troop.AngloBazookaVet09, true)
  Despawn(Building.FlightPathBomber)
  Despawn(Building.FlightPathBomber02)
  Despawn(Building.FlightPathBomber03)
  Despawn(Air_Vehicle.FlightPathBomber)
  Despawn(Air_Vehicle.FlightPathBomber02)
  Despawn(Air_Vehicle.FlightPathBomber03)
  Despawn(Troop.Airbase_Grunt_1, true)
  Despawn(Troop.Airbase_Grunt_2, true)
  Despawn(Water_Vehicle.EndCutsceneFrigate01)
  Despawn(Water_Vehicle.EndCutsceneFrigate02)
  Despawn(Water_Vehicle.EndCutsceneFrigate03)
  Despawn(Air_Vehicle.EndCutsceneBomber01)
  Despawn(Air_Vehicle.EndCutsceneBomber02)
  Despawn(Air_Vehicle.EndCutsceneBomber03)
  repeat
    EndFrame()
  until SeaUnitsWithdrawCutsceneEnd == 1
  repeat
    EndFrame()
  until NumItemsInArea(305, -5, 15, flag.TYPE_SOLAR) > 0
  Spawn(Troop.Airbase_Grunt_1)
  Spawn(Troop.Airbase_Grunt_2)
  Spawn(Air_Vehicle.AngloBomber07)
  Spawn(Air_Vehicle.AngloBomber08)
  Spawn(Troop.AngloFlamer10)
  Spawn(Troop.AngloFlamer11)
  Spawn(Ground_Vehicle.AngloLightTank05)
end
