function C3B_HealActors(owner)
  repeat
    SetHealthPercent(Troop.Xgrunt1, 99)
    SetHealthPercent(Troop.Xgrunt2, 99)
    SetHealthPercent(Troop.Xgrunt3, 99)
    SetHealthPercent(Troop.Xgrunt4, 99)
    SetHealthPercent(Troop.Xgrunt5, 99)
    SetHealthPercent(Troop.Xgrunt6, 99)
    SetHealthPercent(Troop.Xgrunt7, 99)
    SetHealthPercent(Troop.Xgrunt8, 99)
    SetHealthPercent(Troop.Xgrunt9, 9)
    EndFrame()
    SetHealthPercent(Troop.Ssearchlight0001, 99)
    SetHealthPercent(Troop.Ssearchlight0002, 99)
    SetHealthPercent(Troop.SGrunt3, 99)
    SetHealthPercent(Troop.SGrunt4, 99)
    EndFrame()
    SetHealthPercent(Troop.SEHose1, 99)
    SetHealthPercent(Troop.SEHose2, 99)
    SetHealthPercent(Troop.SEHose3, 99)
    SetHealthPercent(Troop.SEHose4, 99)
    EndFrame()
    SetHealthPercent(Troop.SE_CGN01, 99)
    SetHealthPercent(Troop.SE_CGN02, 99)
    SetHealthPercent(Troop.SE_CGN03, 99)
    SetHealthPercent(Troop.SE_CGN04, 99)
    EndFrame()
    SetHealthPercent(Troop.SGrunt9, 99)
    SetHealthPercent(Troop.SGrunt2, 99)
    SetHealthPercent(Troop.SGrunt18, 99)
    SetHealthPercent(Troop.SGrunt19, 99)
    SetHealthPercent(Troop.SGrunt17, 99)
    SetHealthPercent(Troop.SGrunt10, 99)
    SetHealthPercent(Troop.SGrunt15, 99)
    SetHealthPercent(Troop.SGrunt16, 99)
    EndFrame()
    SetHealthPercent(Ground_Vehicle.SHeavyTank1, 99)
    SetHealthPercent(Ground_Vehicle.SHeavyTank2, 99)
    SetHealthPercent(Ground_Vehicle.SHeavyTank3, 99)
    EndFrame()
  until LevelState == 1
end
