function CutScene(owner)
  cutscene = owner
  AttackTarget(Ground_Vehicle.XArt1, Troop.SGrunt2, constant.ORDER_FORCED)
  AttackTarget(Ground_Vehicle.XArt2, Troop.SGrunt3, constant.ORDER_FORCED)
  FreezePlayer()
  StartIntro()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Troop.SE_CGN02)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cut1)
  PhoneMessage(0, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Sad)
  PhoneMessage(1, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Sad)
  WaitFor(12)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam2)
  Despawn(Ground_Vehicle.SHeavyTank1)
  Despawn(Ground_Vehicle.SHeavyTank2)
  Despawn(Ground_Vehicle.SHeavyTank3)
  EndFrame()
  Spawn(Ground_Vehicle.SHeavyTank1)
  Spawn(Ground_Vehicle.SHeavyTank2)
  Spawn(Ground_Vehicle.SHeavyTank3)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Cut2)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Happy)
  PhoneMessage(3, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Happy)
  WaitFor(12)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam3)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Happy)
  PhoneMessage(5, 0, constant.ARMY_SOLAR, 4, SpriteID.CO_SE_Leiqo_Happy)
  WaitFor(12)
  cutscene = 1
end
