function s2_cutscene(owner)
  cutsceneStart = owner
  DebugOut("Cutscene Start ID", cutsceneStart)
  StartIntro()
  FreezePlayer()
  SetCamera(Camera.CutsceneCamera0001)
  CameraSetFOV(Camera.CutsceneCamera0001, 85, constant.IMMEDIATE)
  CameraSetWaypoint(Camera.CutsceneCamera0001, Waypoint.Entity0227)
  CameraSetTarget(Camera.CutsceneCamera0001, Waypoint.Waypoint0075)
  CameraSetFOV(Camera.CutsceneCamera0001, 50, constant.SMOOTH, 5, constant.NO_WAIT)
  PhoneMessage(0, constant.ID_NONE, 0, 8, SpriteID.CO_WF_Austin_Happy)
  EnterVehicle(Troop.XgruntCutscene0001, Air_Vehicle.XgunshipCutscene0001)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutsceneCamera0002)
  CameraSetWaypoint(Camera.CutsceneCamera0002, Waypoint.Entity0222)
  CameraSetTarget(Camera.CutsceneCamera0002, Waypoint.Entity0223)
  ClearMessageQueue()
  PhoneMessage(1, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Austin_Happy)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  EnterVehicle(Troop.WFgruntTcopterCutscene0001, Air_Vehicle.WFtcopterCutscene0001)
  WaitFor(2)
  GoToArea(Air_Vehicle.XgunshipCutscene0001, -300, -200, 20, 0, constant.ORDER_FORCED)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutsceneCamera0003)
  CameraSetWaypoint(Camera.CutsceneCamera0003, Waypoint.Entity0206)
  CameraSetTarget(Camera.CutsceneCamera0003, Waypoint.Entity0213)
  ClearMessageQueue()
  PhoneMessage(2, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Austin_Happy)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutsceneCamera0005)
  CameraSetFOV(Camera.CutsceneCamera0005, 30, constant.IMMEDIATE)
  CameraSetWaypoint(Camera.CutsceneCamera0005, Waypoint.Entity0204)
  CameraSetTarget(Camera.CutsceneCamera0005, Waypoint.Entity0007)
  CameraSetFOV(Camera.CutsceneCamera0005, 70, constant.SMOOTH, 5, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(4)
  GoToArea(Air_Vehicle.WFtcopterCutscene0001, 100, -1100, 20, 0, constant.ORDER_FORCED)
  WaitFor(4)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.PlayerCamera0001)
  cutsceneStart = 1
  Despawn(Troop.XgruntCutscene0001)
  Despawn(Troop.XgruntCutscene0002)
  Despawn(Air_Vehicle.XgunshipCutscene0001)
  Despawn(Air_Vehicle.WFtcopterCutscene0001)
  Despawn(Troop.WFgruntTcopterCutscene0001)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  UnfreezePlayer()
  StartScoringTimer()
  ClearMessageQueue()
  PhoneMessage(3, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Austin_Happy)
  s2_Global_Variable = 1
  DebugOut("s2 Global Variable = ", s2_Global_Variable)
  EndFrame()
  return
end
