function GlobalVariables(owner)
  SeaFortDead = 0
  Player1Army = flag.TYPE_SOLAR
  Player2Army = flag.TYPE_ANGLO
  CurrentPlayer1SpawnX = GetObjectXPosition(Waypoint.SolarSpawnPoint01)
  CurrentPlayer1SpawnZ = GetObjectZPosition(Waypoint.SolarSpawnPoint01)
  CurrentPlayer1WaterSpawnX = GetObjectXPosition(Waypoint.SolarSpawnPoint01)
  CurrentPlayer1WaterSpawnZ = GetObjectZPosition(Waypoint.SolarSpawnPoint01)
  CurrentPlayer2SpawnX = GetObjectXPosition(Waypoint.AngloSpawnPoint01)
  CurrentPlayer2SpawnZ = GetObjectZPosition(Waypoint.AngloSpawnPoint01)
  CurrentPlayer2WaterSpawnX = GetObjectXPosition(Waypoint.AngloSpawnPoint01)
  CurrentPlayer2WaterSpawnZ = GetObjectZPosition(Waypoint.AngloSpawnPoint01)
  CurrentPlayer1Direction = 315
  CurrentPlayer2Direction = 134
  Player1UnitTimer = 20
  Player1GruntTimer = 10
  Player2UnitTimer = 20
  Player2GruntTimer = 10
  Player1LastGruntRevived = 0
  Player2LastGruntRevived = 0
  missionend = 0
  TimerPaused = 0
  netvariable.player1.Cutscene01Skip = 0
  netvariable.player2.Cutscene01Skip = 0
  netvariable.player1.Cutscene02Skip = 0
  netvariable.player2.Cutscene02Skip = 0
  netvariable.player1.Cutscene03Skip = 0
  netvariable.player2.Cutscene03Skip = 0
  netvariable.player1.CutsceneEnd = 0
  netvariable.player1.windsorspeech = 0
  netvariable.player1.navaltransport = 0
  KillCutScene01 = 0
  KillCutScene02 = 0
  KillCutScene03 = 0
  KillCutScene04 = 0
  Cutscene01End = 0
  Cutscene02End = 0
  Cutscene03End = 0
  netvariable.player1.Player1 = 0
  SeaTransportUnit01X = GetObjectXPosition(Waypoint.BeachAngloSeaTransport01)
  SeaTransportUnit01Z = GetObjectZPosition(Waypoint.BeachAngloSeaTransport01)
  SeaTransportUnit02X = GetObjectXPosition(Waypoint.BeachAngloSeaTransport02)
  SeaTransportUnit02Z = GetObjectZPosition(Waypoint.BeachAngloSeaTransport02)
  AngloGruntTeleport01X = GetObjectXPosition(Waypoint.AngloGruntTeleport01)
  AngloGruntTeleport01Z = GetObjectZPosition(Waypoint.AngloGruntTeleport01)
  AngloGruntTeleport02X = GetObjectXPosition(Waypoint.AngloGruntTeleport02)
  AngloGruntTeleport02Z = GetObjectZPosition(Waypoint.AngloGruntTeleport02)
  AngloGruntTeleport03X = GetObjectXPosition(Waypoint.AngloGruntTeleport03)
  AngloGruntTeleport03Z = GetObjectZPosition(Waypoint.AngloGruntTeleport03)
  AngloGruntTeleport04X = GetObjectXPosition(Waypoint.AngloGruntTeleport04)
  AngloGruntTeleport04Z = GetObjectZPosition(Waypoint.AngloGruntTeleport04)
  AngloChainVetTeleport01X = GetObjectXPosition(Waypoint.AngloChainVetTeleport01)
  AngloChainVetTeleport01Z = GetObjectZPosition(Waypoint.AngloChainVetTeleport01)
  AngloChainVetTeleport02X = GetObjectXPosition(Waypoint.AngloChainVetTeleport02)
  AngloChainVetTeleport02Z = GetObjectZPosition(Waypoint.AngloChainVetTeleport02)
  AngloChainVetTeleport03X = GetObjectXPosition(Waypoint.AngloChainVetTeleport03)
  AngloChainVetTeleport03Z = GetObjectZPosition(Waypoint.AngloChainVetTeleport03)
  AngloChainVetTeleport04X = GetObjectXPosition(Waypoint.AngloChainVetTeleport04)
  AngloChainVetTeleport04Z = GetObjectZPosition(Waypoint.AngloChainVetTeleport04)
  AngloBazookaTeleport01X = GetObjectXPosition(Waypoint.AngloBazookaTeleport01)
  AngloBazookaTeleport01Z = GetObjectZPosition(Waypoint.AngloBazookaTeleport01)
  AngloBazookaTeleport02X = GetObjectXPosition(Waypoint.AngloBazookaTeleport02)
  AngloBazookaTeleport02Z = GetObjectZPosition(Waypoint.AngloBazookaTeleport02)
  AngloBazookaTeleport03X = GetObjectXPosition(Waypoint.AngloBazookaTeleport03)
  AngloBazookaTeleport03Z = GetObjectZPosition(Waypoint.AngloBazookaTeleport03)
  AngloBazookaTeleport04X = GetObjectXPosition(Waypoint.AngloBazookaTeleport04)
  AngloBazookaTeleport04Z = GetObjectZPosition(Waypoint.AngloBazookaTeleport04)
  AngloHeavyTankTeleport01X = GetObjectXPosition(Waypoint.AngloHeavyTankTeleport01)
  AngloHeavyTankTeleport01Z = GetObjectZPosition(Waypoint.AngloHeavyTankTeleport01)
  AngloHeavyTankTeleport02X = GetObjectXPosition(Waypoint.AngloHeavyTankTeleport02)
  AngloHeavyTankTeleport02Z = GetObjectZPosition(Waypoint.AngloHeavyTankTeleport02)
  Objective01 = 0
  Objective02 = 0
  Objective03 = 0
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    OutOfBoundsMessageInfo(489, constant.ARMY_SOLAR, 6, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    OutOfBoundsMessageInfo(494, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_TWO)
  end
end
