function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.cutscenecamplayer1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.IntroCutsceneWF2target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.IntroCutsceneWF2)
    CameraSetFOV(Camera.cutscenecamplayer1, 45, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(3, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneWFTroop1, 163, -123, 0, 10)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop2, 155, -128, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop1, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop3, 157, -132, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop2, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop4, 164, -132, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop3, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop5, 160, -122, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop4, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop6, 160, -128, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop5, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop7, 157, -135, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop6, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop8, 154, -124, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop7, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop10, 167, -126, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop8, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneWFTroop11, 161, -133, 0, 10)
    FollowWaypoint(Troop.CutsceneWFTroop10, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    FollowWaypoint(Troop.CutsceneWFTroop11, Waypoint.WFTroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(2.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Troop.CutsceneWFTroop1)
    Despawn(Troop.CutsceneWFTroop2)
    Despawn(Troop.CutsceneWFTroop3)
    Despawn(Troop.CutsceneWFTroop4)
    Despawn(Troop.CutsceneWFTroop5)
    Despawn(Troop.CutsceneWFTroop6)
    Despawn(Troop.CutsceneWFTroop7)
    Despawn(Troop.CutsceneWFTroop8)
    Despawn(Troop.CutsceneWFTroop10)
    Despawn(Troop.CutsceneWFTroop11)
    Spawn(Troop.WF_Player)
    Spawn(Troop.WFbazooka1)
    Spawn(Troop.WFbazooka2)
    Spawn(Troop.WFbazooka3)
    Spawn(Troop.WF_AAvet1)
    Spawn(Troop.WF_Grunt1)
    Spawn(Troop.WF_Grunt2)
    Spawn(Troop.WF_Grunt3)
    Spawn(Troop.WF_Grunt4)
    Spawn(Troop.WF_Grunt5)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.IntroCutsceneWF3target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.IntroCutsceneWF3)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(9)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.IntroCutscene4)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.IntroCutsceneWF4)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(7, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.cutscenecamplayer2)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.IntroCutsceneAI2target)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.IntroCutsceneAI2)
    CameraSetFOV(Camera.cutscenecamplayer2, 45, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(4, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_TWO)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneAITroop1, -161, -110, 0, 10)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop2, -166, -111, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop1, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop3, -166, -104, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop2, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop4, -161, -115, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop3, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop5, -161, -103, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop4, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop6, -155, -113, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop5, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop7, -162, -117, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop6, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop9, -153, -109, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop7, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop10, -161, -112, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop9, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    ReviveDeadUnit(Troop.CutsceneAITroop12, -163, -116, 0, 10)
    FollowWaypoint(Troop.CutsceneAITroop10, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(0.5)
    FollowWaypoint(Troop.CutsceneAITroop12, Waypoint.AITroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(2.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Troop.CutsceneAITroop1)
    Despawn(Troop.CutsceneAITroop2)
    Despawn(Troop.CutsceneAITroop3)
    Despawn(Troop.CutsceneAITroop4)
    Despawn(Troop.CutsceneAITroop5)
    Despawn(Troop.CutsceneAITroop6)
    Despawn(Troop.CutsceneAITroop7)
    Despawn(Troop.CutsceneAITroop9)
    Despawn(Troop.CutsceneAITroop10)
    Despawn(Troop.CutsceneAITroop12)
    Spawn(Troop.AI_Player)
    Spawn(Troop.AIbazooka1)
    Spawn(Troop.AIbazooka2)
    Spawn(Troop.AIbazooka3)
    Spawn(Troop.AI_AA_vet1)
    Spawn(Troop.AI_Grunt1)
    Spawn(Troop.AI_Grunt2)
    Spawn(Troop.AI_Grunt3)
    Spawn(Troop.AI_Grunt4)
    Spawn(Troop.AI_Grunt5)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.IntroCutsceneAI3target)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.IntroCutsceneAI3)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(6, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_TWO)
    WaitFor(9)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.IntroCutscene4)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.IntroCutsceneAI4target)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(8, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_TWO)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
