function Ice_Station_X_Cutscene01(owner)
  Cutscene01Dead = owner
  Despawn(Air_Vehicle.XN_AirTransport01_Cutscene)
  Despawn(Air_Vehicle.XN_AirTransport02_Cutscene)
  Despawn(Air_Vehicle.XN_AirTransport03_Cutscene)
  Despawn(Ground_Vehicle.XN_AAVehicle01_Cutscene)
  Despawn(Troop.Cutscene01_Shot03_XN_AirTransport01_Pilot01)
  Despawn(Troop.Cutscene01_Shot03_XN_AirTransport02_Pilot01)
  Kill(Ground_Vehicle.WF_LightTank01)
  Kill(Troop.WF_Hose03)
  Kill(Troop.WF_AntiArmour02)
  SetInvulnerable(flag.TYPE_TUNDRAN, 1)
  SetInvulnerable(flag.TYPE_XYLVANIAN, 1)
  StartIntro()
  SetCamera(Camera.Cutscene01_Shot01)
  CameraSetTarget(Camera.Cutscene01_Shot01, Waypoint.Cutscene01_Shot01_Target01)
  CameraSetWaypoint(Camera.Cutscene01_Shot01, Waypoint.Cutscene01_Shot01_Spline01)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  Spawn(Air_Vehicle.XN_AirTransport01_Cutscene)
  Spawn(Air_Vehicle.XN_AirTransport02_Cutscene)
  Spawn(Air_Vehicle.XN_AirTransport03_Cutscene)
  PhoneMessage(0, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Ghost_Gorgi_Sad, constant.PLAYER_ONE)
  PhoneMessage(1, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
  WaitFor(1)
  Cutscene01Begun = 1
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.XN_AirTransport01_Cutscene)
  Despawn(Air_Vehicle.XN_AirTransport02_Cutscene)
  Despawn(Air_Vehicle.XN_AirTransport03_Cutscene)
  SetCamera(Camera.Cutscene02_Shot02)
  CameraSetTarget(Camera.Cutscene02_Shot02, Waypoint.Cutscene02_Shot02_Target01)
  CameraSetWaypoint(Camera.Cutscene02_Shot02, Waypoint.Cutscene02_Shot02_Spline01)
  Spawn(Ground_Vehicle.XN_AAVehicle01_Cutscene)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  WaitFor(10)
  FollowWaypoint(Ground_Vehicle.XN_AAVehicle01_Cutscene, Waypoint.XN_AAVehicle01_Cutscene, 0, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetViewDistanceAdjustment(600, 10)
  SetCamera(Camera.Cutscene02_Shot03)
  CameraSetTarget(Camera.Cutscene02_Shot03, Waypoint.Cutscene02_Shot03_Target01)
  CameraSetWaypoint(Camera.Cutscene02_Shot03, Waypoint.Cutscene02_Shot03_Spline01)
  Spawn(Troop.Cutscene01_Shot03_XN_AirTransport01_Pilot01)
  Spawn(Troop.Cutscene01_Shot03_XN_AirTransport02_Pilot01)
  PutUnitInVehicle(Troop.Cutscene01_Shot03_XN_AirTransport01_Pilot01, Air_Vehicle.Cutscene01_Shot03_XN_AirTransport01, 0)
  GoToArea(Air_Vehicle.Cutscene01_Shot03_XN_AirTransport01, GetObjectXPosition(Waypoint.Cutscene01_Shot03_XN_AirTransport01), GetObjectZPosition(Waypoint.Cutscene01_Shot03_XN_AirTransport01), 5, 0, constant.ORDER_FORCED)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Prison_Ubel_Happy, constant.PLAYER_ONE)
  PutUnitInVehicle(Troop.Cutscene01_Shot03_XN_AirTransport02_Pilot01, Air_Vehicle.Cutscene01_Shot03_XN_AirTransport02, 0)
  WaitFor(0.5)
  GoToArea(Air_Vehicle.Cutscene01_Shot03_XN_AirTransport02, GetObjectXPosition(Waypoint.Cutscene01_Shot03_XN_AirTransport01), GetObjectZPosition(Waypoint.Cutscene01_Shot03_XN_AirTransport01), 5, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetViewDistanceAdjustment(-1, 10)
  SetCamera(Camera.Cutscene01_Shot03)
  CameraSetTarget(Camera.Cutscene01_Shot03, Waypoint.Cutscene01_Shot03_Target01)
  CameraSetWaypoint(Camera.Cutscene01_Shot03, Waypoint.Cutscene01_Shot03_Spline01)
  CameraSetFOV(Camera.Cutscene02_Shot03, 60, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.Cutscene02_Shot03, 75, constant.SMOOTH, 1, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(4, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene01_Shot04)
  CameraSetTarget(Camera.Cutscene01_Shot04, Waypoint.Cutscene01_Shot04_Target01)
  CameraSetWaypoint(Camera.Cutscene01_Shot04, Waypoint.Cutscene01_Shot04_Spline01)
  CameraSetFOV(Camera.Cutscene01_Shot04, 60, constant.IMMEDIATE, constant.NO_WAIT)
  CameraSetFOV(Camera.Cutscene01_Shot04, 75, constant.SMOOTH, 1, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(5, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  Cutscene01Finished = 1
end
