function Cutscene_01_Intro(owner)
  cutkiller = owner
  Despawn(Troop.AI_Beach_Grunt_5)
  Despawn(Troop.AI_Beach_Grunt_6)
  Despawn(Troop.Entity260024501)
  Despawn(Troop.Entity260024498)
  Despawn(Troop.Entity260024499)
  Despawn(Troop.Entity260024514)
  Despawn(Troop.CS_Grunt_1)
  Despawn(Troop.CS_Grunt_2)
  Despawn(Troop.CS_Grunt_3)
  Despawn(Troop.CS_Grunt_4)
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  SetInvulnerable(flag.TYPE_ANGLO, 1)
  local tank = 0
  local driver1 = 0
  local driver2 = 0
  Despawn(Ground_Vehicle.SE_Beach_Tank_2)
  Despawn(Troop.SE_Grunt_1)
  Despawn(Troop.SE_Grunt_2)
  Despawn(Troop.SE_Grunt_3)
  Despawn(Troop.SE_Grunt_4)
  Despawn(Troop.SE_Grunt_5)
  Despawn(Troop.SE_Grunt_11)
  Despawn(Troop.SE_Grunt_12)
  Despawn(Building.SE_Sea_Transport_1)
  Despawn(Building.SE_Sea_Transport_2)
  Despawn(Building.SE_Sea_Transport_3)
  Despawn(Water_Vehicle.CS_Sea_Transport_1)
  Despawn(Water_Vehicle.CS_Sea_Transport_2)
  Despawn(Water_Vehicle.CS_Sea_Transport_3)
  Despawn(Ground_Vehicle.AI_Beach_Tank_1, false)
  Despawn(Ground_Vehicle.AI_Beach_Tank_2, false)
  Despawn(Ground_Vehicle.shot_0, false)
  Despawn(Ground_Vehicle.shot_1, false)
  Despawn(Ground_Vehicle.shot_2, false)
  Despawn(Ground_Vehicle.shot_3, false)
  Despawn(Ground_Vehicle.shot_4, false)
  Despawn(Ground_Vehicle.shot_5, false)
  GoToArea(Troop.AI_Intro_Grunt_1, -130, 1240, 10)
  GoToArea(Troop.AI_Intro_Grunt_2, -150, 1250, 10)
  GoToArea(Troop.AI_Intro_Grunt_3, -115, 1230, 10)
  GoToArea(Troop.AI_Intro_Grunt_4, -160, 1245, 10)
  GoToArea(Troop.AI_Intro_Grunt_5, -170, 1255, 10)
  GoToArea(Troop.AI_Intro_Grunt_6, -135, 1230, 10)
  GoToArea(Troop.AI_Intro_Grunt_7, -155, 1235, 10)
  EnterVehicle(Troop.AI_Intro_AT_1_Driver, Air_Vehicle.AI_Intro_Air_Transport_1, constant.ORDER_FORCED)
  EnterVehicle(Troop.AI_Intro_AT_2_Driver, Air_Vehicle.AI_Intro_Air_Transport_2, constant.ORDER_FORCED)
  SetHealthPercent(Ground_Vehicle.SE_LT1, 100)
  SetHealthPercent(Ground_Vehicle.SE_LT2, 100)
  SetHealthPercent(Ground_Vehicle.AI_Light_Tank_b, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_1, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_2, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_3, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_4, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_5, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_6, 100)
  SetHealthPercent(Troop.AI_Intro_Grunt_7, 100)
  shot = 1
  PhoneMessageWithObjective(1, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE, 0, constant.NEW_PRIMARY_OBJECTIVE)
  CameraSetFOV(Camera.Intro_Camera_1, 70, constant.IMMEDIATE, 25, constant.NO_WAIT)
  WaitFor(2)
  GoToArea(Air_Vehicle.AI_Intro_Air_Transport_1, -740, 1500, 10)
  WaitFor(2)
  GoToArea(Air_Vehicle.AI_Intro_Air_Transport_2, -740, 1500, 10)
  WaitFor(2)
  Kill(Ground_Vehicle.SE_LT1)
  SetViewDistanceAdjustment(350, 150)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Ground_Vehicle.AI_Light_Tank_b)
  Despawn(Air_Vehicle.AI_Intro_Air_Transport_1)
  Despawn(Air_Vehicle.AI_Intro_Air_Transport_2)
  Despawn(Troop.AI_Intro_Grunt_1)
  Despawn(Troop.AI_Intro_Grunt_2)
  Despawn(Troop.AI_Intro_Grunt_3)
  Despawn(Troop.AI_Intro_Grunt_4)
  Despawn(Troop.AI_Intro_Grunt_5)
  Despawn(Troop.AI_Intro_Grunt_6)
  Despawn(Troop.AI_Intro_Grunt_7)
  shot = 2
  Spawn(Troop.AI_Beach_Grunt_5)
  Spawn(Troop.AI_Beach_Grunt_6)
  Spawn(Troop.CS_Grunt_1)
  Spawn(Troop.CS_Grunt_2)
  Spawn(Troop.CS_Grunt_3)
  Spawn(Troop.CS_Grunt_4)
  SetHealthPercent(Troop.CS_Grunt_1, 10)
  SetHealthPercent(Troop.CS_Grunt_2, 10)
  SetHealthPercent(Troop.CS_Grunt_3, 10)
  SetHealthPercent(Troop.CS_Grunt_4, 10)
  GoToArea(Troop.CS_Grunt_1, -55, 770, 1, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Grunt_2, -50, 770, 3, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Grunt_3, -55, 770, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Grunt_4, -50, 770, 7, 0, constant.ORDER_FORCED)
  SetCamera(Camera.Intro_Camera_3)
  CameraSetFOV(Camera.Intro_Camera_3, 70, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraSetFOV(Camera.Intro_Camera_3, 40, constant.SMOOTH, 1, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE)
  WaitFor(1)
  AttackTarget(Troop.CS_Grunt_1, Troop.CS_Art_4)
  AttackTarget(Troop.CS_Grunt_2, Troop.CS_Art_3)
  AttackTarget(Troop.CS_Grunt_3, Troop.CS_Art_2)
  AttackTarget(Troop.CS_Grunt_4, Troop.CS_Art_1)
  WaitFor(2)
  Kill(Troop.CS_Grunt_1)
  WaitFor(2)
  Kill(Troop.CS_Grunt_2)
  WaitFor(2)
  Kill(Troop.CS_Grunt_3)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  Kill(Troop.CS_Grunt_4)
  GoToArea(Troop.CS_Art_1, -55, 770, 2, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Art_2, -50, 770, 2, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Art_3, -55, 770, 2, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CS_Art_4, -50, 770, 2, 0, constant.ORDER_FORCED)
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  shot = 4
  SetCamera(Camera.Intro_Camera_5)
  CameraSetFOV(Camera.Intro_Camera_5, 70, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(10, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE, 0, constant.NEW_SECONDARY_OBJECTIVE)
  WaitFor(5)
  Spawn(Troop.AI_R3_1)
  Spawn(Troop.AI_R3_2)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  shot = 4
  SetCamera(Camera.Intro_Camera_6)
  CameraSetFOV(Camera.Intro_Camera_6, 65, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(12, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.AI_R3_1, true)
  Despawn(Troop.AI_R3_2, true)
  shot = 5
  Spawn(Water_Vehicle.CS_Sea_Transport_1)
  Spawn(Water_Vehicle.CS_Sea_Transport_2)
  Spawn(Water_Vehicle.CS_Sea_Transport_3)
  EndFrame()
  BeachWaterUnit(Water_Vehicle.CS_Sea_Transport_1, -240, 85, 0, 1)
  BeachWaterUnit(Water_Vehicle.CS_Sea_Transport_2, -175, 105, 345, 1)
  BeachWaterUnit(Water_Vehicle.CS_Sea_Transport_3, -125, 125, 330, 1)
  SetCamera(Camera.Intro_Camera_2)
  CameraSetFOV(Camera.Intro_Camera_2, 65, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(2, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until NumPassengersInUnit(Water_Vehicle.CS_Sea_Transport_2) == 0
  WaitFor(2)
  PutUnitInVehicle(Troop.CS_Troop_3, Water_Vehicle.CS_Sea_Transport_2, 4)
  PutUnitInVehicle(Troop.CS_Troop_4, Water_Vehicle.CS_Sea_Transport_2, 5)
  EndFrame()
  ExitVehicle(Troop.CS_Troop_3, Water_Vehicle.CS_Sea_Transport_2)
  ExitVehicle(Troop.CS_Troop_4, Water_Vehicle.CS_Sea_Transport_2)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Water_Vehicle.CS_Sea_Transport_1)
  Despawn(Water_Vehicle.CS_Sea_Transport_2)
  Despawn(Water_Vehicle.CS_Sea_Transport_3)
  Despawn(Ground_Vehicle.CS_Light_Tank_1)
  Despawn(Ground_Vehicle.CS_Light_Tank_2)
  Despawn(Troop.CS_Troop_1)
  Despawn(Troop.CS_Troop_2)
  Despawn(Troop.CS_Troop_3)
  Despawn(Troop.CS_Troop_4)
  Despawn(Troop.CS_Troop_5)
  Despawn(Troop.CS_Troop_6)
  Despawn(Troop.CS_Troop_7)
  Despawn(Troop.CS_Troop_8)
  Despawn(Troop.CS_Troop_9)
  cutscene = 1
end
