function Encouters_Across_the_Island(owner)
  Script01 = owner
  local gate = 0
  Despawn(Ground_Vehicle.SO_Artillery_1, true)
  Despawn(Ground_Vehicle.SO_Artillery_2, true)
  Despawn(Troop.AI_Beach_Baz_1, true)
  Despawn(Troop.AI_Beach_Baz_2, true)
  Despawn(Troop.AI_Beach_Baz_3, true)
  Despawn(Troop.AI_Beach_Baz_4, false)
  Despawn(Troop.AI_R2_1, true)
  Despawn(Troop.AI_R2_2, true)
  Despawn(Troop.AI_R2_3, true)
  Despawn(Troop.AI_R2_4, true)
  Despawn(Troop.AI_R2_5, true)
  Despawn(Troop.AI_R2_6, true)
  Despawn(Troop.AI_R3_1, true)
  Despawn(Troop.AI_R3_2, true)
  Despawn(Ground_Vehicle.AI_Light_Tank_a, true)
  Despawn(Ground_Vehicle.AI_Light_Tank_a, true)
  Despawn(Troop.AI_R3_3, true)
  Despawn(Troop.AI_R3_4, true)
  Despawn(Ground_Vehicle.AI_Recon_1, true)
  Despawn(Troop.AI_AGrunt_1)
  Despawn(Troop.AI_AGrunt_2)
  Despawn(Troop.AI_AGrunt_3)
  Despawn(Troop.AI_R4_1, true)
  Despawn(Troop.AI_R4_2, true)
  Despawn(Troop.AI_R4_3, true)
  Despawn(Troop.AI_R4_4, true)
  Despawn(Troop.AI_R4_5)
  Despawn(Troop.AI_R4_6)
  Despawn(Ground_Vehicle.AI_Artillery_5, true)
  Despawn(Troop.Artillery_Baz_1, true)
  Despawn(Troop.Artillery_Baz_2, true)
  Despawn(Troop.Artillery_Baz_3, true)
  Despawn(Troop.Artillery_Baz_4)
  Despawn(Troop.Artillery_Baz_5)
  Despawn(Troop.Artillery_Baz_6, true)
  Despawn(Troop.Artillery_Baz_7, true)
  Despawn(Troop.Artillery_Baz_8, true)
  Despawn(Troop.Entity260024549, true)
  Despawn(Troop.Entity260024550, true)
  Despawn(Troop.Entity260024552, true)
  Despawn(Troop.Entity260024553, true)
  repeat
    EndFrame()
  until cutscene == 1
  local counter = 0
  repeat
    EndFrame()
  until cutscene == 1
  DebugOut("sending in first tank")
  GoToArea(Ground_Vehicle.AI_Beach_Tank_1, -165, 175, 15)
  GoToArea(Troop.AI_Beach_Grunt_1, -145, 185, 15)
  GoToArea(Troop.AI_Beach_Grunt_2, -155, 205, 15)
  GoToArea(Troop.AI_Beach_Grunt_3, -130, 205, 15)
  repeat
    WaitFor(1)
    counter = counter + 1
  until IsDead(Ground_Vehicle.AI_Beach_Tank_1) or counter == 25 or 0 < NumItemsInArea(Map_Zone.Entrance, flag.TYPE_SOLAR)
  PhoneMessage(6, constant.ID_NONE, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE)
  PhoneMessage(7, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE)
  Spawn(Troop.AI_R1_1)
  Spawn(Troop.AI_R1_2)
  Spawn(Troop.AI_Beach_Baz_1)
  Spawn(Troop.AI_Beach_Baz_2)
  Spawn(Troop.AI_Beach_Baz_3)
  GoToArea(Troop.AI_Beach_Baz_1, -145, 185, 15)
  GoToArea(Troop.AI_Beach_Baz_2, -155, 205, 15)
  GoToArea(Troop.AI_Beach_Baz_3, -130, 205, 15)
  repeat
    WaitFor(0.1)
  until 0 < NumItemsInArea(Map_Zone.Reaction_0, flag.TYPE_SOLAR)
  Spawn(Troop.AI_R2_1)
  Spawn(Troop.AI_R2_2)
  Spawn(Troop.AI_R2_3)
  Spawn(Troop.AI_R2_4)
  Spawn(Troop.AI_R2_5)
  Spawn(Troop.AI_R2_6)
  Spawn(Troop.AI_R3_1)
  Spawn(Troop.AI_R3_2)
  Spawn(Ground_Vehicle.AI_Light_Tank_a)
  Spawn(Ground_Vehicle.AI_Light_Tank_a)
  DebugOut("sending in second tank and flame vets")
  GoToArea(Ground_Vehicle.AI_Beach_Tank_2, -145, 290, 15)
  GoToArea(Troop.AI_Beach_Grunt_5, -135, 265, 15)
  GoToArea(Troop.AI_Beach_Grunt_6, -100, 275, 15)
  ClearMessageQueue()
  PhoneMessage(58, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Happy, constant.PLAYER_ONE)
  SetObjectiveData(Objective_Marker.Waypoint_2_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.Waypoint_3_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  repeat
    if 0 < NumPassengersInUnit(Capture_Point.Helipad) then
      WaitFor(5)
      break
    end
    WaitFor(0.1)
  until 0 < NumItemsInArea(Map_Zone.Reaction_1, flag.TYPE_SOLAR)
  SetViewDistanceAdjustment(450, 35)
  PhoneMessage(63, constant.ID_NONE, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE)
  Spawn(Troop.AI_R3_3)
  Spawn(Troop.AI_R3_4)
  Spawn(Ground_Vehicle.AI_Recon_1)
  DebugOut("Reaction 1 Triggered")
  AttackTarget(Troop.AI_R2_1, GetPlayerUnit())
  AttackTarget(Troop.AI_R2_2, GetPlayerUnit())
  AttackTarget(Troop.AI_R2_3, GetPlayerUnit())
  AttackTarget(Troop.AI_R2_4, GetPlayerUnit())
  AttackTarget(Troop.AI_R2_5, GetPlayerUnit())
  AttackTarget(Troop.AI_R2_6, GetPlayerUnit())
  WaitFor(2)
  GoToArea(Ground_Vehicle.AI_Light_Tank_a, -105, 405, 15)
  GoToArea(Ground_Vehicle.AI_Beach_Tank_3, 0, 385, 15)
  WaitFor(10)
  GoToArea(Ground_Vehicle.AI_Light_Tank_a, -90, 370, 15)
  GoToArea(Ground_Vehicle.AI_Beach_Tank_3, -60, 365, 15)
  repeat
    WaitFor(0.2)
  until 0 < NumItemsInArea(Map_Zone.Reaction_2, flag.TYPE_SOLAR)
  Spawn(Troop.SE_POW1)
  Spawn(Troop.SE_POW2)
  Spawn(Troop.SE_POW3)
  Spawn(Troop.SE_POW4)
  SetUnitInvulnerable(Troop.SE_POW1, true)
  SetUnitInvulnerable(Troop.SE_POW2, true)
  SetUnitInvulnerable(Troop.SE_POW3, true)
  SetUnitInvulnerable(Troop.SE_POW4, true)
  DebugOut("Reaction 2 Triggered")
  GoToArea(Ground_Vehicle.AI_Recon_1, -100, 520, 10)
  GoToArea(Troop.AI_R3_3, -110, 530, 10)
  GoToArea(Troop.AI_R3_4, -85, 535, 10)
  ClearMessageQueue()
  PhoneMessage(61, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Happy, constant.PLAYER_ONE)
  PhoneMessage(62, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Sad, constant.PLAYER_ONE)
  WaitFor(1)
  SetObjectiveData(Objective_Marker.Waypoint_3_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.Assault_Vets_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  repeat
    EndFrame()
  until assaultshot == 3
  SetUnitInvulnerable(Troop.SE_POW1, false)
  SetUnitInvulnerable(Troop.SE_POW2, false)
  SetUnitInvulnerable(Troop.SE_POW3, false)
  SetUnitInvulnerable(Troop.SE_POW4, false)
  Spawn(Troop.AI_R4_1)
  Spawn(Troop.AI_R4_2)
  Spawn(Troop.AI_R4_3)
  Spawn(Troop.AI_R4_4)
  Spawn(Ground_Vehicle.AI_Artillery_5)
  DebugOut("Player Reaches Assault Vets")
  ClearMessageQueue()
  PhoneMessage(33, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Happy, constant.PLAYER_ONE)
  assault = 1
  WaitFor(2)
  DebugOut("Send AI Grunts after the SE Assault Vets")
  GoToArea(Troop.AI_R4_1, -50, 770, 10)
  GoToArea(Troop.AI_R4_2, -50, 760, 10)
  GoToArea(Troop.AI_R4_3, -55, 760, 10)
  GoToArea(Troop.AI_R4_4, -55, 750, 10)
  GoToArea(Ground_Vehicle.AI_Artillery_5, -80, 750, 30)
  mid = 1
  Spawn(Troop.Entity260024549)
  Spawn(Troop.Entity260024550)
  Spawn(Troop.Entity260024552)
  Spawn(Troop.Entity260024553)
  repeat
    EndFrame()
  until GetPlayerUnit(constant.PLAYER_ONE) == Troop.SE_POW1 or GetPlayerUnit(constant.PLAYER_ONE) == Troop.SE_POW2 or GetPlayerUnit(constant.PLAYER_ONE) == Troop.SE_POW3 or GetPlayerUnit(constant.PLAYER_ONE) == Troop.SE_POW4
  PhoneMessage(34, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Happy, constant.PLAYER_ONE)
end
