function W4_Air_Transport_09(owner)
  Script13 = owner
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_23)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_24)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_25)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_26)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_27)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_28)
  AddToGroup(Unit_Group.Wave_4, Ground_Vehicle.AI_Light_Tank_5)
  Despawn(Air_Vehicle.AI_Air_Transport_9)
  repeat
    EndFrame()
  until wave == 4
  DebugOut("Wave 4 Begins, Spawn Air Transport 9")
  Spawn(Air_Vehicle.AI_Air_Transport_9)
  WaitFor(1)
  LandAirUnit(Air_Vehicle.AI_Air_Transport_9, 40, 1135, constant.ORDER_FORCED, 1, 5, 270)
  repeat
    EndFrame()
  until GetMovementState(Air_Vehicle.AI_Air_Transport_9) == constant.MOVEMENT_STATE_ON_GROUND
  DebugOut("Air Transport 9 has landed")
  WaitFor(1)
  GoToArea(Troop.AI_Grunt_23, -105, 1335, 10)
  GoToArea(Troop.AI_Grunt_24, -95, 1335, 10)
  GoToArea(Troop.AI_Grunt_25, -85, 1335, 10)
  GoToArea(Troop.AI_Grunt_26, -75, 1335, 10)
  GoToArea(Troop.AI_Grunt_27, -65, 1335, 10)
  GoToArea(Troop.AI_Grunt_28, -55, 1335, 10)
  GoToArea(Ground_Vehicle.AI_Light_Tank_5, -80, 1305, 10)
  WaitFor(2)
  DebugOut("Send Air Transport 9 away from the play area")
  GoToArea(Air_Vehicle.AI_Air_Transport_9, 435, 1335, 10)
  WaitFor(25)
  Despawn(Air_Vehicle.AI_Air_Transport_9)
  DebugOut("Despawn Air Transport 9")
  WaitFor(25)
  EnterVehicle(Troop.AI_Grunt_23, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_24, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_25, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_26, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_27, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_28, Capture_Point.Palace)
end
