function W4_Air_Transport_10(owner)
  Script14 = owner
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_29)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_30)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_31)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_32)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_33)
  AddToGroup(Unit_Group.Wave_4, Troop.AI_Grunt_34)
  AddToGroup(Unit_Group.Wave_4, Ground_Vehicle.AI_Light_Tank_6)
  Despawn(Air_Vehicle.AI_Air_Transport_10)
  repeat
    EndFrame()
  until wave == 4
  DebugOut("Wave 4 Begins, Spawn Air Transport 10")
  Spawn(Air_Vehicle.AI_Air_Transport_10)
  WaitFor(1)
  LandAirUnit(Air_Vehicle.AI_Air_Transport_10, -220, 1145, constant.ORDER_FORCED, 1, 5, 90)
  repeat
    EndFrame()
  until GetMovementState(Air_Vehicle.AI_Air_Transport_10) == constant.MOVEMENT_STATE_ON_GROUND
  DebugOut("Air Transport 10 has landed")
  WaitFor(1)
  GoToArea(Troop.AI_Grunt_29, -105, 1335, 10)
  GoToArea(Troop.AI_Grunt_30, -95, 1335, 10)
  GoToArea(Troop.AI_Grunt_31, -85, 1335, 10)
  GoToArea(Troop.AI_Grunt_32, -75, 1335, 10)
  GoToArea(Troop.AI_Grunt_33, -65, 1335, 10)
  GoToArea(Troop.AI_Grunt_34, -55, 1335, 10)
  GoToArea(Ground_Vehicle.AI_Light_Tank_6, -80, 1305, 10)
  WaitFor(2)
  DebugOut("Send Air Transport 10 away from the play area")
  GoToArea(Air_Vehicle.AI_Air_Transport_10, -835, 1335, 10)
  WaitFor(25)
  Despawn(Air_Vehicle.AI_Air_Transport_10)
  DebugOut("Despawn Air Transport 10")
  WaitFor(25)
  EnterVehicle(Troop.AI_Grunt_29, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_30, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_31, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_32, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_33, Capture_Point.Palace)
  EnterVehicle(Troop.AI_Grunt_34, Capture_Point.Palace)
end
