function Despawn_Units(owner)
  Despawn(Troop.SE_IG_1, true)
  Despawn(Troop.SE_IG_2, true)
  Despawn(Troop.SE_IG_3, true)
  Despawn(Troop.SE_IG_4, true)
  Despawn(Troop.SE_IG_5, true)
  Despawn(Troop.SE_IG_6, true)
  Despawn(Troop.SE_IG_7, true)
  Despawn(Troop.SE_IG_8, true)
  Despawn(Troop.SE_IG_9, true)
  Despawn(Troop.KillMe1, true)
  Despawn(Troop.KillMe2, true)
  Despawn(Troop.KillMe3, true)
  Despawn(Troop.KillMe4, true)
  Despawn(Troop.KillMe5, true)
  Despawn(Troop.KillMe6, true)
  Despawn(Ground_Vehicle.HQ_Heavy_Tank_1, true)
  Despawn(Ground_Vehicle.HQ_Heavy_Tank_2, true)
  Despawn(Ground_Vehicle.HQ_Heavy_Tank_3, true)
  Despawn(Ground_Vehicle.HQ_Heavy_Tank_4, false)
  Despawn(Ground_Vehicle.HQ_Heavy_Tank_5, true)
  Despawn(Water_Vehicle.HQ_Battleship_3, true)
  WaitFor(5)
  DebugOut("Number of Anglo Units in Spawn Zone are", NumItemsInArea(Map_Zone.Spawn_Zone, flag.TYPE_ANGLO))
  repeat
    WaitFor(0.5)
  until NumItemsInArea(Map_Zone.Spawn_Zone, flag.TYPE_ANGLO) > 0
  DebugOut("Anglos near north island, Spawn in Ground Units")
  Spawn(Troop.SE_IG_1)
  Spawn(Troop.SE_IG_2)
  Spawn(Troop.SE_IG_3)
  Spawn(Troop.SE_IG_4)
  Spawn(Troop.SE_IG_5)
  Spawn(Ground_Vehicle.HQ_Heavy_Tank_1)
  WaitFor(4)
  Spawn(Ground_Vehicle.HQ_Heavy_Tank_2)
  WaitFor(4)
  Spawn(Troop.SE_IG_6)
  Spawn(Troop.SE_IG_7)
  repeat
    EndFrame()
  until GetObjectZPosition(GetPlayerUnit(constant.PLAYER_ONE)) > 810
  Spawn(Ground_Vehicle.HQ_Heavy_Tank_3)
  Spawn(Water_Vehicle.HQ_Battleship_3)
  Spawn(Troop.SE_IG_8)
  Spawn(Troop.SE_IG_9)
  repeat
    EndFrame()
  until GetObjectZPosition(GetPlayerUnit(constant.PLAYER_ONE)) > 950
  Spawn(Ground_Vehicle.HQ_Heavy_Tank_5)
  Spawn(Troop.KillMe1)
  Spawn(Troop.KillMe2)
  Spawn(Troop.KillMe3)
  Spawn(Troop.KillMe4)
  Spawn(Troop.KillMe5)
  Spawn(Troop.KillMe6)
  WaitFor(3)
end
