function Intro_Cutscene_AI(owner)
  Despawn(Air_Vehicle.CS_Gunship_1)
  Despawn(Air_Vehicle.CS_Gunship_2)
  Despawn(Air_Vehicle.CS_Gunship_3)
  Despawn(Air_Vehicle.CS_Gunship_4)
  Despawn(Water_Vehicle.CS_Battleship_1)
  Despawn(Water_Vehicle.CS_Battleship_2)
  Despawn(Water_Vehicle.CS_Battleship_3)
  SetUnitInvulnerable(Troop.MrShooty, true)
  Despawn(Troop.MrShooty)
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  SetInvulnerable(flag.TYPE_ANGLO, 1)
  repeat
    EndFrame()
  until shot ~= 0
  if shot == 1 then
    Spawn(Water_Vehicle.CS_Battleship_1)
    Spawn(Water_Vehicle.CS_Battleship_2)
    Spawn(Water_Vehicle.CS_Battleship_3)
    GoToArea(Water_Vehicle.CS_Battleship_1, 330, 434, 1)
    GoToArea(Water_Vehicle.CS_Battleship_2, 350, 430, 1)
    GoToArea(Water_Vehicle.CS_Battleship_3, 370, 426, 1)
    repeat
      EndFrame()
    until shot ~= 1
  end
  if shot == 2 then
    SetInvulnerable(flag.TYPE_SOLAR, 0)
    SetInvulnerable(flag.TYPE_ANGLO, 0)
    EndFrame()
    SetUnitInvulnerable(Water_Vehicle.AI_Frigate_1, true)
    SetUnitInvulnerable(Water_Vehicle.AI_Frigate_2, true)
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_2, true)
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_3, true)
    Spawn(Air_Vehicle.CS_Gunship_1)
    Spawn(Air_Vehicle.CS_Gunship_2)
    Spawn(Air_Vehicle.CS_Gunship_3)
    Spawn(Air_Vehicle.CS_Gunship_4)
    GoToArea(Air_Vehicle.CS_Gunship_4, 125, -65, 25, constant.ORDER_NORMAL)
    GoToArea(Air_Vehicle.CS_Gunship_1, 165, -105, 25, constant.ORDER_NORMAL)
    AttackTarget(Air_Vehicle.CS_Gunship_2, Water_Vehicle.AI_Frigate_1, constant.ORDER_FORCED)
    AttackTarget(Air_Vehicle.CS_Gunship_1, Water_Vehicle.AI_Frigate_1, constant.ORDER_FORCED)
    AttackTarget(Air_Vehicle.CS_Gunship_4, Water_Vehicle.AI_Frigate_2, constant.ORDER_FORCED)
    AttackTarget(Air_Vehicle.CS_Gunship_3, Water_Vehicle.AI_Frigate_2, constant.ORDER_FORCED)
    Despawn(Water_Vehicle.CS_Battleship_1)
    Despawn(Water_Vehicle.CS_Battleship_2)
    Despawn(Water_Vehicle.CS_Battleship_3)
    repeat
      EndFrame()
    until shot ~= 2
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_1, false)
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_2, false)
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_3, false)
    SetUnitInvulnerable(Air_Vehicle.CS_Gunship_4, false)
    WaitFor(1)
    SetUnitInvulnerable(Water_Vehicle.AI_Frigate_1, false)
    SetUnitInvulnerable(Water_Vehicle.AI_Frigate_2, false)
    Kill(Air_Vehicle.CS_Gunship_1)
    Kill(Air_Vehicle.CS_Gunship_2)
    Kill(Air_Vehicle.CS_Gunship_3)
    Kill(Air_Vehicle.CS_Gunship_4)
  end
  repeat
    EndFrame()
  until shot == 4
  Despawn(Air_Vehicle.CS_Gunship_1)
  Despawn(Air_Vehicle.CS_Gunship_2)
  Despawn(Air_Vehicle.CS_Gunship_3)
  Despawn(Air_Vehicle.CS_Gunship_4)
  Despawn(Water_Vehicle.CS_Battleship_1)
  Despawn(Water_Vehicle.CS_Battleship_2)
  Despawn(Water_Vehicle.CS_Battleship_3)
  Despawn(Troop.MrShooty)
  SetInvulnerable(flag.TYPE_SOLAR, 0)
  SetInvulnerable(flag.TYPE_ANGLO, 0)
end
