function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.cutscenecamplayer1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutscene1WFtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutscene1WF)
    CameraSetFOV(Camera.cutscenecamplayer1, 65, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(1, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
    PhoneMessage(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
    WaitFor(17)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutscene2WFtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutscene2WF)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(3, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
    PhoneMessage(7, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
    ReviveDeadUnit(Troop.WFintroTroop1, 453, -80, 0, 10)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop2, 457, -83, 0, 10)
    FollowWaypoint(Troop.WFintroTroop1, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop3, 453, -87, 0, 10)
    FollowWaypoint(Troop.WFintroTroop2, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop4, 463, -86, 0, 10)
    FollowWaypoint(Troop.WFintroTroop3, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop5, 460, -77, 0, 10)
    FollowWaypoint(Troop.WFintroTroop4, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop6, 458, -89, 0, 10)
    FollowWaypoint(Troop.WFintroTroop5, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop7, 456, -81, 0, 10)
    FollowWaypoint(Troop.WFintroTroop6, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop8, 454, -77, 0, 10)
    FollowWaypoint(Troop.WFintroTroop7, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.WFintroTroop9, 461, -83, 0, 10)
    FollowWaypoint(Troop.WFintroTroop8, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    FollowWaypoint(Troop.WFintroTroop9, Waypoint.WFtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(7.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.cutscenecamplayer2)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutscene1Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutscene1T)
    CameraSetFOV(Camera.cutscenecamplayer2, 65, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(2, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_TWO)
    PhoneMessage(6, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_TWO)
    WaitFor(17)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutscene2Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutscene2T)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(4, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_TWO)
    PhoneMessage(8, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_TWO)
    ReviveDeadUnit(Troop.TTintroTroop1, 434, 771, 170, 10)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop2, 439, 768, 170, 10)
    FollowWaypoint(Troop.TTintroTroop1, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop3, 431, 776, 170, 10)
    FollowWaypoint(Troop.TTintroTroop2, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop4, 436, 778, 170, 10)
    FollowWaypoint(Troop.TTintroTroop3, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop5, 432, 765, 170, 10)
    FollowWaypoint(Troop.TTintroTroop4, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop6, 435, 770, 170, 10)
    FollowWaypoint(Troop.TTintroTroop5, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop7, 437, 776, 170, 10)
    FollowWaypoint(Troop.TTintroTroop6, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop8, 441, 771, 170, 10)
    FollowWaypoint(Troop.TTintroTroop7, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.TTintroTroop9, 436, 770, 170, 10)
    FollowWaypoint(Troop.TTintroTroop8, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    FollowWaypoint(Troop.TTintroTroop9, Waypoint.TTtroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(7.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
