function RAT_Cutscene_End(owner)
  CutsceneEndID = owner
  DebugOut("Cutscene End = ", CutsceneEndID)
  Despawn(Building.Pod)
  Despawn(Building.VladEnd)
  Despawn(Building.EndSmoke)
  Despawn(Building.EndSmoke02)
  Despawn(Building.EndSmoke03)
  Despawn(Building.EndSmoke04)
  DestroyablePlayAnim(Destroyable_Object.Pod, 0, 0)
  Despawn(Building.Beam)
  Despawn(Air_Vehicle.VladCopterStart)
  Despawn(Air_Vehicle.VladCopter)
  Despawn(Air_Vehicle.PierceFighter)
  repeat
    EndFrame()
  until cutscene == 1
  WaitFor(5)
  while true do
    if CutsceneEndStart == 1 then
      DebugOut("EndCutscene in progress")
      StartIntro()
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetObjectiveData(Objective.Vlad, constant.OBJECTIVE_DATA_STATE, 1)
      SetObjectiveData(Objective_Marker.Vlad_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      DefeatLament(constant.ARMY_XYLVANIAN, false)
      VictoryDance(constant.ARMY_TUNDRAN, false)
      SetInvulnerable(flag.TYPE_TUNDRAN, true)
      if not IsDead(Ground_Vehicle.T_Battlestation) then
        ForceUnitTransfer(constant.PLAYER_ONE, Ground_Vehicle.T_Battlestation, true)
      end
      Spawn(Building.EndSmoke)
      Despawn(Building.Gun01)
      Despawn(Building.Gun02)
      Despawn(Building.Gun03)
      Despawn(Building.Gun04)
      Despawn(Building.Vlad)
      WaitFor(0.5)
      Spawn(Building.VladWreckage)
      Spawn(Building.Pod)
      Teleport(Air_Vehicle.Tgunship01, -350, -200, 0, 10)
      Teleport(Air_Vehicle.Tgunship02, -360, -200, 0, 10)
      Teleport(Air_Vehicle.Tgunship03, -370, -200, 0, 10)
      Teleport(Air_Vehicle.Tgunship04, -340, -200, 0, 10)
      Teleport(Air_Vehicle.Tgunship05, -330, -200, 0, 10)
      Teleport(Air_Vehicle.Tgunship06, -320, -200, 0, 10)
      Teleport(Air_Vehicle.Tfighter01, -310, -200, 0, 10)
      Teleport(Air_Vehicle.Tfighter02, -380, -200, 0, 10)
      Teleport(Air_Vehicle.Tfighter03, -390, -200, 0, 10)
      if GetPlayerUnit() ~= Air_Vehicle.Tfighter01 then
        Despawn(Air_Vehicle.Tfighter01)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tfighter02 then
        Despawn(Air_Vehicle.Tfighter02)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tfighter03 then
        Despawn(Air_Vehicle.Tfighter03)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tgunship01 then
        Despawn(Air_Vehicle.Tgunship01)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tgunship02 then
        Despawn(Air_Vehicle.Tgunship02)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tgunship03 then
        Despawn(Air_Vehicle.Tgunship03)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tgunship04 then
        Despawn(Air_Vehicle.Tgunship04)
      end
      if GetPlayerUnit() ~= Air_Vehicle.Tgunship05 then
        Despawn(Air_Vehicle.Tgunship05)
      end
      Despawn(Air_Vehicle.Abomber01)
      Despawn(Air_Vehicle.T_Bomber)
      Despawn(Air_Vehicle.X_Fighter_1)
      Despawn(Air_Vehicle.X_Fighter_2)
      Despawn(Air_Vehicle.X_Fighter_3)
      Despawn(Air_Vehicle.X_Gunship_1)
      Despawn(Air_Vehicle.X_Gunship_2)
      Despawn(Air_Vehicle.X_Gunship_3)
      Despawn(Air_Vehicle.X_Gunship_4)
      SetUnitInvulnerable(GetPlayerUnit(), true)
      SetCamera(Camera.CutsceneEnd, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneEnd, Waypoint.End01)
      CameraSetTarget(Camera.CutsceneEnd, Waypoint.End01Target)
      CameraSetFOV(Camera.CutsceneEnd, 70, constant.SMOOTH, 3, constant.NO_WAIT)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(106, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
      WaitFor(0.5)
      Kill(Building.Explosion01)
      WaitFor(1)
      Kill(Building.EndSmoke)
      Kill(Building.Explosion02)
      WaitFor(0.5)
      SetInvulnerable(flag.TYPE_XYLVANIAN, true)
      Kill(Building.ExplosionCamera02)
      Kill(Building.Explosion03)
      WaitFor(1.25)
      Kill(Building.Explosion04)
      WaitFor(0.75)
      Kill(Building.Explosion05)
      WaitFor(1)
      WaitFor(1.5)
      Kill(Building.ExplosionCamera04)
      Kill(Building.Explosion12)
      Kill(Building.Explosion11)
      WaitFor(0.5)
      Kill(Building.Explosion14)
      WaitFor(3)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetCamera(Camera.CutsceneEnd, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneEnd, Waypoint.End03)
      CameraSetTarget(Camera.CutsceneEnd, Waypoint.End03Target)
      CameraSetFOV(Camera.CutsceneEnd, 60, constant.IMMEDIATE, 25, constant.NO_WAIT)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(107, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
      CameraSetFOV(Camera.CutsceneEnd, 45, constant.SMOOTH, 1.5, constant.NO_WAIT)
      WaitFor(3)
      Spawn(Building.Beam)
      repeat
        EndFrame()
      until 0 >= GetNumItemsInMessageQueue(constant.PLAYER_ONE)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Spawn(Air_Vehicle.VladCopter)
      FollowWaypoint(Air_Vehicle.VladCopter, Waypoint.VladCopter, 0, 0, constant.ORDER_FORCED)
      FollowWaypoint(Air_Vehicle.PierceFighter, Waypoint.PierceFighter, 0, 0, constant.ORDER_NORMAL)
      SetCamera(Camera.CutsceneEnd, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneEnd, Waypoint.End04)
      CameraSetTarget(Camera.CutsceneEnd, Waypoint.End04Target)
      CameraSetFOV(Camera.CutsceneEnd, 80, constant.IMMEDIATE, 25, constant.NO_WAIT)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      CameraSetFOV(Camera.CutsceneEnd, 80, constant.SMOOTH, 3, constant.NO_WAIT)
      WaitFor(1)
      LandAirUnit(Air_Vehicle.VladCopter, 0, 1545, constant.ORDER_FORCED, false, 5, 225)
      WaitFor(0.5)
      Kill(Building.Explosion06)
      WaitFor(1)
      ClearMessageQueue(constant.PLAYER_ONE)
      PhoneMessage(108, constant.ID_NONE, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_ONE)
      Spawn(Air_Vehicle.PierceFighter)
      SetUnitInvulnerable(Air_Vehicle.PierceFighter, true)
      SetActive(Air_Vehicle.PierceFighter, constant.INACTIVE, constant.ADJUST_WEAPON)
      WaitFor(3.5)
      Kill(Building.Explosion07)
      SetActive(Air_Vehicle.PierceFighter, constant.ACTIVE, constant.ADJUST_WEAPON)
      AttackTarget(Air_Vehicle.PierceFighter, Air_Vehicle.VladCopter, constant.ORDER_FORCED)
      WaitFor(2)
      Kill(Air_Vehicle.VladCopter)
      SetActive(Air_Vehicle.PierceFighter, constant.INACTIVE, constant.ADJUST_WEAPON)
      FollowWaypoint(Air_Vehicle.PierceFighter, Waypoint.PierceFighterExit, 0, 0, constant.ORDER_FORCED)
      WaitFor(1)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetCamera(Camera.CutsceneEnd, constant.PLAYER_ONE)
      CameraSetWaypoint(Camera.CutsceneEnd, Waypoint.End07)
      CameraSetTarget(Camera.CutsceneEnd, Waypoint.End07Target)
      CameraSetFOV(Camera.CutsceneEnd, 65, constant.IMMEDIATE, 25, constant.NO_WAIT)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(109, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
      WaitFor(2)
      Kill(Building.Explosion08)
      WaitFor(1)
      DestroyablePlayAnim(Building.Pod, 1, 2)
      WaitFor(2)
      Kill(Building.Explosion09)
      WaitFor(2)
      Kill(Building.Explosion10)
      WaitFor(1)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      repeat
        EndFrame()
      until 0 >= GetNumItemsInMessageQueue(constant.PLAYER_ONE)
      DeclareVictory(constant.ARMY_TUNDRAN)
      ClearMessageQueue(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      DebugOut("the player has completed the level")
      missionend = 1
      missioncomplete = 1
      CutsceneEndStart = 2
      EndIntro()
      break
    end
    EndFrame()
  end
  DebugScoring = true
  DebugOut("Debug Scoring = ", DebugScoring)
  DebugOut("Time Taken for level = ", GetTime())
  ListScoringUnits()
  WinMission()
end
