function RAT_Gulag_West_Camp_S(owner)
  scriptGulagWestCampS = owner
  SetUnitInvulnerable(Troop.POW11, true)
  SetUnitInvulnerable(Troop.POW12, true)
  SetUnitInvulnerable(Troop.POW13, true)
  SetUnitInvulnerable(Troop.POW14, true)
  SetUnitInvulnerable(Ground_Vehicle.WFtank07, true)
  SetUnitInvulnerable(Ground_Vehicle.WFtank08, true)
  SetActive(Troop.POW11, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.POW12, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.POW13, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.POW14, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.WFtank07, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.WFtank08, constant.INACTIVE, constant.ADJUST_WEAPON)
  Despawn(Ground_Vehicle.WFtank07)
  Despawn(Ground_Vehicle.WFtank08)
  while cutscene == 0 do
    EndFrame()
  end
  Despawn(Ground_Vehicle.WFtankCutscene01)
  Despawn(Ground_Vehicle.WFtankCutscene02)
  Spawn(Ground_Vehicle.WFtank07)
  Spawn(Ground_Vehicle.WFtank08)
  repeat
    EndFrame()
  until IsDead(Building.WG_F01) or IsDead(Destroyable_Object.WG_F03) or IsDead(Destroyable_Object.WG_F05) or IsDead(Destroyable_Object.WG_F07) or IsDead(Destroyable_Object.WG_F09) or IsDead(Destroyable_Object.WG_F11) or IsDead(Destroyable_Object.WG_F13) or IsDead(Destroyable_Object.WG_F15) or IsDead(Destroyable_Object.WG_F17) or IsDead(Destroyable_Object.WG_F19) or IsDead(Destroyable_Object.WG_F21) or IsDead(Destroyable_Object.WG_F23) or IsDead(Destroyable_Object.WG_F25) or IsDead(Destroyable_Object.WG_F27) or IsDead(Destroyable_Object.WG_F29) or IsDead(Destroyable_Object.WG_F31) or IsDead(Destroyable_Object.WG_F32) or IsDead(Destroyable_Object.WG_F33)
  Kill(Building.WG_F01)
  Kill(Destroyable_Object.WG_F02)
  Kill(Destroyable_Object.WG_F03)
  Kill(Destroyable_Object.WG_F04)
  Kill(Destroyable_Object.WG_F05)
  Kill(Destroyable_Object.WG_F06)
  Kill(Destroyable_Object.WG_F07)
  Kill(Destroyable_Object.WG_F08)
  Kill(Destroyable_Object.WG_F09)
  Kill(Destroyable_Object.WG_F10)
  Kill(Destroyable_Object.WG_F11)
  Kill(Destroyable_Object.WG_F12)
  Kill(Destroyable_Object.WG_F13)
  Kill(Destroyable_Object.WG_F14)
  Kill(Destroyable_Object.WG_F15)
  Kill(Destroyable_Object.WG_F16)
  Kill(Destroyable_Object.WG_F17)
  Kill(Destroyable_Object.WG_F18)
  Kill(Destroyable_Object.WG_F19)
  Kill(Destroyable_Object.WG_F20)
  Kill(Destroyable_Object.WG_F21)
  Kill(Destroyable_Object.WG_F22)
  Kill(Destroyable_Object.WG_F23)
  Kill(Destroyable_Object.WG_F24)
  Kill(Destroyable_Object.WG_F25)
  Kill(Destroyable_Object.WG_F26)
  Kill(Destroyable_Object.WG_F27)
  Kill(Destroyable_Object.WG_F28)
  Kill(Destroyable_Object.WG_F29)
  Kill(Destroyable_Object.WG_F30)
  Kill(Destroyable_Object.WG_F31)
  Kill(Destroyable_Object.WG_F32)
  Kill(Destroyable_Object.WG_F33)
  west = 1
  TechniqueObjectivesCompleted = TechniqueObjectivesCompleted + 1
  EnterVehicle(Troop.POW12, Ground_Vehicle.WFtank07, constant.ORDER_FORCED)
  EnterVehicle(Troop.POW13, Ground_Vehicle.WFtank07, constant.ORDER_FORCED)
  EnterVehicle(Troop.POW11, Ground_Vehicle.WFtank08, constant.ORDER_FORCED)
  EnterVehicle(Troop.POW14, Ground_Vehicle.WFtank08, constant.ORDER_FORCED)
  WaitFor(1)
  if not IsDead(Ground_Vehicle.WFtank07) then
    SetActive(Ground_Vehicle.WFtank07, constant.ACTIVE, constant.ADJUST_WEAPON)
    if GetSpawnMode() == eModeAction.Follow then
      FollowUnit(Ground_Vehicle.WFtank07, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
    end
  end
  if not IsDead(Ground_Vehicle.WFtank08) then
    SetActive(Ground_Vehicle.WFtank08, constant.ACTIVE, constant.ADJUST_WEAPON)
    if GetSpawnMode() == eModeAction.Follow then
      FollowUnit(Ground_Vehicle.WFtank08, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
    end
  end
  SetUnitInvulnerable(Troop.POW11, false)
  SetUnitInvulnerable(Troop.POW12, false)
  SetUnitInvulnerable(Troop.POW13, false)
  SetUnitInvulnerable(Troop.POW14, false)
  SetUnitInvulnerable(Ground_Vehicle.WFtank07, false)
  SetUnitInvulnerable(Ground_Vehicle.WFtank08, false)
  PhoneMessageWithObjective(70, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, 0, constant.SECONDARY_OBJECTIVE_COMPLETE)
  PhoneMessage(72, constant.ID_NONE, constant.ARMY_WF, 6, SpriteID.CO_WF_Betty_Happy, constant.PLAYER_ONE)
  SetObjectiveData(Objective_Marker.Gulag_West_S_OM, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective.Gulag_West_S, constant.OBJECTIVE_DATA_STATE, 1)
end
