function RAT_Gulag_East_Camp_1_P(owner)
  scriptGulagEastCamp1P = owner
  SetUnitInvulnerable(Troop.POW3, true)
  SetUnitInvulnerable(Troop.POW4, true)
  SetUnitInvulnerable(Ground_Vehicle.Saavehicle02, true)
  WaitFor(1)
  SetActive(Troop.POW3, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.POW4, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Saavehicle02, constant.INACTIVE, constant.ADJUST_WEAPON)
  repeat
    EndFrame()
  until IsDead(Building.EG1_F01) or IsDead(Destroyable_Object.EG1_F03) or IsDead(Destroyable_Object.EG1_F05) or IsDead(Destroyable_Object.EG1_F07) or IsDead(Destroyable_Object.EG1_F09) or IsDead(Destroyable_Object.EG1_F11) or IsDead(Destroyable_Object.EG1_F13) or IsDead(Destroyable_Object.EG1_F15) or IsDead(Destroyable_Object.EG1_F17) or IsDead(Destroyable_Object.EG1_F19) or IsDead(Destroyable_Object.EG1_F21) or IsDead(Destroyable_Object.EG1_F23) or IsDead(Destroyable_Object.EG1_F25) or IsDead(Destroyable_Object.EG1_F27) or IsDead(Destroyable_Object.EG1_F29) or IsDead(Destroyable_Object.EG1_F31) or IsDead(Destroyable_Object.EG1_F33)
  Kill(Building.EG1_F01)
  Kill(Destroyable_Object.EG1_F02)
  Kill(Destroyable_Object.EG1_F03)
  Kill(Destroyable_Object.EG1_F04)
  Kill(Destroyable_Object.EG1_F05)
  Kill(Destroyable_Object.EG1_F06)
  Kill(Destroyable_Object.EG1_F07)
  Kill(Destroyable_Object.EG1_F08)
  Kill(Destroyable_Object.EG1_F09)
  Kill(Destroyable_Object.EG1_F10)
  Kill(Destroyable_Object.EG1_F11)
  Kill(Destroyable_Object.EG1_F12)
  Kill(Destroyable_Object.EG1_F13)
  Kill(Destroyable_Object.EG1_F14)
  Kill(Destroyable_Object.EG1_F15)
  Kill(Destroyable_Object.EG1_F16)
  Kill(Destroyable_Object.EG1_F17)
  Kill(Destroyable_Object.EG1_F18)
  Kill(Destroyable_Object.EG1_F19)
  Kill(Destroyable_Object.EG1_F20)
  Kill(Destroyable_Object.EG1_F21)
  Kill(Destroyable_Object.EG1_F22)
  Kill(Destroyable_Object.EG1_F23)
  Kill(Destroyable_Object.EG1_F24)
  Kill(Destroyable_Object.EG1_F25)
  Kill(Destroyable_Object.EG1_F26)
  Kill(Destroyable_Object.EG1_F27)
  Kill(Destroyable_Object.EG1_F28)
  Kill(Destroyable_Object.EG1_F29)
  Kill(Destroyable_Object.EG1_F30)
  Kill(Destroyable_Object.EG1_F31)
  Kill(Destroyable_Object.EG1_F32)
  Kill(Destroyable_Object.EG1_F33)
  WaitFor(1)
  gulagp = 1
  EnterVehicle(Troop.POW3, Ground_Vehicle.Saavehicle02, constant.ORDER_FORCED)
  EnterVehicle(Troop.POW4, Ground_Vehicle.Saavehicle02, constant.ORDER_FORCED)
  WaitFor(1)
  SetActive(Ground_Vehicle.Saavehicle02, constant.ACTIVE, constant.ADJUST_WEAPON)
  if GetSpawnMode() == eModeAction.Follow then
    FollowUnit(Ground_Vehicle.Saavehicle02, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
  end
  SetUnitInvulnerable(Troop.POW3, false)
  SetUnitInvulnerable(Troop.POW4, false)
  SetUnitInvulnerable(Ground_Vehicle.Saavehicle02, false)
end
