function RAT_East_Gulag(owner)
  local SpawnDone = 0
  local MoveDone = 0
  local AAWarningDone = 0
  local POWFence = 0
  SetUnitInvulnerable(Building.EG1_F01, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F02, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F03, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F04, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F05, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F06, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F07, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F08, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F09, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F10, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F11, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F12, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F13, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F14, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F15, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F16, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F17, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F18, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F19, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F20, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F21, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F22, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F23, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F24, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F25, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F26, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F27, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F28, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F29, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F30, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F31, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F32, true)
  SetUnitInvulnerable(Destroyable_Object.EG1_F33, true)
  SetUnitInvulnerable(Building.EG2_F01, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F02, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F03, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F04, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F05, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F06, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F07, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F08, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F09, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F10, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F11, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F12, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F13, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F14, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F15, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F16, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F17, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F18, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F19, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F20, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F21, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F22, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F23, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F24, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F25, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F26, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F27, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F28, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F29, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F30, true)
  SetUnitInvulnerable(Destroyable_Object.EG2_F31, true)
  WaitFor(1)
  while missionend == 0 do
    if SpawnDone == 0 then
      if 0 < NumItemsInArea(Map_Zone.EastGulag, flag.TYPE_TUNDRAN) then
        SpawnDone = 1
      end
      WaitFor(1)
      EndFrame()
    end
    if IsInArea(GetPlayerUnit(), Map_Zone.EastGulag) then
      if POWFence == 0 then
        POWFence = 1
        SetUnitInvulnerable(Building.EG1_F01, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F02, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F03, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F04, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F05, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F06, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F07, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F08, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F09, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F10, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F11, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F12, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F13, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F14, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F15, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F16, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F17, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F18, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F19, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F20, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F21, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F22, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F23, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F24, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F25, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F26, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F27, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F28, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F29, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F30, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F31, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F32, false)
        SetUnitInvulnerable(Destroyable_Object.EG1_F33, false)
        SetUnitInvulnerable(Building.EG2_F01, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F02, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F03, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F04, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F05, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F06, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F07, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F08, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F09, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F10, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F11, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F12, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F13, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F14, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F15, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F16, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F17, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F18, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F19, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F20, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F21, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F22, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F23, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F24, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F25, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F26, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F27, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F28, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F29, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F30, false)
        SetUnitInvulnerable(Destroyable_Object.EG2_F31, false)
      end
      if AAWarningDone == 0 then
        AAWarningDone = 1
        PhoneMessage(65, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
      end
      EndFrame()
    end
    EndFrame()
  end
end
