function RAT_Cutscene_Introduction(owner)
  cutkiller = owner
  Despawn(Ground_Vehicle.CutsceneTank)
  StopAndGuard(Troop.Entity550038880)
  StopAndGuard(Troop.Entity550038881)
  PlayEffect(Scripted_Effect.Blizzard, 3, 0, 0, 0)
  SetCamera(Camera.Intro_Camera_1b)
  CameraSetFOV(Camera.Intro_Camera_1b, 70, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraSetFOV(Camera.Intro_Camera_1b, 50, constant.SMOOTH, 2, constant.NO_WAIT)
  ClearMessageQueue(constant.PLAYER_ONE)
  PhoneMessage(1, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Intro_Camera_1a)
  CameraSetFOV(Camera.Intro_Camera_1a, 80, constant.IMMEDIATE, 25, constant.NO_WAIT)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(20, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, 0, constant.NEW_PRIMARY_OBJECTIVE)
  WaitFor(7)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Spawn(Ground_Vehicle.CutsceneTank)
  EnableWeapon(Ground_Vehicle.CutsceneTank, 0)
  SetUnitInvulnerable(Troop.Entity550038881, true)
  SetCamera(Camera.Intro_Camera_2)
  CameraSetFOV(Camera.Intro_Camera_2, 60, constant.IMMEDIATE, 25, constant.NO_WAIT)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  FollowWaypoint(Ground_Vehicle.CutsceneTank, Waypoint.Entity550040536, 0, 0, constant.ORDER_FORCED)
  WaitFor(4)
  WaitFor(0.5)
  EnableWeapon(Ground_Vehicle.CutsceneTank, 1)
  WaitFor(1)
  AttackTarget(Troop.Entity550038881, Ground_Vehicle.CutsceneTank)
  WaitFor(2.5)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Ground_Vehicle.CutsceneTank)
  PlayEffect(Scripted_Effect.Null, 3, 0, 0, 0)
  SetCamera(Camera.Intro_Camera_3)
  CameraSetFOV(Camera.Intro_Camera_3, 55, constant.IMMEDIATE, 25, constant.NO_WAIT)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, constant.ARMY_XYLVANIAN, 6, SpriteID.CO_X_Prison_Ubel_Happy, constant.PLAYER_ONE)
  PhoneMessageWithObjective(5, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, 0, constant.NEW_SECONDARY_OBJECTIVE)
  CameraSetFOV(Camera.Intro_Camera_3, 75, constant.SMOOTH, 1.5, constant.NO_WAIT)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Intro_Camera_3)
  CameraSetFOV(Camera.Intro_Camera_3, 55, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraSetWaypoint(Camera.Intro_Camera_3, Waypoint.WFGulag)
  CameraSetTarget(Camera.Intro_Camera_3, Waypoint.WFGulagTarget)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(21, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, 0, constant.NEW_SECONDARY_OBJECTIVE)
  CameraSetFOV(Camera.Intro_Camera_3, 75, constant.SMOOTH, 1.5, constant.NO_WAIT)
  WaitFor(7)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PlayEffect(Scripted_Effect.Blizzard, 3, 0, 0, 0)
  SetCamera(Camera.Intro_Camera_3)
  CameraSetFOV(Camera.Intro_Camera_3, 45, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraSetWaypoint(Camera.Intro_Camera_3, Waypoint.TundranArray)
  CameraSetTarget(Camera.Intro_Camera_3, Waypoint.TundranArrayTarget)
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(7, constant.ID_NONE, constant.ARMY_TUNDRAN, 6, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, 0, constant.NEW_SECONDARY_OBJECTIVE)
  CameraSetFOV(Camera.Intro_Camera_3, 60, constant.SMOOTH, 1.5, constant.NO_WAIT)
  GoToArea(Troop.Tmissile01, -296.824, -250.979, 5, 0, constant.ORDER_NORMAL)
  WaitFor(1)
  GoToArea(Troop.Tmissile02, -284.78, -255.333, 5, 0, constant.ORDER_NORMAL)
  WaitFor(1)
  GoToArea(Troop.Tmissile03, -304.1, -260.691, 5, 0, constant.ORDER_NORMAL)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscene = 1
end
