function RAT_Gulag_East_Camp_2_S(owner)
  scriptGulagEastCamp2S = owner
  SetUnitInvulnerable(Troop.POW1, true)
  SetUnitInvulnerable(Troop.POW2, true)
  SetUnitInvulnerable(Ground_Vehicle.Saavehicle01, true)
  WaitFor(1)
  SetActive(Troop.POW1, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.POW2, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Saavehicle01, constant.INACTIVE, constant.ADJUST_WEAPON)
  repeat
    EndFrame()
  until IsDead(Building.EG2_F01) or IsDead(Destroyable_Object.EG2_F03) or IsDead(Destroyable_Object.EG2_F05) or IsDead(Destroyable_Object.EG2_F07) or IsDead(Destroyable_Object.EG2_F09) or IsDead(Destroyable_Object.EG2_F11) or IsDead(Destroyable_Object.EG2_F13) or IsDead(Destroyable_Object.EG2_F15) or IsDead(Destroyable_Object.EG2_F17) or IsDead(Destroyable_Object.EG2_F19) or IsDead(Destroyable_Object.EG2_F21) or IsDead(Destroyable_Object.EG2_F23) or IsDead(Destroyable_Object.EG2_F25) or IsDead(Destroyable_Object.EG2_F27) or IsDead(Destroyable_Object.EG2_F29) or IsDead(Destroyable_Object.EG2_F31)
  Kill(Building.EG2_F01)
  Kill(Destroyable_Object.EG2_F02)
  Kill(Destroyable_Object.EG2_F03)
  Kill(Destroyable_Object.EG2_F04)
  Kill(Destroyable_Object.EG2_F05)
  Kill(Destroyable_Object.EG2_F06)
  Kill(Destroyable_Object.EG2_F07)
  Kill(Destroyable_Object.EG2_F08)
  Kill(Destroyable_Object.EG2_F09)
  Kill(Destroyable_Object.EG2_F10)
  Kill(Destroyable_Object.EG2_F11)
  Kill(Destroyable_Object.EG2_F12)
  Kill(Destroyable_Object.EG2_F13)
  Kill(Destroyable_Object.EG2_F14)
  Kill(Destroyable_Object.EG2_F15)
  Kill(Destroyable_Object.EG2_F16)
  Kill(Destroyable_Object.EG2_F17)
  Kill(Destroyable_Object.EG2_F18)
  Kill(Destroyable_Object.EG2_F19)
  Kill(Destroyable_Object.EG2_F20)
  Kill(Destroyable_Object.EG2_F21)
  Kill(Destroyable_Object.EG2_F22)
  Kill(Destroyable_Object.EG2_F23)
  Kill(Destroyable_Object.EG2_F24)
  Kill(Destroyable_Object.EG2_F25)
  Kill(Destroyable_Object.EG2_F26)
  Kill(Destroyable_Object.EG2_F27)
  Kill(Destroyable_Object.EG2_F28)
  Kill(Destroyable_Object.EG2_F29)
  Kill(Destroyable_Object.EG2_F30)
  Kill(Destroyable_Object.EG2_F31)
  WaitFor(1)
  east = 1
  EnterVehicle(Troop.POW1, Ground_Vehicle.Saavehicle01, constant.ORDER_FORCED)
  EnterVehicle(Troop.POW2, Ground_Vehicle.Saavehicle01, constant.ORDER_FORCED)
  WaitFor(1)
  SetActive(Ground_Vehicle.Saavehicle01, constant.ACTIVE, constant.ADJUST_WEAPON)
  if GetSpawnMode() == eModeAction.Follow then
    FollowUnit(Ground_Vehicle.Saavehicle01, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
  end
  SetUnitInvulnerable(Troop.POW1, false)
  SetUnitInvulnerable(Troop.POW2, false)
  SetUnitInvulnerable(Ground_Vehicle.Saavehicle01, false)
end
