function CUTSCENE(owner)
  local cowscomehome = 0
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.CutsceneCam1)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE2target)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE2)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(1, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(2)
    ReviveDeadUnit(Troop.CutsceneSolarTroop1, -9, 480, 170, 10)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop2, -12, 479, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop1, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop3, -8, 476, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop2, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop4, -6, 475, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop3, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop5, -14, 473, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop4, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop6, -15, 477, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop5, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneSolarTroop7, -9, 480, 170, 10)
    FollowWaypoint(Troop.CutsceneSolarTroop6, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    FollowWaypoint(Troop.CutsceneSolarTroop7, Waypoint.Solartroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(4)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE3target)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE3)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    ClearMessageQueue(constant.PLAYER_ONE)
    PhoneMessage(3, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(5)
    ReviveFullUnitCarrier(flag.TYPE_SOLAR, flag.GTYPE_GRUNT, Ground_Vehicle.CutsceneSolartank1, 50, 371, 170, 5)
    GoToArea(Ground_Vehicle.CutsceneSolartank1, 46, 285, 5, constant.ORDER_FORCED)
    WaitFor(5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Ground_Vehicle.CutsceneSolartank1)
    Despawn(Troop.CutsceneSolarTroop1)
    Despawn(Troop.CutsceneSolarTroop2)
    Despawn(Troop.CutsceneSolarTroop3)
    Despawn(Troop.CutsceneSolarTroop4)
    Despawn(Troop.CutsceneSolarTroop5)
    Despawn(Troop.CutsceneSolarTroop6)
    Despawn(Troop.CutsceneSolarTroop7)
    Spawn(Troop.SE_Player)
    Spawn(Troop.SEGrunt1)
    Spawn(Troop.SEGrunt2)
    Spawn(Troop.SEGrunt3)
    Spawn(Troop.SEFlame1)
    Spawn(Troop.SEBazooka1)
    Spawn(Troop.SEBazooka2)
    Spawn(Ground_Vehicle.SEhTank)
    CameraSetTarget(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE1target)
    CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.IntroCutsceneSE1)
    CameraSetFOV(Camera.CutsceneCam1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    ClearMessageQueue(constant.PLAYER_ONE)
    PhoneMessage(5, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
    WaitFor(9.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.CutsceneCam2)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL1target)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL1)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(2, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(2)
    ReviveDeadUnit(Troop.CutsceneLegionTroop1, -22, -195, 10, 10)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop2, -18, -192, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop1, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop3, -17, -196, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop2, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop4, -23, -189, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop3, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop5, -16, -198, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop4, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop6, -23, -200, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop5, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    ReviveDeadUnit(Troop.CutsceneLegionTroop7, -17, -199, 10, 10)
    FollowWaypoint(Troop.CutsceneLegionTroop6, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(1)
    FollowWaypoint(Troop.CutsceneLegionTroop7, Waypoint.Legiontroops, 0, 0, constant.ORDER_FORCED)
    WaitFor(4)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL2target)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL2)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    ClearMessageQueue(constant.PLAYER_TWO)
    PhoneMessage(4, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(5)
    ReviveFullUnitCarrier(flag.TYPE_UNDERWORLD, flag.GTYPE_GRUNT, Ground_Vehicle.CutsceneLegiontank1, 45, -74, 0, 5)
    GoToArea(Ground_Vehicle.CutsceneLegiontank1, 43, 47, 5, constant.ORDER_FORCED)
    WaitFor(5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Ground_Vehicle.CutsceneLegiontank1)
    Despawn(Troop.CutsceneLegionTroop1)
    Despawn(Troop.CutsceneLegionTroop2)
    Despawn(Troop.CutsceneLegionTroop3)
    Despawn(Troop.CutsceneLegionTroop4)
    Despawn(Troop.CutsceneLegionTroop5)
    Despawn(Troop.CutsceneLegionTroop6)
    Despawn(Troop.CutsceneLegionTroop7)
    Spawn(Troop.IL_Player)
    Spawn(Troop.ILGrunt1)
    Spawn(Troop.ILGrunt2)
    Spawn(Troop.ILGrunt3)
    Spawn(Troop.ILFlame1)
    Spawn(Troop.ILBazooka1)
    Spawn(Troop.ILBazooka2)
    Spawn(Ground_Vehicle.ILhTank)
    CameraSetTarget(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL3target)
    CameraSetWaypoint(Camera.CutsceneCam2, Waypoint.IntroCutsceneIL3)
    CameraSetFOV(Camera.CutsceneCam2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    ClearMessageQueue(constant.PLAYER_TWO)
    PhoneMessage(6, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_TWO)
    WaitFor(9.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
