function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.cutscenecamplayer1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutscene1Xtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneshot1X)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(2, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Ubel_Happy, constant.PLAYER_ONE)
    WaitFor(4)
    PutUnitInVehicle(Troop.CutsceneXYGunship2pilot1, Air_Vehicle.CutsceneXYGunship2, 0)
    GoToArea(Air_Vehicle.CutsceneXYGunship2, -400, 210, 5, constant.ORDER_FORCED)
    WaitFor(2)
    PutUnitInVehicle(Troop.CutsceneXYGunship1pilot1, Air_Vehicle.CutsceneXYGunship1, 0)
    GoToArea(Air_Vehicle.CutsceneXYGunship1, -300, 210, 5, constant.ORDER_FORCED)
    WaitFor(6.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Air_Vehicle.CutsceneXYGunship1)
    Despawn(Air_Vehicle.CutsceneXYGunship2)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneshot4Xtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneshot4X)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(8, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Ubel_Happy, constant.PLAYER_ONE)
    WaitFor(4)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt1, 162, 256, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt1, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt2, 159, 254, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt2, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt3, 165, 251, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt3, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt4, 160, 258, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt4, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt5, 163, 255, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt5, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt6, 164, 259, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt6, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt7, 158, 252, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt7, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt8, 166, 257, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt8, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt9, 163, 253, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt9, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt10, 160, 259, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt10, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt11, 161, 254, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt11, 0, 140, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.XintrocutsceneGrunt12, 158, 256, 225, 10)
    WaitFor(0.5)
    GoToArea(Troop.XintrocutsceneGrunt12, 0, 140, 0, 0, constant.ORDER_FORCED)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Troop.XintrocutsceneGrunt1)
    Despawn(Troop.XintrocutsceneGrunt2)
    Despawn(Troop.XintrocutsceneGrunt3)
    Despawn(Troop.XintrocutsceneGrunt4)
    Despawn(Troop.XintrocutsceneGrunt5)
    Despawn(Troop.XintrocutsceneGrunt6)
    Despawn(Troop.XintrocutsceneGrunt7)
    Despawn(Troop.XintrocutsceneGrunt8)
    Despawn(Troop.XintrocutsceneGrunt9)
    Despawn(Troop.XintrocutsceneGrunt10)
    Despawn(Troop.XintrocutsceneGrunt11)
    Despawn(Troop.XintrocutsceneGrunt12)
    Spawn(Troop.Xgrunt1)
    Spawn(Troop.Xgrunt2)
    Spawn(Troop.Xgrunt3)
    Spawn(Troop.Xgrunt4)
    Spawn(Troop.Xgrunt5)
    Spawn(Troop.Xgrunt6)
    Spawn(Troop.Xgrunt7)
    Spawn(Troop.Xbazooka01)
    Spawn(Troop.Xbazooka02)
    Spawn(Troop.Xbazooka03)
    Spawn(Troop.Xbazooka04)
    Spawn(Troop.Xbazooka05)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneshot2Xtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneshot2X)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(4, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Ubel_Happy, constant.PLAYER_ONE)
    WaitFor(12)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutscene3Xtarget)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneshot3X)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_ONE)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(6, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Ubel_Happy, constant.PLAYER_ONE)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.cutscenecamplayer2)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutscene1Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutsceneshot1T)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(1, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Happy, constant.PLAYER_TWO)
    WaitFor(3)
    PutUnitInVehicle(Troop.CutsceneTTGunship1pilot, Air_Vehicle.CutsceneTTGunship1, 0)
    GoToArea(Air_Vehicle.CutsceneTTGunship1, 0, 210, 5, constant.ORDER_FORCED)
    WaitFor(2)
    PutUnitInVehicle(Troop.CutsceneTTGunship2pilot, Air_Vehicle.CutsceneTTGunship2, 0)
    GoToArea(Air_Vehicle.CutsceneTTGunship2, -82, 210, 5, constant.ORDER_FORCED)
    WaitFor(7.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Air_Vehicle.CutsceneTTGunship1)
    Despawn(Air_Vehicle.CutsceneTTGunship2)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutsceneshot4Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutsceneshot4T)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(7, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Happy, constant.PLAYER_TWO)
    WaitFor(4)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt1, -149, -179, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt1, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt2, -145, -176, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt2, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt3, -147, -174, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt3, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt4, -146, -181, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt4, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt5, -148, -178, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt5, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt6, -146, -182, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt6, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt7, -145, -177, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt7, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt8, -149, -173, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt8, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt9, -148, -175, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt9, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt10, -146, -176, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt10, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt11, -147, -180, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt11, -10, -45, 0, 0, constant.ORDER_FORCED)
    ReviveDeadUnit(Troop.TintrocutsceneGrunt12, -149, -179, 45, 10)
    WaitFor(0.5)
    GoToArea(Troop.TintrocutsceneGrunt12, -10, -45, 0, 0, constant.ORDER_FORCED)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    Despawn(Troop.TintrocutsceneGrunt1)
    Despawn(Troop.TintrocutsceneGrunt2)
    Despawn(Troop.TintrocutsceneGrunt3)
    Despawn(Troop.TintrocutsceneGrunt4)
    Despawn(Troop.TintrocutsceneGrunt5)
    Despawn(Troop.TintrocutsceneGrunt6)
    Despawn(Troop.TintrocutsceneGrunt7)
    Despawn(Troop.TintrocutsceneGrunt8)
    Despawn(Troop.TintrocutsceneGrunt9)
    Despawn(Troop.TintrocutsceneGrunt10)
    Despawn(Troop.TintrocutsceneGrunt11)
    Despawn(Troop.TintrocutsceneGrunt12)
    Spawn(Troop.Tgrunt1)
    Spawn(Troop.Tgrunt2)
    Spawn(Troop.Tgrunt3)
    Spawn(Troop.Tgrunt4)
    Spawn(Troop.Tgrunt5)
    Spawn(Troop.Tgrunt6)
    Spawn(Troop.Tgrunt7)
    Spawn(Troop.Tbazooka1)
    Spawn(Troop.Tbazooka2)
    Spawn(Troop.Tbazooka3)
    Spawn(Troop.Tbazooka4)
    Spawn(Troop.Tbazooka5)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutsceneshot2Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutsceneshot2T)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(3, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Happy, constant.PLAYER_TWO)
    WaitFor(12)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer2, Waypoint.cutscene3Ttarget)
    CameraSetWaypoint(Camera.cutscenecamplayer2, Waypoint.cutscene3T)
    CameraSetFOV(Camera.cutscenecamplayer2, 60, constant.IMMEDIATE, 10, constant.NO_WAIT)
    ClearMessageQueue(constant.PLAYER_TWO)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(5, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Happy, constant.PLAYER_TWO)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
