function Cutscene_Start(owner)
  cutscenes = owner
  FreezePlayer()
  StartIntro()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Entity0113)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Entity0114)
  PhoneMessage(0, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  PhoneMessage(1, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  WaitFor(14)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam2)
  CameraSetTarget(Camera.Cam2, Waypoint.Entity0120)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Entity0117)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  PhoneMessage(3, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  WaitFor(14)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam8)
  CameraSetTarget(Camera.Cam8, Waypoint.Entity0158)
  CameraSetWaypoint(Camera.Cam8, Waypoint.Entity0155)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, 0, 0, 6, SpriteID.CO_WF_Betty_Happy)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam3)
  CameraSetTarget(Camera.Cam3, Waypoint.Entity0128)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Entity0136)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(5, 0, 0, 6, SpriteID.CO_WF_Betty_Happy)
  PhoneMessage(7, 0, 0, 5, SpriteID.CO_WF_Betty_Happy)
  WaitFor(14)
  DebugOut("Cutscene has run its natural course")
  cutscene = 1
end
