function C4M5_Cutscene(owner)
  cutscene = owner
  FreezePlayer()
  StartIntro()
  GoToArea(Air_Vehicle.XBomber1, 450, 350, 20, constant.ORDER_FORCED)
  SetCamera(Camera.Cam1)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cut1)
  PhoneMessage(1, constant.ID_NONE, 0, 7, SpriteID.CO_WF_Betty_Happy)
  EndFrame()
  WaitFor(7)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Happy)
  SetCamera(Camera.Cam2)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Cut2)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(7)
  Despawn(Air_Vehicle.XBomber1)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PhoneMessage(3, 0, 2, 6, SpriteID.CO_T_Nova_Happy)
  SetCamera(Camera.Cam3)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Cut3)
  Spawn(Air_Vehicle.TGunship3)
  Spawn(Air_Vehicle.TGunship4)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(8)
  ClearMessageQueue()
  PhoneMessage(4, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Happy)
  SetCamera(Camera.Cam4)
  CameraSetWaypoint(Camera.Cam4, Waypoint.Cut4)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(7)
  cutscene = 1
  EndFrame()
  return
end
