function First_Wall(owner)
  Despawn(Air_Vehicle.TGunship1)
  Despawn(Air_Vehicle.TGunship2)
  WaitFor(1)
  repeat
    EndFrame()
  until NumItemsInArea(Map_Zone.FirstWall, flag.TYPE_WFRONTIER) > 0
  Spawn(Air_Vehicle.TGunship1)
  Spawn(Air_Vehicle.TGunship2)
  Spawn(Air_Vehicle.XBomber1)
  DebugOut("Spawn Xbomber")
  DebugOut("Spawn Gunship1")
  DebugOut("Spawn Gunship2")
  PhoneMessage(8, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  GoToArea(Air_Vehicle.TGunship1, 8, -123, 35, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.TGunship2, 8, -123, 35, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.XBomber1, 8, -123, 35, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.TGunship1, Building.XpillboxEmpty0004, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.TGunship2, Building.XpillboxEmpty0005, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.XBomber1, Ground_Vehicle.WFlightTank0001, constant.ORDER_FORCED)
  WaitFor(5)
  PhoneMessage(37, 0, 2, 4, SpriteID.CO_T_Nova_Happy)
  WaitFor(5)
  PhoneMessage(18, 0, 0, 4, SpriteID.CO_WF_Betty_Happy)
  AttackTarget(Ground_Vehicle.XAA1, Air_Vehicle.TGunship2, constant.ORDER_FORCED)
  EndFrame()
end
