function Intro_Cut_Scene(owner)
  cutscenes = owner
  StartIntro()
  FreezePlayer()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Look1)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cut1)
  GoToArea(Air_Vehicle.LChopperCut1, 0, 190, 10, constant.ORDER_FORCED)
  PhoneMessage(0, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  WaitFor(7)
  ClearMessageQueue()
  Despawn(Air_Vehicle.LChopperCut1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam2)
  CameraSetTarget(Camera.Cam2, Waypoint.Look2)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Cut2)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  WaitFor(9)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam4)
  CameraSetTarget(Camera.Cam4, Waypoint.Look4)
  CameraSetWaypoint(Camera.Cam4, Waypoint.Cut4)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(44, 0, 3, 4, SpriteID.CO_SE_Leiqo_Happy)
  WaitFor(9)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam3)
  CameraSetTarget(Camera.Cam3, Waypoint.Look3)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Cut3)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, 0, 0, 4, SpriteID.CO_WF_Austin_Happy)
  WaitFor(9)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscene = 1
end
