function CUTSCENE_OUTRO_WIN(owner)
  outrocutscene = owner
  repeat
    EndFrame()
  until dreadnaughtdead == 1
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Teleport(Water_Vehicle.SEdreadnaught, 503.4, 189.9, 270, 5)
  ClearMessageQueue()
  StartOutro()
  Despawn(Building.Statue)
  Spawn(Building.StatueClean)
  Spawn(Troop.dummy)
  EndFrame()
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.dummy, true)
  Despawn(Air_Vehicle.AIbomber1)
  Despawn(Air_Vehicle.AIbomber2)
  Spawn(Troop.Winningdude1)
  Spawn(Troop.Winningdude2)
  Spawn(Troop.Winningdude3)
  Spawn(Troop.Winningdude4)
  Spawn(Troop.Winningdude5)
  Spawn(Troop.Winningdude6)
  Spawn(Troop.Winningdude7)
  Spawn(Troop.Winningdude8)
  Spawn(Troop.Winningdude9)
  Spawn(Troop.Winningdude10)
  DeclareVictory(constant.ARMY_ANGLO)
  SetCamera(Camera.cutscenecam)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE)
  CameraSetTarget(Camera.cutscenecam, Waypoint.wincutscenetargetDREAD)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.wincutsceneDREAD)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(103, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Happy, constant.PLAYER_ONE)
  WaitFor(3.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE)
  CameraSetTarget(Camera.cutscenecam, Waypoint.wincutscenetarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.wincutscene)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(119, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
  PhoneMessage(120, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  PhoneMessage(121, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Happy, constant.PLAYER_ONE)
  WaitFor(32)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  OutroCutsceneEnded = true
end
