function CUTSCENE_INTRO(owner)
  cutscene = owner
  Despawn(Water_Vehicle.cutsceneship1)
  FreezePlayer(constant.PLAYER_ONE)
  StartIntro()
  SetCamera(Camera.cutscenecam)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1Atarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1Awp)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(0, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Spawn(Water_Vehicle.cutsceneship1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1Btarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1Bwp)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE)
  PhoneMessage(6, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Happy, constant.PLAYER_ONE)
  WaitFor(6)
  GoToArea(Water_Vehicle.cutsceneship1, 626, 196, 5, constant.ORDER_FORCED)
  WaitFor(12.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1Ctarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1Cwp)
  CameraSetFOV(Camera.cutscenecam, 75, constant.IMMEDIATE)
  GoToArea(Ground_Vehicle.SEltank5, -713.2, -99.9, 5, constant.ORDER_FORCED)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(5, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1Dtarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1Dwp)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE, 3)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(8, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Sad, constant.PLAYER_ONE, false, constant.NEW_SECONDARY_OBJECTIVE)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1Etarget)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1Ewp)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(10, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Happy, constant.PLAYER_ONE)
  WaitFor(11.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  EndFrame()
  cutsceneskipped = true
end
