function Cutscene01(owner)
  cutscene = owner
  SetObjectiveData(Objective_Marker.TT_Spawn01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.XN_Spawn01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.TT_Spawn01_Logo, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.XN_Spawn01_Logo, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  Despawn(Water_Vehicle.XN_Battleship01)
  Despawn(Water_Vehicle.IntroXBattleship01)
  Despawn(Air_Vehicle.TT_Bomber01)
  Despawn(Air_Vehicle.TT_Bomber02)
  Despawn(Air_Vehicle.IntroTTBomber01)
  Despawn(Air_Vehicle.IntroTTBomber02)
  Despawn(Troop.XN_AntiAir03)
  Despawn(Troop.XN_AntiAir06)
  Kill(Troop.IntroXGrunt01)
  Kill(Troop.IntroXGrunt02)
  Kill(Troop.IntroXGrunt03)
  Kill(Troop.IntroXGrunt04)
  Kill(Troop.IntroXGrunt05)
  Kill(Troop.IntroXGrunt06)
  Kill(Troop.IntroXAAVet01)
  Kill(Troop.IntroXAAVet02)
  Kill(Troop.IntroXAAVet03)
  Kill(Troop.IntroXAAVet04)
  Kill(Troop.IntroXAAVet05)
  Kill(Troop.IntroXAAVet06)
  Kill(Troop.IntroXFlamer01)
  Kill(Troop.IntroXFlamer02)
  Kill(Troop.IntroXFlamer03)
  Kill(Troop.IntroXFlamer04)
  Kill(Ground_Vehicle.IntroXTank01)
  Spawn(Water_Vehicle.IntroXBattleship01)
  Spawn(Air_Vehicle.IntroTTBomber01)
  GoToArea(Water_Vehicle.IntroXBattleship01, GetObjectXPosition(Water_Vehicle.XN_Battleship01), GetObjectZPosition(Water_Vehicle.XN_Battleship01), 0, 0, constant.ORDER_FORCED)
  StartIntro()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.Player01Cutscene, constant.PLAYER_ONE)
    CameraSetFOV(Camera.Player01Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player01Cutscene, Waypoint.IntroXShot01Spline)
    CameraSetTarget(Camera.Player01Cutscene, Waypoint.IntroXShot01Target)
    PhoneMessage(102, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
    PhoneMessage(103, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.Player02Cutscene, constant.PLAYER_TWO)
    CameraSetFOV(Camera.Player02Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player02Cutscene, Waypoint.IntroTTShot01Spline)
    CameraSetTarget(Camera.Player02Cutscene, Waypoint.IntroTTShot01Target)
    PhoneMessage(107, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO)
    PhoneMessage(108, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Happy, constant.PLAYER_TWO)
  end
  WaitFor(7)
  Despawn(Air_Vehicle.IntroTTBomber01)
  Despawn(Air_Vehicle.IntroTTBomber02)
  WaitFor(13)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Water_Vehicle.IntroXBattleship01)
  Despawn(Troop.IntroXGrunt01)
  Despawn(Troop.IntroXGrunt02)
  Despawn(Troop.IntroXGrunt03)
  Despawn(Troop.IntroXGrunt04)
  Despawn(Troop.IntroXGrunt05)
  Despawn(Troop.IntroXGrunt06)
  Despawn(Troop.IntroXAAVet01)
  Despawn(Troop.IntroXAAVet02)
  Despawn(Troop.IntroXAAVet03)
  Despawn(Troop.IntroXAAVet04)
  Despawn(Troop.IntroXAAVet05)
  Despawn(Troop.IntroXAAVet06)
  Despawn(Troop.IntroXFlamer01)
  Despawn(Troop.IntroXFlamer02)
  Despawn(Troop.IntroXFlamer03)
  Despawn(Troop.IntroXFlamer04)
  Despawn(Ground_Vehicle.IntroXTank01)
  Spawn(Water_Vehicle.XN_Battleship01)
  Spawn(Troop.XN_Grunt01)
  Spawn(Troop.XN_Grunt02)
  Spawn(Troop.XN_Grunt03)
  Spawn(Troop.XN_Grunt04)
  Spawn(Troop.XN_Grunt05)
  Spawn(Troop.XN_Grunt06)
  Spawn(Troop.XN_AntiAir01)
  Spawn(Troop.XN_AntiAir02)
  Spawn(Troop.XN_AntiAir03)
  Spawn(Troop.XN_AntiAir04)
  Spawn(Troop.XN_AntiAir05)
  Spawn(Troop.XN_Hose01)
  Spawn(Troop.XN_Hose02)
  Spawn(Troop.XN_Hose03)
  Spawn(Troop.XN_Hose04)
  Spawn(Ground_Vehicle.XN_LightTank01)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.Player01Cutscene, constant.PLAYER_ONE)
    CameraSetFOV(Camera.Player01Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player01Cutscene, Waypoint.IntroXShot02Spline)
    CameraSetTarget(Camera.Player01Cutscene, Waypoint.IntroXShot02Target)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.Player02Cutscene, constant.PLAYER_TWO)
    CameraSetFOV(Camera.Player02Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player02Cutscene, Waypoint.IntroTTShot02Spline)
    CameraSetTarget(Camera.Player02Cutscene, Waypoint.IntroTTShot02Target)
  end
  ClearMessageQueue(constant.PLAYER_ONE)
  ClearMessageQueue(constant.PLAYER_TWO)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(104, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  PhoneMessageWithObjective(109, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO, false, constant.NEW_PRIMARY_OBJECTIVE)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetObjectiveData(Objective_Marker.TT_BridgeBarricade, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.XN_BridgeBarricade, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.Player01Cutscene, constant.PLAYER_ONE)
    CameraSetFOV(Camera.Player01Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player01Cutscene, Waypoint.IntroXShot03Spline)
    CameraSetTarget(Camera.Player01Cutscene, Waypoint.IntroXShot03Target)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.Player02Cutscene, constant.PLAYER_TWO)
    CameraSetFOV(Camera.Player02Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player02Cutscene, Waypoint.IntroTTShot03Spline)
    CameraSetTarget(Camera.Player02Cutscene, Waypoint.IntroTTShot03Target)
  end
  ClearMessageQueue(constant.PLAYER_ONE)
  ClearMessageQueue(constant.PLAYER_TWO)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(105, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  PhoneMessage(110, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetObjectiveData(Objective_Marker.XN_HQ01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.TT_HQ01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.Player01Cutscene, constant.PLAYER_ONE)
    CameraSetFOV(Camera.Player01Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player01Cutscene, Waypoint.IntroXShot04Spline)
    CameraSetTarget(Camera.Player01Cutscene, Waypoint.IntroXShot04Target)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.Player02Cutscene, constant.PLAYER_TWO)
    CameraSetFOV(Camera.Player02Cutscene, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
    CameraSetWaypoint(Camera.Player02Cutscene, Waypoint.IntroTTShot04Spline)
    CameraSetTarget(Camera.Player02Cutscene, Waypoint.IntroTTShot04Target)
  end
  ClearMessageQueue(constant.PLAYER_ONE)
  ClearMessageQueue(constant.PLAYER_TWO)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(106, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  PhoneMessage(112, constant.ID_NONE, 1, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  PhoneMessage(111, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO)
  PhoneMessage(113, constant.ID_NONE, 2, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO)
  WaitFor(18)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    netvariable.player1.ReadyForFade = 0
    netvariable.player1.skip = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    netvariable.player2.ReadyForFade = 0
    netvariable.player2.skip = 1
  end
end
