function Global_Variables(owner)
  MissionTime = 480
  Player1LastGruntRevived = 0
  Player2LastGruntRevived = 0
  CurrentXNX = -349
  CurrentXNZ = -67
  CurrentWaterXNX = -502
  CurrentWaterXNZ = -217
  CurrentTTX = 130
  CurrentTTZ = -322
  spawner = stop
  gamestate = 0
  tensecondspawner = 0
  spawner = 0
  go = 1
  stop = 0
  gamestate = 0
  cutscene = 0
  cutscenefinished = 0
  cutsceneabort = 0
  cutsceneskipped = 0
  KillCutscene02 = 0
  Cutscene02Finished = 0
  Cutscene02Begins = 0
  KillCutscene03 = 0
  Cutscene03Finished = 0
  Cutscene03Begins = 0
  KillObjectives = 0
  CutsceneHasEnded = 0
  netvariable.player1.skip = 0
  netvariable.player2.skip = 0
  netvariable.player1.skip02 = 0
  netvariable.player2.skip02 = 0
  netvariable.player1.skip03 = 0
  netvariable.player2.skip03 = 0
  netvariable.player1.Objective01 = 0
  netvariable.player2.Objective01 = 0
  netvariable.player1.ReadyForCutscene02 = 0
  netvariable.player2.ReadyForCutscene02 = 0
  netvariable.player1.ReadyForCutscene03 = 0
  netvariable.player2.ReadyForCutscene03 = 0
  netvariable.player1.FreezingWater01 = 0
  netvariable.player2.FreezingWater01 = 0
  netvariable.player1.ReadyForFade = 0
  netvariable.player2.ReadyForFade = 0
  netvariable.player1.TransferComplete = 0
  netvariable.player2.TransferComplete = 0
  XylvaniaCrossingBridge = 0
  DeadTTWarehouses = 0
  TT_Warehouse01Dead = 0
  TT_Warehouse02Dead = 0
  TT_Warehouse03Dead = 0
  DeadTTWarehouseMessage01 = 0
  DeadTTWarehouseMessage02 = 0
  TT_FuelTank01Dead = 0
  TT_FuelTank02Dead = 0
  TT_FuelTank03Dead = 0
  BridgeDefence01Dead = 0
  BridgeDefence02Dead = 0
  BridgeDefence03Dead = 0
  BridgeDefence04Dead = 0
  BridgeDefence05Dead = 0
  TT_SuperGun01Dead = 0
  TT_SuperGun02Dead = 0
  TT_RPGTower01Dead = 0
  TT_RPGTower02Dead = 0
  TT_RPGTower03Dead = 0
  DeadBridgeDefences = 0
  DeadBridgeDefenceObjective01 = 0
  DeadBridgeDefenceObjective02 = 0
  DeadBridgeDefenceObjective03 = 0
  DeadBridgeDefenceObjective04 = 0
  DeadTTFuel = 0
  DeadTTFuelMessage01 = 0
  DeadTTFuelMessage02 = 0
  DeadTTFuelMessage03 = 0
  DeadTTFuelObjective01 = 0
  DeadTTFuelObjective02 = 0
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    OutOfBoundsMessageInfo(501, 1, 6, SpriteID.CO_X_Vlad_Sad, constant.PLAYER_ONE)
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    OutOfBoundsMessageInfo(484, 2, 6, SpriteID.CO_T_Nova_Sad, constant.PLAYER_TWO)
  end
end
