function C3M1_Cutscene(owner)
  Despawn(Ground_Vehicle.Xbattlestation0001)
  Despawn(Ground_Vehicle.Xbattlestation0002)
  cutsceneStart = owner
  DebugOut("Cutscene Start ID", cutsceneStart)
  StartIntro()
  FreezePlayer()
  SetCamera(Camera.CutsceneCamera0003)
  CameraSetWaypoint(Camera.CutsceneCamera0003, Waypoint.Entity0221)
  CameraSetTarget(Camera.CutsceneCamera0003, Waypoint.Entity0223)
  PhoneMessage(0, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Sad)
  PhoneMessage(1, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Happy)
  WaitFor(14)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutsceneCamera0002)
  CameraSetWaypoint(Camera.CutsceneCamera0002, Waypoint.Entity0217)
  CameraSetTarget(Camera.CutsceneCamera0002, Waypoint.Entity0219)
  EnterVehicle(Troop.SgruntMG0001, Building.SmgNest0001, constant.ORDER_FORCED)
  EnterVehicle(Troop.SgruntMG0002, Building.SmgNest0002, constant.ORDER_FORCED)
  GoToArea(Troop.Sgrunt0004, 346, -182, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Sgrunt0005, 367, -176, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Sgrunt0006, 357, -192, 5, constant.ORDER_FORCED)
  GoToArea(Troop.Sgrunt0007, 351, -205, 5, constant.ORDER_FORCED)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, 3, 4, SpriteID.CO_SE_Leiqo_Happy)
  PhoneMessage(3, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Happy)
  WaitFor(14)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutsceneCamera0001)
  CameraSetFOV(Camera.CutsceneCamera0001, 30, constant.IMMEDIATE)
  CameraSetWaypoint(Camera.CutsceneCamera0001, Waypoint.Entity0211)
  CameraSetTarget(Camera.CutsceneCamera0001, Waypoint.Entity0216)
  CameraSetFOV(Camera.CutsceneCamera0001, 70, constant.SMOOTH, 5, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(4, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Betty_Happy)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Camera0001)
  Spawn(Ground_Vehicle.Xbattlestation0001)
  Spawn(Ground_Vehicle.Xbattlestation0002)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(5, constant.ID_NONE, 3, 6, SpriteID.CO_SE_Leiqo_Happy)
  PhoneMessage(6, constant.ID_NONE, 0, 4, SpriteID.CO_WF_Betty_Happy)
  cutsceneStart = 1
  UnfreezePlayer()
  StartScoringTimer()
  EndFrame()
  return
end
