function GStringID(owner)
end
NumGlobalStrings = GetNumGlobalStrings()
StringID = {}
StringID.Back = 18
StringID.Continue = 2
StringID.Yes = 12
StringID.No = 13
StringID.OK = NumGlobalStrings + 12
StringID.Accept = NumGlobalStrings + 5
StringID.Confirm = NumGlobalStrings + 6
StringID.Cancel = NumGlobalStrings + 7
StringID.On = NumGlobalStrings + 8
StringID.Off = NumGlobalStrings + 9
StringID.Challenge = NumGlobalStrings + 471
StringID.YES = NumGlobalStrings + 201
StringID.NO = NumGlobalStrings + 202
StringID.WesternFrontier = NumGlobalStrings + 22
StringID.TundranTerritories = NumGlobalStrings + 23
StringID.SolarEmpire = NumGlobalStrings + 24
StringID.Xylvania = NumGlobalStrings + 25
StringID.AngloIsles = NumGlobalStrings + 26
StringID.IronLegion = NumGlobalStrings + 27
FactionNameTable = {
  StringID.SolarEmpire,
  StringID.WesternFrontier,
  StringID.AngloIsles,
  StringID.IronLegion,
  StringID.TundranTerritories,
  StringID.Xylvania
}
StringID.ByKUJU = NumGlobalStrings + 43
StringID.ABToStart = NumGlobalStrings + 44
StringID.PleasePress = NumGlobalStrings + 47
StringID.Ampersand = NumGlobalStrings + 48
StringID.ToBegin = NumGlobalStrings + 49
StringID.Loading = NumGlobalStrings + 65
StringID.ClearSave = NumGlobalStrings + 71
StringID.ClrCamProgTitle = NumGlobalStrings + 72
StringID.ClrCamProgMssg = NumGlobalStrings + 73
StringID.Empty = NumGlobalStrings + 74
StringID.Saving = NumGlobalStrings + 77
StringID.Creating = NumGlobalStrings + 79
StringID.OpSuccessful = NumGlobalStrings + 80
StringID.Checking = NumGlobalStrings + 81
StringID.DoNotTurnOffPower = NumGlobalStrings + 82
StringID.A = NumGlobalStrings + 253
StringID.B = NumGlobalStrings + 254
StringID.C = NumGlobalStrings + 255
StringID.EditProfile = NumGlobalStrings + 256
StringID.ChangeName = NumGlobalStrings + 257
StringID.NewNameMessg = NumGlobalStrings + 258
StringID.Save = NumGlobalStrings + 259
StringID.LoadingSP = NumGlobalStrings + 260
StringID.LoadingMP = NumGlobalStrings + 261
StringID.CreatingSP = NumGlobalStrings + 262
StringID.CreatingMP = NumGlobalStrings + 263
StringID.DeletingSP = NumGlobalStrings + 264
StringID.DeletingMP = NumGlobalStrings + 271
StringID.LoadingSPMessg = NumGlobalStrings + 265
StringID.LoadingMPMessg = NumGlobalStrings + 266
StringID.CreatingSPMessg = NumGlobalStrings + 267
StringID.CreatingMPMessg = NumGlobalStrings + 268
StringID.DeletingSPMessg = NumGlobalStrings + 270
StringID.DeletingMPMessg = NumGlobalStrings + 269
StringID.Deleting = NumGlobalStrings + 264
StringID.DeletingMessg = NumGlobalStrings + 270
StringID.TotalWins = NumGlobalStrings + 94
StringID.TotalLosses = NumGlobalStrings + 95
StringID.FriendCode = NumGlobalStrings + 96
StringID.Add = NumGlobalStrings + 106
StringID.FriendList = NumGlobalStrings + 107
StringID.Delete = NumGlobalStrings + 108
StringID.DeleteFriend = NumGlobalStrings + 109
StringID.AreYouSure = NumGlobalStrings + 110
StringID.SinglePlayer = NumGlobalStrings + 127
StringID.Multiplayer = NumGlobalStrings + 128
StringID.Options = NumGlobalStrings + 129
StringID.Extras = NumGlobalStrings + 130
StringID.GameOptions = NumGlobalStrings + 148
StringID.Sound = NumGlobalStrings + 149
StringID.Language = NumGlobalStrings + 150
StringID.General = NumGlobalStrings + 151
StringID.Advanced = NumGlobalStrings + 151
StringID.OptionsDialogTitle = NumGlobalStrings + 152
StringID.OptionsDialogMssg = NumGlobalStrings + 153
StringID.SaveMenu = NumGlobalStrings + 154
StringID.SoundVolume = NumGlobalStrings + 169
StringID.Music = NumGlobalStrings + 170
StringID.SFX = NumGlobalStrings + 171
StringID.COVoice = NumGlobalStrings + 172
StringID.COSubtitles = NumGlobalStrings + 173
StringID.MovieSubtitles = NumGlobalStrings + 174
StringID.LangSubtitles = NumGlobalStrings + 190
StringID.Movie = NumGlobalStrings + 191
StringID.COMessage = NumGlobalStrings + 192
StringID.Wait = NumGlobalStrings + 193
StringID.Follow = NumGlobalStrings + 194
StringID.UnitSpawn = NumGlobalStrings + 195
StringID.UnitAttack = NumGlobalStrings + 196
StringID.DisplayTutorials = NumGlobalStrings + 197
StringID.UnitsSpawnedMssg = NumGlobalStrings + 198
StringID.UnitsAttackMssg = NumGlobalStrings + 199
StringID.TutorialOnOffMssg = NumGlobalStrings + 200
StringID.GeneralOptions = NumGlobalStrings + 211
StringID.Brightness = NumGlobalStrings + 212
StringID.Rumble = NumGlobalStrings + 213
StringID.Prologue = NumGlobalStrings + 232
StringID.Concepts = NumGlobalStrings + 233
StringID.Movies = NumGlobalStrings + 234
StringID.Units = NumGlobalStrings + 235
StringID.Armies = NumGlobalStrings + 236
StringID.Factions = NumGlobalStrings + 237
StringID.Credits = NumGlobalStrings + 238
StringID.PlayPrologueTitle = NumGlobalStrings + 239
StringID.PlayPrologueMssg = NumGlobalStrings + 240
StringID.TotalScore = NumGlobalStrings + 294
StringID.NextUnlock = NumGlobalStrings + 295
StringID.CampaignSelect = NumGlobalStrings + 296
StringID.AllARank = NumGlobalStrings + 297
StringID.AllSRank = NumGlobalStrings + 298
StringID.Completed = NumGlobalStrings + 299
StringID.Campaign1 = NumGlobalStrings + 300
StringID.Campaign2 = NumGlobalStrings + 301
StringID.Campaign3 = NumGlobalStrings + 302
StringID.Flashback1 = NumGlobalStrings + 303
StringID.Flashback2 = NumGlobalStrings + 304
StringID.PlayFriend = NumGlobalStrings + 358
StringID.PlayAnyone = NumGlobalStrings + 359
StringID.GettingServers = NumGlobalStrings + 362
StringID.PlayCreating = NumGlobalStrings + 363
StringID.CreateFailed = NumGlobalStrings + 364
StringID.Joining = NumGlobalStrings + 365
StringID.JoinFailed = NumGlobalStrings + 366
StringID.Name = NumGlobalStrings + 383
StringID.Status = NumGlobalStrings + 384
StringID.WinLose = NumGlobalStrings + 385
StringID.Code = NumGlobalStrings + 386
StringID.Rank = NumGlobalStrings + 387
StringID.Ratio = NumGlobalStrings + 388
StringID.EditFriends = NumGlobalStrings + 389
StringID.FMDeleteFriend = NumGlobalStrings + 390
StringID.FMAreYouSure = NumGlobalStrings + 391
StringID.Assault = NumGlobalStrings + 400
StringID.Skirmish = NumGlobalStrings + 401
StringID.COOP = NumGlobalStrings + 402
StringID.Locked = NumGlobalStrings + 422
StringID.Friends = NumGlobalStrings + 441
StringID.Statistics = NumGlobalStrings + 442
StringID.MPProfile = NumGlobalStrings + 442
StringID.NameIsUsedMssg = NumGlobalStrings + 443
StringID.ConceptGallery = NumGlobalStrings + 8
StringID.Access = NumGlobalStrings + 546
StringID.AllocFailed = NumGlobalStrings + 547
StringID.Busy = NumGlobalStrings + 548
StringID.Corrupt = NumGlobalStrings + 549
StringID.ECCCritical = NumGlobalStrings + 550
StringID.Exists = NumGlobalStrings + 551
StringID.Invalid = NumGlobalStrings + 552
StringID.MaxBlocks = NumGlobalStrings + 553
StringID.MaxFD = NumGlobalStrings + 554
StringID.MaxFiles = NumGlobalStrings + 555
StringID.NoExists = NumGlobalStrings + 556
StringID.NotEmpty = NumGlobalStrings + 557
StringID.OpenFD = NumGlobalStrings + 558
StringID.Authentication = NumGlobalStrings + 559
StringID.Unknown = NumGlobalStrings + 560
StringID.FatalError = NumGlobalStrings + 561
StringID.NotReady = NumGlobalStrings + 562
StringID.InitFailed = NumGlobalStrings + 563
StringID.NoMemory = NumGlobalStrings + 564
StringID.NoInodes = NumGlobalStrings + 565
StringID.NoBlocks = NumGlobalStrings + 566
StringID.NoBlocksMP = NumGlobalStrings + 576
StringID.WriteError = NumGlobalStrings + 567
StringID.ReadError = NumGlobalStrings + 568
StringID.CRCError = NumGlobalStrings + 569
StringID.UnknownOp = NumGlobalStrings + 570
StringID.UnknownOpState = NumGlobalStrings + 571
StringID.UnknownError = NumGlobalStrings + 572
StringID.ContinueNoSave = NumGlobalStrings + 573
StringID.QuitToIPL = NumGlobalStrings + 574
StringID.Create = NumGlobalStrings + 575
StringID.PowerDesc = NumGlobalStrings + 595
StringID.SpeedDesc = NumGlobalStrings + 596
StringID.TechniqueDesc = NumGlobalStrings + 597
StringID.CoopPowerDesc = NumGlobalStrings + 957
StringID.CoopSpeedDesc = NumGlobalStrings + 958
StringID.CoopTechniqueDesc = NumGlobalStrings + 959
StringID.CoopPower = NumGlobalStrings + 960
StringID.CoopSpeed = NumGlobalStrings + 961
StringID.CoopTechnique = NumGlobalStrings + 962
StringID.MissionCompleteTime = NumGlobalStrings + 598
StringID.Hours = NumGlobalStrings + 611
StringID.Minutes = NumGlobalStrings + 603
StringID.Seconds = NumGlobalStrings + 604
StringID.PreviousBest = NumGlobalStrings + 599
StringID.SpeedRequired = NumGlobalStrings + 600
StringID.Slow = NumGlobalStrings + 601
StringID.Fast = NumGlobalStrings + 602
StringID.TechniqueObjectives = NumGlobalStrings + 594
StringID.DestroyObjectives = NumGlobalStrings + 593
StringID.Speed01 = NumGlobalStrings + 598
StringID.Speed02 = NumGlobalStrings + 599
StringID.Speed03 = NumGlobalStrings + 600
StringID.Destroyed = NumGlobalStrings + 608
StringID.Remaining = NumGlobalStrings + 609
StringID.UnlockNothing = NumGlobalStrings + 305
StringID.UnlockA = NumGlobalStrings + 306
StringID.UnlockS = NumGlobalStrings + 307
StringID.UnlockPrologue = NumGlobalStrings + 308
StringID.UnlockLastSAndMP = NumGlobalStrings + 657
StringID.UnlockLastSNoMP = NumGlobalStrings + 658
StringID.UnlockMPMap = NumGlobalStrings + 768
StringID.UnlockCoopMap = NumGlobalStrings + 771
StringID.UnlockAssaultMap = NumGlobalStrings + 772
StringID.UnlockSkirmishMap = NumGlobalStrings + 773
StringID.Rewards = NumGlobalStrings + 610
StringID.Promoted = NumGlobalStrings + 766
StringID.Demoted = NumGlobalStrings + 767
StringID.RankIncrease = NumGlobalStrings + 769
StringID.RankDecrease = NumGlobalStrings + 770
StringID.ReasonsForDefeat = 87
StringID.OtherPlayerQuit = NumGlobalStrings + 732
StringID.ConnectionLost = NumGlobalStrings + 733
StringID.IQuit = NumGlobalStrings + 734
StringID.OtherPlayerQuitCoop = NumGlobalStrings + 735
StringID.IQuitCoop = NumGlobalStrings + 736
StringID.DisconnectTitle = NumGlobalStrings + 737
StringID.Friend = NumGlobalStrings + 620
StringID.Play = NumGlobalStrings + 639
StringID.Player = NumGlobalStrings + 642
StringID.Enemy = NumGlobalStrings + 643
StringID.VS = NumGlobalStrings + 644
StringID.Power = NumGlobalStrings + 645
StringID.Speed = NumGlobalStrings + 646
StringID.Technique = NumGlobalStrings + 647
StringID.Total = NumGlobalStrings + 648
StringID.MissionObjectives = NumGlobalStrings + 649
StringID.IronLegionCamTitle = NumGlobalStrings + 651
StringID.WesternFrontierCamTitle = NumGlobalStrings + 652
StringID.AngloIslesCamTitle = NumGlobalStrings + 653
StringID.SolarEmpireCamTitle = NumGlobalStrings + 654
StringID.TundranTerritoriesCamTitle = NumGlobalStrings + 655
StringID.NextAssaultUnlock = NumGlobalStrings + 683
StringID.NextSkirmishUnlock = NumGlobalStrings + 684
StringID.NextCOOPUnlock = NumGlobalStrings + 685
StringID.Times = NumGlobalStrings + 686
StringID.PlayAssault = NumGlobalStrings + 687
StringID.PlaySkirmish = NumGlobalStrings + 688
StringID.PlayCOOP = NumGlobalStrings + 689
StringID.Briefing = NumGlobalStrings + 705
StringID.Intro = NumGlobalStrings + 706
StringID.Outro = NumGlobalStrings + 707
StringID.Clear = NumGlobalStrings + 782
StringID.VictoryMPInfantry = NumGlobalStrings + 756
StringID.VictoryMPGroundVehicles = NumGlobalStrings + 757
StringID.VictoryMPAirUnits = NumGlobalStrings + 758
StringID.VictoryMPNavalScore = NumGlobalStrings + 759
StringID.VictoryMPFinalScore = NumGlobalStrings + 760
StringID.VictoryMPTimeRemaining = NumGlobalStrings + 761
StringID.VictoryMPObjectives = NumGlobalStrings + 762
StringID.VictoryMPEnemyDestroyed = NumGlobalStrings + 763
StringID.MPVicPlayer1 = NumGlobalStrings + 764
StringID.MPVicPlayer2 = NumGlobalStrings + 765
StringID.PreferredArmy = NumGlobalStrings + 905
StringID.Whichever = NumGlobalStrings + 906
StringID.CAChallenge = NumGlobalStrings + 907
StringID.Search = NumGlobalStrings + 908
StringID.PrefMayBeRefused = NumGlobalStrings + 909
StringID.Attacker = NumGlobalStrings + 910
StringID.Defender = NumGlobalStrings + 911
StringID.ChallengeErrorCode = NumGlobalStrings + 354
StringID.ChallengeThereIsNoResponse = NumGlobalStrings + 478
StringID.ChallengeYouAreWaiting = NumGlobalStrings + 465
StringID.ChallengeDeclinedYourChallenge = NumGlobalStrings + 469
StringID.ChallengeFriendIsWaiting = NumGlobalStrings + 468
StringID.ChallengeHasChallengedSpecificLevel = NumGlobalStrings + 476
StringID.ChallengeDoYouAccept = NumGlobalStrings + 467
StringID.ChallengeRandomGame = NumGlobalStrings + 477
StringID.ChallengeAssaultGame = NumGlobalStrings + 473
StringID.ChallengeSkirmishGame = NumGlobalStrings + 474
StringID.ChallengeCoopGame = NumGlobalStrings + 475
StringID.ChallengeWaitingAcknowledge = NumGlobalStrings + 466
StringID.ChallengeWithdrewChallenge = NumGlobalStrings + 464
StringID.MPLoadPlayer1 = NumGlobalStrings + 931
StringID.MPLoadPlayer2 = NumGlobalStrings + 932
StringID.RematchYouWillSwapSides = NumGlobalStrings + 501
StringID.RematchPlayerIsThinking = NumGlobalStrings + 497
StringID.RematchPlayerApproves = NumGlobalStrings + 496
StringID.RematchPlayerDeclines = NumGlobalStrings + 498
StringID.RematchDoYouWantToReplay = NumGlobalStrings + 494
StringID.RematchDoYouWantToRematch = NumGlobalStrings + 495
StringID.RematchNoRematch = NumGlobalStrings + 499
StringID.RematchWaiting = NumGlobalStrings + 500
StringID.SearchWaitingRandomGame = NumGlobalStrings + 525
StringID.SearchWaitingSkirmishGame = NumGlobalStrings + 526
StringID.SearchWaitingAssaultGame = NumGlobalStrings + 527
StringID.SearchWaitingCoopGame = NumGlobalStrings + 528
StringID.SearchWaitingLevel = NumGlobalStrings + 529
StringID.SearchPlayAnybody = NumGlobalStrings + 530
StringID.SearchPlayFriend = NumGlobalStrings + 531
StringID.SearchRestarting = NumGlobalStrings + 533
StringID.SearchTrying = NumGlobalStrings + 534
StringID.SearchFailed = NumGlobalStrings + 535
StringID.SearchWaiting = NumGlobalStrings + 536
StringID.SearchWaitingConnecting = NumGlobalStrings + 335
StringID.SearchWaitingConnectingTitle = NumGlobalStrings + 341
local levelNameStart = 1212
function GetMissionNameStart()
  return NumGlobalStrings + levelNameStart
end
local levelMissionStart = 1132
function GetMissionDescStart()
  return NumGlobalStrings + levelMissionStart
end
local levelObjectivesStart = 1284
function GetMissionObjectivesStart()
  return NumGlobalStrings + levelObjectivesStart
end
function GetMissionObjectives(mission)
  local start = NumGlobalStrings + levelObjectivesStart
  local objectivesBase = start + mission * 3
  return objectivesBase
end
StringID.UnitsLibrary = 16
StringID.Infantry = NumGlobalStrings + 0
StringID.GroundVehicles = NumGlobalStrings + 42
StringID.AirVehicles = NumGlobalStrings + 84
StringID.SeaVehicles = NumGlobalStrings + 122
StringID.Zoom = 38
StringID.Captions = 42
DebugOut("StringID ticked ***")
function GStringID_end()
end
