function Cutscene(owner)
  Despawn(Air_Vehicle.CutsceneFighter)
  Despawn(Air_Vehicle.CutsceneFighter2)
  SetActive(Troop.CutsceneGrunt1, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt2, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt3, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt4, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt5, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt6, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.CutsceneGrunt7, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.TBazooka7, constant.INACTIVE, constant.ADJUST_WEAPON)
  cutscene = owner
  StartIntro()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam1Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam1Spline)
  PhoneMessage(0, 0, 1, 9, SpriteID.CO_X_Vlad_Happy)
  GoToArea(Ground_Vehicle.TLight8, -128, -296, 10, constant.ORDER_FORCED)
  GoToArea(Ground_Vehicle.TLight9, -128, -296, 10, constant.ORDER_FORCED)
  WaitFor(8.5)
  GoToArea(Troop.CutsceneGrunt1, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt2, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt3, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt4, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt5, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt6, -601, -226, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt7, -601, -226, 1, constant.ORDER_FORCED)
  Spawn(Air_Vehicle.CutsceneFighter)
  Spawn(Air_Vehicle.CutsceneFighter2)
  SetActive(Air_Vehicle.CutsceneFighter, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.CutsceneFighter2, constant.INACTIVE, constant.ADJUST_WEAPON)
  GoToArea(Air_Vehicle.CutsceneFighter, -620, -370, 1, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.CutsceneFighter2, -580, -370, 1, constant.ORDER_FORCED)
  WaitFor(0.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam2Spline)
  CameraSetTarget(Camera.Cam1, Waypoint.Cam2Target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, 0, 2, 5, SpriteID.CO_T_Nova_Sad)
  WaitFor(0.5)
  PlayEffect(Scripted_Effect.WEGOTABLACKHAWKDOWN, flag.SOUND, Camera.Cam1)
  WaitFor(1)
  Kill(Destroyable_Object.Building)
  WaitFor(0.2)
  Kill(Destroyable_Object.Entity0253)
  Kill(Destroyable_Object.Entity0254)
  WaitFor(0.2)
  Kill(Destroyable_Object.Entity0247)
  Kill(Destroyable_Object.Entity0251)
  Kill(Troop.CutsceneGrunt1)
  Kill(Troop.CutsceneGrunt2)
  Kill(Troop.CutsceneGrunt3)
  Kill(Troop.CutsceneGrunt4)
  Kill(Troop.CutsceneGrunt5)
  Kill(Troop.CutsceneGrunt6)
  Kill(Troop.CutsceneGrunt7)
  WaitFor(1)
  Kill(Destroyable_Object.Building2)
  WaitFor(4)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.CutsceneFighter)
  Despawn(Air_Vehicle.CutsceneFighter2)
  repeat
    EndFrame()
  until IsReadyToRevive(Troop.CutsceneGrunt1) and IsReadyToRevive(Troop.CutsceneGrunt2) and IsReadyToRevive(Troop.CutsceneGrunt3) and IsReadyToRevive(Troop.CutsceneGrunt4) and IsReadyToRevive(Troop.CutsceneGrunt5) and IsReadyToRevive(Troop.CutsceneGrunt6) and IsReadyToRevive(Troop.CutsceneGrunt7)
  ReviveDeadUnit(Troop.CutsceneGrunt1)
  ReviveDeadUnit(Troop.CutsceneGrunt2)
  ReviveDeadUnit(Troop.CutsceneGrunt3)
  ReviveDeadUnit(Troop.CutsceneGrunt4)
  ReviveDeadUnit(Troop.CutsceneGrunt5)
  ReviveDeadUnit(Troop.CutsceneGrunt6)
  ReviveDeadUnit(Troop.CutsceneGrunt7)
  WaitFor(1)
  Teleport(Troop.CutsceneGrunt1, -515, -272, 61, 0)
  Teleport(Troop.CutsceneGrunt2, -510, -267, 61, 0)
  Teleport(Troop.CutsceneGrunt3, -511, -253, 61, 0)
  Teleport(Troop.CutsceneGrunt4, -506, -261, 61, 0)
  Teleport(Troop.CutsceneGrunt5, -524, -260, 61, 0)
  Teleport(Troop.CutsceneGrunt6, -517, -265, 61, 0)
  Teleport(Troop.CutsceneGrunt7, -502, -263, 61, 0)
  GoToArea(Troop.CutsceneGrunt1, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt2, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt3, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt4, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt5, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt6, -475, -233, 1, constant.ORDER_FORCED)
  GoToArea(Troop.CutsceneGrunt7, -475, -233, 1, constant.ORDER_FORCED)
  WaitFor(1)
  CameraSetTarget(Camera.Cam1, Air_Vehicle.CutsceneChopper)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam3Spline)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(41, 0, 2, 8, SpriteID.CO_T_Nova_Sad)
  WaitFor(4)
  GoToArea(Air_Vehicle.CutsceneChopper, -1236, -38, 10, constant.ORDER_FORCED)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  actors = 1
  CameraSetTarget(Camera.Cam1, Waypoint.Cam4Target)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Cam4Spline)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, 0, 1, 6, SpriteID.CO_X_Vlad_Happy)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1.2)
  cutscene = 1
end
