function CutsceneAbort(owner)
  cutsceneabort = owner
  FreezePlayer()
  WaitFor(1)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED)) then
      ClearMessageQueue()
      Kill(cutscene)
      cutscene = 1
      CameraFade(constant.FADE_OUT, constant.WAIT, 0.25)
      DebugOut("Killed cutscene")
    end
    EndFrame()
  until cutscene == 1
  StoreSummaryMessage(0, 1, SpriteID.CO_X_Vlad_Happy)
  StoreSummaryMessage(1, 2, SpriteID.CO_T_Nova_Sad)
  StoreSummaryMessage(41, 2, SpriteID.CO_T_Nova_Sad)
  StoreSummaryMessage(2, 1, SpriteID.CO_X_Vlad_Happy)
  Teleport(Air_Vehicle.CutsceneFighter, -600, -780, 61, 0)
  Teleport(Air_Vehicle.CutsceneFighter2, -600, -780, 61, 0)
  Despawn(Air_Vehicle.CutsceneFighter)
  Despawn(Air_Vehicle.CutsceneFighter2)
  Despawn(Troop.Pilot)
  Despawn(Troop.Pilot2)
  SetActive(Troop.TBazooka7, constant.ACTIVE, constant.ADJUST_WEAPON)
  ClearMessageQueue()
  StartScoringTimer()
  Teleport(Ground_Vehicle.TLight8, -670, -416, 61, 0)
  Teleport(Ground_Vehicle.TLight9, -710, -364, 61, 0)
  GoToArea(Ground_Vehicle.TLight8, -670, -416, 5, constant.ORDER_FORCED)
  GoToArea(Ground_Vehicle.TLight9, -710, -364, 5, constant.ORDER_FORCED)
  Kill(chopperhack)
  actors = 1
  SetCamera(Camera.PlayerCam)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, 0, 1, 4, SpriteID.CO_X_Vlad_Happy)
  PhoneMessage(4, 0, 1, 6, SpriteID.CO_X_Vlad_Happy)
  cutscenetimer = GetTime()
  SetTimer(600)
  ShowTimer(1)
  WaitFor(1)
  Despawn(Troop.CutsceneGrunt1)
  Despawn(Troop.CutsceneGrunt2)
  Despawn(Troop.CutsceneGrunt3)
  Despawn(Troop.CutsceneGrunt4)
  Despawn(Troop.CutsceneGrunt5)
  Despawn(Troop.CutsceneGrunt6)
  Despawn(Troop.CutsceneGrunt7)
  Despawn(Air_Vehicle.CutsceneChopper)
  Vanish(Destroyable_Object.Building)
  Vanish(Destroyable_Object.Entity0253)
  Vanish(Destroyable_Object.Entity0254)
  Vanish(Destroyable_Object.Entity0247)
  Vanish(Destroyable_Object.Entity0251)
  Vanish(Destroyable_Object.Building2)
  UnfreezePlayer()
end
