function Intro_Cutscene(owner)
  cutkiller = owner
  CameraSetFOV(Camera.first, 10, constant.IMMEDIATE, 1.5, constant.NO_WAIT)
  WaitFor(0.5)
  CameraSetFOV(Camera.first, 70, constant.SMOOTH, 8, constant.NO_WAIT)
  WaitFor(0.5)
  PhoneMessage(0, constant.ID_NONE, 0, 10, SpriteID.CO_WF_Betty_Happy)
  WaitFor(12)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.second)
  CameraSetFOV(Camera.second, 60, constant.IMMEDIATE, 1.5, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, constant.ID_NONE, 0, 7, SpriteID.CO_WF_Betty_Happy)
  WaitFor(3.5)
  CameraSetFOV(Camera.second, 5, constant.SMOOTH, 4, constant.NO_WAIT)
  WaitFor(7.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.third)
  CameraSetFOV(Camera.third, 2.5, constant.IMMEDIATE, 8, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, 0, 5, SpriteID.CO_WF_Betty_Happy)
  WaitFor(4.4)
  CameraSetFOV(Camera.third, 60, constant.SMOOTH, 12, constant.NO_WAIT)
  WaitFor(5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscene = 1
end
