function CutScene01Skip(owner)
  WaitFor(1)
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      cutscenefinished01 = 1
      DebugOut("*CutScene01Skip* - Player 1 Killed CutScene01")
    end
    EndFrame()
  until cutscenefinished01 == 1
  ClearMessageQueue()
  Kill(cutscene01)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.TT_Flame_Barracks_2_1, true)
  Despawn(Troop.TT_Flame_Barracks_2_2, true)
  Kill(Troop.BridgeCounterGrunt01)
  Kill(Troop.BridgeCounterGrunt02)
  Kill(Troop.BridgeCounterGrunt03)
  Kill(Air_Vehicle.TT_Gunship_1)
  Kill(Ground_Vehicle.TT_Recon_1)
  Spawn(Ground_Vehicle.WF_Recon_1)
  SetCamera(Camera.Player_Camera)
  Teleport(Ground_Vehicle.WF_Recon_1, 102, -468, 90, 10)
  ForceUnitTransfer(constant.PLAYER_ONE, Ground_Vehicle.WF_Recon_1, true, true)
  CleanupSkipCutscene()
  EndIntro()
  StoreSummaryMessage(constant.PLAYER_ONE, 0, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 1, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 2, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 3, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  Spawn(Troop.CutSceneTundranGrunt01)
  Spawn(Troop.CutSceneTundranGrunt02)
  Spawn(Troop.CutSceneTundranGrunt03)
  Spawn(Troop.CutSceneTundranGrunt04)
  Spawn(Troop.CutSceneTundranGrunt06)
  Spawn(Troop.CutSceneTundranGrunt07)
  Spawn(Troop.CutSceneTundranGrunt09)
  Spawn(Troop.CutSceneTundranGrunt10)
  SetActive(Troop.WF_Grunt_1, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_2, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_3, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_4, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_5, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_6, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_7, constant.INACTIVE)
  SetActive(Troop.WF_Grunt_8, constant.INACTIVE)
  SetActive(Building.WFMGNest01, constant.INACTIVE)
  SetActive(Building.WFMGNest02, constant.INACTIVE)
  Despawn(Morphing_Building.TT_HQ_MG_Turret_1, true)
  Despawn(Morphing_Building.TT_HQ_MG_Turret_2, true)
  Despawn(Morphing_Building.TT_HQ_MG_Turret_3, true)
  Despawn(Morphing_Building.TT_HQ_MG_Turret_4, true)
  Despawn(Troop.TT_Flame_TT_HQ_1, true)
  Despawn(Troop.TT_Flame_TT_HQ_2, true)
  Despawn(Troop.TT_Flame_TT_HQ_3, true)
  Despawn(Troop.TT_Flame_TT_HQ_4, true)
  Despawn(Building.Entity340002005, true)
  Despawn(Building.Entity340002008, true)
  Despawn(Troop.XCutSceneTroop01)
  Despawn(Troop.XCutSceneTroop02)
  Despawn(Troop.XCutSceneTroop03)
  Despawn(Troop.XCutSceneTroop04)
  Despawn(Troop.XCutSceneTroop05)
  Despawn(Troop.XCutSceneTroop06)
  Despawn(Troop.XCutSceneTroop07)
  Despawn(Troop.CutSceneTroop01)
  Despawn(Ground_Vehicle.CutSceneRecon)
  Kill(Destroyable_Object.Entity210102434)
  Vanish(Destroyable_Object.Ramp01)
  ClearMessageQueue()
  SetFunctionIndicatorState(false)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  UnfreezePlayer(constant.PLAYER_ONE)
  ResetCommandBar()
  PhoneMessageWithObjective(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  ResetHealthAndScoreTotals()
  StartScoringTimer()
  SetUnitInvulnerable(Ground_Vehicle.WF_Recon_1, false)
  timer = GetTime()
  DebugOut("ended")
end
