function CutScene03_WinMission(owner)
  cutscene03kill = owner
  while missionend == 0 do
    if tundranHQ == 1 then
      missionend = 1
      SepiaFade = true
      WaitFor(2.2)
      PlayEffect(Scripted_Effect.SepiaFadeIn, 3, 0, 0, 0)
      WaitFor(1.8)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      SetInvulnerable(flag.TYPE_WFRONTIER, 1)
      SetInvulnerable(flag.TYPE_XYLVANIAN, 1)
      SetInvulnerable(flag.TYPE_TUNDRAN, 1)
      Despawn(Troop.BridgeCounterGrunt01)
      Despawn(Troop.BridgeCounterGrunt02)
      Despawn(Troop.BridgeCounterGrunt03)
      Despawn(Troop.CutSceneTundranGrunt01)
      Despawn(Troop.CutSceneTundranGrunt02)
      Despawn(Troop.CutSceneTundranGrunt03)
      Despawn(Troop.CutSceneTundranGrunt04)
      Despawn(Troop.CutSceneTundranGrunt05)
      Despawn(Troop.CutSceneTundranGrunt06)
      Despawn(Troop.CutSceneTundranGrunt07)
      Despawn(Troop.CutSceneTundranGrunt08)
      Despawn(Troop.CutSceneTundranGrunt09)
      Despawn(Troop.CutSceneTundranGrunt10)
      Despawn(Troop.Entity340001648)
      Despawn(Troop.Entity340001649)
      Despawn(Troop.Entity340001650)
      Despawn(Troop.Entity340001652)
      Despawn(Troop.Entity340001653)
      Despawn(Troop.Entity340001655)
      Despawn(Troop.Entity340001656)
      Despawn(Troop.Entity340001657)
      Despawn(Troop.Entity340001659)
      Despawn(Troop.Entity340002109)
      Despawn(Troop.Entity340002110)
      Despawn(Troop.Entity340002112)
      Despawn(Troop.Entity340002113)
      Despawn(Troop.Entity340002118)
      Despawn(Troop.Entity340002119)
      Despawn(Troop.TT_AA_Gunner_2)
      Despawn(Troop.TT_AA_Tower_Grunt_2)
      Despawn(Troop.TT_AA_Tower_Grunt_3)
      Despawn(Troop.TT_AA_Tower_Grunt_4)
      Despawn(Troop.TT_AA_Tower_Grunt_6)
      Despawn(Troop.TT_AA_Tower_Grunt_7)
      Despawn(Troop.TT_AA_Vet_Barracks_2_1)
      Despawn(Troop.TT_AA_Vet_Barracks_2_2)
      Despawn(Troop.TT_AA_Vet_Barracks_2_3)
      Despawn(Troop.TT_AA_Vet_Barracks_2_4)
      Despawn(Troop.TT_Airbase_AA_Vet_1)
      Despawn(Troop.TT_Airbase_Bazooka_1)
      Despawn(Troop.TT_Airbase_Bazooka_2)
      Despawn(Troop.TT_Bazooka_Barracks_2_1)
      Despawn(Troop.TT_Bazooka_Barracks_2_2)
      Despawn(Troop.TT_Bazooka_Barracks_2_3)
      Despawn(Troop.TT_Bazooka_Barracks_2_4)
      Despawn(Troop.TT_Bazooka_Barracks_2_6)
      Despawn(Troop.TT_Bazooka_Barracks_2_7)
      Despawn(Troop.TT_Bship_Grunt_1)
      Despawn(Troop.TT_Bship_Grunt_2)
      Despawn(Troop.TT_Bship_Grunt_3)
      Despawn(Troop.TT_Flame_Airbase_1)
      Despawn(Troop.TT_Flame_Barracks_1_1)
      Despawn(Troop.TT_Flame_Barracks_2_1)
      Despawn(Troop.TT_Flame_Barracks_2_2)
      Despawn(Troop.TT_Flame_TT_HQ_1)
      Despawn(Troop.TT_Flame_TT_HQ_2)
      Despawn(Troop.TT_Flame_TT_HQ_3)
      Despawn(Troop.TT_Flame_TT_HQ_4)
      Despawn(Troop.TT_Flame_Vet_Factory_1)
      Despawn(Troop.TT_Grunt_Airbase_1)
      Despawn(Troop.TT_Grunt_Airbase_2)
      Despawn(Troop.TT_Grunt_Airbase_3)
      Despawn(Troop.TT_Grunt_Airbase_6)
      Despawn(Troop.TT_Grunt_Airbase_7)
      Despawn(Troop.TT_Grunt_Airbase_8)
      Despawn(Troop.TT_Grunt_Airbase_9)
      Despawn(Troop.TT_Grunt_Barracks_1_1)
      Despawn(Troop.TT_Grunt_Barracks_1_2)
      Despawn(Troop.TT_Grunt_Barracks_1_3)
      Despawn(Troop.TT_Grunt_Barracks_1_6)
      Despawn(Troop.TT_Grunt_Barracks_1_7)
      Despawn(Troop.TT_Grunt_Barracks_1_8)
      Despawn(Troop.TT_Grunt_Barracks_2_1)
      Despawn(Troop.TT_Grunt_Barracks_2_2)
      Despawn(Troop.TT_Grunt_Barracks_2_3)
      Despawn(Troop.TT_Grunt_Barracks_2_4)
      Despawn(Troop.TT_Grunt_Barracks_2_6)
      Despawn(Troop.TT_Grunt_Barracks_2_7)
      Despawn(Troop.TT_Grunt_Barracks_2_8)
      Despawn(Troop.TT_Grunt_Barracks_2_9)
      Despawn(Troop.TT_Grunt_Factory_1)
      Despawn(Troop.TT_Grunt_Factory_2)
      Despawn(Troop.TT_Grunt_Factory_3)
      Despawn(Troop.TT_Grunt_MG_Nest_A)
      Despawn(Troop.TT_Grunt_MG_Nest_B)
      Despawn(Troop.TT_Gunship_Pilot_1)
      Despawn(Troop.TT_Gunship_Pilot_2)
      Despawn(Troop.TT_Gunship_Pilot_3)
      Despawn(Troop.TT_Gunship_Pilot_4)
      Despawn(Troop.TT_Gunship_Pilot_5)
      Despawn(Troop.TT_Gunship_Pilot_6)
      Despawn(Troop.TT_MG_Nest_Grunt_1)
      Despawn(Troop.TT_MG_Nest_Grunt_2)
      Despawn(Troop.TT_MG_Nest_Grunt_3)
      Despawn(Troop.TT_MG_Nest_Grunt_5)
      Despawn(Troop.TT_MG_Nest_Grunt_6)
      Despawn(Troop.TT_Recon_Driver_1)
      Despawn(Troop.TT_Recon_Gunner_1)
      Despawn(Troop.TundranFactoryAAVet01)
      Despawn(Troop.TundranFactoryGrunt01)
      Despawn(Troop.TundranFactoryGrunt02)
      Despawn(Troop.TundranFactoryGrunt03)
      Despawn(Troop.TundranFactoryGrunt04)
      Despawn(Air_Vehicle.TT_Gunship_1)
      Despawn(Air_Vehicle.TT_Gunship_2)
      Despawn(Air_Vehicle.TT_Gunship_3)
      Despawn(Air_Vehicle.TT_Gunship_4)
      Despawn(Air_Vehicle.TT_Gunship_5)
      Despawn(Air_Vehicle.TT_Gunship_6)
      Despawn(Water_Vehicle.TT_Bship1)
      Despawn(Ground_Vehicle.TT_Recon_1)
      Teleport(Ground_Vehicle.WF_Recon_1, 417, 850, 0, 20)
      Teleport(Ground_Vehicle.WF_Heavy_Tank_1, 417, 850, 0, 20)
      Teleport(Troop.WF_Mortar_Vet_1, 417, 850, 0, 20)
      Teleport(Troop.WF_Mortar_Vet_2, 417, 850, 0, 20)
      Teleport(Troop.WF_Mortar_Vet_3, 417, 850, 0, 20)
      Teleport(Troop.WF_Mortar_Vet_4, 417, 850, 0, 20)
      Teleport(Troop.WF_AA_Vet_1, 417, 850, 0, 20)
      Teleport(Troop.WF_AA_Vet_2, 417, 850, 0, 20)
      Teleport(Troop.WF_AA_Vet_3, 417, 850, 0, 20)
      Teleport(Troop.WF_AA_Vet_4, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_1, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_2, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_3, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_4, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_5, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_6, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_7, 417, 850, 0, 20)
      Teleport(Troop.WF_Grunt_8, 417, 850, 0, 20)
      Teleport(Air_Vehicle.WF_Gunship_1, 577, 599, 0, 20)
      Teleport(Air_Vehicle.WF_Gunship_2, 577, 599, 0, 20)
      Spawn(Troop.TTCutSceneTroop01)
      Spawn(Troop.TTCutSceneTroop02)
      Spawn(Troop.TTCutSceneTroop03)
      Spawn(Troop.TTCutSceneTroop04)
      if northernbarracks == 1 or southernbarracks == 1 then
        Spawn(Troop.WFCutSceneTroop01)
        Spawn(Troop.WFCutSceneTroop02)
        Spawn(Troop.WFCutSceneTroop03)
        Spawn(Troop.WFCutSceneTroop04)
      end
      Spawn(Troop.WFCutSceneTroop05)
      Spawn(Troop.WFCutSceneTroop06)
      Spawn(Troop.WFCutSceneTroop07)
      Spawn(Troop.WFCutSceneTroop08)
      DefeatLament(constant.ARMY_TUNDRAN)
      VictoryDance(constant.ARMY_WF)
      ClearMessageQueue(constant.PLAYER_ONE)
      SetCamera(Camera.Camera6)
      CameraSetWaypoint(Camera.Camera6, Waypoint.CutScene6Waypoint)
      StartOutro()
      PlayEffect(Scripted_Effect.SepiaC2, 3, 0, 0, 0)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      tundranHQ = 2
      Spawn(Air_Vehicle.XylvanianAirTransport01)
      Spawn(Air_Vehicle.XylvanianAirTransport02)
      PhoneMessage(33, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
      PhoneMessage(34, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
      PhoneMessage(35, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Herman_Happy, constant.PLAYER_ONE)
      Vanish(Destroyable_Object.XCLOSEDMINESHAFT01)
      Vanish(Destroyable_Object.XCLOSEDMINESHAFT02)
      Spawn(Building.XOPENMINESHAFT01)
      Spawn(Building.XOPENMINESHAFT02)
      WaitFor(24)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      ClearMessageQueue(constant.PLAYER_ONE)
      SetCamera(Camera.Camera10)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(36, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
      Spawn(Troop.XylvanianAirTransport01Troop01)
      GoToArea(Troop.XylvanianAirTransport01Troop01, 295, -530, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      Spawn(Troop.XylvanianAirTransport02Troop01)
      GoToArea(Troop.XylvanianAirTransport02Troop01, 301, -565, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      Spawn(Troop.XylvanianAirTransport01Troop02)
      GoToArea(Troop.XylvanianAirTransport01Troop02, 295, -530, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      Spawn(Troop.XylvanianAirTransport02Troop02)
      GoToArea(Troop.XylvanianAirTransport02Troop02, 301, -565, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      Spawn(Troop.XylvanianAirTransport01Troop03)
      GoToArea(Troop.XylvanianAirTransport01Troop03, 295, -530, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      PutUnitInVehicle(Troop.XylvanianAirTransport01Troop01, Air_Vehicle.XylvanianAirTransport01, 0)
      Spawn(Troop.XylvanianAirTransport01Troop01)
      Spawn(Troop.XylvanianAirTransport02Troop03)
      GoToArea(Troop.XylvanianAirTransport02Troop03, 301, -565, 1, 0, constant.ORDER_FORCED)
      WaitFor(1)
      Spawn(Troop.XylvanianAirTransport01Troop04)
      GoToArea(Troop.XylvanianAirTransport01Troop04, 295, -530, 1, 0, constant.ORDER_FORCED)
      WaitFor(2)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      PutUnitInVehicle(Troop.XylvanianAirTransport01Troop02, Air_Vehicle.XylvanianAirTransport01, 1)
      PutUnitInVehicle(Troop.XylvanianAirTransport01Troop03, Air_Vehicle.XylvanianAirTransport01, 2)
      PutUnitInVehicle(Troop.XylvanianAirTransport01Troop04, Air_Vehicle.XylvanianAirTransport01, 3)
      PutUnitInVehicle(Troop.XylvanianAirTransport02Troop02, Air_Vehicle.XylvanianAirTransport02, 1)
      PutUnitInVehicle(Troop.XylvanianAirTransport02Troop03, Air_Vehicle.XylvanianAirTransport02, 2)
      SetCamera(Camera.Camera8)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      PhoneMessage(37, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Herman_Sad, constant.PLAYER_ONE)
      GoToArea(Air_Vehicle.XylvanianAirTransport01, 297, 217, 10, 0, constant.ORDER_FORCED)
      PutUnitInVehicle(Troop.XylvanianAirTransport02Troop01, Air_Vehicle.XylvanianAirTransport02, 0)
      Spawn(Troop.XylvanianAirTransport02Troop01)
      WaitFor(1.8)
      GoToArea(Air_Vehicle.XylvanianAirTransport02, 297, 217, 10, 0, constant.ORDER_FORCED)
      WaitFor(9)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      EndOutro()
      DeclareVictory(constant.ARMY_WF)
      WinMission()
      break
    end
    EndFrame()
  end
end
