function CutScene01(owner)
  Despawn(Ground_Vehicle.WF_Recon_1)
  cutscene01 = owner
  StartIntro()
  PhoneMessage(0, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(10)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ClearMessageQueue()
  GoToArea(Troop.BridgeCounterGrunt01, 556, 153, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.BridgeCounterGrunt02, 556, 153, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.BridgeCounterGrunt03, 556, 153, 10, 0, constant.ORDER_FORCED)
  SetCamera(Camera.Camera1, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Camera1, Waypoint.Entity330101750)
  CameraSetTarget(Camera.Camera1, Waypoint.Entity330104862)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(2)
  GoToArea(Ground_Vehicle.TT_Recon_1, 595, 255, 10, 0, constant.ORDER_FORCED)
  WaitFor(4)
  GoToArea(Air_Vehicle.TT_Gunship_1, 306, 319, 10, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ClearMessageQueue()
  Spawn(Troop.CutSceneTundranGrunt01)
  Spawn(Troop.CutSceneTundranGrunt02)
  Spawn(Troop.CutSceneTundranGrunt03)
  Spawn(Troop.CutSceneTundranGrunt04)
  Spawn(Troop.CutSceneTundranGrunt06)
  Spawn(Troop.CutSceneTundranGrunt07)
  Spawn(Troop.CutSceneTundranGrunt09)
  Spawn(Troop.CutSceneTundranGrunt10)
  SetCamera(Camera.Camera3)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(2, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(4)
  GoToArea(Troop.CutSceneTundranGrunt01, 439, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt02, 439, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt03, 439, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt04, 439, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt06, 458, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt07, 458, -149, 10, 0, constant.ORDER_FORCED)
  GoToArea(Troop.CutSceneTundranGrunt08, 458, -149, 10, 0, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutSceneTundranGrunt05, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutSceneTundranGrunt09, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutSceneTundranGrunt10, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
  WaitFor(4)
  Spawn(Ground_Vehicle.CutSceneRecon)
  GoToArea(Ground_Vehicle.CutSceneRecon, 222, -735, 2, 0, constant.ORDER_FORCED)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ClearMessageQueue()
  SetCamera(Camera.Camera9)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(3, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(5)
  Spawn(Ground_Vehicle.WF_Recon_1)
  GoToArea(Ground_Vehicle.WF_Recon_1, 144, -440, 5, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.5)
  Despawn(Ground_Vehicle.CutSceneRecon)
  Kill(Destroyable_Object.Entity210102434)
  SetCamera(Camera.Camera4)
  Teleport(Troop.XCutSceneTroop01, 118, -661, 315, 5)
  Teleport(Troop.XCutSceneTroop02, 104, -658, 315, 5)
  Teleport(Troop.XCutSceneTroop03, 127, -676, 315, 5)
  Teleport(Troop.XCutSceneTroop05, 115, -687, 315, 5)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.5)
  reconskip = 1
  repeat
    EndFrame()
  until IsInArea(Ground_Vehicle.WF_Recon_1, Map_Zone.CameraChangeMapZone)
  reconskip = 2
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.1)
  SetCamera(Camera.Camera4b)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.1)
  GoToArea(Ground_Vehicle.WF_Recon_1, 114, -465, 2, 0, constant.ORDER_FORCED)
  Kill(Destroyable_Object.Ramp01)
  WaitFor(3)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscenefinished01 = 1
end
