function Startup(owner)
  DebugOut("Removing unwanted WF units at start for facilities respawn later.")
  Despawn(Ground_Vehicle.CutSceneRecon)
  Despawn(Troop.TTCutSceneTroop01)
  Despawn(Troop.TTCutSceneTroop02)
  Despawn(Troop.TTCutSceneTroop03)
  Despawn(Troop.TTCutSceneTroop04)
  Despawn(Troop.WFCutSceneTroop01)
  Despawn(Troop.WFCutSceneTroop02)
  Despawn(Troop.WFCutSceneTroop03)
  Despawn(Troop.WFCutSceneTroop04)
  Despawn(Troop.WFCutSceneTroop05)
  Despawn(Troop.WFCutSceneTroop06)
  Despawn(Troop.WFCutSceneTroop07)
  Despawn(Troop.WFCutSceneTroop08)
  SetUnitInvulnerable(Troop.WF_Grunt_1, true)
  SetUnitInvulnerable(Troop.WF_Grunt_2, true)
  SetUnitInvulnerable(Troop.WF_Grunt_3, true)
  SetUnitInvulnerable(Troop.WF_Grunt_4, true)
  SetUnitInvulnerable(Troop.WF_Grunt_5, true)
  SetUnitInvulnerable(Troop.WF_Grunt_6, true)
  SetUnitInvulnerable(Troop.WF_Grunt_7, true)
  SetUnitInvulnerable(Troop.WF_Grunt_8, true)
  SetUnitInvulnerable(Ground_Vehicle.WF_Recon_1, true)
  Despawn(Troop.XylvanianGrunt01, false)
  Despawn(Troop.XylvanianGrunt02, false)
  Despawn(Troop.XylvanianGrunt03, false)
  Despawn(Troop.XylvanianGrunt04, false)
  Despawn(Troop.XylvanianAirTransport01Troop01)
  Despawn(Troop.XylvanianAirTransport01Troop02)
  Despawn(Troop.XylvanianAirTransport01Troop03)
  Despawn(Troop.XylvanianAirTransport01Troop04)
  Despawn(Troop.XylvanianAirTransport02Troop01)
  Despawn(Troop.XylvanianAirTransport02Troop02)
  Despawn(Troop.XylvanianAirTransport02Troop03)
  Despawn(Air_Vehicle.XylvanianAirTransport01)
  Despawn(Air_Vehicle.XylvanianAirTransport02)
  Kill(Air_Vehicle.WF_Gunship_1)
  Kill(Air_Vehicle.WF_Gunship_2)
  Kill(Troop.WF_AA_Vet_1)
  Kill(Troop.WF_AA_Vet_2)
  Kill(Troop.WF_AA_Vet_3)
  Kill(Troop.WF_AA_Vet_4)
  Kill(Troop.WF_Mortar_Vet_1)
  Kill(Troop.WF_Mortar_Vet_2)
  Kill(Troop.WF_Mortar_Vet_3)
  Kill(Troop.WF_Mortar_Vet_4)
  Kill(Ground_Vehicle.WF_Heavy_Tank_1)
  Despawn(Troop.CutSceneTundranGrunt01, false)
  Despawn(Troop.CutSceneTundranGrunt02, false)
  Despawn(Troop.CutSceneTundranGrunt03, false)
  Despawn(Troop.CutSceneTundranGrunt04, false)
  Despawn(Troop.CutSceneTundranGrunt05, false)
  Despawn(Troop.CutSceneTundranGrunt06, false)
  Despawn(Troop.CutSceneTundranGrunt07, false)
  Despawn(Troop.CutSceneTundranGrunt08, false)
  AddToGroup(Unit_Group.WFUnits, Air_Vehicle.WF_Gunship_1)
  AddToGroup(Unit_Group.WFUnits, Ground_Vehicle.WF_Heavy_Tank_1)
  AddToGroup(Unit_Group.WFUnits, Ground_Vehicle.WF_Recon_1)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_1)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_2)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_3)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_4)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_5)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_6)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_7)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Grunt_8)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Mortar_Vet_1)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Mortar_Vet_2)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Mortar_Vet_3)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_Mortar_Vet_4)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_AA_Vet_1)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_AA_Vet_2)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_AA_Vet_3)
  AddToGroup(Unit_Group.WFUnits, Troop.WF_AA_Vet_4)
end
