function THQAttackA(owner)
  while missionend == 0 do
    if IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.HQ_Counter_Attack_1) then
      SetFunctionIndicatorState(true)
      SetActive(Troop.WF_Grunt_1, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_2, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_3, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_4, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_5, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_6, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_7, constant.ACTIVE)
      SetActive(Troop.WF_Grunt_8, constant.ACTIVE)
      SetActive(Building.WFMGNest01, constant.ACTIVE)
      SetActive(Building.WFMGNest02, constant.ACTIVE)
      SetUnitInvulnerable(Troop.WF_Grunt_1, false)
      SetUnitInvulnerable(Troop.WF_Grunt_2, false)
      SetUnitInvulnerable(Troop.WF_Grunt_3, false)
      SetUnitInvulnerable(Troop.WF_Grunt_4, false)
      SetUnitInvulnerable(Troop.WF_Grunt_5, false)
      SetUnitInvulnerable(Troop.WF_Grunt_6, false)
      SetUnitInvulnerable(Troop.WF_Grunt_7, false)
      SetUnitInvulnerable(Troop.WF_Grunt_8, false)
      EndFrame()
      ResetCommandBar()
      recondead = 1
      Spawn(Troop.CutSceneTundranGrunt05)
      Spawn(Troop.CutSceneTundranGrunt08)
      Despawn(Troop.XylvanianGrunt01, false)
      Despawn(Troop.XylvanianGrunt02, false)
      Despawn(Troop.XylvanianGrunt03, false)
      Despawn(Troop.XylvanianGrunt04, false)
      Despawn(Troop.Xgrunt01, false)
      Despawn(Troop.Xgrunt02, false)
      Despawn(Troop.Xgrunt03, false)
      WaitFor(0.2)
      EnterVehicle(Troop.CutSceneTundranGrunt05, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
      EnterVehicle(Troop.CutSceneTundranGrunt08, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
      DebugOut("Map Zone Triggered - HQ Counter Attack 1.")
      WaitFor(10)
      EnterVehicle(Troop.TT_Grunt_Barracks_1_1, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
      EnterVehicle(Troop.TT_Grunt_Barracks_1_2, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
      EnterVehicle(Troop.TT_Grunt_Barracks_1_3, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
      WaitFor(3)
      PhoneMessage(8, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
      DebugOut("Map Zone Triggered - HQ Attack 2.")
      WaitFor(15)
      ClearMessageQueue()
      PhoneMessage(9, constant.ID_NONE, constant.ARMY_TUNDRAN, 8, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_ONE)
      PhoneMessage(10, constant.ID_NONE, constant.ARMY_WF, 8, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
      LandAirUnit(Air_Vehicle.TT_T_Copter_A, 450, -60, constant.ORDER_FORCED, false, 10, 320)
      LandAirUnit(Air_Vehicle.TT_T_Copter_B, 455, -85, constant.ORDER_FORCED, false, 10, 20)
      DebugOut("Map Zone Triggered - HQ Counter Attack 2 - T Copter A.")
      break
    end
    EndFrame()
  end
  repeat
    if missionend == 0 and IsInArea(Air_Vehicle.TT_T_Copter_A, 450, -60, 20) and GetMovementState(Air_Vehicle.TT_T_Copter_A) == constant.MOVEMENT_STATE_ON_GROUND then
      ExitVehicle(GetUnitInSeat(Air_Vehicle.TT_T_Copter_A, 5), Air_Vehicle.TT_T_Copter_A)
      ExitVehicle(GetUnitInSeat(Air_Vehicle.TT_T_Copter_A, 4), Air_Vehicle.TT_T_Copter_A)
      ExitVehicle(GetUnitInSeat(Air_Vehicle.TT_T_Copter_A, 3), Air_Vehicle.TT_T_Copter_A)
      TCopterAUnload = 1
    end
    EndFrame()
  until TCopterAUnload == 1
  EnterVehicle(Troop.TT_T_Copter_Grunt_A2, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_FORCED)
  EnterVehicle(Troop.TT_T_Copter_Grunt_A3, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_NORMAL)
  EnterVehicle(Troop.TT_T_Copter_Grunt_A4, Capture_Point.WF_HQ_Capture_Point, constant.ORDER_NORMAL)
  WaitFor(5)
  GoToArea(Air_Vehicle.TT_T_Copter_A, 400, -1000, 5, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until IsInArea(Air_Vehicle.TT_T_Copter_A, 400, -1000, 20)
  DebugOut("Destroying T Copter A.")
  Despawn(Air_Vehicle.TT_T_Copter_A)
end
