function MP3_Cutscene_Mid_LANDING(owner)
  cutsceneMidID = owner
  Despawn(Troop.MidTTGrunt01)
  Despawn(Troop.MidTTGrunt02)
  Despawn(Troop.MidTTGrunt03)
  Despawn(Troop.MidTTGrunt04)
  Despawn(Troop.MidTTGrunt05)
  Despawn(Troop.MidTTGrunt06)
  Kill(Ground_Vehicle.MidTTTank01)
  Despawn(Troop.MidTTTank01Driver)
  while true do
    if ObjectiveOneIsDone == 1 and ObjectiveTwoIsDone == 1 then
      PauseTimerActive = 1
      MissionTimeLeft = GetTimeLeft()
      ShowTimer(false)
      TimerShown = 0
      if IsNetworkPlayer(constant.PLAYER_ONE) then
        SetObjectiveData(Objective.P1BlimpDead7, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective.P1Blimp, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective_Marker.P1Blimp, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
        SetObjectiveData(Objective.P1Refuel, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective_Marker.P1Refuel, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
        StartOutro()
        FreezePlayer(constant.PLAYER_ONE)
        SetInvulnerable(flag.TYPE_WFRONTIER, true)
        ClearMessageQueue(constant.PLAYER_ONE)
        CameraFade(constant.FADE_OUT, constant.WAIT, 1)
        SetCamera(Camera.P1Mid01, constant.PLAYER_ONE)
        CameraSetWaypoint(Camera.P1Mid01, Waypoint.MidWFShot01Spline)
        CameraSetTarget(Camera.P1Mid01, Waypoint.MidWFShot01Target)
        CameraSetFOV(Camera.P1Mid01, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
        ClearMessageQueue(constant.PLAYER_ONE)
        PhoneMessage(14, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Young_Herman_Happy, constant.PLAYER_ONE)
      end
      if IsNetworkPlayer(constant.PLAYER_TWO) then
        SetObjectiveData(Objective.P2BlimpDead7, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective.P2Blimp, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective_Marker.P2Blimp, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
        SetObjectiveData(Objective.P2Refuel, constant.OBJECTIVE_DATA_STATE, 1)
        SetObjectiveData(Objective_Marker.P2Refuel, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
        StartOutro()
        FreezePlayer(constant.PLAYER_TWO)
        SetInvulnerable(flag.TYPE_TUNDRAN, true)
        ClearMessageQueue(constant.PLAYER_TWO)
        CameraFade(constant.FADE_OUT, constant.WAIT, 1)
        SetCamera(Camera.P2Mid01, constant.PLAYER_TWO)
        CameraSetWaypoint(Camera.P2Mid01, Waypoint.MidTTShot01Spline)
        CameraSetTarget(Camera.P2Mid01, Waypoint.MidTTShot01Target)
        CameraSetFOV(Camera.P2Mid01, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
        ClearMessageQueue(constant.PLAYER_TWO)
        PhoneMessage(64, constant.ID_NONE, 2, 6, SpriteID.CO_T_Young_Gorgi_Sad, constant.PLAYER_TWO)
      end
      Spawn(Capture_Point.HQ)
      Despawn(Building.CapturePointDummy)
      SetActive(Air_Vehicle.WFfighter1, constant.INACTIVE, constant.ADJUST_WEAPON)
      SetActive(Air_Vehicle.WFfighter2, constant.INACTIVE, constant.ADJUST_WEAPON)
      SetActive(Air_Vehicle.WFbomber01, constant.INACTIVE, constant.ADJUST_WEAPON)
      SetActive(Air_Vehicle.TTfighter1, constant.INACTIVE, constant.ADJUST_WEAPON)
      SetActive(Air_Vehicle.TTfighter2, constant.INACTIVE, constant.ADJUST_WEAPON)
      Teleport(Air_Vehicle.WFfighter1, 150, 850, 0, 10)
      Teleport(Air_Vehicle.WFfighter2, 130, 850, 0, 10)
      Teleport(Air_Vehicle.WFbomber01, 110, 850, 0, 10)
      Teleport(Air_Vehicle.TTfighter1, 200, 850, 0, 10)
      Teleport(Air_Vehicle.TTfighter2, 220, 850, 0, 10)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      WaitFor(4)
      Kill(Destroyable_Object.Gate07)
      Kill(Destroyable_Object.Gate08)
      Kill(Destroyable_Object.Gate09)
      Kill(Destroyable_Object.Gate10)
      Kill(Destroyable_Object.Gate11)
      Kill(Destroyable_Object.Gate12)
      DestroyablePlayAnim(Destroyable_Object.GateFall01, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall06, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall02, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall05, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall03, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall04, 1, 2)
      WaitFor(1)
      Kill(Destroyable_Object.Gate19)
      Kill(Destroyable_Object.Gate20)
      Kill(Destroyable_Object.Gate21)
      DestroyablePlayAnim(Destroyable_Object.GateFall19, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall20, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall21, 1, 2)
      WaitFor(1)
      Kill(Destroyable_Object.Gate22)
      Kill(Destroyable_Object.Gate23)
      Kill(Destroyable_Object.Gate24)
      DestroyablePlayAnim(Destroyable_Object.GateFall22, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall23, 1, 2)
      DestroyablePlayAnim(Destroyable_Object.GateFall24, 1, 2)
      WaitFor(1)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Spawn(Troop.MidTTGrunt01)
      Spawn(Troop.MidTTGrunt02)
      Spawn(Troop.MidTTGrunt03)
      Spawn(Troop.MidTTGrunt04)
      Spawn(Troop.MidTTGrunt05)
      Spawn(Troop.MidTTGrunt06)
      Teleport(Troop.MidTTGrunt01, -120, -613, 90, 2)
      Teleport(Troop.MidTTGrunt02, -125, -610, 90, 2)
      Teleport(Troop.MidTTGrunt03, -121, -617, 90, 2)
      Teleport(Troop.MidTTGrunt04, -124, -632, 90, 2)
      Teleport(Troop.MidTTGrunt05, -127, -628, 90, 2)
      Teleport(Troop.MidTTGrunt06, -128, -635, 90, 2)
      if IsNetworkPlayer(constant.PLAYER_ONE) then
        SetCamera(Camera.P1Mid01, constant.PLAYER_ONE)
        CameraSetWaypoint(Camera.P1Mid01, Waypoint.MidWFShot02Spline)
        CameraSetTarget(Camera.P1Mid01, Waypoint.MidWFShot02Target)
        CameraSetFOV(Camera.P1Mid01, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
        ClearMessageQueue(constant.PLAYER_ONE)
        PhoneMessageWithObjective(15, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Young_Herman_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
      end
      if IsNetworkPlayer(constant.PLAYER_TWO) then
        SetCamera(Camera.P2Mid01, constant.PLAYER_TWO)
        CameraSetWaypoint(Camera.P2Mid01, Waypoint.MidTTShot02Spline)
        CameraSetTarget(Camera.P2Mid01, Waypoint.MidTTShot02Target)
        CameraSetFOV(Camera.P2Mid01, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
        ClearMessageQueue(constant.PLAYER_TWO)
        PhoneMessageWithObjective(65, constant.ID_NONE, 2, 6, SpriteID.CO_T_Young_Gorgi_Happy, constant.PLAYER_TWO, false, constant.NEW_PRIMARY_OBJECTIVE)
      end
      Spawn(Air_Vehicle.WFtransport04)
      Spawn(Air_Vehicle.WFtransport05)
      Spawn(Air_Vehicle.WFtransport06)
      SetUnitInvulnerable(Air_Vehicle.WFtransport04, true)
      SetUnitInvulnerable(Air_Vehicle.WFtransport05, true)
      SetUnitInvulnerable(Air_Vehicle.WFtransport06, true)
      GoToArea(Air_Vehicle.WFtransport04, WFtransport04XLandingCoord, WFtransport04ZLandingCoord, 5, 0, constant.ORDER_FORCED)
      GoToArea(Air_Vehicle.WFtransport05, WFtransport05XLandingCoord, WFtransport05ZLandingCoord, 5, 0, constant.ORDER_FORCED)
      GoToArea(Air_Vehicle.WFtransport06, WFtransport06XLandingCoord, WFtransport06ZLandingCoord, 5, 0, constant.ORDER_FORCED)
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      WaitFor(2)
      ReviveDeadUnit(Ground_Vehicle.MidTTTank01, -120, -623, 90, 0)
      Spawn(Troop.MidTTTank01Driver)
      PutUnitInVehicle(Troop.MidTTTank01Driver, Ground_Vehicle.MidTTTank01, 0)
      GoToArea(Ground_Vehicle.MidTTTank01, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(1)
      GoToArea(Troop.MidTTGrunt01, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(0.5)
      GoToArea(Troop.MidTTGrunt02, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      GoToArea(Troop.WFgrunt7, 110, -360, 40, 40, constant.ORDER_FORCED)
      GoToArea(Troop.WFgrunt1, 110, -360, 40, 40, constant.ORDER_FORCED)
      GoToArea(Troop.WFgrunt3, 110, -360, 40, 40, constant.ORDER_FORCED)
      GoToArea(Troop.WFbazooka02, 110, -360, 40, 40, constant.ORDER_FORCED)
      WaitFor(0.5)
      GoToArea(Troop.MidTTGrunt03, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(0.5)
      GoToArea(Troop.MidTTGrunt04, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(0.5)
      GoToArea(Troop.MidTTGrunt05, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(0.5)
      GoToArea(Troop.MidTTGrunt06, GetObjectXPosition(Capture_Point.HQ), GetObjectZPosition(Capture_Point.HQ), 10, 10, constant.ORDER_FORCED)
      WaitFor(0.5)
      WaitFor(1)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      break
    end
    EndFrame()
  end
  Despawn(Troop.MidTTGrunt01)
  Despawn(Troop.MidTTGrunt02)
  Despawn(Troop.MidTTGrunt03)
  Despawn(Troop.MidTTGrunt04)
  Despawn(Troop.MidTTGrunt05)
  Despawn(Troop.MidTTGrunt06)
  Despawn(Ground_Vehicle.MidTTTank01)
  Despawn(Troop.MidTTTank01Driver)
  Spawn(Troop.TTgrunt1)
  Spawn(Troop.TTgrunt2)
  Spawn(Troop.TTgrunt3)
  Spawn(Troop.TTgrunt4)
  Spawn(Troop.TTgrunt5)
  Spawn(Troop.TTgrunt6)
  Spawn(Troop.TThose01)
  Spawn(Troop.TThose02)
  Spawn(Troop.TTchain03)
  Spawn(Ground_Vehicle.TTantiair01)
  Spawn(Ground_Vehicle.TTtank01)
  Spawn(Troop.WFhose01)
  Spawn(Troop.WFbazooka01)
  Spawn(Troop.WFgrunt5)
  Spawn(Troop.WFgrunt6)
  Spawn(Troop.WFhose02)
  Spawn(Troop.WFbazooka03)
  Teleport(Troop.WFgrunt7, 102, -337, 180, 0)
  Teleport(Troop.WFgrunt1, 90, -350, 180, 0)
  Teleport(Troop.WFbazooka02, 125, -330, 180, 0)
  Teleport(Troop.WFgrunt3, 104, -325, 180, 0)
  Spawn(Air_Vehicle.WFbomber03)
  WaitFor(0.1)
  EndOutro()
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    ForceUnitTransfer(constant.PLAYER_TWO, Ground_Vehicle.TTantiair01, true)
    WaitFor(0.5)
  end
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    ForceUnitTransfer(constant.PLAYER_ONE, Troop.WFbazooka01, true)
    WaitFor(0.5)
  end
  Despawn(Air_Vehicle.WFfighter1)
  Despawn(Air_Vehicle.WFfighter2)
  Despawn(Air_Vehicle.WFbomber01)
  Despawn(Air_Vehicle.TTfighter1)
  Despawn(Air_Vehicle.TTfighter2)
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    ClearMessageQueue(constant.PLAYER_TWO)
    PhoneMessageWithObjective(75, constant.ID_NONE, 2, 6, SpriteID.CO_T_Young_Gorgi_Happy, constant.PLAYER_TWO, false, constant.NEW_SECONDARY_OBJECTIVE)
    SetCamera(Camera.player2cam, constant.PLAYER_TWO)
    SetInvulnerable(flag.TYPE_TUNDRAN, false)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
  end
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    ClearMessageQueue(constant.PLAYER_ONE)
    PhoneMessageWithObjective(25, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Young_Herman_Happy, constant.PLAYER_ONE, false, constant.NEW_SECONDARY_OBJECTIVE)
    SetCamera(Camera.player1cam, constant.PLAYER_ONE)
    SetInvulnerable(flag.TYPE_WFRONTIER, false)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
  end
  WaitFor(FreezeDelay)
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    UnfreezePlayer(constant.PLAYER_ONE)
    SetInvulnerable(flag.TYPE_WFRONTIER, false)
    ResetCommandBar()
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    UnfreezePlayer(constant.PLAYER_TWO)
    SetInvulnerable(flag.TYPE_TUNDRAN, false)
    ResetCommandBar()
  end
  PauseTimerActive = 0
  SetTimer(MissionTimeLeft)
  ShowTimer(1)
  TimerShown = 1
  CutsceneMid = 1
end
