function CutScene01(owner)
  IntroCutsceneGlobal = owner
  StartIntro()
  CameraSetFOV(Camera.IntroductionCutsceneCamera, 80, constant.IMMEDIATE, 100, constant.NO_WAIT)
  CameraSetWaypoint(Camera.IntroductionCutsceneCamera, Waypoint.IntroductionCutscene01Waypoint02)
  PhoneMessage(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  PhoneMessageWithObjective(6, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  GoToArea(Water_Vehicle.TFrigate01, -92, -715, 5, constant.ORDER_FORCED)
  WaitFor(8)
  GoToArea(Water_Vehicle.TFrigate02, -12, -692, 5, constant.ORDER_FORCED)
  WaitFor(8)
  FollowWaypoint(Water_Vehicle.TFrigate01, Waypoint.TFrigate01Waypoint01, 0, 0, constant.ORDER_FORCED)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.IntroductionCutsceneCamera02)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessageWithObjective(14, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  WaitFor(7)
  PhoneMessage(90, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
  WaitFor(1)
  GoToArea(Troop.WFAAVet05, 213.161, -1182.14, 1, 0, constant.ORDER_FORCED)
  WaitFor(2)
  GoToArea(Troop.WFAAVet06, 212.475, -1175.7, 1, 0, constant.ORDER_FORCED)
  WaitFor(2)
  GoToArea(Troop.WFAAVet07, 205.574, -1174.36, 1, 0, constant.ORDER_FORCED)
  WaitFor(2)
  GoToArea(Troop.WFAAVet08, 204.798, -1167.35, 1, 0, constant.ORDER_FORCED)
  WaitFor(3)
  IntroCutsceneFinished = 1
end
