function CutScene03Skip(owner)
  repeat
    EndFrame()
  until StartedCutscene03 == 1
  WaitFor(1)
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      DebugOut("Mid Cutscene Skipped")
      EndCutscene03 = 1
    end
    EndFrame()
  until EndCutscene03 == 1
  ClearMessageQueue()
  Kill(AbortCutscene03)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PutUnitInVehicle(Troop.TGunship02Occupant01, Air_Vehicle.TundranGunship02, 0)
  PutUnitInVehicle(Troop.TGunship03Occupant01, Air_Vehicle.TundranGunship03, 0)
  GoToArea(Air_Vehicle.TundranGunship02, 7, -456, 15, 0, constant.ORDER_NORMAL)
  GoToArea(Air_Vehicle.TundranGunship03, 7, -456, 15, 0, constant.ORDER_NORMAL)
  EndIntro()
  StoreSummaryMessage(11, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Happy)
  StoreSummaryMessage(72, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  StoreSummaryMessage(73, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  SetObjectiveData(Objective.CaptureAirbase, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.CaptureAirbase, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective.FreePowsInTheAirbase, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.FreePowsInTheAirbase, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  Kill(Destroyable_Object.ElectroMagneticGate01)
  Kill(Destroyable_Object.ElectroMagneticGate02)
  Kill(Destroyable_Object.ElectroMagneticGate03)
  Kill(Destroyable_Object.ElectroMagneticGate04)
  Vanish(Destroyable_Object.ElectroMagneticGateFall01)
  Vanish(Destroyable_Object.ElectroMagneticGateFall02)
  Vanish(Destroyable_Object.ElectroMagneticGateFall03)
  Vanish(Destroyable_Object.ElectroMagneticGateFall04)
  Kill(Building.Entity570014236)
  Kill(Building.Entity570014247)
  Kill(Building.Entity570014235)
  Kill(Building.Entity570014246)
  Kill(Building.Entity570014234)
  Kill(Building.Entity570014245)
  Kill(Building.Entity570014238)
  Kill(Building.Entity570014248)
  Kill(Building.Unknown01)
  Kill(Building.Entity570014250)
  Kill(Building.Entity570014595)
  Kill(Building.Entity570014596)
  SetCamera(Camera.PlayerCamera)
  Spawn(Troop.TundranFlamer01)
  Spawn(Troop.TundranFlamer02)
  Spawn(Troop.TundranFlamer03)
  Spawn(Troop.TundranFlamer04)
  Spawn(Troop.TundranAntiAirVet01)
  Spawn(Troop.TundranAntiAirVet02)
  Spawn(Troop.TundranAntiAirVet03)
  Spawn(Troop.TundranAntiAirVet04)
  Spawn(Troop.TundranChainVet01)
  Spawn(Troop.TundranChainVet02)
  Spawn(Troop.TundranChainVet03)
  Spawn(Troop.TundranChainVet04)
  GoToArea(Troop.TundranAntiAirVet01, 131, -85, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.TundranAntiAirVet02, 121, -84, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.TundranAntiAirVet03, 112, -84, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.TundranAntiAirVet04, 100, -85, 5, 0, constant.ORDER_FORCED)
  CleanupSkipCutscene()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  playerincutscene = false
  UnfreezePlayer(constant.PLAYER_ONE)
  PauseTimerActive = 0
  SetInvulnerable(flag.TYPE_WFRONTIER, 0)
  PhoneMessageWithObjective(12, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
end
