function CutScene02Skip(owner)
  repeat
    EndFrame()
  until StartedCutscene02 == 1
  WaitFor(1)
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      DebugOut("Mid Cutscene Skipped")
      EndCutscene02 = 1
    end
    EndFrame()
  until EndCutscene02 == 1
  ClearMessageQueue()
  Kill(AbortCutscene02)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  EndIntro()
  StoreSummaryMessage(7, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Happy)
  StoreSummaryMessage(70, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  StoreSummaryMessage(71, constant.ARMY_WF, SpriteID.CO_WF_Young_Herman_Sad)
  Despawn(Air_Vehicle.WFGunship01)
  Spawn(Air_Vehicle.WFGunship03)
  SetActive(Air_Vehicle.WFGunship02, constant.ACTIVE)
  SetActive(Troop.WFGunship02Occupant01, constant.ACTIVE)
  SetUnitInvulnerable(Troop.WFGunship02Occupant01, false)
  if GetSpawnMode() == eModeAction.Follow then
    FollowUnit(Air_Vehicle.WFGunship02, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
    FollowUnit(Air_Vehicle.WFGunship03, GetPlayerUnit(), -1, 0, constant.ORDER_NORMAL)
  else
    GoToArea(Air_Vehicle.WFGunship02, 231, -1178, 1)
    GoToArea(Air_Vehicle.WFGunship03, 238, -1188, 1)
  end
  GoToArea(Air_Vehicle.TundranGunship01, 63, 84, 10, constant.ORDER_FORCED)
  SetObjectiveData(Objective.DestroyGenerator, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.Generator01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.Generator02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.Generator03, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.Generator04, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetActive(Building.TundranGenerator01, constant.ACTIVE)
  SetActive(Building.TundranGenerator02, constant.ACTIVE)
  SetActive(Building.TundranGenerator03, constant.ACTIVE)
  SetActive(Building.TundranGenerator04, constant.ACTIVE)
  SetActive(Building.TundranSuperGunTower01, constant.ACTIVE)
  SetActive(Building.TundranAmmoDump01, constant.ACTIVE)
  SetActive(Building.Entity270013776, constant.ACTIVE)
  SetActive(Building.Entity270013775, constant.ACTIVE)
  SetActive(Building.Entity270013777, constant.ACTIVE)
  SetActive(Building.Entity270013778, constant.ACTIVE)
  SetActive(Building.Entity270013779, constant.ACTIVE)
  SetActive(Building.Entity270013780, constant.ACTIVE)
  SetActive(Building.Entity270013078, constant.ACTIVE)
  SetActive(Building.Entity270013077, constant.ACTIVE)
  SetUnitInvulnerable(Building.TundranGenerator01, false)
  SetUnitInvulnerable(Building.TundranGenerator02, false)
  SetUnitInvulnerable(Building.TundranGenerator03, false)
  SetUnitInvulnerable(Building.TundranGenerator04, false)
  Spawn(Air_Vehicle.TundranGunship01)
  Spawn(Air_Vehicle.TundranGunship02)
  Spawn(Air_Vehicle.TundranGunship03)
  Spawn(Ground_Vehicle.XsylvanianLightTank01)
  Spawn(Troop.XGrunt01)
  Spawn(Troop.XGrunt02)
  Spawn(Troop.XsylvanianDigSiteWFAAVet01)
  Spawn(Troop.XsylvanianDigSiteWFAAVet02)
  Spawn(Troop.XsylvanianDigSiteWFAAVet03)
  Spawn(Troop.XsylvanianDigSiteWFAAVet04)
  Spawn(Building.XPowAmmoDump01)
  SetViewDistanceAdjustment(-1, 10)
  SetCamera(Camera.PlayerCamera)
  CleanupSkipCutscene()
  SetObjectiveData(Objective.ProtectTheArtillery03, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.ProtectTheArtillery02, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.ProtectTheArtillery01, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.ProtectTheArtillery00, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective_Marker.ArtilleryMarker03, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.ArtilleryMarker02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.ArtilleryMarker01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  playerincutscene = false
  UnfreezePlayer(constant.PLAYER_ONE)
  PauseTimerActive = 0
  SetInvulnerable(flag.TYPE_WFRONTIER, 0)
end
