function DespawnInactiveKilledUnits(owner)
  Kill(Troop.WFGunshipGrunt)
  Kill(Troop.TundranKill01)
  Kill(Troop.TundranKill02)
  Despawn(Air_Vehicle.TundranBomber01)
  Despawn(Air_Vehicle.TundranGunship06)
  Despawn(Troop.TundranAntiAirTower03Occupant01)
  Despawn(Troop.TundranAntiAirTower04Occupant01)
  Despawn(Troop.TGunship02Occupant01)
  Despawn(Troop.TGunship03Occupant01)
  Despawn(Troop.EndCutSceneGrunt01)
  Despawn(Troop.EndCutSceneGrunt02)
  Despawn(Troop.EndCutSceneGrunt03)
  Despawn(Troop.EndCutSceneGrunt04)
  Despawn(Troop.EndCutSceneGrunt05)
  Despawn(Troop.EndCutSceneGrunt06)
  Despawn(Troop.EndCutSceneGrunt07)
  Despawn(Troop.EndCutSceneGrunt08)
  Despawn(Troop.EndCutSceneGrunt09)
  Despawn(Troop.TundranAirTransport01Occupant01, false)
  Despawn(Troop.TundranAirTransport02Occupant01, false)
  Despawn(Troop.TundranAirTransport03Occupant01, false)
  Despawn(Troop.TundranAirTransport04Occupant01, false)
  Despawn(Troop.TundranCounterFlameVet01, true)
  Despawn(Troop.TundranCounterFlameVet02, true)
  Despawn(Troop.TundranCounterFlameVet03, true)
  Despawn(Troop.TundranCounterAAVet01, true)
  Despawn(Troop.TundranCounterAAVet02, true)
  Despawn(Troop.TundranCounterAAVet03, true)
  Despawn(Troop.TundranCounterAAVet04, true)
  Despawn(Troop.TundranAACounterTroop01, true)
  Despawn(Troop.TundranAACounterTroop02, true)
  Despawn(Ground_Vehicle.TundranHeavyTank01, true)
  Despawn(Ground_Vehicle.TundranHeavyTank02, true)
  Despawn(Ground_Vehicle.TundranHeavyTank03, true)
  Despawn(Ground_Vehicle.TundranHeavyTank04, true)
  Despawn(Troop.TundranAntiAirVet01, false)
  Despawn(Troop.TundranAntiAirVet02, false)
  Despawn(Troop.TundranAntiAirVet03, false)
  Despawn(Troop.TundranAntiAirVet04, false)
  Despawn(Building.TundranRpgTower03, true)
  Despawn(Building.TundranRpgTower04, true)
  Despawn(Building.TundranAntiAirTower12, true)
  Despawn(Building.TundranAntiAirTower13, true)
  Despawn(Troop.TundranFlamer01, false)
  Despawn(Troop.TundranFlamer02, false)
  Despawn(Troop.TundranFlamer03, false)
  Despawn(Troop.TundranFlamer04, false)
  Despawn(Troop.TundranFlamer05, true)
  Despawn(Troop.TundranFlamer06, true)
  Despawn(Troop.TundranFlamer07, true)
  Despawn(Troop.TundranFlamer08, true)
  Despawn(Troop.TundranBazookaVet07, true)
  Despawn(Troop.TundranBazookaVet03, true)
  Despawn(Troop.TundranBazookaVet04, true)
  Despawn(Troop.TundranBazookaVet06, true)
  Despawn(Troop.TundranChainVet01, false)
  Despawn(Troop.TundranChainVet02, false)
  Despawn(Troop.TundranChainVet03, false)
  Despawn(Troop.TundranChainVet04, false)
  Despawn(Troop.TundranChainVet05, true)
  Despawn(Troop.TundranChainVet06, true)
  Despawn(Troop.TundranChainVet07, true)
  Despawn(Troop.TundranChainVet08, true)
  Despawn(Troop.TundranChainVet09, true)
  Despawn(Air_Vehicle.TundranGunship01, true)
  Despawn(Ground_Vehicle.XsylvanianLightTank01, false)
  Despawn(Troop.XGrunt01, false)
  Despawn(Troop.XGrunt02, false)
  Despawn(Building.XPowAmmoDump01, false)
  Despawn(Air_Vehicle.TundranAirTransport01, true)
  Despawn(Air_Vehicle.TundranAirTransport02, true)
  Despawn(Air_Vehicle.TundranAirTransport03, true)
  Despawn(Air_Vehicle.TundranAirTransport04, true)
  Despawn(Air_Vehicle.TundranGunship04, true)
  Despawn(Air_Vehicle.TundranGunship05, true)
  SetUnitInvulnerable(Building.TundranAirTransport01RefuelingStation, true)
  SetUnitInvulnerable(Building.TundranAirTransport02RefuelingStation, true)
  SetUnitInvulnerable(Building.TundranAirTransport03RefuelingStation, true)
  SetUnitInvulnerable(Building.TundranAirTransport04RefuelingStation, true)
end
