function SecondaryObjective02FreeTheAirbasePows(owner)
  SetActive(Troop.AirbasePowWFChainVet01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.AirbasePowWFChainVet02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.AirbasePowWFChainVet03, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.AirbasePowWFChainVet04, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetUnitInvulnerable(Troop.AirbasePowWFChainVet01, true)
  SetUnitInvulnerable(Troop.AirbasePowWFChainVet02, true)
  SetUnitInvulnerable(Troop.AirbasePowWFChainVet03, true)
  SetUnitInvulnerable(Troop.AirbasePowWFChainVet04, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence01, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence02, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence03, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence04, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence05, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence06, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence07, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence08, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence09, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence10, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence11, true)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence12, true)
  SetUnitInvulnerable(Building.AirbasePowAmmoDump01, true)
  SetActive(Building.AirbasePowAmmoDump01, constant.INACTIVE)
  local teleporttimer = GetTime()
  repeat
    if IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.ArtificialMissionBoundary) then
      teleporttimer = GetTime()
      PhoneMessage(13, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Sad, constant.PLAYER_ONE)
      repeat
        EndFrame()
      until GetTime() > teleporttimer + 7 or IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.ArtificialMissionBoundary02)
      if IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.ArtificialMissionBoundary) or IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.ArtificialMissionBoundary02) then
        FreezePlayer(constant.PLAYER_ONE)
        CameraFade(constant.FADE_OUT, constant.WAIT, 1)
        Teleport(GetPlayerUnit(constant.PLAYER_ONE), 70, -387, 180, 2)
        CameraFade(constant.FADE_IN, constant.WAIT, 1)
        WaitFor(0.5)
        UnfreezePlayer(constant.PLAYER_ONE)
        WaitFor(1)
      else
        EndFrame()
      end
    end
    WaitFor(0.2)
  until Objective02 == 1
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence01, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence02, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence03, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence04, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence05, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence06, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence07, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence08, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence09, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence10, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence11, false)
  SetUnitInvulnerable(Destroyable_Object.AirbasePowFence12, false)
  SetUnitInvulnerable(Building.AirbasePowAmmoDump01, false)
  SetActive(Building.AirbasePowAmmoDump01, constant.ACTIVE)
  while missionend == 0 do
    if IsDead(Destroyable_Object.AirbasePowFence01) or IsDead(Destroyable_Object.AirbasePowFence02) or IsDead(Destroyable_Object.AirbasePowFence03) or IsDead(Destroyable_Object.AirbasePowFence04) or IsDead(Destroyable_Object.AirbasePowFence05) or IsDead(Destroyable_Object.AirbasePowFence06) or IsDead(Destroyable_Object.AirbasePowFence07) or IsDead(Destroyable_Object.AirbasePowFence08) or IsDead(Destroyable_Object.AirbasePowFence09) or IsDead(Destroyable_Object.AirbasePowFence10) or IsDead(Destroyable_Object.AirbasePowFence11) or IsDead(Destroyable_Object.AirbasePowFence12) or IsDead(Building.AirbasePowAmmoDump01) then
      pow02 = 1
      SetObjectiveData(Objective.FreePowsInTheAirbase, constant.OBJECTIVE_DATA_STATE, 1)
      SetObjectiveData(Objective_Marker.FreePowsInTheAirbase, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      PhoneMessageWithObjective(55, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Young_Herman_Happy, constant.PLAYER_ONE, false, constant.SECONDARY_OBJECTIVE_COMPLETE)
      TechniqueObjectivesCompleted = TechniqueObjectivesCompleted + 1
      Kill(Destroyable_Object.AirbasePowFence01)
      Kill(Destroyable_Object.AirbasePowFence02)
      Kill(Destroyable_Object.AirbasePowFence03)
      Kill(Destroyable_Object.AirbasePowFence04)
      Kill(Destroyable_Object.AirbasePowFence05)
      Kill(Destroyable_Object.AirbasePowFence06)
      Kill(Destroyable_Object.AirbasePowFence07)
      Kill(Destroyable_Object.AirbasePowFence08)
      Kill(Destroyable_Object.AirbasePowFence09)
      Kill(Destroyable_Object.AirbasePowFence10)
      Kill(Destroyable_Object.AirbasePowFence11)
      Kill(Destroyable_Object.AirbasePowFence12)
      Kill(Building.AirbasePowAmmoDump01)
      EndFrame()
      SetActive(Troop.AirbasePowWFChainVet01, constant.ACTIVE, constant.ADJUST_WEAPON)
      SetActive(Troop.AirbasePowWFChainVet02, constant.ACTIVE, constant.ADJUST_WEAPON)
      SetActive(Troop.AirbasePowWFChainVet03, constant.ACTIVE, constant.ADJUST_WEAPON)
      SetActive(Troop.AirbasePowWFChainVet04, constant.ACTIVE, constant.ADJUST_WEAPON)
      EndFrame()
      if GetSpawnMode() == eModeAction.Follow then
        FollowUnit(Troop.AirbasePowWFChainVet01, GetPlayerUnit(0), -1, constant.ORDER_FORCED)
        FollowUnit(Troop.AirbasePowWFChainVet02, GetPlayerUnit(0), -1, constant.ORDER_FORCED)
        FollowUnit(Troop.AirbasePowWFChainVet03, GetPlayerUnit(0), -1, constant.ORDER_FORCED)
        FollowUnit(Troop.AirbasePowWFChainVet04, GetPlayerUnit(0), -1, constant.ORDER_FORCED)
      end
      SetUnitInvulnerable(Troop.AirbasePowWFChainVet01, false)
      SetUnitInvulnerable(Troop.AirbasePowWFChainVet02, false)
      SetUnitInvulnerable(Troop.AirbasePowWFChainVet03, false)
      SetUnitInvulnerable(Troop.AirbasePowWFChainVet04, false)
      DebugOut("*SecondaryObjective02FreeTheAirbasePows* - 1. The Airbase POWs have been freed")
      break
    end
    EndFrame()
  end
end
