function Melee_Cutscene02(owner)
  Cutscene02Dead = owner
  Despawn(Air_Vehicle.CutsceneSEGunship03)
  Despawn(Air_Vehicle.CutsceneSEGunship04)
  Despawn(Air_Vehicle.CutsceneSEGunship05)
  Despawn(Air_Vehicle.CutsceneSEGunship06)
  Despawn(Air_Vehicle.CutsceneSEGunship07)
  Despawn(Troop.CutsceneSEGunship03Pilot)
  Despawn(Troop.CutsceneSEGunship04Pilot)
  Despawn(Troop.CutsceneSEGunship05Pilot)
  Despawn(Troop.CutsceneSEGunship06Pilot)
  Despawn(Troop.CutsceneSEGunship07Pilot)
  repeat
    EndFrame()
  until ReadyForCutscene02 == 1
  Despawn(Building.SE_HeavyTank_Grounded04_HeavyTank01)
  Despawn(Building.SE_HeavyTank_Grounded04_HeavyTank02)
  Despawn(Building.SE_HeavyTank_Grounded04_HeavyTank03)
  Despawn(Building.SE_HeavyTank_Grounded04_HeavyTank04)
  Despawn(Ground_Vehicle.SE_HeavyTank_Grounded04_HeavyTank01)
  Despawn(Ground_Vehicle.SE_HeavyTank_Grounded04_HeavyTank02)
  Spawn(Building.AmmoDump_HeavyTank_Grounded01)
  Spawn(Building.AmmoDump_HeavyTank_Grounded04)
  Spawn(Air_Vehicle.CutsceneSEGunship03)
  Spawn(Air_Vehicle.CutsceneSEGunship04)
  Spawn(Air_Vehicle.CutsceneSEGunship05)
  Spawn(Air_Vehicle.CutsceneSEGunship06)
  Spawn(Air_Vehicle.CutsceneSEGunship07)
  Spawn(Troop.CutsceneSEGunship03Pilot)
  Spawn(Troop.CutsceneSEGunship04Pilot)
  Spawn(Troop.CutsceneSEGunship05Pilot)
  Spawn(Troop.CutsceneSEGunship06Pilot)
  Spawn(Troop.CutsceneSEGunship07Pilot)
  Spawn(Building.SE_HeavyTank_Grounded01)
  Spawn(Building.SE_HeavyTank_Grounded04)
  Spawn(Building.SE_HeavyTank_Grounded05)
  Spawn(Building.SE_HeavyTank_Grounded06)
  EnterVehicle(Troop.CutsceneSEGunship03Pilot, Air_Vehicle.CutsceneSEGunship03, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutsceneSEGunship04Pilot, Air_Vehicle.CutsceneSEGunship04, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutsceneSEGunship05Pilot, Air_Vehicle.CutsceneSEGunship05, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutsceneSEGunship06Pilot, Air_Vehicle.CutsceneSEGunship06, constant.ORDER_FORCED)
  EnterVehicle(Troop.CutsceneSEGunship07Pilot, Air_Vehicle.CutsceneSEGunship07, constant.ORDER_FORCED)
  SetCamera(Camera.Cutscene02_Shot00)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(1)
  PhoneMessageWithObjective(22, constant.ID_NONE, constant.ARMY_UNDERWORLD, 6, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE, false, constant.PRIMARY_OBJECTIVE_COMPLETE)
  WaitFor(1)
  DestroyablePlayAnim(Building.IL_Battlestation01, 1, 2)
  DestroyablePlayAnim(Destroyable_Object.IL_BattlestationElevator01, 1, 2)
  Cutscene02Begins = 1
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene02_Shot01)
  CameraSetFOV(Camera.Cutscene02_Shot01, 80, constant.IMMEDIATE, 1.5, constant.NO_WAIT)
  Despawn(Building.IL_Battlestation01)
  Spawn(Ground_Vehicle.IL_Battlestation01)
  WaitFor(1)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(21, constant.ID_NONE, constant.ARMY_UNDERWORLD, 6, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  repeat
    GoToArea(Ground_Vehicle.IL_Battlestation01, GetObjectXPosition(Waypoint.IL_Battlestation01), GetObjectZPosition(Waypoint.IL_Battlestation01), 5, constant.ORDER_FORCED)
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene02_Shot02)
  CameraSetFOV(Camera.Cutscene02_Shot02, 65, constant.IMMEDIATE, 25, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(53, constant.ID_NONE, constant.ARMY_SOLAR, 6, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  GoToArea(Air_Vehicle.CutsceneSEGunship06, GetObjectXPosition(Waypoint.CutsceneSEGunship03Path), GetObjectZPosition(Waypoint.CutsceneSEGunship03Path), 5, 0, constant.ORDER_FORCED)
  WaitFor(1)
  GoToArea(Air_Vehicle.CutsceneSEGunship04, GetObjectXPosition(Waypoint.CutsceneSEGunship03Path), GetObjectZPosition(Waypoint.CutsceneSEGunship03Path), 5, 0, constant.ORDER_FORCED)
  WaitFor(1.5)
  GoToArea(Air_Vehicle.CutsceneSEGunship07, GetObjectXPosition(Waypoint.CutsceneSEGunship03Path), GetObjectZPosition(Waypoint.CutsceneSEGunship03Path), 5, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  GoToArea(Air_Vehicle.CutsceneSEGunship03, GetObjectXPosition(Waypoint.CutsceneSEGunship03Path), GetObjectZPosition(Waypoint.CutsceneSEGunship03Path), 5, 0, constant.ORDER_FORCED)
  WaitFor(2)
  GoToArea(Air_Vehicle.CutsceneSEGunship05, GetObjectXPosition(Waypoint.CutsceneSEGunship03Path), GetObjectZPosition(Waypoint.CutsceneSEGunship03Path), 5, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Cutscene02Complete = 1
  DebugOut("Cutscene02 ended naturally")
end
