function CutScene01Skip(owner)
  local breakvariable = 0
  CreateGroup(Unit_Group.Tundrans)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranGrunt01)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranGrunt02)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranGrunt03)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranGrunt04)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranGrunt05)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet01)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet02)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet03)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet04)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet05)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranBazookaVet06)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranFlameVet01)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranFlameVet02)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranFlameVet03)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranFlameVet04)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranAntiAirVet01)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranAntiAirVet02)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranAntiAirVet03)
  AddToGroup(Unit_Group.Tundrans, Troop.TundranAntiAirVet04)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper01Grunt01)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper01Grunt02)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper02AA01)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper01AA01)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper02Flame01)
  AddToGroup(Unit_Group.Tundrans, Troop.HelipadChopper02Flame02)
  AddToGroup(Unit_Group.Tundrans, Ground_Vehicle.TundranArtillery01)
  AddToGroup(Unit_Group.Tundrans, Ground_Vehicle.TundranArtillery02)
  WaitFor(1)
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      cutsceneskip01 = 1
      DebugOut("*CutScene01Skip* - Player 1 Killed CutScene01")
    end
    EndFrame()
  until cutsceneskip01 == 1 or cutscenefinished01 == 1
  ClearMessageQueue()
  Kill(cutsceneabort01)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  GoToArea(Troop.XylvanianGrunt10, 178, -85, 2)
  GoToArea(Troop.XylvanianGrunt09, 176, -89, 2)
  GoToArea(Troop.XylvanianGrunt08, 179, -93, 2)
  GoToArea(Troop.XylvanianGrunt07, 183, -90, 2)
  GoToArea(Ground_Vehicle.XylvanianLightTank01, 186, -100, 10)
  GoToArea(Ground_Vehicle.XylvanianLightTank02, 191, -84, 10)
  Teleport(Troop.XylvanianAirbaseGrunt01, 22, -134, 180, 2)
  Teleport(Troop.XylvanianAirbaseGrunt02, 26, -141, 180, 2)
  Teleport(Troop.XylvanianAirbaseGrunt03, 22, -134, 180, 2)
  Teleport(Troop.XylvanianAirbaseGrunt04, 26, -141, 180, 2)
  Teleport(Troop.XylvanianGrunt10, 178, -85, 170, 2)
  Teleport(Troop.XylvanianGrunt09, 176, -89, 90, 2)
  Teleport(Troop.XylvanianGrunt08, 179, -93, 0, 2)
  Teleport(Troop.XylvanianGrunt07, 183, -90, 290, 2)
  Teleport(Ground_Vehicle.XylvanianLightTank01, 186, -100, 270, 10)
  Teleport(Ground_Vehicle.XylvanianLightTank02, 191, -84, 270, 10)
  SetInvulnerable(flag.TYPE_XYLVANIAN, 0)
  SetUnitInvulnerable(Troop.CutSceneGrunt01, 0)
  Kill(Building.CutSceneAmmoDump01)
  Kill(Building.CutSceneAmmoDump02)
  Kill(Troop.BurningGrunt01)
  Kill(Troop.BurningGrunt02)
  Kill(Troop.CutSceneGrunt01)
  Kill(Troop.CutSceneGrunt02)
  Kill(Troop.CutSceneGrunt03)
  Kill(Troop.CutSceneGrunt04)
  Teleport(Troop.XylvanianMortarVet01, 563, 516, 200, 2)
  Teleport(Troop.XylvanianMortarVet02, 566, 513, 200, 2)
  Teleport(Troop.XylvanianMortarVet03, 579, 504, 200, 2)
  Teleport(Troop.XylvanianMortarVet04, 582, 501, 200, 2)
  Teleport(Troop.XMausoleumGrunt01, 537, 539, 200, 2)
  Teleport(Troop.XMausoleumGrunt02, 538, 536, 200, 2)
  Teleport(Troop.XMausoleumGrunt03, 540, 533, 200, 2)
  Teleport(Troop.XMausoleumGrunt04, 603, 488, 200, 2)
  Teleport(Troop.XMausoleumGrunt05, 607, 488, 200, 2)
  Teleport(Troop.XMausoleumGrunt06, 612, 488, 200, 2)
  Teleport(Ground_Vehicle.XylvanianArtillery01, 411, 497, 215, 2)
  Teleport(Ground_Vehicle.XylvanianArtillery03, 595, 344, 215, 2)
  Teleport(Troop.XylvanianBazookaVet15, 296, 422, 220, 10)
  Teleport(Troop.XylvanianBazookaVet16, 298, 420, 220, 10)
  Teleport(Troop.XylvanianBazookaVet17, 300, 418, 220, 10)
  Teleport(Troop.XylvanianBazookaVet18, 302, 416, 220, 10)
  Teleport(Troop.XylvanianBazookaVet19, 304, 414, 220, 10)
  Teleport(Ground_Vehicle.XylvanianLightTank03, 310, 414, 220, 20)
  Teleport(Ground_Vehicle.XylvanianLightTank04, 304, 426, 220, 20)
  SetObjectiveData(Objective_Marker.BurningGrunt01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.BurningGrunt02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  Teleport(Air_Vehicle.XylvanianGunship02, 34, -126, 210, 15)
  Teleport(Air_Vehicle.XylvanianGunship03, 34, -102, 210, 15)
  CleanupSkipCutscene()
  StoreSummaryMessage(constant.PLAYER_ONE, 16, constant.ARMY_TUNDRAN, SpriteID.CO_T_Ghost_Gorgi_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 44, constant.ARMY_TUNDRAN, SpriteID.CO_T_Ghost_Gorgi_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 17, constant.ARMY_TUNDRAN, SpriteID.CO_T_Nova_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 19, constant.ARMY_WF, SpriteID.CO_WF_Betty_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 22, constant.ARMY_TUNDRAN, SpriteID.CO_T_Nova_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 28, constant.ARMY_XYLVANIAN, SpriteID.CO_X_Prison_Ubel_Happy)
  Despawn(Air_Vehicle.CutSceneGunship01, false)
  Despawn(Air_Vehicle.CutSceneGunship02, false)
  Despawn(Ground_Vehicle.XylvanianArtillery01, true)
  Despawn(Ground_Vehicle.XylvanianArtillery03, true)
  Despawn(Troop.XMausoleumGrunt01, true)
  Despawn(Troop.XMausoleumGrunt02, true)
  Despawn(Troop.XMausoleumGrunt03, true)
  Despawn(Troop.XMausoleumGrunt04, true)
  Despawn(Troop.XMausoleumGrunt05, true)
  Despawn(Troop.XMausoleumGrunt06, true)
  Despawn(Troop.XylvanianMortarVet01, true)
  Despawn(Troop.XylvanianMortarVet02, true)
  Despawn(Troop.XylvanianMortarVet03, true)
  Despawn(Troop.XylvanianMortarVet04, true)
  Despawn(Troop.XylvanianBazookaVet15, true)
  Despawn(Troop.XylvanianBazookaVet16, true)
  Despawn(Troop.XylvanianBazookaVet17, true)
  Despawn(Troop.XylvanianBazookaVet18, true)
  Despawn(Troop.XylvanianBazookaVet19, true)
  Despawn(Ground_Vehicle.XylvanianLightTank03, true)
  Despawn(Ground_Vehicle.XylvanianLightTank04, true)
  Despawn(Building.XylvanianAATower06, true)
  Despawn(Building.XylvanianAATower07, true)
  Despawn(Building.XylvanianMGNest06, true)
  Despawn(Building.XylvanianMGNest07, true)
  Despawn(Ground_Vehicle.XylvanianLightTank01, true)
  Despawn(Ground_Vehicle.XylvanianLightTank02, true)
  Despawn(Troop.XylvanianGrunt07, true)
  Despawn(Troop.XylvanianGrunt08, true)
  Despawn(Troop.XylvanianGrunt09, true)
  Despawn(Troop.XylvanianGrunt10, true)
  Despawn(Building.XylvanianMGTower01, true)
  Despawn(Building.XylvanianMGTower02, true)
  Despawn(Building.XylvanianAATower03, true)
  Despawn(Building.XylvanianAATower04, true)
  Despawn(Troop.WesternFrontierMortarVet01, true)
  Despawn(Troop.WesternFrontierMortarVet02, true)
  Despawn(Troop.WesternFrontierMortarVet03, true)
  Despawn(Troop.WesternFrontierMortarVet04, true)
  Despawn(Troop.WesternFrontierMortarVet05, true)
  Spawn(Troop.TundranAntiAirVet01)
  Spawn(Troop.TundranAntiAirVet02)
  Spawn(Troop.TundranAntiAirVet03)
  Spawn(Troop.TundranAntiAirVet04)
  Spawn(Troop.TundranFlameVet01)
  Spawn(Troop.TundranFlameVet02)
  Spawn(Troop.TundranFlameVet03)
  Spawn(Troop.TundranFlameVet04)
  Spawn(Troop.TundranGrunt01)
  Spawn(Troop.TundranGrunt02)
  Spawn(Troop.TundranGrunt04)
  Spawn(Troop.TundranGrunt05)
  Spawn(Ground_Vehicle.TundranArtillery01)
  Spawn(Ground_Vehicle.TundranArtillery02)
  Spawn(Troop.XylvanianBazookaVet01)
  Spawn(Troop.XylvanianBazookaVet02)
  Spawn(Troop.XylvanianBazookaVet03)
  Spawn(Troop.XylvanianGrunt01)
  Spawn(Troop.XylvanianGrunt02)
  Spawn(Troop.XylvanianGrunt03)
  Spawn(Troop.XylvanianGrunt04)
  Spawn(Troop.Entity330100783)
  Spawn(Troop.Entity330100784)
  Spawn(Troop.Entity330005604)
  Spawn(Troop.Entity330005605)
  Spawn(Troop.Entity330005606)
  Spawn(Troop.Entity330005607)
  Spawn(Troop.Entity330004369)
  Spawn(Troop.Entity330004368)
  Spawn(Morphing_Building.AirbaseGunTurret01)
  Spawn(Morphing_Building.AirbaseGunTurret02)
  SetCamera(Camera.Player1Cam)
  EndFrame()
  ResetCommandBar()
  EndIntro()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  UnfreezePlayer(constant.PLAYER_ONE)
  cutscene01 = 1
  ResetHealthAndScoreTotals()
  StartScoringTimer()
  while missionend == 0 do
    if breakvariable == 0 then
      PhoneMessage(31, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
      PhoneMessage(32, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
      WaitFor(14)
      if IsDead(Ground_Vehicle.TundranArtillery01) == false then
        GoToArea(Troop.XylvanianBazookaVet01, GetObjectXPosition(Ground_Vehicle.TundranArtillery01), GetObjectZPosition(Ground_Vehicle.TundranArtillery01), 10, 0, constant.ORDER_NORMAL)
        GoToArea(Troop.XylvanianBazookaVet02, GetObjectXPosition(Ground_Vehicle.TundranArtillery01), GetObjectZPosition(Ground_Vehicle.TundranArtillery01), 10, 0, constant.ORDER_NORMAL)
      else
        GoToArea(Troop.XylvanianBazookaVet01, -465, -111, 5, 0, constant.ORDER_NORMAL)
        GoToArea(Troop.XylvanianBazookaVet02, -465, -111, 5, 0, constant.ORDER_NORMAL)
      end
      if IsDead(Ground_Vehicle.TundranArtillery02) == false then
        GoToArea(Troop.XylvanianBazookaVet03, GetObjectXPosition(Ground_Vehicle.TundranArtillery02), GetObjectZPosition(Ground_Vehicle.TundranArtillery02), 10, 0, constant.ORDER_NORMAL)
      else
        GoToArea(Troop.XylvanianBazookaVet03, -473, -136, 5, 0, constant.ORDER_NORMAL)
      end
      DebugOut("*XylvanianOpeningBazookaVetAttack - The Xylvanian Bazooka Vets have been sent to attack the Tundran Heavy Tanks")
      WaitFor(20)
      repeat
        EndFrame()
      until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
      AttackTarget(Air_Vehicle.XylvanianGunship01, GetPlayerUnit(constant.PLAYER_ONE), constant.ORDER_NORMAL)
      AttackTarget(Air_Vehicle.XylvanianGunship02, GetPlayerUnit(constant.PLAYER_ONE), constant.ORDER_NORMAL)
      PhoneMessage(33, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
      if IsDead(Troop.TundranAntiAirVet01) == false and IsDead(Troop.TundranAntiAirVet02) == false and IsDead(Troop.TundranAntiAirVet03) == false and IsDead(Troop.TundranAntiAirVet04) == false then
        PhoneMessage(34, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
      end
      WaitFor(30)
      Spawn(Troop.XylvanianBazookaVet05)
      Spawn(Troop.XylvanianBazookaVet06)
      EndFrame()
      AttackTarget(Troop.XylvanianBazookaVet05, GetPlayerUnit(constant.PLAYER_ONE), constant.ORDER_NORMAL)
      AttackTarget(Troop.XylvanianBazookaVet06, GetPlayerUnit(constant.PLAYER_ONE), constant.ORDER_NORMAL)
      repeat
        if playerinminezone == 0 or bryan == 0 then
          AttackTarget(Air_Vehicle.XylvanianGunship01, GetPlayerUnit(constant.PLAYER_ONE), constant.ORDER_NORMAL)
          WaitFor(90)
        else
          GoToArea(Air_Vehicle.XylvanianGunship01, 9, -138, 10, 0, constant.ORDER_FORCED)
          WaitFor(90)
        end
      until IsDead(Troop.TundranAntiAirVet01) and IsDead(Troop.TundranAntiAirVet02) and IsDead(Troop.TundranAntiAirVet03) and IsDead(Troop.TundranAntiAirVet04)
      break
    end
    EndFrame()
  end
end
