function CutScene02Skip(owner)
  repeat
    EndFrame()
  until cutscene02 == 1
  WaitFor(1)
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      cutsceneskip02 = 1
      DebugOut("Player 1 Killed CutScene02")
    end
    EndFrame()
  until cutsceneskip02 == 1 or cutscenefinished02 == 1
  ClearMessageQueue()
  Kill(cutsceneabort02)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CleanupSkipCutscene()
  StoreSummaryMessage(constant.PLAYER_ONE, 29, constant.ARMY_TUNDRAN, SpriteID.CO_T_Ghost_Gorgi_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 87, constant.ARMY_XYLVANIAN, SpriteID.CO_X_Prison_Ubel_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 88, constant.ARMY_TUNDRAN, SpriteID.CO_T_Ghost_Gorgi_Sad)
  SetCamera(Camera.Player1Cam)
  EndIntro()
  Spawn(Ground_Vehicle.XylvanianArtillery01)
  Spawn(Ground_Vehicle.XylvanianArtillery03)
  Spawn(Troop.XylvanianBazookaVet15)
  Spawn(Troop.XylvanianBazookaVet16)
  Spawn(Troop.XylvanianBazookaVet17)
  Spawn(Troop.XylvanianBazookaVet18)
  Spawn(Troop.XylvanianBazookaVet19)
  Spawn(Ground_Vehicle.XylvanianLightTank03)
  Spawn(Ground_Vehicle.XylvanianLightTank04)
  Spawn(Troop.XMausChainVet01)
  Spawn(Troop.XMausChainVet02)
  Spawn(Troop.XMausChainVet03)
  Spawn(Troop.XMausChainVet04)
  Spawn(Troop.XCounterMortarVet01)
  Spawn(Troop.XCounterMortarVet02)
  Spawn(Troop.XCounterMortarVet03)
  SetUnitInvulnerable(Destroyable_Object.Sandbag01, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag02, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag03, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag04, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag05, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag06, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag07, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag08, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag09, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag10, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag11, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag12, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag13, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag14, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag15, false)
  SetUnitInvulnerable(Destroyable_Object.Sandbag16, false)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  PauseTimerActive = 0
  SetInvulnerable(flag.TYPE_TUNDRAN, 0)
  SetInvulnerable(flag.TYPE_XYLVANIAN, 0)
  SetInvulnerable(flag.TYPE_WFRONTIER, 0)
  UnfreezePlayer(constant.PLAYER_ONE)
  SetTimer(180)
  ShowTimer(1)
  mausoleumobjective = 1
  DebugOut("*CutScene03Skip* - The player has successfully skipped cutscene 03")
  PhoneMessage(14, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
end
