function CutScene02(owner)
  cutsceneabort02 = owner
  repeat
    EndFrame()
  until cutscene01 == 1
  WaitFor(10)
  while missionend == 0 do
    if mausoleumobjective == 0 and 1 < NumItemsInArea(Map_Zone.TundranMausoleumObjectiveTriggerZone, flag.TYPE_TUNDRAN) then
      PauseTimerActive = 1
      FreezePlayer(constant.PLAYER_ONE)
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      Spawn(Troop.XylvanianBazookaVet15)
      Spawn(Troop.XylvanianBazookaVet16)
      Spawn(Troop.XylvanianBazookaVet17)
      Spawn(Troop.XylvanianBazookaVet18)
      Spawn(Troop.XylvanianBazookaVet19)
      Spawn(Ground_Vehicle.XylvanianLightTank03)
      Spawn(Ground_Vehicle.XylvanianLightTank04)
      Spawn(Building.XylvanianAATower06)
      Spawn(Building.XylvanianAATower07)
      Spawn(Building.XylvanianMGNest06)
      Spawn(Building.XylvanianMGNest07)
      Spawn(Building.Dynamite01)
      Spawn(Building.Dynamite02)
      Spawn(Building.Dynamite03)
      Spawn(Building.Dynamite04)
      Spawn(Building.Dynamite05)
      Spawn(Building.Dynamite06)
      Spawn(Building.Dynamite07)
      Spawn(Building.Dynamite08)
      Spawn(Building.Dynamite09)
      Spawn(Building.Dynamite10)
      Spawn(Building.Dynamite11)
      Spawn(Building.Dynamite12)
      Spawn(Building.Dynamite13)
      Spawn(Building.Dynamite14)
      Spawn(Building.Dynamite15)
      Spawn(Building.Dynamite16)
      Spawn(Capture_Point.Pillar01)
      Spawn(Capture_Point.Pillar02)
      Spawn(Capture_Point.Pillar03)
      Spawn(Capture_Point.Pillar04)
      Spawn(Building.Cable01)
      Spawn(Building.Cable02)
      Spawn(Building.Cable03)
      Spawn(Building.Cable04)
      Spawn(Building.Cable05)
      SetInvulnerable(flag.TYPE_TUNDRAN, 1)
      SetInvulnerable(flag.TYPE_XYLVANIAN, 1)
      SetInvulnerable(flag.TYPE_WFRONTIER, 1)
      SetObjectiveData(Objective_Marker.MausoleumPillarObjectiveMarker01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.MausoleumPillarObjectiveMarker02, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.MausoleumPillarObjectiveMarker03, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      SetObjectiveData(Objective_Marker.MausoleumPillarObjectiveMarker04, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
      SetObjectiveData(Objective.TravelToTundranMausoleumObjective, constant.OBJECTIVE_DATA_VISIBLE, 0)
      SetObjectiveData(Objective_Marker.TundranMausoleumObjectiveMarker, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      SetObjectiveData(Objective.MausoleumPillarObjective00, constant.OBJECTIVE_DATA_VISIBLE, 1)
      ClearMessageQueue()
      GoToArea(Air_Vehicle.XylvanianGunship01, 593, 510, 10)
      GoToArea(Air_Vehicle.XylvanianGunship02, 593, 510, 10)
      SetCamera(Camera.DynamiteCutScene)
      CameraSetTarget(Camera.DynamiteCutScene, Waypoint.Entity330104306)
      CameraSetWaypoint(Camera.DynamiteCutScene, Waypoint.DynamiteCameraWaypoint)
      StartOutro()
      cutscene02 = 1
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      ClearMessageQueue()
      PhoneMessageWithObjective(29, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Sad, constant.PLAYER_ONE, false, constant.PRIMARY_OBJECTIVE_COMPLETE)
      PhoneMessage(87, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Prison_Ubel_Sad, constant.PLAYER_ONE)
      PhoneMessageWithObjective(88, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Ghost_Gorgi_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
      WaitFor(29)
      ClearMessageQueue()
      cutscenefinished02 = 1
      DebugOut("*CutScene02* - The player has triggered the Mausoleum objective")
      break
    end
    WaitFor(0.2)
    EndFrame()
  end
end
