function DespawnRespawnFPSOptimisations(owner)
  local FPS01 = 0
  local FPS02 = 0
  SetUnitInvulnerable(Destroyable_Object.Sandbag01, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag02, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag03, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag04, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag05, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag06, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag07, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag08, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag09, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag10, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag11, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag12, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag13, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag14, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag15, true)
  SetUnitInvulnerable(Destroyable_Object.Sandbag16, true)
  SetUnitInvulnerable(Building.TundranMausoleum, true)
  Despawn(Troop.CutScenePlayer)
  Despawn(Building.Dynamite01)
  Despawn(Building.Dynamite02)
  Despawn(Building.Dynamite03)
  Despawn(Building.Dynamite04)
  Despawn(Building.Dynamite05)
  Despawn(Building.Dynamite06)
  Despawn(Building.Dynamite07)
  Despawn(Building.Dynamite08)
  Despawn(Building.Dynamite09)
  Despawn(Building.Dynamite10)
  Despawn(Building.Dynamite11)
  Despawn(Building.Dynamite12)
  Despawn(Building.Dynamite13)
  Despawn(Building.Dynamite14)
  Despawn(Building.Dynamite15)
  Despawn(Building.Dynamite16)
  Despawn(Capture_Point.Pillar01)
  Despawn(Capture_Point.Pillar02)
  Despawn(Capture_Point.Pillar03)
  Despawn(Capture_Point.Pillar04)
  Despawn(Building.Cable01)
  Despawn(Building.Cable02)
  Despawn(Building.Cable03)
  Despawn(Building.Cable04)
  Despawn(Building.Cable05)
  SetActive(Troop.BurningGrunt01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.BurningGrunt02, constant.INACTIVE, constant.ADJUST_WEAPON)
  Despawn(Troop.XMausChainVet01, true)
  Despawn(Troop.XMausChainVet02, true)
  Despawn(Troop.XMausChainVet03, true)
  Despawn(Troop.XMausChainVet04, true)
  Despawn(Troop.XCounterMortarVet01, true)
  Despawn(Troop.XCounterMortarVet02, true)
  Despawn(Troop.XCounterMortarVet03, true)
  Despawn(Troop.TundranAntiAirVet01)
  Despawn(Troop.TundranAntiAirVet02)
  Despawn(Troop.TundranAntiAirVet03)
  Despawn(Troop.TundranAntiAirVet04)
  Despawn(Troop.TundranFlameVet02)
  Despawn(Troop.TundranFlameVet03)
  Despawn(Troop.TundranFlameVet04)
  Despawn(Troop.TundranGrunt01)
  Despawn(Troop.TundranGrunt02)
  Despawn(Troop.TundranGrunt04)
  Despawn(Troop.TundranGrunt05)
  Despawn(Ground_Vehicle.TundranArtillery01)
  Despawn(Ground_Vehicle.TundranArtillery02)
  Despawn(Air_Vehicle.HelipadChopper01)
  Despawn(Air_Vehicle.XAirTransport)
  Despawn(Air_Vehicle.XPOW2Transport01)
  Despawn(Air_Vehicle.XPOW2Transport02)
  Kill(Air_Vehicle.TundranGunship01)
  Kill(Air_Vehicle.TundranGunship02)
  Despawn(Troop.XylvanianBazookaVet01)
  Despawn(Troop.XylvanianBazookaVet02)
  Despawn(Troop.XylvanianBazookaVet03)
  Despawn(Troop.XylvanianGrunt01)
  Despawn(Troop.XylvanianGrunt02)
  Despawn(Troop.XylvanianGrunt03)
  Despawn(Troop.XylvanianGrunt04)
  Despawn(Troop.Entity330100783)
  Despawn(Troop.Entity330100784)
  Despawn(Troop.Entity330005604)
  Despawn(Troop.Entity330005605)
  Despawn(Troop.Entity330005606)
  Despawn(Troop.Entity330005607)
  Despawn(Troop.Entity330004369)
  Despawn(Troop.Entity330004368)
  Despawn(Morphing_Building.AirbaseGunTurret01, true)
  Despawn(Morphing_Building.AirbaseGunTurret02, true)
  Despawn(Troop.XylvanianGrunt12, true)
  Despawn(Troop.XylvanianGrunt13, true)
  Despawn(Troop.XylvanianGrunt14, true)
  Despawn(Troop.XylvanianGrunt15, true)
  Despawn(Troop.XylvanianGrunt16, true)
  Despawn(Troop.XylvanianBazookaVet10, true)
  Despawn(Troop.XylvanianBazookaVet11, true)
  Despawn(Troop.XylvanianBazookaVet12, true)
  Despawn(Troop.XylvanianBazookaVet13, true)
  Despawn(Troop.XylvanianBazookaVet14, true)
  Despawn(Troop.XylvanianChainVet05, true)
  Despawn(Troop.XylvanianChainVet06, true)
  Despawn(Troop.XylvanianChainVet07, true)
  Despawn(Troop.XylvanianChainVet08, true)
  Despawn(Troop.XylvanianChainVet09, true)
  Despawn(Morphing_Building.FactoryGunTurret01, true)
  Despawn(Morphing_Building.FactoryGunTurret02, true)
  Despawn(Morphing_Building.FactoryGunTurret03, true)
  Despawn(Morphing_Building.FactoryGunTurret04, true)
  SetUnitInvulnerable(Building.POW01AmmoDump01, true)
  SetActive(Building.POW01AmmoDump01, constant.INACTIVE)
  Despawn(Troop.XylvanianBazookaVet05, true)
  Despawn(Troop.XylvanianBazookaVet06, true)
  Despawn(Troop.XylvanianBazookaVet07, true)
  Despawn(Troop.XylvanianBazookaVet08, true)
  Despawn(Troop.XylvanianBazookaVet09, true)
  Despawn(Building.XylvanianRPGTower04, true)
  Despawn(Building.XylvanianRPGTower03, true)
  Despawn(Building.XylvanianAATower01, true)
  Despawn(Building.XylvanianAATower02, true)
  Despawn(Ground_Vehicle.XylvanianLightTank05, true)
  Despawn(Ground_Vehicle.XylvanianLightTank06, true)
  Despawn(Troop.XylvanianChainVet01, true)
  Despawn(Troop.XylvanianChainVet02, true)
  Despawn(Troop.XylvanianChainVet03, true)
  Despawn(Troop.XylvanianChainVet04, true)
  Despawn(Troop.XylvanianBazookaVet20, true)
  Despawn(Troop.XylvanianBazookaVet21, true)
  Despawn(Troop.XylvanianBazookaVet22, true)
  Despawn(Troop.XylvanianBazookaVet23, true)
  Despawn(Troop.XylvanianBazookaVet24, true)
  Despawn(Troop.XylvanianBazookaVet25, true)
  Despawn(Troop.XylvanianBazookaVet26, true)
  Despawn(Building.XylvanianMGNest01, true)
  Despawn(Building.XylvanianMGNest05, true)
  Despawn(Troop.WesternFrontierGrunt01, true)
  Despawn(Troop.WesternFrontierGrunt02, true)
  Despawn(Troop.WesternFrontierGrunt03, true)
  Despawn(Troop.WesternFrontierGrunt04, true)
  Despawn(Troop.WesternFrontierGrunt05, true)
  Despawn(Troop.WesternFrontierGrunt06, true)
  DebugOut("*DESPAWN BS* - despawned all units in level")
  local airbasecounterrespawn = 0
  local powcamprespawn = 0
  local helipadrespawn = 0
  local factoryrespawn = 0
  local bazookacounterrespawn = 0
  local windingroadrespawn = 0
  local wfrespawn = 0
  repeat
    EndFrame()
  until cutscene01 == 1
  while missionend == 0 do
    if airbasecounterrespawn == 0 and 0 < NumItemsInArea(Map_Zone.AirbaseCounterMapZone, flag.TYPE_TUNDRAN) then
      Spawn(Ground_Vehicle.XylvanianLightTank01)
      Spawn(Ground_Vehicle.XylvanianLightTank02)
      Spawn(Troop.XylvanianGrunt07)
      Spawn(Troop.XylvanianGrunt08)
      Spawn(Troop.XylvanianGrunt09)
      Spawn(Troop.XylvanianGrunt10)
      DebugOut("*RESPAWN BS* - Player has spawned the AIRBASE counter troops")
      airbasecounterrespawn = 1
    end
    EndFrame()
    if powcamprespawn == 0 and 0 < NumItemsInArea(Map_Zone.PowCampRespawnZone, flag.TYPE_TUNDRAN) then
      Spawn(Troop.XylvanianBazookaVet05)
      Spawn(Troop.XylvanianBazookaVet06)
      Spawn(Troop.XylvanianBazookaVet07)
      Spawn(Troop.XylvanianBazookaVet08)
      Spawn(Troop.XylvanianBazookaVet09)
      Spawn(Building.XylvanianRPGTower04)
      Spawn(Building.XylvanianRPGTower03)
      Spawn(Building.XylvanianAATower01)
      Spawn(Building.XylvanianAATower02)
      EndFrame()
      Spawn(Troop.TundranBazookaVet01)
      Spawn(Troop.TundranBazookaVet02)
      Spawn(Troop.TundranBazookaVet03)
      Spawn(Troop.TundranBazookaVet04)
      Spawn(Troop.TundranBazookaVet05)
      Spawn(Troop.TundranBazookaVet06)
      Spawn(Ground_Vehicle.XylvanianLightTank05)
      Spawn(Ground_Vehicle.XylvanianLightTank06)
      SetUnitInvulnerable(Building.POW01AmmoDump01, false)
      SetActive(Building.POW01AmmoDump01, constant.ACTIVE)
      DebugOut("*RESPAWN BS* - Player has spawned the POWs and enemy POW TROOPS")
      powcamprespawn = 1
    end
    EndFrame()
    if bazookacounterrespawn == 0 and 0 < NumItemsInArea(Map_Zone.BazookaCounterRespawnZone, flag.TYPE_TUNDRAN) then
      Spawn(Troop.XylvanianGrunt12)
      Spawn(Troop.XylvanianGrunt13)
      Spawn(Troop.XylvanianGrunt14)
      Spawn(Troop.XylvanianGrunt15)
      Spawn(Troop.XylvanianGrunt16)
      Spawn(Troop.XylvanianBazookaVet10)
      Spawn(Troop.XylvanianBazookaVet11)
      Spawn(Troop.XylvanianBazookaVet12)
      Spawn(Troop.XylvanianBazookaVet13)
      Spawn(Troop.XylvanianBazookaVet14)
      DebugOut("*RESPAWN BS* - Player has spawned the FACTORY COUNTER TROOPS")
      bazookacounterrespawn = 1
    end
    EndFrame()
    if factoryrespawn == 0 and 0 < NumItemsInArea(Map_Zone.FactoryRespawn, flag.TYPE_TUNDRAN) then
      Spawn(Troop.XylvanianChainVet05)
      Spawn(Troop.XylvanianChainVet06)
      Spawn(Troop.XylvanianChainVet07)
      Spawn(Troop.XylvanianChainVet08)
      Spawn(Troop.XylvanianChainVet09)
      Spawn(Morphing_Building.FactoryGunTurret01)
      Spawn(Morphing_Building.FactoryGunTurret02)
      Spawn(Morphing_Building.FactoryGunTurret03)
      Spawn(Morphing_Building.FactoryGunTurret04)
      EndFrame()
      Spawn(Troop.XylvanianGrunt12)
      Spawn(Troop.XylvanianGrunt13)
      Spawn(Troop.XylvanianGrunt14)
      Spawn(Troop.XylvanianGrunt15)
      Spawn(Troop.XylvanianGrunt16)
      Spawn(Troop.XylvanianBazookaVet10)
      Spawn(Troop.XylvanianBazookaVet11)
      Spawn(Troop.XylvanianBazookaVet12)
      Spawn(Troop.XylvanianBazookaVet13)
      Spawn(Troop.XylvanianBazookaVet14)
      DebugOut("*RESPAWN BS* - Player has spawned the enemy units at the FACTORY")
      factoryrespawn = 1
    end
    EndFrame()
    if windingroadrespawn == 0 and 0 < NumItemsInArea(Map_Zone.WindingRoadRespawnZone, flag.TYPE_TUNDRAN) then
      Spawn(Troop.XylvanianChainVet01)
      Spawn(Troop.XylvanianChainVet02)
      Spawn(Troop.XylvanianChainVet03)
      Spawn(Troop.XylvanianChainVet04)
      Spawn(Troop.XylvanianBazookaVet20)
      Spawn(Troop.XylvanianBazookaVet21)
      Spawn(Troop.XylvanianBazookaVet22)
      Spawn(Troop.XylvanianBazookaVet23)
      Spawn(Troop.XylvanianBazookaVet24)
      Spawn(Troop.XylvanianBazookaVet25)
      Spawn(Troop.XylvanianBazookaVet26)
      Spawn(Building.XylvanianMGNest01)
      Spawn(Building.XylvanianMGNest05)
      DebugOut("*RESPAWN BS* - Player has spawned the enemy units at the WINDING ROAD")
      windingroadrespawn = 1
    end
    EndFrame()
    if helipadrespawn == 0 and 0 < NumItemsInArea(Map_Zone.HelipadRespawnZone, flag.TYPE_TUNDRAN) then
      Spawn(Building.XylvanianMGTower01)
      Spawn(Building.XylvanianMGTower02)
      Spawn(Building.XylvanianAATower03)
      Spawn(Building.XylvanianAATower04)
      DebugOut("*RESPAWN BS* - Player has spawned 4 enemy towers at the HELIPAD")
      helipadrespawn = 1
    end
    if wfrespawn == 0 and 0 < NumItemsInArea(Map_Zone.SavedBryan, flag.TYPE_TUNDRAN) then
      Spawn(Troop.WesternFrontierGrunt01)
      Spawn(Troop.WesternFrontierGrunt02)
      Spawn(Troop.WesternFrontierGrunt03)
      Spawn(Troop.WesternFrontierGrunt04)
      Spawn(Troop.WesternFrontierGrunt05)
      Spawn(Troop.WesternFrontierGrunt06)
      Spawn(Troop.WesternFrontierMortarVet01)
      Spawn(Troop.WesternFrontierMortarVet02)
      Spawn(Troop.WesternFrontierMortarVet03)
      Spawn(Troop.WesternFrontierMortarVet04)
      Spawn(Troop.WesternFrontierMortarVet05)
      wfrespawn = 1
    end
    EndFrame()
    if FPS01 == 0 then
      WaitFor(0.2)
      if IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.FactoryRespawn) or IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.SavedBryan) then
        SetUnitShadowDistance(10)
        SetCharacterAnimUpdateLOD(true)
        FPS01 = 1
        DebugOut("Starting WF FPS optimisations")
      end
    end
    EndFrame()
    if FPS01 == 1 then
      WaitFor(0.2)
      if IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.FactoryRespawn) == false and IsInArea(GetPlayerUnit(constant.PLAYER_ONE), Map_Zone.SavedBryan) == false then
        SetUnitShadowDistance(75)
        SetCharacterAnimUpdateLOD(false)
        FPS01 = 0
        DebugOut("Ending WF FPS optimisations")
      end
    end
    if FPS02 == 0 then
      WaitFor(0.2)
      if 1 < NumItemsInArea(Map_Zone.TundranMausoleumObjectiveTriggerZone, flag.TYPE_TUNDRAN) then
        SetUnitShadowDistance(10)
        FPS02 = 1
        DebugOut("Starting Mausoleum FPS optimisations")
      end
    end
    EndFrame()
    if FPS02 == 1 then
      WaitFor(0.2)
      if NumItemsInArea(Map_Zone.TundranMausoleumObjectiveTriggerZone, flag.TYPE_TUNDRAN) < 2 then
        SetUnitShadowDistance(75)
        FPS02 = 0
        DebugOut("Ending Mausoleum FPS optimisations")
      end
    end
    EndFrame()
  end
end
