function Their_Finest_Hour_Cutscene_End(owner)
  CutsceneEnd = owner
  EnableWeapon(Air_Vehicle.AI_Fighter02_Cutscene, 0)
  EnableWeapon(Air_Vehicle.AI_Fighter03_Cutscene, 0)
  EnableWeapon(Air_Vehicle.AI_Bomber02_Cutscene, 0)
  EnableWeapon(Air_Vehicle.AI_Bomber03_Cutscene, 0)
  Despawn(Air_Vehicle.AI_Fighter02_Cutscene)
  Despawn(Air_Vehicle.AI_Fighter03_Cutscene)
  Despawn(Air_Vehicle.AI_Bomber02_Cutscene)
  Despawn(Air_Vehicle.AI_Bomber03_Cutscene)
  Despawn(Air_Vehicle.SE_Finale_Fighter01)
  Despawn(Air_Vehicle.SE_Finale_Fighter02)
  Despawn(Air_Vehicle.SE_Finale_Fighter03)
  Despawn(Air_Vehicle.SE_Finale_Fighter04)
  Despawn(Air_Vehicle.SE_Finale_Fighter05)
  Despawn(Air_Vehicle.SE_Finale_Gunship01)
  Despawn(Air_Vehicle.SE_Finale_Gunship02)
  Despawn(Air_Vehicle.SE_Finale_AirTransport01)
  Despawn(Air_Vehicle.SE_Finale_AirTransport02)
  Despawn(Air_Vehicle.AI_Finale_Bomber01)
  Despawn(Air_Vehicle.AI_Finale_Bomber02)
  Despawn(Air_Vehicle.AI_Finale_Fighter01)
  Despawn(Air_Vehicle.AI_Finale_Fighter02)
  Despawn(Air_Vehicle.AI_Finale_Fighter03)
  Despawn(Air_Vehicle.AI_Finale_Fighter04)
  Despawn(Air_Vehicle.AI_Finale_Fighter05)
  Despawn(Air_Vehicle.AI_Finale_Fighter06)
  Despawn(Air_Vehicle.AI_Finale_Fighter07)
  Despawn(Air_Vehicle.AI_Finale_Fighter08)
  Despawn(Air_Vehicle.AI_Finale_Fighter09)
  Despawn(Air_Vehicle.AI_Finale_Fighter10)
  repeat
    EndFrame()
  until CutsceneEndReady == 1 and AirTransportCutsceneActive == 0
  AirTransportCutsceneActive = 1
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetInvulnerable(flag.TYPE_ANGLO, 1)
  StopScoringTimer()
  FreezePlayer(constant.PLAYER_ONE)
  StartOutro()
  SetCamera(Camera.CutsceneCam1)
  CameraSetTarget(Camera.CutsceneCam1, Waypoint.CutsceneCamEndShot01Target)
  CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.CutsceneCamEndShot01Spline)
  CameraSetFOV(Camera.CutsceneCam1, 55, constant.IMMEDIATE, 0, constant.NO_WAIT)
  Kill(KillFinale)
  Kill(AirRespawner)
  Kill(KillAIRespawnBombers)
  Kill(KillAIRespawnFighters)
  Kill(CutsceneAbort)
  Kill(Cutscene02)
  Kill(Cutscene02Abort)
  Kill(CutsceneHelipad)
  Kill(CutsceneHelipadAbort)
  Kill(CutscenePOW02)
  Kill(CutscenePOW02Abort)
  Kill(AttackWave01)
  Spawn(Troop.CUTSCENE)
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.CUTSCENE, true)
  Spawn(Air_Vehicle.AI_Fighter02_Cutscene)
  Spawn(Air_Vehicle.AI_Bomber01_Cutscene)
  Spawn(Air_Vehicle.AI_Bomber02_Cutscene)
  Spawn(Air_Vehicle.AI_Bomber03_Cutscene)
  Teleport(Air_Vehicle.AI_Bomber01_Cutscene, GetObjectXPosition(Waypoint.EndCutsceneShot01Bomber01), GetObjectZPosition(Waypoint.EndCutsceneShot01Bomber01), 180)
  GoToArea(Air_Vehicle.AI_Fighter02, GetObjectXPosition(Waypoint.EndCutsceneShot01Bomber01), GetObjectZPosition(Waypoint.EndCutsceneShot01Bomber01), 0, constant.ORDER_FORCED)
  FollowWaypoint(Air_Vehicle.AI_Bomber02, Waypoint.EndCutsceneShot01Bomber02, 1, 1, constant.ORDER_FORCED)
  if IsDead(Air_Vehicle.SE_Respawner_Fighter01) == false then
    Spawn(Air_Vehicle.SE_Respawner_Fighter01)
    Kill(Air_Vehicle.SE_Respawner_Fighter01)
  end
  if IsDead(Air_Vehicle.SE_Respawner_Gunship01) == false then
    Spawn(Air_Vehicle.SE_Respawner_Gunship01)
    Kill(Air_Vehicle.SE_Respawner_Gunship01)
  end
  if IsDead(Air_Vehicle.SE_Gunship04) == false then
    Spawn(Air_Vehicle.SE_Gunship04)
    Kill(Air_Vehicle.SE_Gunship04)
  end
  Despawn(Air_Vehicle.SE_Gunship_Barracks01)
  Despawn(Air_Vehicle.SE_Gunship_Barracks02)
  Despawn(Air_Vehicle.SE_Gunship_Factory01)
  Despawn(Air_Vehicle.SE_Gunship_Factory02)
  Despawn(Air_Vehicle.SE_Gunship01)
  Despawn(Air_Vehicle.SE_Gunship02)
  Despawn(Air_Vehicle.SE_Gunship03)
  Despawn(Air_Vehicle.SE_Gunship05)
  Despawn(Air_Vehicle.SE_Gunship06)
  Despawn(Building.SE_AATower01)
  Despawn(Building.SE_AATower02)
  Despawn(Troop.Entity280010923)
  Despawn(Troop.Entity280010925)
  Despawn(Ground_Vehicle.SE_Airbase01_LightTank01)
  Despawn(Ground_Vehicle.SE_Airbase01_LightTank02)
  Despawn(Air_Vehicle.AI_Bomber01)
  Despawn(Air_Vehicle.AI_Bomber02)
  Despawn(Air_Vehicle.AI_Fighter01)
  Despawn(Air_Vehicle.AI_Fighter02)
  Despawn(Air_Vehicle.AI_Fighter03)
  Despawn(Ground_Vehicle.AI_HeavyTank01)
  Despawn(Troop.AI_AntiArmour01)
  Despawn(Troop.AI_AntiArmour02)
  Despawn(Troop.AI_AntiArmour03)
  Despawn(Troop.AI_AntiArmour04)
  Despawn(Troop.AI_AntiArmour05)
  Despawn(Troop.AI_Grunt01)
  Despawn(Troop.AI_Grunt02)
  Despawn(Troop.AI_Grunt03)
  Despawn(Troop.AI_Grunt04)
  Despawn(Troop.AI_Grunt05)
  Despawn(Troop.AI_Grunt06)
  Despawn(Troop.AI_Grunt07)
  Despawn(Troop.AI_Grunt08)
  Despawn(Troop.AI_Grunt09)
  Despawn(Troop.AI_Grunt10)
  Despawn(Troop.AI_Hose01)
  Despawn(Troop.AI_Hose02)
  Despawn(Troop.AI_Hose03)
  Despawn(Troop.AI_Hose04)
  Despawn(Troop.AI_Hose05)
  Despawn(Air_Vehicle.SE_Gunship01)
  Despawn(Troop.SE_Gunship01_Pilot01)
  Despawn(Air_Vehicle.SE_Gunship02)
  Despawn(Troop.SE_Gunship02_Pilot01)
  Despawn(Air_Vehicle.SE_Gunship03)
  Despawn(Troop.SE_Gunship03_Pilot01)
  Despawn(Air_Vehicle.SE_Gunship04)
  Despawn(Troop.SE_Gunship04_Pilot01)
  Despawn(Air_Vehicle.SE_Gunship05)
  Despawn(Troop.SE_Gunship05_Pilot01)
  Despawn(Air_Vehicle.SE_Gunship06)
  Despawn(Troop.SE_Gunship06_Pilot01)
  Despawn(Ground_Vehicle.SE_AttackWaveArmour_LightTank01)
  Despawn(Troop.SE_AttackWaveArmour_LightTank01_Pilot01)
  Despawn(Ground_Vehicle.SE_AttackWaveArmour_LightTank02)
  Despawn(Troop.SE_AttackWaveArmour_LightTank02_Pilot01)
  Despawn(Air_Vehicle.SE_AttackWaveGrunts_AirTransport01)
  Despawn(Air_Vehicle.SE_AttackWaveGrunts_AirTransport02)
  Despawn(Troop.SE_AttackWaveGrunts_AirTransport01_Pilot01)
  Despawn(Troop.SE_AttackWaveGrunts_AirTransport02_Pilot01)
  Despawn(Air_Vehicle.SE_AttackWaveArmour_AirTransport01)
  Despawn(Air_Vehicle.SE_AttackWaveArmour_AirTransport02)
  Despawn(Troop.SE_AttackWaveArmour_AirTransport01_Pilot01)
  Despawn(Troop.SE_AttackWaveArmour_AirTransport02_Pilot01)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt01)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt02)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt03)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt04)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt05)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt06)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt07)
  Despawn(Troop.SE_AttackWaveGrunts_Grunt08)
  Despawn(Air_Vehicle.SE_Fighter01)
  Despawn(Troop.SE_Fighter01_Pilot01)
  Despawn(Air_Vehicle.SE_Fighter02)
  Despawn(Troop.SE_Fighter02_Pilot01)
  Despawn(Air_Vehicle.SE_AttackWaveArmour_AirTransport01)
  Despawn(Ground_Vehicle.SE_AttackWaveArmour_LightTank01)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(1)
  CutsceneEndBegun = 1
  ClearMessageQueue()
  PhoneMessage(82, constant.ID_NONE, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_ONE)
  WaitFor(2)
  Spawn(Air_Vehicle.AI_Fighter03_Cutscene)
  FollowWaypoint(Air_Vehicle.AI_Fighter03, Waypoint.EndCutsceneShot01Fighter03, 1, 1, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Spawn(Air_Vehicle.SE_Finale_Fighter01)
  Spawn(Air_Vehicle.SE_Finale_Fighter02)
  Spawn(Air_Vehicle.SE_Finale_Fighter03)
  Spawn(Air_Vehicle.SE_Finale_Fighter04)
  Spawn(Air_Vehicle.SE_Finale_Fighter05)
  Spawn(Air_Vehicle.SE_Finale_Gunship01)
  Spawn(Air_Vehicle.SE_Finale_Gunship02)
  Spawn(Air_Vehicle.SE_Finale_AirTransport01)
  Spawn(Air_Vehicle.SE_Finale_AirTransport02)
  Spawn(Air_Vehicle.AI_Finale_Bomber01)
  Spawn(Air_Vehicle.AI_Finale_Bomber02)
  Spawn(Air_Vehicle.AI_Finale_Fighter01)
  Spawn(Air_Vehicle.AI_Finale_Fighter02)
  Spawn(Air_Vehicle.AI_Finale_Fighter03)
  Spawn(Air_Vehicle.AI_Finale_Fighter04)
  Spawn(Air_Vehicle.AI_Finale_Fighter05)
  Spawn(Air_Vehicle.AI_Finale_Fighter06)
  Spawn(Air_Vehicle.AI_Finale_Fighter07)
  Spawn(Air_Vehicle.AI_Finale_Fighter08)
  Spawn(Air_Vehicle.AI_Finale_Fighter09)
  Spawn(Air_Vehicle.AI_Finale_Fighter10)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter01, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter02, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter03, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter04, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter05, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter06, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter07, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter08, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter09, 0)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter10, 0)
  CameraSetTarget(Camera.CutsceneCam1, Waypoint.CutsceneCamEndShot02Target)
  CameraSetWaypoint(Camera.CutsceneCam1, Waypoint.CutsceneCamEndShot02Spline)
  CameraSetFOV(Camera.CutsceneCam1, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(83, constant.ID_NONE, constant.ARMY_ANGLO, 6, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_ONE)
  PhoneMessage(84, constant.ID_NONE, constant.ARMY_SOLAR, 6, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  WaitFor(7)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter01, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter02, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter03, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter04, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter05, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter06, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter07, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter08, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter09, 1)
  EnableWeapon(Air_Vehicle.AI_Finale_Fighter10, 1)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CutsceneEndFinished = 1
end
