function C1M6_Cutscene(owner)
  cutsceneStart = owner
  DebugOut("Cutscene Start ID", cutsceneStart)
  FreezePlayer()
  StartIntro()
  SetCamera(Camera.Cutscene0001)
  CameraSetWaypoint(Camera.Cutscene0001, Waypoint.Entity0303)
  CameraSetTarget(Camera.Cutscene0001, Waypoint.Entity0306)
  PhoneMessage(40, constant.ID_NONE, 0, 5, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(41, constant.ID_NONE, 0, 9, SpriteID.CO_WF_Herman_Happy)
  WaitFor(14)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0004)
  CameraSetWaypoint(Camera.Cutscene0004, Waypoint.Entity0288)
  CameraSetTarget(Camera.Cutscene0004, Air_Vehicle.Tgunship0001)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(42, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Herman_Happy)
  WaitFor(9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0002)
  CameraSetWaypoint(Camera.Cutscene0002, Waypoint.Entity0174)
  CameraSetTarget(Camera.Cutscene0002, Waypoint.CutsceneTarget0002)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(44, constant.ID_NONE, 2, 6, SpriteID.CO_T_Nova_Happy)
  WaitFor(7)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene0003)
  CameraSetWaypoint(Camera.Cutscene0003, Waypoint.Entity0309)
  CameraSetTarget(Camera.Cutscene0003, Waypoint.Entity0315)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(45, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Herman_Happy)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Player0001)
  cutsceneStart = 1
  C1M1_Global_Variable = 1
  DebugOut("C1M1 Global Variable = ", C1M1_Global_Variable)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  UnfreezePlayer()
  StartScoringTimer()
  FollowWaypoint(Ground_Vehicle.TheavyTank0001, Waypoint.Entity0194, 5, 5, constant.ORDER_NORMAL)
  ClearMessageQueue()
  PhoneMessage(43, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(47, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(50, constant.ID_NONE, 0, 6, SpriteID.CO_WF_Herman_Happy)
  EndFrame()
  return
end
