function CutsceneOutroLostMission(owner)
  scriptCutsceneOutroLostMissionStart = owner
  repeat
    EndFrame()
  until CutsceneOutroLostMissionStart == 1
  local shaketimer = 0
  local reasongiven = 0
  FreezePlayer(constant.PLAYER_ONE)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  if assaultvets == 1 then
    Teleport(Troop.SolarAssault1, 183, 206, 270, 15)
    Teleport(Troop.SolarAssault2, 183, 206, 270, 15)
    Teleport(Troop.SolarAssault3, 183, 206, 270, 15)
    Teleport(Troop.SolarAssault4, 183, 206, 270, 15)
    Teleport(Troop.SolarAssault5, 183, 206, 270, 15)
  end
  Teleport(Troop.Grunt1, 183, 206, 270, 15)
  Teleport(Troop.Grunt2, 183, 206, 270, 15)
  Teleport(Troop.Grunt3, 183, 206, 270, 15)
  Teleport(Troop.Grunt4, 183, 206, 270, 15)
  Teleport(Troop.Grunt5, 183, 206, 270, 15)
  Teleport(Troop.Grunt6, 183, 206, 270, 15)
  Teleport(Troop.Grunt7, 183, 206, 270, 15)
  Teleport(Troop.Grunt8, 183, 206, 270, 15)
  Teleport(Troop.Grunt9, 183, 206, 270, 15)
  Teleport(Troop.Grunt10, 183, 206, 270, 15)
  Teleport(Ground_Vehicle.SolarLightTank, 183, 206, 270, 15)
  Teleport(Ground_Vehicle.SolarRecon, 183, 206, 270, 15)
  Teleport(Troop.Admiral, 183, 206, 270, 15)
  StartOutro()
  Spawn(Troop.CutsceneBazooka1)
  Spawn(Troop.CutsceneBazooka2)
  Spawn(Troop.TransferMonkey)
  ForceUnitTransfer(constant.PLAYER_ONE, Troop.TransferMonkey, true, true)
  Spawn(Water_Vehicle.CutsceneRow1Boat1)
  Spawn(Water_Vehicle.CutsceneRow1Boat2)
  Spawn(Water_Vehicle.CutsceneRow1Boat3)
  Spawn(Water_Vehicle.CutsceneRow1Boat4)
  Spawn(Water_Vehicle.CutsceneRow1Boat5)
  Spawn(Building.OuterIslandRocketsAnim)
  Despawn(Building.OuterIslandRockets)
  Despawn(Building.OuterIslandRocketsBomb)
  SetCamera(Camera.CutsceneCam, constant.PLAYER_ONE)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.RocketAnimWP1)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.RocketAnimSpline)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  if rocketsobjectivefailed == 1 then
    PhoneMessage(88, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
    reasongiven = 1
  end
  if lostalltroops == 1 then
    PhoneMessage(28, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  end
  if IsDead(Ground_Vehicle.SolarRecon) and dontneedrecon == 0 and reasongiven == 0 then
    PhoneMessage(47, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
    reasongiven = 1
  end
  if IsDead(Troop.Admiral) and gotrecon == 1 and reasongiven == 0 then
    PhoneMessage(24, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
    reasongiven = 1
  end
  WaitFor(1)
  CutsceneOutroLostMissionCanNowBeSkipped = 1
  WaitFor(2)
  DestroyablePlayAnim(Building.OuterIslandRocketsAnim, 1, 2)
  WaitFor(1.5)
  PlayEffect(Scripted_Effect.WMissileSiloLaunch, flag.SOUND, Building.OuterIslandRocketsAnim)
  CameraShake(Camera.CutsceneCam, 0.5)
  WaitFor(0.35)
  PlayEffect(Scripted_Effect.WMissileSiloLaunch, flag.SOUND, Building.OuterIslandRocketsAnim)
  CameraShake(Camera.CutsceneCam, 0.5)
  WaitFor(0.35)
  PlayEffect(Scripted_Effect.WMissileSiloLaunch, flag.SOUND, Building.OuterIslandRocketsAnim)
  CameraShake(Camera.CutsceneCam, 0.5)
  WaitFor(0.35)
  PlayEffect(Scripted_Effect.WMissileSiloLaunch, flag.SOUND, Building.OuterIslandRocketsAnim)
  CameraShake(Camera.CutsceneCam, 0.5)
  WaitFor(0.35)
  PlayEffect(Scripted_Effect.WMissileSiloLaunch, flag.SOUND, Building.OuterIslandRocketsAnim)
  CameraShake(Camera.CutsceneCam, 0.5)
  WaitFor(0.25)
  ClearMessageQueue()
  PhoneMessage(43, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Windsor_Happy, constant.PLAYER_ONE)
  WaitFor(5.5)
  FollowWaypoint(Water_Vehicle.CutsceneRow1Boat1, Waypoint.CutsceneRow1Boat1, -1, -1, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  FollowWaypoint(Water_Vehicle.CutsceneRow1Boat2, Waypoint.CutsceneRow1Boat2, -1, -1, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  FollowWaypoint(Water_Vehicle.CutsceneRow1Boat3, Waypoint.CutsceneRow1Boat3, -1, -1, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  FollowWaypoint(Water_Vehicle.CutsceneRow1Boat4, Waypoint.CutsceneRow1Boat4, -1, -1, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  FollowWaypoint(Water_Vehicle.CutsceneRow1Boat5, Waypoint.CutsceneRow1Boat5, -1, -1, constant.ORDER_FORCED, constant.FORMATION_DISALLOWED)
  WaitFor(2)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetViewDistanceAdjustment(600, 10)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.CutsceneBoatsTarget)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.CutsceneBoatsSpline)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(42, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  WaitFor(3.5)
  Spawn(Building.EvilRocket)
  Spawn(Building.EvilRocket2)
  Spawn(Building.EvilRocket3)
  Spawn(Building.EvilRocket4)
  Spawn(Building.EvilRocket5)
  AttackTarget(Building.EvilRocket, Water_Vehicle.CutsceneRow1Boat1, constant.ORDER_FORCED)
  AttackTarget(Building.EvilRocket2, Water_Vehicle.CutsceneRow1Boat2, constant.ORDER_FORCED)
  AttackTarget(Building.EvilRocket3, Water_Vehicle.CutsceneRow1Boat3, constant.ORDER_FORCED)
  AttackTarget(Building.EvilRocket4, Water_Vehicle.CutsceneRow1Boat4, constant.ORDER_FORCED)
  AttackTarget(Building.EvilRocket5, Water_Vehicle.CutsceneRow1Boat5, constant.ORDER_FORCED)
  WaitFor(0.75)
  Kill(Destroyable_Object.Nuke)
  Kill(Water_Vehicle.CutsceneRow1Boat5)
  WaitFor(1)
  PlayEffect(Scripted_Effect.DEAtomic, flag.SOUND, Building.NukeAudio)
  CameraShake(Camera.CutsceneCam, 0.1)
  WaitFor(0.1)
  CameraShake(Camera.CutsceneCam, 0.2)
  WaitFor(0.1)
  CameraShake(Camera.CutsceneCam, 0.3)
  WaitFor(0.1)
  CameraShake(Camera.CutsceneCam, 0.4)
  WaitFor(0.1)
  CameraShake(Camera.CutsceneCam, 0.5)
  shaketimer = GetTime()
  Despawn(Water_Vehicle.CutsceneRow1Boat1)
  Despawn(Water_Vehicle.CutsceneRow1Boat2)
  Despawn(Water_Vehicle.CutsceneRow1Boat3)
  Despawn(Water_Vehicle.CutsceneRow1Boat4)
  Despawn(Water_Vehicle.CutsceneRow1Boat5)
  while GetTime() < shaketimer + 0.5 do
    WaitFor(0.05)
    CameraShake(Camera.CutsceneCam, 0.5)
    EndFrame()
  end
  EndOutro()
  DeclareVictory(constant.ARMY_XYLVANIAN)
  CutsceneOutroLostMissionFinished = 1
end
