function DespawnUnits(owner)
  SetActive(Capture_Point.HQ, constant.INACTIVE)
  SetActive(Morphing_Building.HQ, constant.INACTIVE)
  Despawn(Air_Vehicle.SolarAssaultChopper)
  Despawn(Air_Vehicle.SolarReconChopper)
  Despawn(Air_Vehicle.ExtractionChopper)
  Despawn(Water_Vehicle.SolarBattleship)
  Despawn(Troop.CutsceneGrunt1)
  Despawn(Troop.CutsceneGrunt2)
  Despawn(Troop.CutsceneGrunt3)
  Despawn(Troop.CutsceneGrunt4)
  Despawn(Troop.CutsceneGrunt5)
  Despawn(Troop.CutsceneVet1)
  Despawn(Troop.CutsceneVet2)
  Despawn(Troop.CutsceneVet3)
  Despawn(Troop.CutsceneVet4)
  Despawn(Ground_Vehicle.CutsceneTank)
  Despawn(Troop.CutsceneTankDriver)
  Despawn(Water_Vehicle.CutsceneRow1Boat1)
  Despawn(Water_Vehicle.CutsceneRow1Boat2)
  Despawn(Water_Vehicle.CutsceneRow1Boat3)
  Despawn(Water_Vehicle.CutsceneRow1Boat4)
  Despawn(Water_Vehicle.CutsceneRow1Boat5)
  SetUnitInvulnerable(Building.TopHillRockets, true)
  SetUnitInvulnerable(Building.OuterIslandRockets, true)
  SetUnitInvulnerable(Building.RuinsRockets, true)
  SetUnitInvulnerable(Building.DestroyableWall, true)
  SetUnitInvulnerable(Building.DropOffPortcullis, true)
  SetUnitInvulnerable(Troop.Admiral, true)
  SetUnitInvulnerable(Air_Vehicle.SolarAssaultChopper, true)
  SetUnitInvulnerable(Building.Portcullis1, true)
  SetUnitInvulnerable(Building.Portcullis2, true)
  Despawn(Ground_Vehicle.AngloLightTank1, true)
  Despawn(Ground_Vehicle.AngloLightTank2, true)
  Despawn(Ground_Vehicle.AngloLightTank3, true)
  Despawn(Ground_Vehicle.AngloLightTank4, true)
  Despawn(Building.GunTower1, true)
  Despawn(Building.GunTower2, true)
  Despawn(Building.RPGTower1, true)
  Despawn(Building.RPGTower2, true)
  Despawn(Building.RPGTower3, true)
  Despawn(Building.RPGTower4, true)
  Despawn(Troop.MainBasePatroller1, true)
  Despawn(Troop.MainBasePatroller2, true)
  Despawn(Troop.AngryAnglo1, true)
  Despawn(Troop.AngryAnglo2, true)
  Despawn(Troop.AngryAnglo3, true)
  Despawn(Troop.AngryAnglo4, true)
  Despawn(Troop.AngryAnglo5, true)
  AddToGroup(Unit_Group.PlayerControlledUnits, Ground_Vehicle.SolarLightTank)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt1)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt2)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt3)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt4)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt5)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt6)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt7)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt8)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt9)
  AddToGroup(Unit_Group.PlayerControlledUnits, Troop.Grunt10)
  AddToGroup(Unit_Group.Player_Army, Ground_Vehicle.SolarLightTank)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt1)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt2)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt3)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt4)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt5)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt6)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt7)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt8)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt9)
  AddToGroup(Unit_Group.Player_Army, Troop.Grunt10)
  DebugOut("Despawned base units")
  repeat
    WaitFor(0.5)
    EndFrame()
  until IsInRange(Unit_Group.PlayerControlledUnits, Objective_Marker.HQ, 275)
  DebugOut("Player in range of main base, spawning base units")
  Spawn(Ground_Vehicle.AngloLightTank1)
  Spawn(Ground_Vehicle.AngloLightTank2)
  Spawn(Ground_Vehicle.AngloLightTank3)
  Spawn(Ground_Vehicle.AngloLightTank4)
  Spawn(Building.GunTower1)
  Spawn(Building.GunTower2)
  Spawn(Building.RPGTower1)
  Spawn(Building.RPGTower2)
  Spawn(Building.RPGTower3)
  Spawn(Building.RPGTower4)
end
