function Functions(owner)
  function KillScripts()
    Kill(scriptAdmiralPOWCamp)
    Kill(scriptAngloBazookaChopper)
    Kill(scriptAngloRuinsReinforcements)
    Kill(scriptCountRockets)
    Kill(scriptCutsceneIntro)
    Kill(scriptCutsceneIntroAbort)
    Kill(scriptCutsceneMidtroBattleship)
    Kill(scriptCutsceneSolarReconReinforcements)
    Kill(scriptMainBaseAttack)
    Kill(scriptMessages)
    Kill(scriptRaceTrackObjectives)
    Kill(scriptRocketObjectives)
    Kill(scriptCutsceneSolarAssaultReinforcements)
    Kill(scriptTriggerAttacks)
    Kill(scriptCutsceneSolarAssaultReinforcementsAbort)
    Kill(scriptCutsceneMunitionsExpert)
    Kill(scriptCutsceneMunitionsExpertAbort)
    Kill(scriptCutsceneMunitionsExpertSilo2)
    Kill(scriptCutsceneMunitionsExpertSilo2Abort)
    Kill(scriptCutsceneMunitionsExpertSilo3)
    Kill(scriptCutsceneMunitionsExpertSilo3Abort)
  end
end
