function Intro_Cutscene(owner)
  cutkiller = owner
  CameraSetFOV(Camera.first, 6.5, constant.IMMEDIATE, 5, constant.NO_WAIT)
  WaitFor(1.5)
  PhoneMessage(0, constant.ID_NONE, 0, 7, SpriteID.CO_WF_Betty_Sad)
  WaitFor(3)
  CameraSetFOV(Camera.first, 60, constant.SMOOTH, 6.5, constant.NO_WAIT)
  WaitFor(7.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.second)
  CameraSetFOV(Camera.second, 75, constant.IMMEDIATE, 5, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  CameraSetFOV(Camera.second, 60, constant.SMOOTH, 1, constant.NO_WAIT)
  WaitFor(1)
  PhoneMessage(1, constant.ID_NONE, 2, 6, SpriteID.CO_T_Nova_Happy)
  WaitFor(9.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.third)
  Teleport(Troop.baz2, -135, -220, 215, 5)
  Teleport(Troop.baz3, -130, -195, 215, 5)
  CameraSetFOV(Camera.third, 65, constant.IMMEDIATE, 5, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  GoToArea(Troop.baz2, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.baz3, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.cut1, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.cut2, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0200, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0203, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0204, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0199, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0205, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0267, -220, -320, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Entity0268, -220, -320, 5, 0, constant.ORDER_FORCED)
  WaitFor(0.5)
  PhoneMessage(2, constant.ID_NONE, 2, 7.5, SpriteID.CO_T_Nova_Sad)
  WaitFor(11)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.fourth)
  CameraSetFOV(Camera.fourth, 65, constant.IMMEDIATE, 5, constant.NO_WAIT)
  Spawn(Ground_Vehicle.Entity0012)
  FollowWaypoint(Unit_Group.wf, Waypoint.four, 0, 0, 20)
  FollowWaypoint(Ground_Vehicle.Entity0012, Waypoint.five, 0, 0, 20)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(1)
  PhoneMessage(3, constant.ID_NONE, 0, 5, SpriteID.CO_WF_Betty_Happy)
  WaitFor(6)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscene = 1
end
