function Purge_Gates(owner)
  Despawn(Building.NeutralMGNest01, true)
  Despawn(Building.NeutralMGNest04, true)
  Despawn(Troop.ILhose01, true)
  Despawn(Troop.ILhose02, true)
  repeat
    EndFrame()
  until cutscene01 >= 1
  Despawn(Ground_Vehicle.Stank04, true)
  Despawn(Ground_Vehicle.Stank05, true)
  Despawn(Ground_Vehicle.Stank06, true)
  Despawn(Ground_Vehicle.Stank07, true)
  Despawn(Ground_Vehicle.Stank08, true)
  Despawn(Ground_Vehicle.Stank09, true)
  Despawn(Troop.Sgrunt16, true)
  Despawn(Troop.Sgrunt17, true)
  Despawn(Troop.Sbazooka01, true)
  Despawn(Troop.Sbazooka02, true)
  Despawn(Troop.SolarBazooka01, true)
  Despawn(Troop.SolarHose03, true)
  Despawn(Troop.SolarBazooka02, true)
  Despawn(Troop.SolarGrunt04, true)
  Despawn(Troop.SolarGrunt06, true)
  Despawn(Troop.SolarHose02, true)
  Despawn(Building.SolarMGNest01, true)
  Despawn(Building.SolarMGNest02, true)
  Despawn(Building.SolarMGNest03, true)
  Despawn(Building.SolarMGNest04, true)
  Despawn(Building.SbazookaTower01, true)
  Despawn(Building.SbazookaTower02, true)
  Despawn(Building.SbazookaTower03, true)
  Despawn(Building.SbazookaTower04, true)
  Despawn(Building.Searchlight01, true)
  Despawn(Building.Searchlight02, true)
  Despawn(Building.Searchlight03, true)
  Despawn(Building.Searchlight04, true)
  Despawn(Building.Searchlight05, true)
  Despawn(Building.Searchlight06, true)
  Despawn(Building.Searchlight07, true)
  while true do
    if IsDead(Building.Winch01) and IsDead(Building.Winch02) and RightSecondGatesOpened == 0 then
      RightSecondGatesOpened = 1
      Kill(Building.Gates05)
      DestroyablePlayAnim(Building.Gates05, 1, 2)
      ResetPathBlocking(Building.Gates05)
    end
    if IsDead(Building.Winch03) and IsDead(Building.Winch04) and LeftSecondGatesOpened == 0 then
      LeftSecondGatesOpened = 1
      Kill(Building.Gates07)
      DestroyablePlayAnim(Building.Gates07, 1, 2)
      ResetPathBlocking(Building.Gates07)
    end
    if IsDead(Building.Winch05) and IsDead(Building.Winch06) and RightFirstGatesOpened == 0 then
      RightFirstGatesOpened = 1
      Kill(Building.Gates09)
      DestroyablePlayAnim(Building.Gates09, 1, 2)
      ResetPathBlocking(Building.Gates09)
    end
    if IsDead(Building.Winch07) and IsDead(Building.Winch08) and LeftFirstGatesOpened == 0 then
      LeftFirstGatesOpened = 1
      Kill(Building.Gates11)
      DestroyablePlayAnim(Building.Gates11, 1, 2)
      ResetPathBlocking(Building.Gates11)
    end
    if (RightSecondGatesOpened == 1 or LeftSecondGatesOpened == 1) and SpawnTanks == 0 then
      SpawnTanks = 1
      Spawn(Building.Pillbox01)
      Spawn(Building.Pillbox02)
      Spawn(Building.AAtower01)
      Spawn(Building.AAtower02)
      Spawn(Building.AAtower03)
      Spawn(Building.NeutralMGNest01)
      Spawn(Building.NeutralMGNest04)
      Spawn(Troop.ILhose01)
      Spawn(Troop.ILhose02)
      Spawn(Ground_Vehicle.Stank04)
      Spawn(Ground_Vehicle.Stank05)
      Spawn(Ground_Vehicle.Stank06)
      Spawn(Ground_Vehicle.Stank07)
      Spawn(Ground_Vehicle.Stank08)
      Spawn(Ground_Vehicle.Stank09)
      Spawn(Troop.Sgrunt16)
      Spawn(Troop.Sgrunt17)
      Spawn(Troop.Sbazooka01)
      Spawn(Troop.Sbazooka02)
      Spawn(Troop.SolarBazooka01)
      Spawn(Troop.SolarHose03)
      Spawn(Troop.SolarBazooka02)
      Spawn(Troop.SolarGrunt04)
      Spawn(Troop.SolarGrunt06)
      Spawn(Troop.SolarHose02)
      Spawn(Building.SolarMGNest01)
      Spawn(Building.SolarMGNest02)
      Spawn(Building.SolarMGNest03)
      Spawn(Building.SolarMGNest04)
      Spawn(Building.SbazookaTower01)
      Spawn(Building.SbazookaTower02)
      Spawn(Building.SbazookaTower03)
      Spawn(Building.SbazookaTower04)
      Spawn(Building.Searchlight01)
      Spawn(Building.Searchlight02)
      Spawn(Building.Searchlight03)
      WaitFor(0.5)
      Spawn(Pickup.HealthPack01)
      Spawn(Pickup.HealthPack02)
      Spawn(Pickup.HealthPack03)
      Spawn(Pickup.HealthPack04)
      Spawn(Pickup.HealthPack05)
      Spawn(Pickup.HealthPack06)
      Spawn(Pickup.HealthPack07)
      Spawn(Pickup.HealthPack08)
      Spawn(Pickup.HealthPack09)
      Spawn(Pickup.JerryCan01)
      Spawn(Pickup.JerryCan02)
      Spawn(Pickup.JerryCan03)
      Spawn(Pickup.JerryCan04)
      Spawn(Pickup.JerryCan05)
      Spawn(Pickup.JerryCan06)
      Spawn(Pickup.JerryCan07)
      Spawn(Pickup.JerryCan08)
      Spawn(Pickup.JerryCan09)
    end
    EndFrame()
  end
end
