function Purge_CutsceneFailSiegeGuns(owner)
  cutsceneFailGunID = owner
  Despawn(Air_Vehicle.Sgunship01Fail)
  while true do
    if cutsceneFailGunBegin == 1 then
      cutsceneFailGunBegin = 2
      break
    end
    EndFrame()
  end
  StartOutro()
  FreezePlayer()
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  SetInvulnerable(flag.TYPE_UNDERWORLD, 1)
  DefeatLament(constant.ARMY_UNDERWORLD, false)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetViewDistanceAdjustment(350, 90)
  SpawnTanks = 0
  RightSecondGatesOpened = 1
  LeftSecondGatesOpened = 1
  Spawn(Air_Vehicle.Sgunship01)
  Spawn(Air_Vehicle.Sgunship02)
  Spawn(Air_Vehicle.Sgunship03)
  Spawn(Air_Vehicle.Sgunship04)
  SetObjectiveData(Objective_Marker.SolarFortifications, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  Spawn(Air_Vehicle.Sgunship01Fail)
  SetActive(Air_Vehicle.Sgunship01Fail, constant.INACTIVE, constant.ADJUST_WEAPON)
  WaitFor(0.5)
  Teleport(Ground_Vehicle.ILtank01, -1160, -240, 0, 5)
  Teleport(Troop.LegionGrunt02, -1180, -230, 0, 5)
  Teleport(Troop.LegionGrunt03, -1180, -235, 0, 5)
  Teleport(Troop.LegionGrunt04, -1180, -240, 0, 5)
  Teleport(Troop.LegionGrunt05, -1180, -245, 0, 5)
  Teleport(Troop.LegionGrunt06, -1180, -250, 0, 5)
  Teleport(Troop.ILbazooka01, -1140, -230, 0, 5)
  Teleport(Troop.ILbazooka02, -1140, -235, 0, 5)
  Teleport(Troop.ILbazooka03, -1140, -240, 0, 5)
  Teleport(Troop.ILbazooka04, -1140, -245, 0, 5)
  Teleport(Troop.ILbazooka05, -1140, -250, 0, 5)
  Teleport(Troop.ILmortar01, -1200, -230, 0, 5)
  Teleport(Troop.ILmortar02, -1200, -235, 0, 5)
  Teleport(Troop.ILmortar03, -1200, -240, 0, 5)
  Teleport(Troop.ILmortar04, -1200, -245, 0, 5)
  Teleport(Troop.ILmortar05, -1200, -250, 0, 5)
  Despawn(Troop.ILhose01)
  Despawn(Troop.ILhose02)
  SetHealthPercent(Building.AAtower01, 11)
  SetHealthPercent(Building.AAtower03, 11)
  SetHealthPercent(Building.AAtower02, 11)
  SetHealthPercent(Building.NeutralMGNest01, 11)
  SetHealthPercent(Building.NeutralMGNest04, 11)
  Teleport(Ground_Vehicle.Stank05, -1209, 310, 180, 5)
  Teleport(Ground_Vehicle.Stank04, -1235, 295, 180, 5)
  Teleport(Ground_Vehicle.Stank06, -1188, 334, 180, 5)
  Teleport(Ground_Vehicle.Stank07, -1160, 352, 180, 5)
  Teleport(Ground_Vehicle.Stank08, -1095, 285, 225, 5)
  Teleport(Ground_Vehicle.Stank09, -1132, 345, 180, 5)
  Teleport(Air_Vehicle.Sgunship01, -1255, 300, 180, 5)
  Teleport(Air_Vehicle.Sgunship02, -1197, 320, 180, 5)
  Teleport(Air_Vehicle.Sgunship03, -1167, 340, 180, 5)
  Teleport(Air_Vehicle.Sgunship04, -1110, 330, 180, 5)
  Spawn(Air_Vehicle.Sgunship01Fail)
  SetActive(Air_Vehicle.Sgunship01Fail, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarHose02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarHose03, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarBazooka02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarBazooka01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarGrunt04, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarGrunt06, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.Sbazooka01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.Sbazooka02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank06, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank07, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank08, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank09, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.Sgunship03, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.Sgunship04, constant.INACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Air_Vehicle.Sgunship01, Building.Pillbox01, constant.ORDER_NORMAL)
  AttackTarget(Air_Vehicle.Sgunship02, Building.Pillbox01, constant.ORDER_NORMAL)
  AttackTarget(Ground_Vehicle.Stank04, Building.Pillbox01, constant.ORDER_NORMAL)
  AttackTarget(Ground_Vehicle.Stank05, Building.AAtower01, constant.ORDER_NORMAL)
  AttackTarget(Troop.Sbazooka01, Building.NeutralMGNest01, constant.ORDER_NORMAL)
  AttackTarget(Troop.SolarBazooka01, Building.NeutralMGNest01, constant.ORDER_NORMAL)
  AttackTarget(Ground_Vehicle.Stank06, Building.AAtower03, constant.ORDER_NORMAL)
  AttackTarget(Troop.SolarBazooka02, Building.NeutralMGNest04, constant.ORDER_NORMAL)
  AttackTarget(Troop.SolarGrunt04, Building.NeutralMGNest04, constant.ORDER_NORMAL)
  AttackTarget(Ground_Vehicle.Stank07, Building.AAtower02, constant.ORDER_NORMAL)
  GoToArea(Troop.SolarHose02, -1110, 260, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.SolarHose03, -1120, 262, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.SolarGrunt06, -1115, 265, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.Sbazooka02, -1122, 267, 5, 0, constant.ORDER_FORCED)
  GoToArea(Ground_Vehicle.Stank09, -1130, 260, 5, 0, constant.ORDER_FORCED)
  AttackTarget(Ground_Vehicle.Stank08, Building.Pillbox02, constant.ORDER_NORMAL)
  AttackTarget(Air_Vehicle.Sgunship03, Building.Pillbox02, constant.ORDER_NORMAL)
  AttackTarget(Air_Vehicle.Sgunship04, Building.Pillbox02, constant.ORDER_NORMAL)
  WaitFor(0.5)
  SetCamera(Camera.CutsceneFailSiegeGuns2, constant.PLAYER_ONE)
  CameraSetFOV(Camera.CutsceneFailSiegeGuns2, 80, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetWaypoint(Camera.CutsceneFailSiegeGuns2, Waypoint.CutsceneFailSiegeGuns2)
  CameraSetTarget(Camera.CutsceneFailSiegeGuns2, Waypoint.CutsceneFailSiegeGunsTarget2)
  CameraSetFOV(Camera.CutsceneFailSiegeGuns2, 60, constant.SMOOTH, 3, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(6, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  WaitFor(3)
  SetActive(Air_Vehicle.Sgunship01Fail, constant.ACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Air_Vehicle.Sgunship01Fail, Building.AAtower03, constant.ORDER_NORMAL)
  WaitFor(2)
  SetActive(Troop.Sbazooka01, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarBazooka01, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank06, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarBazooka02, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarGrunt04, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Ground_Vehicle.Stank07, constant.ACTIVE, constant.ADJUST_WEAPON)
  WaitFor(2)
  SetActive(Ground_Vehicle.Stank08, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.Sgunship03, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.Sgunship04, constant.ACTIVE, constant.ADJUST_WEAPON)
  WaitFor(1)
  Kill(Building.Pillbox01)
  WaitFor(1)
  SetHealthPercent(Building.AAtower01, 1)
  WaitFor(1.5)
  SetHealthPercent(Building.NeutralMGNest01, 1)
  WaitFor(1.5)
  PhoneMessage(74, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Sad, constant.PLAYER_ONE)
  SetActive(Ground_Vehicle.Stank09, constant.ACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Ground_Vehicle.Stank09, Building.Pillbox02, constant.ORDER_NORMAL)
  SetHealthPercent(Building.AAtower03, 1)
  WaitFor(1)
  SetHealthPercent(Building.NeutralMGNest04, 1)
  WaitFor(1.5)
  SetHealthPercent(Building.AAtower02, 1)
  SetActive(Troop.SolarHose02, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarHose03, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.SolarGrunt06, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Troop.Sbazooka02, constant.ACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Troop.SolarHose02, Building.Pillbox02, constant.ORDER_NORMAL)
  AttackTarget(Troop.SolarHose03, Building.Pillbox02, constant.ORDER_NORMAL)
  AttackTarget(Troop.SolarGrunt06, Building.Pillbox02, constant.ORDER_NORMAL)
  AttackTarget(Troop.Sbazooka02, Building.Pillbox02, constant.ORDER_NORMAL)
  WaitFor(2.5)
  Kill(Building.Pillbox02)
  DeclareVictory(constant.ARMY_SOLAR)
  VictoryDance(constant.ARMY_SOLAR, false)
  WaitFor(3)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutsceneFailGunIsOver = 1
end
