function Purge_CutsceneForcefieldSkip(owner)
  repeat
    EndFrame()
  until IsDead(Building.Forcefield01) and IsDead(Building.Forcefield02) or IsDead(Building.Forcefield03) and IsDead(Building.Forcefield04)
  WaitFor(2)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO)) then
      Kill(cutsceneforcefield)
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      StoreSummaryMessage(constant.PLAYER_ONE, 66, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 62, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
      cutsceneforcefieldend = 1
      EndFrame()
    end
    EndFrame()
  until cutsceneforcefieldend == 1
  Spawn(Air_Vehicle.SolarGunship01)
  Spawn(Air_Vehicle.SolarGunship02)
  DebugOut("Spawning Gunships at the Solar HQ")
  SetObjectiveData(Objective.Mine, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective_Marker.Mine, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  Kill(Troop.Entity550041683, false)
  Kill(Troop.Entity550041684, false)
  Kill(Troop.Entity550041685, false)
  Kill(Troop.Entity550042267, false)
  Kill(Troop.SgruntCutscene01, false)
  Kill(Troop.SchainCutscene01, false)
  Kill(Troop.SbazookaCutscene01, false)
  WaitFor(0.1)
  Despawn(Troop.Entity550041683)
  Despawn(Troop.Entity550041684)
  Despawn(Troop.Entity550041685)
  Despawn(Troop.Entity550042267)
  Despawn(Troop.SgruntCutscene01)
  Despawn(Troop.SchainCutscene01)
  Despawn(Troop.SbazookaCutscene01)
  EndIntro()
  Kill(cutsceneforcefield)
  SetCamera(Camera.Player_Camera)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(0.5)
  UnfreezePlayer()
  SetInvulnerable(flag.TYPE_SOLAR, 0)
  SetInvulnerable(flag.TYPE_UNDERWORLD, 0)
  PauseTimerActive = 0
  SetHealthPercent(Building.Saw01, 100)
  SetHealthPercent(Building.Saw02, 100)
  SetHealthPercent(Building.Saw03, 80)
end
