function Purge_CutsceneBombers(owner)
  cutscenebombers = owner
  local BombedGates = 0
  Despawn(Building.CarpetBombTarget01)
  Despawn(Building.CarpetBombTarget02)
  Despawn(Troop.Smissile01)
  Despawn(Troop.Smissile02)
  Despawn(Building.GateExplosion01)
  Despawn(Building.GateExplosion02)
  Despawn(Building.GateExplosion03)
  Despawn(Building.GateExplosion04)
  Despawn(Building.GateExplosion05)
  SetActive(Morphing_Building.SolarBarracks01, constant.INACTIVE, constant.DONT_ADJUST_WEAPON)
  SetActive(Capture_Point.SolarBarracksCapturePoint01, constant.INACTIVE, constant.DONT_ADJUST_WEAPON)
  repeat
    EndFrame()
  until cutscenebombersstart == 1
  StartOutro()
  FreezePlayer()
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  SetInvulnerable(flag.TYPE_UNDERWORLD, 1)
  PauseTimerActive = 1
  Spawn(Air_Vehicle.LegionBomber01)
  Spawn(Air_Vehicle.LegionBomber02)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.Sgunship01)
  Despawn(Air_Vehicle.Sgunship02)
  Despawn(Air_Vehicle.Sgunship03)
  Despawn(Air_Vehicle.Sgunship04)
  Despawn(Building.SolarMGNest01)
  Despawn(Building.SolarMGNest02)
  Despawn(Building.SolarMGNest03)
  Despawn(Building.SolarMGNest04)
  Spawn(Building.CarpetBombTarget01)
  Spawn(Building.CarpetBombTarget02)
  Spawn(Building.GateExplosion01)
  Spawn(Building.GateExplosion02)
  Spawn(Building.GateExplosion03)
  Spawn(Building.GateExplosion04)
  Spawn(Building.GateExplosion05)
  Teleport(Air_Vehicle.LegionBomber01, -935, 433, 270, 0)
  Teleport(Air_Vehicle.LegionBomber02, -875, 465, 225, 0)
  GoToArea(Air_Vehicle.LegionBomber01, -1733, 311, 10, 0, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.LegionBomber02, -1733, 372, 10, 0, constant.ORDER_FORCED)
  DebugOut("All of the Pillboxes have been destroyed. Objective complete")
  SetCamera(Camera.CutsceneBombers, constant.PLAYER_ONE)
  CameraSetFOV(Camera.CutsceneBombers, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetWaypoint(Camera.CutsceneBombers, Waypoint.CutsceneBombers)
  CameraSetTarget(Camera.CutsceneBombers, Waypoint.CutsceneBombersTarget)
  CameraSetFOV(Camera.CutsceneBombers, 80, constant.SMOOTH, 5, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(12, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  SetActive(Air_Vehicle.LegionBomber01, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.LegionBomber02, constant.ACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Air_Vehicle.LegionBomber01, Building.CarpetBombTarget01, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.LegionBomber02, Building.CarpetBombTarget02, constant.ORDER_FORCED)
  WaitFor(7.25)
  ExitVehicle(Troop.Entity550038092, Building.SbazookaTower04)
  Despawn(Troop.Entity550038092)
  Kill(Building.SbazookaTower04)
  WaitFor(0.25)
  Kill(Building.GateExplosion05)
  WaitFor(0.25)
  Kill(Building.GateExplosion04)
  Kill(Building.GateExplosion03)
  WaitFor(0.25)
  ExitVehicle(Troop.Entity550038091, Building.SbazookaTower03)
  Despawn(Troop.Entity550038091)
  Kill(Building.SbazookaTower03)
  Kill(Building.GateExplosion02)
  WaitFor(0.25)
  Kill(Building.GateExplosion01)
  Kill(Building.Searchlight03)
  WaitFor(0.25)
  Kill(Building.Searchlight02)
  WaitFor(0.25)
  Kill(Building.Searchlight01)
  Kill(Building.Gates03)
  DestroyablePlayAnim(Building.Gates03, 1, 2)
  WaitFor(0.5)
  Kill(Building.Gates01)
  DestroyablePlayAnim(Building.Gates01, 1, 2)
  GoToArea(Air_Vehicle.LegionBomber01, -1195, 415, 10, 0, constant.ORDER_FORCED)
  SetActive(Air_Vehicle.LegionBomber01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Air_Vehicle.LegionBomber02, constant.INACTIVE, constant.ADJUST_WEAPON)
  Spawn(Troop.Smissile01)
  Spawn(Troop.Smissile02)
  AttackTarget(Troop.Smissile01, Air_Vehicle.LegionBomber01, constant.ORDER_FORCED)
  AttackTarget(Troop.Smissile02, Air_Vehicle.LegionBomber02, constant.ORDER_FORCED)
  WaitFor(0.1)
  ResetPathBlocking(Building.Gates03)
  ResetPathBlocking(Building.Gates01)
  WaitFor(1)
  ExitVehicle(Troop.Entity550038090, Building.SbazookaTower02)
  Despawn(Troop.Entity550038090)
  Kill(Building.SbazookaTower02)
  GoToArea(Air_Vehicle.LegionBomber02, -1150, 400, 10, 0, constant.ORDER_FORCED)
  WaitFor(1)
  WaitFor(0.1)
  WaitFor(0.1)
  WaitFor(0.1)
  WaitFor(0.5)
  ExitVehicle(Troop.Entity550038089, Building.SbazookaTower01)
  Despawn(Troop.Entity550038089)
  Kill(Building.SbazookaTower01)
  WaitFor(2)
  Kill(Air_Vehicle.LegionBomber01)
  WaitFor(1.5)
  Kill(Air_Vehicle.LegionBomber02)
  WaitFor(0.5)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  cutscenebombersend = 1
end
