function Purge_CutsceneIntro(owner)
  SetActive(Building.Pillbox01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Building.Pillbox02, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetUnitInvulnerable(Building.Pillbox01, true)
  SetUnitInvulnerable(Building.Pillbox02, true)
  Despawn(Troop.Sgrunt16, true)
  Despawn(Troop.Sgrunt17, true)
  Despawn(Troop.Sbazooka01, true)
  Despawn(Troop.Sbazooka02, true)
  Despawn(Troop.SolarBazooka01, true)
  Despawn(Troop.SolarHose03, true)
  Despawn(Troop.SolarBazooka02, true)
  Despawn(Troop.SolarGrunt04, true)
  Despawn(Troop.SolarGrunt06, true)
  Despawn(Troop.SolarHose02, true)
  Despawn(Troop.Entity550041683)
  Despawn(Troop.Entity550041684)
  Despawn(Troop.Entity550041685)
  Despawn(Troop.Entity550042267)
  Despawn(Troop.Entity550041688)
  Despawn(Troop.Entity550041689)
  cutsceneabort = owner
  StartIntro()
  ClearMessageQueue()
  SetInvulnerable(flag.TYPE_UNDERWORLD, true)
  SetCamera(Camera.Cutscene01aCamera, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene01aCamera, Waypoint.Cutscene01a)
  CameraSetTarget(Camera.Cutscene01aCamera, Waypoint.Cutscene01aTarget)
  CameraSetFOV(Camera.Cutscene01aCamera, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.Cutscene01aCamera, 75, constant.SMOOTH, 1.5, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(33, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Sad, constant.PLAYER_ONE)
  WaitFor(2)
  PutUnitInVehicle(Troop.SpilotCutscene02, Air_Vehicle.SgunshipCutscene02, 0)
  GoToArea(Air_Vehicle.SgunshipCutscene02, -1340, 1100, 5, 0, constant.ORDER_FORCED)
  WaitFor(2)
  PutUnitInVehicle(Troop.SpilotCutscene01, Air_Vehicle.SgunshipCutscene01, 0)
  GoToArea(Air_Vehicle.SgunshipCutscene01, -1355, 1107, 5, 0, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetWaterRenderEnable(false)
  SetCamera(Camera.Cutscene02Camera, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene02Camera, Waypoint.Cutscene02)
  CameraSetTarget(Camera.Cutscene02Camera, Waypoint.Cutscene02Target)
  CameraSetFOV(Camera.Cutscene02Camera, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.Cutscene02Camera, 75, constant.SMOOTH, 1.5, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(35, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Sad, constant.PLAYER_ONE)
  WaitFor(4)
  Spawn(Ground_Vehicle.STankCutscene01)
  AttackTarget(Ground_Vehicle.STankCutscene01, Building.Pillbox01, constant.ORDER_FORCED)
  Spawn(Troop.Entity550042267)
  Spawn(Troop.Entity550041684)
  Spawn(Troop.Entity550041683)
  AttackTarget(Troop.Entity550042267, Building.Pillbox01, constant.ORDER_NORMAL)
  AttackTarget(Troop.Entity550041684, Building.Pillbox01, constant.ORDER_NORMAL)
  AttackTarget(Troop.Entity550041683, Building.Pillbox01, constant.ORDER_NORMAL)
  SetHealthPercent(Troop.Entity550042267, 20)
  SetHealthPercent(Troop.Entity550041684, 20)
  SetHealthPercent(Troop.Entity550041683, 20)
  WaitFor(2)
  GoToArea(Troop.Entity550042267, -1228, 297, 5, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.Entity550041684, -1236, 287, 5, 0, constant.ORDER_NORMAL)
  WaitFor(2)
  PhoneMessage(45, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE)
  SetActive(Building.Pillbox01, constant.ACTIVE, constant.ADJUST_WEAPON)
  SetActive(Building.Pillbox02, constant.ACTIVE, constant.ADJUST_WEAPON)
  AttackTarget(Building.Pillbox01, Troop.Entity550041683, constant.ORDER_NORMAL)
  WaitFor(3)
  Spawn(Troop.Entity550041685)
  AttackTarget(Building.Pillbox01, Troop.Entity550041685, constant.ORDER_NORMAL)
  SetHealthPercent(Troop.Entity550041685, 60)
  SetHealthPercent(Ground_Vehicle.STankCutscene01, 60)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  Kill(Troop.Entity550041685)
  Kill(Ground_Vehicle.STankCutscene01)
  FollowWaypoint(Ground_Vehicle.Stank02, Waypoint.SolarGrunt05WayPoint02, 5, 5, constant.ORDER_NORMAL)
  FollowWaypoint(Ground_Vehicle.Stank03, Waypoint.SolarGrunt02WayPoint01, 5, 5, constant.ORDER_NORMAL)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  DebugOut("Reducing to 300m instantly")
  SetViewDistanceAdjustment(250, 5)
  SetCamera(Camera.Cutscene02aCamera, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene02aCamera, Waypoint.Cutscene02a)
  CameraSetTarget(Camera.Cutscene02aCamera, Waypoint.Cutscene02aTarget)
  CameraSetFOV(Camera.Cutscene02aCamera, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.Cutscene02aCamera, 65, constant.SMOOTH, 2, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(34, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cutscene03Camera, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.Cutscene03Camera, Waypoint.Cutscene03)
  CameraSetTarget(Camera.Cutscene03Camera, Waypoint.Cutscene03Target)
  CameraSetFOV(Camera.Cutscene03Camera, 60, constant.IMMEDIATE, 0, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(36, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Sad, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  DebugOut("Reducing to ViewDistance2: ", ViewDistance2, "instantly")
  SetViewDistanceAdjustment(ViewDistance2, 5)
  SetActive(Building.Pillbox01, constant.INACTIVE, constant.ADJUST_WEAPON)
  SetActive(Building.Pillbox02, constant.INACTIVE, constant.ADJUST_WEAPON)
  Despawn(Troop.SpilotCutscene01)
  Despawn(Troop.SpilotCutscene02)
  Despawn(Air_Vehicle.SgunshipCutscene01)
  Despawn(Air_Vehicle.SgunshipCutscene02)
  Despawn(Ground_Vehicle.STankCutscene01)
  Despawn(Troop.Entity550041683)
  Despawn(Troop.Entity550041684)
  Despawn(Troop.Entity550041685)
  Despawn(Troop.Entity550042267)
  Despawn(Troop.Entity550041688)
  Despawn(Troop.Entity550041689)
  Despawn(Troop.SgruntCutscene01)
  Despawn(Troop.SchainCutscene01)
  Despawn(Troop.SbazookaCutscene01)
  SetInvulnerable(flag.TYPE_SOLAR, false)
  SetInvulnerable(flag.TYPE_UNDERWORLD, false)
  EndIntro()
  SetCamera(Camera.Player_Camera, constant.PLAYER_ONE)
  cutscene01 = 1
  EndFrame()
  ResetCommandBar()
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  SetWaterRenderEnable(false)
  WaitFor(0.5)
  PhoneMessageWithObjective(46, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  PhoneMessage(73, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
  UnfreezePlayer(constant.PLAYER_ONE)
  DebugOut("Player can move")
  ResetHealthAndScoreTotals()
  StartScoringTimer()
  SetTimer(180)
  ShowTimer(1)
  ClockIsTicking = 1
  cutscene01 = 2
end
