function Purge_CutsceneIntroSkip(owner)
  WaitFor(2)
  while cutscene01 == 0 do
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_TWO)) then
      Kill(cutsceneabort)
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      StoreSummaryMessage(constant.PLAYER_ONE, 33, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Sad)
      StoreSummaryMessage(constant.PLAYER_ONE, 35, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Sad)
      StoreSummaryMessage(constant.PLAYER_ONE, 45, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 34, constant.ARMY_SOLAR, SpriteID.CO_SE_Leiqo_Helmet_Happy)
      StoreSummaryMessage(constant.PLAYER_ONE, 36, constant.ARMY_UNDERWORLD, SpriteID.CO_L_Ferrok_Sad)
      SetActive(Building.Pillbox01, constant.INACTIVE, constant.ADJUST_WEAPON)
      SetActive(Building.Pillbox02, constant.INACTIVE, constant.ADJUST_WEAPON)
      Despawn(Troop.SpilotCutscene01)
      Despawn(Troop.SpilotCutscene02)
      Despawn(Air_Vehicle.SgunshipCutscene01)
      Despawn(Air_Vehicle.SgunshipCutscene02)
      Despawn(Troop.Entity550041683)
      Despawn(Troop.Entity550041684)
      Despawn(Troop.Entity550041685)
      Despawn(Troop.Entity550042267)
      Despawn(Troop.Entity550041688)
      Despawn(Troop.Entity550041689)
      Despawn(Troop.SgruntCutscene01)
      Despawn(Troop.SchainCutscene01)
      Despawn(Troop.SbazookaCutscene01)
      Despawn(Ground_Vehicle.STankCutscene01)
      FollowWaypoint(Ground_Vehicle.Stank02, Waypoint.SolarGrunt05WayPoint01, 5, 5, constant.ORDER_NORMAL)
      DebugOut("Reducing to ViewDistance2: ", ViewDistance2, "instantly")
      SetViewDistanceAdjustment(ViewDistance2, 5)
      SetInvulnerable(flag.TYPE_SOLAR, false)
      SetInvulnerable(flag.TYPE_UNDERWORLD, false)
      EndIntro()
      SetCamera(Camera.Player_Camera)
      cutscene01 = 1
      EndFrame()
      ResetCommandBar()
      ClearMessageQueue()
      CameraFade(constant.FADE_IN, constant.WAIT, 1)
      SetWaterRenderEnable(false)
      WaitFor(0.5)
      PhoneMessageWithObjective(46, constant.ID_NONE, constant.ARMY_UNDERWORLD, 0, SpriteID.CO_L_Ferrok_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
      PhoneMessage(73, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Leiqo_Helmet_Happy, constant.PLAYER_ONE)
      UnfreezePlayer(constant.PLAYER_ONE)
      DebugOut("Player can move")
      ResetHealthAndScoreTotals()
      StartScoringTimer()
      SetTimer(180)
      ShowTimer(1)
      ClockIsTicking = 1
      cutscene01 = 2
      DebugOut("The player has successfully skipped the cutscene")
    end
    EndFrame()
  end
end
