function CutSkip1(owner)
  Despawn(Troop.WF2_Rifleman)
  Despawn(Troop.WF3_Rifleman)
  Despawn(Troop.WF4_Rifleman)
  Despawn(Troop.WF5_Rifleman)
  WaitFor(1)
  repeat
    if GetCurrentMissionAttempted() == true then
      if ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED) then
        Kill(cutscene)
        ClearMessageQueue()
        cutscene = 1
        CameraFade(constant.FADE_OUT, constant.WAIT, 1)
        DebugOut("Skipped cutscene")
        Spawn(Air_Vehicle.T1_Fighter)
        GoToArea(Air_Vehicle.T1_Fighter, -469, -425, 10, nil, constant.ORDER_FORCED)
        DebugOut("Teleport Fighters")
        Spawn(Troop.WF2_Rifleman)
        Spawn(Troop.WF3_Rifleman)
        Spawn(Troop.WF4_Rifleman)
        Spawn(Troop.WF5_Rifleman)
        Despawn(Troop.WF2Cut)
        Despawn(Troop.WF3Cut)
        Despawn(Troop.WF4Cut)
        Despawn(Troop.WF5Cut)
        GoToArea(Troop.WF2_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
        GoToArea(Troop.WF3_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
        GoToArea(Troop.WF4_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
        GoToArea(Troop.WF5_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
        Despawn(Air_Vehicle.WF_Air_Transport_2)
        Spawn(Air_Vehicle.WF3_Transport)
        UnfreezePlayer()
        EndIntro()
        SetCamera(Camera.PlayerCam)
        StoreSummaryMessage(41, 0, SpriteID.CO_WF_Herman_Happy)
        StoreSummaryMessage(42, 0, SpriteID.CO_WF_Herman_Happy)
        StoreSummaryMessage(43, 0, SpriteID.CO_WF_Herman_Happy)
        StoreSummaryMessage(44, 0, SpriteID.CO_WF_Herman_Happy)
        CameraFade(constant.FADE_IN, constant.WAIT, 1)
      end
      EndFrame()
    end
    EndFrame()
  until cutscene == 1
  EndFrame()
  Despawn(Air_Vehicle.T1_Fighter)
  PhoneMessage(1, 0, 0, 2.5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(2)
  Despawn(Troop.T1Cutscene)
  Spawn(Troop.T15_RifleMan)
  EnterVehicle(Troop.TPilot1, Air_Vehicle.WF3_Transport, constant.ORDER_FORCED)
  WaitFor(1)
  GoToArea(Air_Vehicle.WF3_Transport, -832, -620, 10, nil, constant.ORDER_FORCED)
  WaitFor(15)
  Despawn(Air_Vehicle.WF3_Transport)
  EndFrame()
end
