function CutScene(owner)
  cutscene = owner
  StartIntro()
  FreezePlayer()
  Despawn(Air_Vehicle.T1_Fighter)
  Despawn(Air_Vehicle.WF1_Fighter)
  Despawn(Air_Vehicle.WF2_Fighter)
  Despawn(Air_Vehicle.WF3_Transport)
  Despawn(Troop.T15_RifleMan)
  SetCamera(Camera.Intro1Cam)
  CameraSetWaypoint(Camera.Intro1Cam, Waypoint.Intro1Cut)
  CameraSetTarget(Camera.Intro1Cam, Waypoint.Intro1CutTarget)
  PhoneMessage(41, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  WaitFor(6)
  ClearMessageQueue()
  Spawn(Troop.T15_RifleMan)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.CutCam1)
  CameraSetWaypoint(Camera.CutCam1, Waypoint.Cut1)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(42, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(7)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ClearMessageQueue()
  Spawn(Air_Vehicle.T1_Fighter)
  GoToArea(Air_Vehicle.T1_Fighter, -469, -425, 10, nil, constant.ORDER_FORCED)
  CameraSetWaypoint(Camera.CutCam2, Waypoint.Cut2)
  CameraSetTarget(Camera.CutCam2, Waypoint.Cut2Target)
  SetCamera(Camera.CutCam2)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(43, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  WaitFor(4)
  WaitFor(3)
  Spawn(Air_Vehicle.WF_Air_Transport_2)
  GoToArea(Air_Vehicle.WF_Air_Transport_2, -688, -1119, 2, nil, constant.ORDER_FORCED)
  Despawn(Troop.T1Cutscene)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ClearMessageQueue()
  Spawn(Air_Vehicle.WF1_Fighter)
  Spawn(Air_Vehicle.WF2_Fighter)
  GoToArea(Air_Vehicle.WF1_Fighter, -678, 117, 10, nil, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.WF2_Fighter, -678, 117, 10, nil, constant.ORDER_FORCED)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Cut3)
  CameraSetTarget(Camera.Cam3, Waypoint.Cut3Target)
  SetCamera(Camera.Cam3)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(44, 0, 0, 7, SpriteID.CO_WF_Herman_Happy)
  WaitFor(12)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Air_Vehicle.T1_Fighter)
  Despawn(Air_Vehicle.T1_Fighter)
  Spawn(Air_Vehicle.T1_Fighter)
  GoToArea(Air_Vehicle.T1_Fighter, -469, -425, 10, nil, constant.ORDER_FORCED)
  Spawn(Air_Vehicle.WF1_Fighter)
  Spawn(Air_Vehicle.WF2_Fighter)
  DebugOut("Teleport Fighters")
  Teleport(Air_Vehicle.WF1_Fighter, -678, 117, 10, 20)
  Teleport(Air_Vehicle.WF2_Fighter, -678, 117, 10, 20)
  Spawn(Troop.WF2_Rifleman)
  Spawn(Troop.WF3_Rifleman)
  Spawn(Troop.WF4_Rifleman)
  Spawn(Troop.WF5_Rifleman)
  Despawn(Troop.WF2Cut)
  Despawn(Troop.WF3Cut)
  Despawn(Troop.WF4Cut)
  Despawn(Troop.WF5Cut)
  GoToArea(Troop.WF2_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
  GoToArea(Troop.WF3_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
  GoToArea(Troop.WF4_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
  GoToArea(Troop.WF5_Rifleman, -678, -1117, 10, nil, constant.ORDER_FORCED)
  Despawn(Air_Vehicle.WF_Air_Transport_2)
  Spawn(Air_Vehicle.WF3_Transport)
  EndIntro()
  SetCamera(Camera.PlayerCam)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  UnfreezePlayer()
  cutscene = 1
  EndFrame()
end
