function MG_Nest(owner)
  Despawn(Troop.T12_RifleMan)
  Despawn(Troop.T21_RifleMan)
  Despawn(Troop.T31_Rifleman)
  Despawn(Troop.T32_Rifleman)
  repeat
    EndFrame()
  until NumItemsInArea(Map_Zone.Trigger12, flag.TYPE_WFRONTIER) > 0
  DebugOut("MGNest1")
  Kill(thirdencdead)
  PhoneMessage(22, 0, 2, 5, SpriteID.CO_T_Gorgi_Sad)
  PhoneMessage(39, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  SetObjectiveData(Objective.Phase2, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.MGnest, constant.OBJECTIVE_DATA_STATE, 0)
  SetObjectiveData(Objective_Marker.MGNestMark, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  WaitFor(5)
  SetHudState(constant.HUD_CONTROLIMAGE_ALL, constant.HUD_ITEM_ON, 540, 380, 0.6)
  SetHudState(constant.HUD_CONTROLIMAGE_B, constant.HUD_ITEM_FLASH, 7, 540, 380, 0.6)
  WaitFor(7)
  SetHudState(constant.HUD_CONTROLIMAGE_ALL, constant.HUD_ITEM_OFF, 540, 380, 0.6)
  Kill(third)
  Spawn(Troop.T12_RifleMan)
  Spawn(Troop.T21_RifleMan)
  Spawn(Troop.T31_Rifleman)
  Spawn(Troop.T32_Rifleman)
  SetUnitAI(Troop.T12_RifleMan, constant.AI_DODGE, constant.DODGE_NOT_ALLOWED)
  SetUnitAI(Troop.T21_RifleMan, constant.AI_DODGE, constant.DODGE_NOT_ALLOWED)
  SetUnitAI(Troop.T31_Rifleman, constant.AI_DODGE, constant.DODGE_NOT_ALLOWED)
  SetUnitAI(Troop.T32_Rifleman, constant.AI_DODGE, constant.DODGE_NOT_ALLOWED)
  SetObjectiveData(Objective.MGnest, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.MGNest2, constant.OBJECTIVE_DATA_STATE, 0)
  SetObjectiveData(Objective_Marker.MGNestMark2, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  DebugOut("MGNest2")
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.MG1Zone, flag.TYPE_WFRONTIER)
  Kill(thirdencdead)
  SetObjectiveData(Objective.MGNest2, constant.OBJECTIVE_DATA_STATE, 1)
  SetObjectiveData(Objective.Pows, constant.OBJECTIVE_DATA_STATE, 0)
  SetObjectiveData(Objective_Marker.Pows, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.MG1Zone)
  PhoneMessage(38, 0, 0, 5, SpriteID.CO_WF_Herman_Happy)
  EndFrame()
end
