function WF_Bomber(owner)
  Despawn(Air_Vehicle.WF1_Bomber)
  repeat
    EndFrame()
  until NumItemsInArea(Map_Zone.Trigger11, flag.TYPE_WFRONTIER) > 0
  Spawn(Air_Vehicle.WF1_Bomber)
  Spawn(Troop.T28_Rifleman)
  Spawn(Troop.T27_Rifleman)
  Spawn(Troop.T25_Rifleman)
  Spawn(Troop.T24_Rifleman)
  Spawn(Troop.T5_Rifleman)
  Spawn(Troop.T9_RifleMan)
  Spawn(Troop.T8_RifleMan)
  Spawn(Troop.T7_RifleMan)
  EndFrame()
  PhoneMessage(31, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(60, 0, 2, 4, SpriteID.CO_T_Gorgi_Happy)
  PhoneMessage(61, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  PhoneMessage(62, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  AttackTarget(Air_Vehicle.WF1_Bomber, Building.TundMGnest1, constant.ORDER_FORCED)
  WaitFor(13)
  GoToArea(Air_Vehicle.WF1_Bomber, -12, -511, 10, nil, constant.ORDER_FORCED)
  WaitFor(11)
  PhoneMessage(32, 0, 0, 4, SpriteID.CO_WF_Herman_Happy)
  SetHudState(constant.HUD_CONTROLIMAGE_ALL, constant.HUD_ITEM_ON, 540, 380, 0.6)
  SetHudState(constant.HUD_CONTROLIMAGE_SHOULDERL, constant.HUD_ITEM_ON, 540, 380, 0.6)
  SetHudState(constant.HUD_CONTROLIMAGE_B, constant.HUD_ITEM_FLASH, 6, 540, 380, 0.6)
  bomberalive = 1
  WaitFor(5)
  SetHudState(constant.HUD_CONTROLIMAGE_ALL, constant.HUD_ITEM_OFF, 540, 380, 0.6)
  SetHudState(constant.HUD_CONTROLIMAGE_SHOULDERL, constant.HUD_ITEM_OFF, 540, 380, 0.6)
  EndFrame()
end
