function CutsceneOutro(owner)
  scriptCutsceneOutro = owner
  local captured = 0
  local destroyed = 0
  local played = 0
  Despawn(Troop.CutsceneTroop1)
  Despawn(Troop.CutsceneTroop2)
  Despawn(Troop.CutsceneTroop3)
  Despawn(Troop.CutsceneTroop4)
  Despawn(Troop.CutsceneTroop5)
  Despawn(Troop.CutsceneTroop6)
  Despawn(Troop.CutsceneXylvanian1)
  Despawn(Troop.CutsceneXylvanian2)
  Despawn(Troop.CutsceneXylvanian3)
  Despawn(Troop.CutsceneXylvanian4)
  Despawn(Building.ExplosionShot1)
  Despawn(Building.ExplosionShot2)
  Despawn(Building.MunitionsDetonator1)
  Despawn(Building.MunitionsDetonator2)
  Despawn(Building.MunitionsDetonator3)
  Despawn(Building.MunitionsDetonator4)
  Despawn(Building.MunitionsDetonator5)
  Despawn(Building.CaveDreadnoughtStatic)
  Despawn(Ground_Vehicle.CutsceneTank)
  Kill(Building.Detonator1)
  Kill(Building.Detonator2)
  Kill(Building.Detonator3)
  while true do
    if GetState(Capture_Point.MunitionsExpert) == flag.TYPE_TUNDRAN and towersdestroyed == 1 then
      SetObjectiveData(Objective_Marker.GeneralMarkerForHelipad, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
      break
    end
    if GetState(Capture_Point.MunitionsExpert) == flag.TYPE_TUNDRAN and towersdestroyed == 0 and destroyed == 0 then
      if destroyed == 0 then
        PhoneMessageWithObjective(12, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE, false, constant.PRIMARY_OBJECTIVE_COMPLETE)
        SetObjectiveData(Objective_Marker.Helipad, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
        SetObjectiveData(Objective.CountHelipad, constant.OBJECTIVE_DATA_STATE, 1)
        destroyed = 1
      end
      captured = 1
    end
    EndFrame()
  end
  finishmission = 1
  FreezePlayer(constant.PLAYER_ONE)
  notincutscene = 1
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Kill(Air_Vehicle.XGunship1)
  Kill(Air_Vehicle.XGunship2)
  StopCapturePointSounds(Capture_Point.MunitionsExpert)
  Teleport(Ground_Vehicle.TLightTank1, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot2, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot3, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot4, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot5, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot6, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot2, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot3, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot4, -175, -100, 320, 20)
  if mainpowcamp == 1 then
    Teleport(Ground_Vehicle.TLightTank2, -175, -100, 320, 20)
    Teleport(Troop.AAMortar1, -175, -100, 320, 20)
    Teleport(Troop.AAMortar2, -175, -100, 320, 20)
    Teleport(Troop.AAMortar3, -175, -100, 320, 20)
    Teleport(Troop.AAVet1, -175, -100, 320, 20)
    Teleport(Troop.AAVet2, -175, -100, 320, 20)
  end
  if aapowcamp == 1 then
    Teleport(Troop.TundranAAPOW1, -175, -100, 320, 20)
    Teleport(Troop.TundranAAPOW2, -175, -100, 320, 20)
    Teleport(Troop.TundranAAPOW3, -175, -100, 320, 20)
    Teleport(Troop.TundranAAPOW4, -175, -100, 320, 20)
    Teleport(Troop.TundranAAPOW5, -175, -100, 320, 20)
  end
  Spawn(Water_Vehicle.CaveDreadnought1)
  Spawn(Water_Vehicle.CaveDreadnought2)
  Spawn(Water_Vehicle.CaveDreadnought3)
  Spawn(Water_Vehicle.CaveDreadnought4)
  Despawn(Troop.EndMissionUnit1)
  Despawn(Troop.EndMissionUnit2)
  Despawn(Troop.EndMissionUnit3)
  Despawn(Troop.EndMissionUnit4)
  Despawn(Air_Vehicle.MunitionsTransport)
  Despawn(Air_Vehicle.HelipadGunship1)
  Despawn(Air_Vehicle.HelipadGunship2)
  Teleport(Building.ScatteredAATower4, -356, -321, 40, 5)
  Kill(Building.ScatteredAATower4)
  WaitFor(1)
  SetInvulnerable(flag.TYPE_TUNDRAN, true)
  beachlandingcomplete = 2
  Spawn(Air_Vehicle.MunitionsTransport)
  SetViewDistanceAdjustment(500, 5)
  WaitFor(0.2)
  LandAirUnit(Air_Vehicle.MunitionsTransport, GetObjectXPosition(Destroyable_Object.Helipad), GetObjectZPosition(Destroyable_Object.Helipad), constant.ORDER_FORCED, false, 5, 310)
  StartIntro()
  SetCamera(Camera.CutsceneCam, constant.PLAYER_ONE)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.MunitionsCam1Spline)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.MunitionsCam1Target)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(51, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
  WaitFor(7)
  ExitVehicle(Troop.MunitionsExpert1, constant.ID_NONE)
  WaitFor(0.2)
  ExitVehicle(Troop.MunitionsExpert2, constant.ID_NONE)
  WaitFor(0.2)
  ExitVehicle(Troop.MunitionsExpert3, constant.ID_NONE)
  WaitFor(0.2)
  ExitVehicle(Troop.MunitionsExpert4, constant.ID_NONE)
  WaitFor(0.2)
  ExitVehicle(Troop.MunitionsExpert5, constant.ID_NONE)
  GoToArea(Troop.MunitionsExpert1, 460, 347, 20, constant.ORDER_FORCED)
  GoToArea(Troop.MunitionsExpert2, 460, 349, 20, constant.ORDER_FORCED)
  GoToArea(Troop.MunitionsExpert3, 460, 351, 20, constant.ORDER_FORCED)
  GoToArea(Troop.MunitionsExpert4, 460, 353, 20, constant.ORDER_FORCED)
  GoToArea(Troop.MunitionsExpert5, 460, 355, 20, constant.ORDER_FORCED)
  ClearMessageQueue()
  PhoneMessage(52, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PlayEffect(Scripted_Effect.Null, 3, 0, 0, 0)
  Teleport(Troop.MunitionsExpert1, 725, 590, 40, 5)
  Teleport(Troop.MunitionsExpert2, 700, 592, 40, 5)
  Teleport(Troop.MunitionsExpert3, 705, 596, 40, 5)
  Teleport(Troop.MunitionsExpert4, 710, 600, 40, 5)
  Teleport(Troop.MunitionsExpert5, 715, 604, 40, 5)
  EnterVehicle(Troop.MunitionsExpert1, Capture_Point.MunitionsPoint1)
  EnterVehicle(Troop.MunitionsExpert2, Capture_Point.MunitionsPoint2)
  EnterVehicle(Troop.MunitionsExpert3, Capture_Point.MunitionsPoint3)
  EnterVehicle(Troop.MunitionsExpert4, Capture_Point.MunitionsPoint4)
  EnterVehicle(Troop.MunitionsExpert5, Capture_Point.MunitionsPoint5)
  CameraSetFOV(Camera.CutsceneCam, 45, constant.IMMEDIATE, 45, constant.NO_WAIT)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.MunitionsCam3Spline)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.MunitionsCam3Target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(53, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
  WaitFor(8)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Troop.MunitionsExpert1)
  Despawn(Troop.MunitionsExpert2)
  Despawn(Troop.MunitionsExpert3)
  Despawn(Troop.MunitionsExpert4)
  Despawn(Troop.MunitionsExpert5)
  CameraSetFOV(Camera.CutsceneCam, 45, constant.IMMEDIATE, 45, constant.NO_WAIT)
  ReviveDeadUnit(Building.Detonator1)
  ReviveDeadUnit(Building.Detonator2)
  ReviveDeadUnit(Building.Detonator3)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.MunitionsCutsceneDetonatorShot1Spline)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.MunitionsCutsceneDetonatorShot1Target)
  Spawn(Building.CaveDreadnoughtStatic)
  Despawn(Water_Vehicle.CaveDreadnought1)
  Despawn(Water_Vehicle.CaveDreadnought2)
  Despawn(Water_Vehicle.CaveDreadnought3)
  Despawn(Water_Vehicle.CaveDreadnought4)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(54, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
  WaitFor(5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Despawn(Building.CaveDreadnoughtStatic)
  Despawn(Building.Detonator1)
  Spawn(Water_Vehicle.CaveDreadnought1)
  Spawn(Water_Vehicle.CaveDreadnought2)
  Spawn(Water_Vehicle.CaveDreadnought3)
  Spawn(Water_Vehicle.CaveDreadnought4)
  SetPathReblocking(false)
  Spawn(Building.ExplosionShot1)
  Spawn(Building.ExplosionShot2)
  CameraSetFOV(Camera.CutsceneCam, 75, constant.IMMEDIATE, 45, constant.NO_WAIT)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.MunitionsCam6Spline)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.MunitionsCam6Target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(55, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
  WaitFor(2)
  Despawn(Building.Detonator1)
  Kill(Destroyable_Object.Dock1)
  Despawn(Building.MunitionsDetonator1)
  Despawn(Building.MunitionsDetonator2)
  Despawn(Building.MunitionsDetonator3)
  Despawn(Building.MunitionsDetonator4)
  Despawn(Building.MunitionsDetonator5)
  WaitFor(0.3)
  Despawn(Building.Detonator2)
  Kill(Water_Vehicle.CaveDreadnought1)
  WaitFor(0.2)
  Kill(Destroyable_Object.Dock5)
  WaitFor(0.1)
  Despawn(Building.Detonator3)
  Kill(Destroyable_Object.Dock4)
  Kill(Building.ExplosionShot1)
  Kill(Water_Vehicle.CaveDreadnought4)
  WaitFor(0.3)
  Kill(Destroyable_Object.Dock2)
  WaitFor(0.2)
  Kill(Water_Vehicle.CaveDreadnought2)
  WaitFor(0.1)
  Kill(Destroyable_Object.Dock3)
  WaitFor(0.1)
  Kill(Building.ExplosionShot2)
  Kill(Water_Vehicle.CaveDreadnought3)
  Spawn(Troop.CutsceneTroop1)
  Spawn(Troop.CutsceneTroop2)
  Spawn(Troop.CutsceneTroop3)
  Spawn(Troop.CutsceneTroop4)
  Spawn(Troop.CutsceneTroop5)
  Spawn(Troop.CutsceneTroop6)
  Spawn(Ground_Vehicle.CutsceneTank)
  Spawn(Troop.CutsceneXylvanian1)
  Spawn(Troop.CutsceneXylvanian2)
  Spawn(Troop.CutsceneXylvanian3)
  Spawn(Troop.CutsceneXylvanian4)
  if IsDead(Ground_Vehicle.TLightTank1) == false then
    Teleport(Ground_Vehicle.TLightTank1, 301, 313, 200, 5)
  elseif IsDead(Ground_Vehicle.TLightTank2) == false then
    Teleport(Ground_Vehicle.TLightTank2, 301, 313, 200, 5)
  end
  if IsDead(Troop.TAirTransport1Pilot4) == false then
    Teleport(Troop.TAirTransport1Pilot4, 302, 296, 180, 5)
  end
  if IsDead(Troop.TAirTransport1Pilot2) == false then
    Teleport(Troop.TAirTransport1Pilot2, 307, 294, 180, 5)
  end
  if IsDead(Troop.TAirTransport1Pilot3) == false then
    Teleport(Troop.TAirTransport1Pilot3, 313, 293, 180, 5)
  end
  if IsDead(Troop.TAirTransport1Pilot5) == false then
    Teleport(Troop.TAirTransport1Pilot4, 321, 293, 180, 5)
  end
  if IsDead(Troop.TAirTransport1Pilot6) == false then
    Teleport(Troop.TAirTransport1Pilot4, 326, 294, 180, 5)
  end
  DeclareVictory(constant.ARMY_TUNDRAN)
  WaitFor(3)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PlayEffect(Scripted_Effect.Lightning, 3, 0, 0, 0)
  SetInvulnerable(flag.TYPE_XYLVANIAN, true)
  CameraSetWaypoint(Camera.CutsceneCam, Waypoint.MunitionsCam7Spline)
  CameraSetTarget(Camera.CutsceneCam, Waypoint.MunitionsCam7Target)
  CameraSetFOV(Camera.CutsceneCam, 45, constant.IMMEDIATE, 45, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessage(29, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Happy, constant.PLAYER_ONE)
  WaitFor(10)
  missionwon = 1
end
