function CutsceneLandingAbort(owner)
  cutscenelandingabort = owner
  scriptCutsceneLandingAbort = owner
  repeat
    EndFrame()
  until cutscenelandingskippable == 1
  PrepareSkipCutscene()
  repeat
    if GetCurrentMissionAttempted() == true and CheckSkipCutscene() then
      Kill(cutscenelanding)
      DebugOut("Killed cutscenelanding")
      cutscenelandingfinished = 1
    end
    EndFrame()
  until cutscenelandingfinished == 1
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetViewDistanceAdjustment(300, 5)
  GunshipPatrol = 3
  Spawn(Air_Vehicle.XGunship1)
  Spawn(Air_Vehicle.XGunship2)
  if IsDead(Air_Vehicle.XGunship2) == false then
    Kill(Air_Vehicle.XGunship2)
  end
  if IsDead(Air_Vehicle.XGunship1) then
    ReviveFullUnitCarrier(flag.TYPE_XYLVANIAN, flag.GTYPE_GRUNT, Air_Vehicle.XGunship1, 11, -180, 270, 20)
  end
  Teleport(Air_Vehicle.XGunship1, -278, 300, 180, 20)
  WaitFor(0.1)
  FollowWaypoint(Air_Vehicle.XGunship1, Waypoint.GunshipPatrol3, 0, 0, constant.ORDER_NORMAL)
  Kill(cutscenelanding)
  CleanupSkipCutscene()
  ClearMessageQueue()
  notincutscene = 0
  Despawn(Water_Vehicle.CaveDreadnought1, true)
  Despawn(Water_Vehicle.CaveDreadnought2, true)
  Despawn(Water_Vehicle.CaveDreadnought3, true)
  Despawn(Water_Vehicle.CaveDreadnought4, true)
  SetObjectiveData(Objective.SolarAA, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.SolarAA, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective.SolarMortar, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective_Marker.SolarMortar, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective.CountAATowers02, constant.OBJECTIVE_DATA_VISIBLE, 1)
  SetObjectiveData(Objective.CountHelipad, constant.OBJECTIVE_DATA_VISIBLE, 1)
  Spawn(Air_Vehicle.TAirTransport1)
  Spawn(Air_Vehicle.TAirTransport2)
  ExitVehicle(Troop.TAirTransport1Pilot2, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport1Pilot3, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport1Pilot4, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport1Pilot5, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport1Pilot6, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport2Pilot2, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport2Pilot3, constant.ID_NONE)
  ExitVehicle(Troop.TAirTransport2Pilot4, constant.ID_NONE)
  ExitVehicle(Ground_Vehicle.TLightTank1, constant.ID_NONE)
  Teleport(Ground_Vehicle.TLightTank1, -211, -71, 320, 20)
  Teleport(Troop.TAirTransport1Pilot2, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot3, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot4, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot5, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport1Pilot6, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot2, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot3, -175, -100, 320, 20)
  Teleport(Troop.TAirTransport2Pilot4, -175, -100, 320, 20)
  AddToGroup(Unit_Group.LandUnits, Ground_Vehicle.TLightTank1)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport1Pilot2)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport1Pilot3)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport1Pilot4)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport1Pilot5)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport1Pilot6)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport2Pilot2)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport2Pilot3)
  AddToGroup(Unit_Group.LandUnits, Troop.TAirTransport2Pilot4)
  AddToGroup(Unit_Group.Player_Army, Ground_Vehicle.TLightTank1)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport1Pilot2)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport1Pilot3)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport1Pilot4)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport1Pilot5)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport1Pilot6)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport2Pilot2)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport2Pilot3)
  AddToGroup(Unit_Group.Player_Army, Troop.TAirTransport2Pilot4)
  StoreSummaryMessage(constant.PLAYER_ONE, 59, constant.ARMY_TUNDRAN, SpriteID.CO_T_Nova_Sad)
  StoreSummaryMessage(constant.PLAYER_ONE, 61, constant.ARMY_XYLVANIAN, SpriteID.CO_X_Vlad_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 62, constant.ARMY_TUNDRAN, SpriteID.CO_T_Nova_Happy)
  StoreSummaryMessage(constant.PLAYER_ONE, 63, constant.ARMY_TUNDRAN, SpriteID.CO_T_Nova_Happy)
  SetCamera(Camera.Player1Cam, constant.PLAYER_ONE)
  ForceUnitTransfer(constant.PLAYER_ONE, Ground_Vehicle.TLightTank1, true, true)
  Despawn(Troop.DummyGrunt)
  EndIntro()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  UnfreezePlayer(constant.PLAYER_ONE)
  PauseTimerActive = 0
  SetInvulnerable(flag.TYPE_TUNDRAN, false)
  SetInvulnerable(flag.TYPE_XYLVANIAN, false)
  PhoneMessage(67, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE)
  PhoneMessage(19, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_ONE)
  PhoneMessageWithObjective(69, constant.ID_NONE, constant.ARMY_TUNDRAN, 0, SpriteID.CO_T_Nova_Sad, constant.PLAYER_ONE, false, constant.NEW_SECONDARY_OBJECTIVE)
  beachlandingcomplete = 1
  GoToArea(Air_Vehicle.TAirTransport1, 623, -179, 5, 0, constant.ORDER_FORCED)
  GoToArea(Air_Vehicle.TAirTransport2, 625, -181, 5, 0, constant.ORDER_FORCED)
  GoToArea(Troop.XHoseVet1, -183, -95, 5, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.XHoseVet2, -183, -95, 5, 0, constant.ORDER_NORMAL)
  GoToArea(Troop.XHoseVet3, -183, -95, 5, 0, constant.ORDER_NORMAL)
  WaitFor(20)
  Despawn(Air_Vehicle.TAirTransport1)
  Despawn(Air_Vehicle.TAirTransport2)
  while true do
    ListScoringUnits()
    WaitFor(5)
    EndFrame()
  end
end
