function Functions(owner)
  function KillScripts()
    Kill(scriptBoatGameFlow)
    Kill(scriptCutscene)
    Kill(scriptCutsceneAbort)
    Kill(scriptCutsceneLanding)
    Kill(scriptCutsceneLandingAbort)
    Kill(scriptCutsceneOutro)
    Kill(scriptDespawnUnits)
    Kill(scriptGhostTown)
    Kill(scriptMessages)
    Kill(scriptObjectiveBattleship)
    Kill(scriptObjectiveDreadnought)
    Kill(scriptObjectiveFrigates)
    Kill(scriptObjectiveMarkerBattleships)
    Kill(scriptObjectiveMarkerFrigates)
    Kill(scriptObjectiveMarkerSubmarines)
    Kill(scriptObjectiveSubmarines)
    Kill(scriptPOWCampMain)
    Kill(scriptPOWCampMortar)
  end
end
