function C1M4_Cutscene(owner)
  cutscenes = owner
  FreezePlayer()
  StartIntro()
  SetCamera(Camera.Cam1)
  CameraSetTarget(Camera.Cam1, Waypoint.Entity0043)
  CameraSetWaypoint(Camera.Cam1, Waypoint.Entity0040)
  GoToArea(Troop.TGrunt24, -254, -573, 1)
  WaitFor(1)
  GoToArea(Troop.TGrunt27, -263, -587, 1)
  PhoneMessage(57, 0, 0, 6, SpriteID.CO_WF_Betty_Happy)
  WaitFor(2)
  GoToArea(Ground_Vehicle.TTank6, -242, -593, 1)
  WaitFor(9)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam2)
  CameraSetTarget(Camera.Cam2, Ground_Vehicle.WF_Recon)
  CameraSetWaypoint(Camera.Cam2, Waypoint.Entity0047)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(58, 0, 0, 6, SpriteID.CO_WF_Betty_Happy)
  WaitFor(9)
  ClearMessageQueue()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCamera(Camera.Cam3)
  CameraSetTarget(Camera.Cam3, Waypoint.Entity0053)
  CameraSetWaypoint(Camera.Cam3, Waypoint.Entity0051)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(59, 0, 0, 6, SpriteID.CO_WF_Betty_Happy)
  WaitFor(8)
  DebugOut("Cutscene has run its natural course")
  cutscene = 1
end
