function CUTSCENE(owner)
  cutscene = owner
  StartIntro()
  PrepareSkipCutscene()
  if IsNetworkPlayer(constant.PLAYER_ONE) then
    SetCamera(Camera.cutscenecamplayer1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneWF1target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneWF1)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(1, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(12.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneXY2target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneXY2)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(3, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneWF3target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneWF3)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(5, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
    WaitFor(14)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player1.cutsceneskipped = 1
  end
  if IsNetworkPlayer(constant.PLAYER_TWO) then
    SetCamera(Camera.cutscenecamplayer1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneXY1target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneXY1)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(2, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_TWO)
    WaitFor(12.5)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneWF2target)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneWF2)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(4, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_TWO)
    WaitFor(10)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    CameraSetTarget(Camera.cutscenecamplayer1, Waypoint.cutsceneXY3)
    CameraSetWaypoint(Camera.cutscenecamplayer1, Waypoint.cutsceneXY3target)
    CameraSetFOV(Camera.cutscenecamplayer1, 60, constant.IMMEDIATE, constant.NO_WAIT)
    CameraFade(constant.FADE_IN, constant.WAIT, 1)
    PhoneMessage(6, constant.ID_NONE, constant.ARMY_XYLVANIAN, 0, SpriteID.CO_X_Vlad_Happy, constant.PLAYER_TWO)
    WaitFor(14)
    CameraFade(constant.FADE_OUT, constant.WAIT, 1)
    netvariable.player2.cutsceneskipped = 1
  end
  EndFrame()
end
