function Cutscene_Mid_Docks(owner)
  MidCutsceneDocks = owner
  Despawn(Ground_Vehicle.SEHtank1)
  Despawn(Ground_Vehicle.SEHtank2)
  Despawn(Air_Vehicle.cutscenebomber1)
  Despawn(Air_Vehicle.cutscenebomber2)
  Despawn(Air_Vehicle.cutsceneairtransport1)
  Despawn(Air_Vehicle.cutsceneairtransport2)
  Despawn(Troop.cutscenegrunt10)
  Despawn(Troop.cutscenegrunt11)
  Despawn(Troop.cutscenegrunt12)
  Despawn(Troop.cutscenegrunt13)
  Despawn(Troop.cutscenegrunt14)
  Despawn(Troop.cutscenegrunt15)
  repeat
    EndFrame()
  until MidCutsceneDocksSetup == 1
  Spawn(Ground_Vehicle.SEHtank1)
  Spawn(Ground_Vehicle.SEHtank2)
  Spawn(Air_Vehicle.cutscenebomber1)
  Spawn(Air_Vehicle.cutscenebomber2)
  Spawn(Air_Vehicle.cutsceneairtransport1)
  Spawn(Air_Vehicle.cutsceneairtransport2)
  AttackTarget(Air_Vehicle.cutscenebomber1, Capture_Point.dockCP, constant.ORDER_FORCED)
  AttackTarget(Air_Vehicle.cutscenebomber2, Building.BombDropTarget, constant.ORDER_FORCED)
  LandAirUnit(Air_Vehicle.cutsceneairtransport1, -65, 515, constant.ORDER_FORCED)
  LandAirUnit(Air_Vehicle.cutsceneairtransport2, -120, 460, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until ThirdEncounterEnd == true
  ClearMessageQueue()
  FreezePlayer()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  PauseTimerActive = 1
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  Spawn(Troop.cutscenegrunt10)
  Spawn(Troop.cutscenegrunt11)
  Spawn(Troop.cutscenegrunt12)
  Spawn(Troop.cutscenegrunt13)
  Spawn(Troop.cutscenegrunt14)
  Spawn(Troop.cutscenegrunt15)
  FollowWaypoint(Ground_Vehicle.SEHtank1, Waypoint.SEHeavyTank01Path02, 1, 1, constant.ORDER_FORCED)
  FollowWaypoint(Ground_Vehicle.SEHtank2, Waypoint.SEHeavyTank02Path, 1, 1, constant.ORDER_FORCED)
  StartOutro()
  SetCamera(Camera.cutscenecam)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene1target)
  CameraSetFOV(Camera.cutscenecam, 45, constant.IMMEDIATE, 0, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(1, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  WaitFor(3)
  SetHealthPercent(Ground_Vehicle.SEHtank2, 15)
  WaitFor(0.5)
  Kill(Ground_Vehicle.SEHtank2)
  StopAndGuard(Ground_Vehicle.SEHtank1)
  WaitFor(0.25)
  SetHealthPercent(Ground_Vehicle.SEHtank1, 15)
  WaitFor(0.5)
  Kill(Ground_Vehicle.SEHtank1)
  EnableWeapon(Air_Vehicle.cutscenebomber1, 0)
  EnableWeapon(Air_Vehicle.cutscenebomber2, 0)
  CameraSetFOV(Camera.cutscenecam, 90, constant.SMOOTH, 0.25, constant.NO_WAIT)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(0.5)
  PhoneMessage(60, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(0.5)
  PhoneMessageWithObjective(3, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(0.9)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetCapturePointHeight(Capture_Point.dockCP, constant.ARMY_ANGLO, 100)
  Teleport(Troop.WFgrunt1, -85.474, -113.312, 45, 0)
  Teleport(Troop.WFgrunt2, -83.052, -116.29, 45, 0)
  Teleport(Troop.WFgrunt3, -80.479, -118.612, 45, 0)
  Teleport(Troop.WFgrunt4, -89.763, -114.776, 45, 0)
  Teleport(Troop.WFgrunt5, -87.19, -117.501, 45, 0)
  Teleport(Troop.WFgrunt6, -84.414, -120.379, 45, 0)
  WFTeleportHack = 1
  SetHealthPercent(Troop.cutscenegrunt10, 50)
  SetHealthPercent(Troop.cutscenegrunt11, 50)
  SetHealthPercent(Troop.cutscenegrunt12, 50)
  SetHealthPercent(Troop.cutscenegrunt13, 50)
  SetHealthPercent(Troop.cutscenegrunt14, 50)
  SetHealthPercent(Troop.cutscenegrunt15, 50)
  GoToArea(Troop.cutscenegrunt10, -70, -103, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  GoToArea(Troop.cutscenegrunt11, -70, -103, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  GoToArea(Troop.cutscenegrunt12, -75, -111, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  GoToArea(Troop.cutscenegrunt13, -75, -111, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  GoToArea(Troop.cutscenegrunt14, -70, -103, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  GoToArea(Troop.cutscenegrunt15, -70, -103, 5, 0, constant.ORDER_FORCED, constant.FORMATION_ALLOWED)
  ClearMessageQueue()
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene2)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene2target)
  CameraSetFOV(Camera.cutscenecam, 60, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(46, constant.ID_NONE, constant.ARMY_WF, 0, SpriteID.CO_WF_Betty_Sad, constant.PLAYER_ONE)
  WaitFor(3)
  WFTeleportHack = 0
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  EnableWeapon(Troop.cutscenegrunt10, 0)
  EnableWeapon(Troop.cutscenegrunt11, 0)
  EnableWeapon(Troop.cutscenegrunt12, 0)
  EnableWeapon(Troop.cutscenegrunt13, 0)
  EnableWeapon(Troop.cutscenegrunt14, 0)
  EnableWeapon(Troop.cutscenegrunt15, 0)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  MidCutsceneEndedDocks = true
end
