function Cutscene_Outro(owner)
  outrocutscene = owner
  Despawn(Water_Vehicle.CutsceneSolarFrigate01)
  Despawn(Water_Vehicle.CutsceneSolarFrigate02)
  Despawn(Water_Vehicle.CutsceneSolarFrigate03)
  Despawn(Air_Vehicle.CutsceneAngloBomber01)
  Despawn(Air_Vehicle.CutsceneAngloBomber02)
  repeat
    EndFrame()
  until MidCutsceneEndedDocks == true
  WaitFor(10)
  repeat
    EndFrame()
  until NumItemsInArea(Map_Zone.docks, flag.TYPE_SOLAR) > 0 and CheckCapturePoint(Capture_Point.dockCP, constant.ARMY_SOLAR, 97, 2, 0) == true
  SetCapturePointHeight(Capture_Point.dockCP, constant.ARMY_SOLAR, 100)
  SetInstallationOwner(Strategic_Installation.Docks, constant.ARMY_SOLAR)
  SetObjectiveData(Objective_Marker.RecaptureBase, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective.RecaptureBase, constant.OBJECTIVE_DATA_STATE, 1)
  StopScoringTimer()
  MissionWin = 1
  DebugOut("Mission Won!")
  DebugOut("Time taken - ", GetTime())
  repeat
    EndFrame()
  until MissionWin == 1 and ReinforcementsCutscenePlaying == 0
  ClearMessageQueue()
  Kill(WinLoseScript)
  Kill(MissionFlow)
  Kill(MissionFlow2)
  Kill(CutsceneHelipad)
  Kill(midcutscene2)
  Kill(WFOutpost)
  Kill(COMessages)
  FreezePlayer(constant.PLAYER_ONE)
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 0.5)
  StartOutro()
  Despawn(Air_Vehicle.AIairtransport3)
  Despawn(Air_Vehicle.AIairtransport4)
  Despawn(Air_Vehicle.AIairtransport5)
  Despawn(Air_Vehicle.AIbomber)
  Despawn(Air_Vehicle.AIbomber1)
  Despawn(Air_Vehicle.AIbomber2)
  Despawn(Air_Vehicle.AIbomber3)
  Despawn(Air_Vehicle.AIbomber4)
  Despawn(Troop.AIgruntD1)
  Despawn(Troop.AIgruntD2)
  Despawn(Troop.AIgruntD3)
  Despawn(Troop.AIgruntD4)
  Despawn(Troop.AIgruntE1)
  Despawn(Troop.AIgruntE2)
  Despawn(Troop.AIgruntE3)
  Despawn(Troop.AIgruntE4)
  Despawn(Troop.AIgruntF1)
  Despawn(Troop.AIgruntF2)
  Despawn(Troop.AIgruntF3)
  Despawn(Troop.AIgruntF4)
  Despawn(Troop.AIgruntG1)
  Despawn(Troop.AIgruntG2)
  Despawn(Troop.AIgruntG3)
  Despawn(Troop.AIgruntG4)
  Despawn(Troop.AIgruntG5)
  Despawn(Troop.AIgruntG6)
  Despawn(Troop.AIgruntG7)
  Despawn(Troop.AIgruntG8)
  Despawn(Ground_Vehicle.AIlighttank5)
  Despawn(Ground_Vehicle.AIlighttank6)
  Despawn(Ground_Vehicle.AIlighttank7)
  Teleport(Ground_Vehicle.SEaatank1, GetObjectXPosition(Waypoint.SEAATank1OutroPath), GetObjectZPosition(Waypoint.SEAATank1OutroPath), 70, 0)
  StopAndGuard(Ground_Vehicle.SEaatank1)
  if IsActive(Ground_Vehicle.SEaatank2) then
    Teleport(Ground_Vehicle.SEaatank2, GetObjectXPosition(Waypoint.SEAATank2OutroPath), GetObjectZPosition(Waypoint.SEAATank2OutroPath), 90, 0)
    StopAndGuard(Ground_Vehicle.SEaatank2)
  end
  Teleport(Troop.SEgrunt1, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 20)
  Teleport(Troop.SEgrunt2, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 20)
  Teleport(Troop.SEgrunt3, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 20)
  Teleport(Troop.SEgrunt4, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 20)
  Teleport(Troop.SEgrunt5, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 20)
  Teleport(Troop.SEflame1, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 30)
  Teleport(Troop.SEflame2, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 30)
  Teleport(Troop.SEflame7, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 30)
  Teleport(Troop.SEflame8, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 30)
  Teleport(Troop.SEflame9, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 30)
  Teleport(Troop.SEbazooka2, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 40)
  Teleport(Troop.SEbazooka3, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 40)
  Teleport(Troop.SEbazooka4, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 40)
  Teleport(Troop.SEbazooka5, GetObjectXPosition(Capture_Point.dockCP), GetObjectZPosition(Capture_Point.dockCP), 80, 40)
  EnableWeapon(Ground_Vehicle.SEaatank1, 0)
  EnableWeapon(Ground_Vehicle.SEaatank2, 0)
  VictoryDance(constant.ARMY_SOLAR, 1)
  SetCamera(Camera.cutscenecam)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.outrocutscene1)
  CameraSetTarget(Camera.cutscenecam, Waypoint.outrocutscene1target)
  CameraSetFOV(Camera.cutscenecam, 50, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.cutscenecam, 90, constant.SMOOTH, 2, constant.NO_WAIT)
  CameraFade(constant.FADE_IN, constant.WAIT, 0.5)
  ClearMessageQueue()
  PhoneMessage(32, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  Spawn(Water_Vehicle.CutsceneSolarFrigate01)
  Spawn(Water_Vehicle.CutsceneSolarFrigate02)
  Spawn(Water_Vehicle.CutsceneSolarFrigate03)
  Spawn(Air_Vehicle.CutsceneAngloBomber01)
  Spawn(Air_Vehicle.CutsceneAngloBomber02)
  SetUnitInvulnerable(Air_Vehicle.CutsceneAngloBomber01, true)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate01, 0)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate02, 0)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate03, 0)
  EnableWeapon(Air_Vehicle.CutsceneAngloBomber01, 0)
  EnableWeapon(Air_Vehicle.CutsceneAngloBomber02, 0)
  FollowWaypoint(Air_Vehicle.CutsceneAngloBomber01, Waypoint.CutsceneAngloBomber01Path, 0, 0, constant.ORDER_FORCED)
  FollowWaypoint(Air_Vehicle.CutsceneAngloBomber02, Waypoint.CutsceneAngloBomber02Path, 0, 0, constant.ORDER_FORCED)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.outrocutscene2)
  CameraSetTarget(Camera.cutscenecam, Waypoint.outrocutscene2target)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(33, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  PhoneMessage(34, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  WaitFor(2.5)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate02, 1)
  AttackTarget(Water_Vehicle.CutsceneSolarFrigate02, Air_Vehicle.CutsceneAngloBomber02)
  WaitFor(0.5)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate01, 1)
  AttackTarget(Water_Vehicle.CutsceneSolarFrigate01, Air_Vehicle.CutsceneAngloBomber02)
  WaitFor(3)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate01, 0)
  EnableWeapon(Water_Vehicle.CutsceneSolarFrigate02, 0)
  WaitFor(4)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  OutroCutsceneEnded = true
end
