function Cutscene_Mid_Solar_Bazookas(owner)
  midcutscene = owner
  EnableWeapon(Ground_Vehicle.AIlighttank1, 0)
  repeat
    EndFrame()
  until BeginBazookaCutscene == true
  ClearMessageQueue()
  FreezePlayer()
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  SetInvulnerable(flag.TYPE_SOLAR, 1)
  PauseTimerActive = 1
  Teleport(Troop.SEbazooka2, GetObjectXPosition(Waypoint.BazookaRun02), GetObjectZPosition(Waypoint.BazookaRun02), 300)
  Teleport(Troop.SEbazooka3, GetObjectXPosition(Waypoint.BazookaRun03), GetObjectZPosition(Waypoint.BazookaRun03), 300)
  Teleport(Troop.SEbazooka4, GetObjectXPosition(Waypoint.BazookaRun04), GetObjectZPosition(Waypoint.BazookaRun04), 300)
  Teleport(Troop.SEbazooka5, GetObjectXPosition(Waypoint.BazookaRun05), GetObjectZPosition(Waypoint.BazookaRun05), 300)
  SetActive(Troop.SEbazooka2, constant.ACTIVE)
  SetActive(Troop.SEbazooka3, constant.ACTIVE)
  SetActive(Troop.SEbazooka4, constant.ACTIVE)
  SetActive(Troop.SEbazooka5, constant.ACTIVE)
  Spawn(Building.CutsceneAngloTankShot)
  FollowWaypoint(Ground_Vehicle.AIlighttank1, Waypoint.BazookaRun, 0, 0, constant.ORDER_FORCED)
  SetCamera(Camera.cutscenecam)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.bazookashot)
  CameraSetTarget(Camera.cutscenecam, Waypoint.bazookashottarget)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(18, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  EnableWeapon(Troop.SEbazooka2, 1)
  EnableWeapon(Troop.SEbazooka3, 1)
  EnableWeapon(Troop.SEbazooka4, 1)
  EnableWeapon(Troop.SEbazooka5, 1)
  WaitFor(4)
  EnableWeapon(Ground_Vehicle.AIlighttank1, 1)
  AttackTarget(Ground_Vehicle.AIlighttank1, Building.CutsceneAngloTankShot, constant.ORDER_NORMAL)
  WaitFor(0.5)
  EnableWeapon(Ground_Vehicle.AIlighttank1, 0)
  WaitFor(0.5)
  AttackTarget(Troop.SEbazooka5, Ground_Vehicle.AIlighttank1, constant.ORDER_FORCED)
  WaitFor(0.5)
  AttackTarget(Troop.SEbazooka3, Ground_Vehicle.AIlighttank1, constant.ORDER_FORCED)
  WaitFor(1)
  AttackTarget(Troop.SEbazooka4, Ground_Vehicle.AIlighttank1, constant.ORDER_FORCED)
  WaitFor(0.5)
  AttackTarget(Troop.SEbazooka2, Ground_Vehicle.AIlighttank1, constant.ORDER_FORCED)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  MidCutsceneEnded = true
end
