function Cutscene_Intro(owner)
  introcutscene = owner
  Despawn(Troop.WFgrunt1)
  Despawn(Troop.SEbazooka5)
  Despawn(Water_Vehicle.AItransport2)
  Despawn(Water_Vehicle.AItransport3)
  Despawn(Water_Vehicle.AItransport4)
  Despawn(Water_Vehicle.AItransport5)
  Despawn(Ground_Vehicle.CutsceneLightTank02)
  SetUnitInvulnerable(Water_Vehicle.AItransport1, true)
  SetUnitInvulnerable(Water_Vehicle.AItransport1target, true)
  SetUnitInvulnerable(Water_Vehicle.AItransport2target, true)
  SetUnitInvulnerable(Water_Vehicle.AItransport3target, true)
  SetUnitInvulnerable(Water_Vehicle.AItransport4target, true)
  SetUnitInvulnerable(Water_Vehicle.CutsceneNavalTransport01, true)
  SetHealthPercent(Water_Vehicle.CutsceneNavalTransport02, 55)
  EnableWeapon(Building.NavalCannon1, 0)
  EnableWeapon(Ground_Vehicle.CutsceneLightTank01, 0)
  SetCamera(Camera.cutscenecam)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene3)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene3target)
  StartIntro()
  CameraSetFOV(Camera.cutscenecam, 60, constant.IMMEDIATE, 0, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  AttackTarget(Building.NavalCannon2, Water_Vehicle.CutsceneNavalTransport02, constant.ORDER_FORCED)
  WaitFor(0.5)
  PhoneMessage(6, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  WaitFor(1)
  BeachWaterUnit(Water_Vehicle.CutsceneNavalTransport03, GetObjectXPosition(Waypoint.AItransport1LandingPoint), GetObjectZPosition(Waypoint.AItransport1LandingPoint), 180, 0)
  WaitFor(1)
  EnableWeapon(Building.NavalCannon1, 1)
  AttackTarget(Building.NavalCannon1, Water_Vehicle.CutsceneNavalTransport01, constant.ORDER_FORCED)
  WaitFor(0.2)
  Kill(Water_Vehicle.CutsceneNavalTransport02)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(0.5)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  ExitVehicle(Troop.AIAirTransport01Pilot, Air_Vehicle.AIAirTransport01)
  Despawn(Troop.AIAirTransport01Pilot)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene5)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene5target)
  CameraSetFOV(Camera.cutscenecam, 60, constant.IMMEDIATE, 0, constant.NO_WAIT)
  CameraSetFOV(Camera.cutscenecam, 90, constant.SMOOTH, 0.5, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  PhoneMessage(7, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  Spawn(Troop.SEbazooka5)
  Teleport(Troop.SEbazooka5, GetObjectXPosition(Waypoint.IntroBazookaPathEnd), GetObjectZPosition(Waypoint.IntroBazookaPathEnd), 235, 0)
  WaitFor(1)
  ExitVehicle(Ground_Vehicle.CutsceneLightTank01, Water_Vehicle.CutsceneNavalTransport03)
  PutUnitInVehicle(Ground_Vehicle.CutsceneLightTank01, Air_Vehicle.AIAirTransport01, 6)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  WaitFor(1.25)
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CameraSetWaypoint(Camera.cutscenecam, Waypoint.cutscene4)
  CameraSetTarget(Camera.cutscenecam, Waypoint.cutscene4target)
  CameraSetFOV(Camera.cutscenecam, 65, constant.IMMEDIATE, 0, constant.NO_WAIT)
  ClearMessageQueue()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  ClearMessageQueue()
  PhoneMessageWithObjective(8, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE, false, constant.NEW_PRIMARY_OBJECTIVE)
  repeat
    EndFrame()
  until GetNumItemsInMessageQueue(constant.PLAYER_ONE) == 0
  CameraFade(constant.FADE_OUT, constant.WAIT, 1)
  CutsceneEnded = true
end
