function Cutscene_Intro_Skip(owner)
  WaitFor(2)
  repeat
    if GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      Kill(introcutscene)
      DebugOut("Intro Cutscene skipped")
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      CutsceneEnded = true
      EndFrame()
    else
    end
    EndFrame()
  until CutsceneEnded == true
  EndIntro()
  Kill(introcutscene)
  ClearMessageQueue()
  StoreSummaryMessage(6, constant.ARMY_SOLAR, SpriteID.CO_SE_Aqira_Happy)
  StoreSummaryMessage(7, constant.ARMY_SOLAR, SpriteID.CO_SE_Aqira_Happy)
  StoreSummaryMessage(8, constant.ARMY_SOLAR, SpriteID.CO_SE_Aqira_Happy)
  ExitVehicle(Troop.AIAirTransport01Pilot, Air_Vehicle.AIAirTransport01)
  Despawn(Troop.AIAirTransport01Pilot)
  ExitVehicle(Ground_Vehicle.CutsceneLightTank01, Air_Vehicle.AIAirTransport01)
  Despawn(Ground_Vehicle.CutsceneLightTank01)
  Despawn(Troop.cutscenegrunt6)
  Despawn(Troop.cutscenegrunt7)
  Despawn(Troop.cutscenegrunt8)
  Despawn(Troop.cutscenegrunt9)
  Despawn(Water_Vehicle.CutsceneNavalTransport01)
  Despawn(Water_Vehicle.CutsceneNavalTransport02)
  Despawn(Water_Vehicle.CutsceneNavalTransport03)
  Despawn(Water_Vehicle.AItransport2target)
  Despawn(Water_Vehicle.AItransport3target)
  Despawn(Water_Vehicle.AItransport4target)
  Despawn(Water_Vehicle.AItransport5target)
  Teleport(Water_Vehicle.AItransport1target, GetObjectXPosition(Water_Vehicle.AItransport1target), GetObjectZPosition(Water_Vehicle.AItransport1target), 180, 0)
  Despawn(Ground_Vehicle.CutsceneLightTank01)
  Despawn(Ground_Vehicle.CutsceneLightTank02)
  Spawn(Water_Vehicle.AItransport1)
  Spawn(Ground_Vehicle.AIlighttank1)
  Spawn(Ground_Vehicle.AIlighttank2)
  Spawn(Troop.SEbazooka5)
  GoToArea(Troop.SEbazooka5, GetObjectXPosition(Waypoint.IntroBazookaPathEnd), GetObjectZPosition(Waypoint.IntroBazookaPathEnd), 1, 0, constant.ORDER_FORCED)
  SetActive(Ground_Vehicle.AIlighttank1, constant.INACTIVE)
  SetActive(Building.NavalCannon1, constant.INACTIVE)
  SetActive(Building.NavalCannon2, constant.INACTIVE)
  EnableWeapon(Building.NavalCannon1, 0)
  EnableWeapon(Building.NavalCannon2, 0)
  SetActive(Troop.SEbazooka2, constant.INACTIVE)
  SetActive(Troop.SEbazooka3, constant.INACTIVE)
  SetActive(Troop.SEbazooka4, constant.INACTIVE)
  SetActive(Troop.SEbazooka5, constant.INACTIVE)
  EnableWeapon(Troop.SEbazooka2, constant.INACTIVE)
  EnableWeapon(Troop.SEbazooka3, constant.INACTIVE)
  EnableWeapon(Troop.SEbazooka4, constant.INACTIVE)
  EnableWeapon(Troop.SEbazooka5, constant.INACTIVE)
  Teleport(Troop.AIbazooka1, -305.391, -622.968, 155, 0)
  Teleport(Troop.AIbazooka2, -308.808, -624.734, 150, 0)
  Teleport(Troop.AIbazooka3, -310.022, -620.153, 155, 0)
  Teleport(Troop.AIbazooka4, -309.195, -616.788, 155, 0)
  SetActive(Troop.AIbazooka1, constant.INACTIVE)
  SetActive(Troop.AIbazooka2, constant.INACTIVE)
  SetActive(Troop.AIbazooka3, constant.INACTIVE)
  SetActive(Troop.AIbazooka4, constant.INACTIVE)
  SetUnitInvulnerable(Ground_Vehicle.SEaatank1, true)
  SetUnitInvulnerable(Troop.AIbazooka1, true)
  SetUnitInvulnerable(Troop.AIbazooka2, true)
  SetUnitInvulnerable(Troop.AIbazooka3, true)
  SetUnitInvulnerable(Troop.AIbazooka4, true)
  Spawn(Troop.WFgrunt1)
  Teleport(Troop.WFgrunt1, -85.474, -113.312, 45, 0)
  Teleport(Troop.WFgrunt2, -83.052, -116.29, 45, 0)
  Teleport(Troop.WFgrunt3, -80.479, -118.612, 45, 0)
  Teleport(Troop.WFgrunt4, -89.763, -114.776, 45, 0)
  Teleport(Troop.WFgrunt5, -87.19, -117.501, 45, 0)
  Teleport(Troop.WFgrunt6, -84.414, -120.379, 45, 0)
  SetActive(Troop.WFgrunt1, constant.INACTIVE)
  SetActive(Troop.WFgrunt2, constant.INACTIVE)
  SetActive(Troop.WFgrunt3, constant.INACTIVE)
  SetActive(Troop.WFgrunt4, constant.INACTIVE)
  SetActive(Troop.WFgrunt5, constant.INACTIVE)
  SetActive(Troop.WFgrunt6, constant.INACTIVE)
  SetActive(Capture_Point.HelipadUntargetable, constant.INACTIVE)
  SetObjectiveData(Objective_Marker.NavalGunWaypoint01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetFunctionIndicatorState(true)
  SetEnableGuardMode(constant.PLAYER_ONE, false)
  FollowUnit(Troop.SEgrunt1, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEgrunt2, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEgrunt3, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEgrunt4, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEgrunt5, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEflame2, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEflame7, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEflame8, Troop.SEflame1, -1, 0)
  FollowUnit(Troop.SEflame9, Troop.SEflame1, -1, 0)
  FollowUnit(Ground_Vehicle.SEaatank1, Troop.SEflame1, -1, 0)
  SetCamera(Camera.player1cam)
  EndFrame()
  ResetCommandBar()
  ResetHealthAndScoreTotals()
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(UnfreezeDelay)
  UnfreezePlayer(constant.PLAYER_ONE)
  StartScoringTimer()
  ClearMessageQueue()
  PhoneMessage(91, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  WaitFor(10)
  SetUnitInvulnerable(Water_Vehicle.AItransport1, false)
  SetUnitInvulnerable(Water_Vehicle.AItransport1target, false)
  SetUnitInvulnerable(Water_Vehicle.AItransport2target, false)
  SetUnitInvulnerable(Water_Vehicle.AItransport3target, false)
  SetUnitInvulnerable(Water_Vehicle.AItransport4target, false)
end
