function Mission_Flow_Part_2(owner)
  MissionFlow2 = owner
  repeat
    EndFrame()
  until GuardTutorialEnd == true
  WaitFor(2)
  if GetCurrentMissionCompleted() ~= true or GetTutorialMode() ~= false then
    PhoneMessage(10, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  end
  SetActive(Building.NavalCannon1, constant.ACTIVE)
  SetActive(Building.NavalCannon2, constant.ACTIVE)
  WaitFor(2.5)
  PhoneMessage(64, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Happy, constant.PLAYER_ONE)
  EnableWeapon(Building.NavalCannon1, 1)
  EnableWeapon(Building.NavalCannon2, 1)
  BeachWaterUnit(Water_Vehicle.AItransport1, GetObjectXPosition(Waypoint.AItransport1LandingPoint), GetObjectZPosition(Waypoint.AItransport1LandingPoint), 180, 1)
  GoToArea(Water_Vehicle.AItransport1target, GetObjectXPosition(Waypoint.AITransport1TargetPoint), GetObjectZPosition(Waypoint.AITransport1TargetPoint), 10, 0, constant.ORDER_FORCED)
  WaitFor(2)
  Spawn(Water_Vehicle.AItransport2)
  BeachWaterUnit(Water_Vehicle.AItransport2, GetObjectXPosition(Waypoint.AItransport2LandingPoint), GetObjectZPosition(Waypoint.AItransport2LandingPoint), 180, 1)
  SetUnitInvulnerable(Water_Vehicle.AItransport1, true)
  WaitFor(5)
  SetUnitInvulnerable(Water_Vehicle.AItransport1, false)
  WaitFor(25)
  Spawn(Water_Vehicle.AItransport2target)
  Teleport(Water_Vehicle.AItransport2target, GetObjectXPosition(Waypoint.ReviveNavalDummy2), GetObjectZPosition(Waypoint.ReviveNavalDummy2), 180, 0)
  GoToArea(Water_Vehicle.AItransport2target, GetObjectXPosition(Waypoint.AITransport2TargetPoint), GetObjectZPosition(Waypoint.AITransport2TargetPoint), 10, 0, constant.ORDER_FORCED)
  Spawn(Water_Vehicle.AItransport3)
  BeachWaterUnit(Water_Vehicle.AItransport3, GetObjectXPosition(Waypoint.AItransport3LandingPoint), GetObjectZPosition(Waypoint.AItransport3LandingPoint), 180, 1)
  WaitFor(25)
  Spawn(Water_Vehicle.AItransport3target)
  Teleport(Water_Vehicle.AItransport3target, GetObjectXPosition(Waypoint.ReviveNavalDummy3), GetObjectZPosition(Waypoint.ReviveNavalDummy3), 180, 0)
  GoToArea(Water_Vehicle.AItransport3target, GetObjectXPosition(Waypoint.AITransport3TargetPoint), GetObjectZPosition(Waypoint.AITransport3TargetPoint), 10, 0, constant.ORDER_FORCED)
  Spawn(Water_Vehicle.AItransport4)
  BeachWaterUnit(Water_Vehicle.AItransport4, GetObjectXPosition(Waypoint.AItransport4LandingPoint), GetObjectZPosition(Waypoint.AItransport4LandingPoint), 180, 1)
  WaitFor(25)
  WaitFor(5)
  WaitFor(5)
  Spawn(Water_Vehicle.AItransport6)
  BeachWaterUnit(Water_Vehicle.AItransport6, GetObjectXPosition(Waypoint.AItransport6LandingPoint), GetObjectZPosition(Waypoint.AItransport6LandingPoint), 180, 1)
  Spawn(Water_Vehicle.AItransport7)
  BeachWaterUnit(Water_Vehicle.AItransport7, GetObjectXPosition(Waypoint.AItransport7LandingPoint), GetObjectZPosition(Waypoint.AItransport7LandingPoint), 180, 1)
  Spawn(Water_Vehicle.AItransport4target)
  Teleport(Water_Vehicle.AItransport4target, GetObjectXPosition(Waypoint.ReviveNavalDummy4), GetObjectZPosition(Waypoint.ReviveNavalDummy4), 180, 0)
  GoToArea(Water_Vehicle.AItransport4target, GetObjectXPosition(Waypoint.AITransport4TargetPoint), GetObjectZPosition(Waypoint.AITransport4TargetPoint), 10, 0, constant.ORDER_FORCED)
  WaitFor(10)
  PhoneMessage(61, constant.ID_NONE, constant.ARMY_ANGLO, 0, SpriteID.CO_AI_Pierce_Sad, constant.PLAYER_ONE)
  PhoneMessage(20, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  PhoneMessage(21, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Sad, constant.PLAYER_ONE)
  WaitFor(5)
  Spawn(Water_Vehicle.AItransport5target)
  Teleport(Water_Vehicle.AItransport5target, GetObjectXPosition(Waypoint.ReviveNavalDummy5), GetObjectZPosition(Waypoint.ReviveNavalDummy5), 180, 0)
  GoToArea(Water_Vehicle.AItransport5target, GetObjectXPosition(Waypoint.AITransport5TargetPoint), GetObjectZPosition(Waypoint.AITransport5TargetPoint), 10, 0, constant.ORDER_FORCED)
  WaitFor(5)
  Spawn(Water_Vehicle.AItransport5)
  BeachWaterUnit(Water_Vehicle.AItransport5, GetObjectXPosition(Waypoint.AItransport5LandingPoint), GetObjectZPosition(Waypoint.AItransport5LandingPoint), 180, 1)
  Spawn(Water_Vehicle.AItransport8)
  BeachWaterUnit(Water_Vehicle.AItransport8, GetObjectXPosition(Waypoint.AItransport8LandingPoint), GetObjectZPosition(Waypoint.AItransport8LandingPoint), 180, 1)
  repeat
    WaitFor(1)
    EndFrame()
  until IsDead(Ground_Vehicle.AItank1) and IsDead(Ground_Vehicle.AItank2) and IsDead(Ground_Vehicle.AItank3) and IsDead(Ground_Vehicle.AItank4) and IsDead(Troop.AIboat2grunt1) and IsDead(Troop.AIboat2grunt2) and IsDead(Troop.AIboat2grunt3) and IsDead(Troop.AIboat2bazooka1) and IsDead(Troop.AIboat2bazooka2) and IsDead(Troop.AIboat4grunt1) and IsDead(Troop.AIboat4grunt2) and IsDead(Troop.AIboat4grunt3) and IsDead(Troop.AIboat4bazooka1) and IsDead(Troop.AIboat4bazooka2) and IsDead(Troop.AIboat6grunt1) and IsDead(Troop.AIboat6grunt2) and IsDead(Troop.AIboat6grunt3) and IsDead(Troop.AIboat6bazooka1) and IsDead(Troop.AIboat6bazooka2) and IsDead(Troop.AIboat7grunt1) and IsDead(Troop.AIboat7grunt2) and IsDead(Troop.AIboat7grunt3) and IsDead(Troop.AIboat7bazooka1) and IsDead(Troop.AIboat7bazooka2)
  DisableAAVehicleControls = 1
  Spawn(Air_Vehicle.AIbomber)
  SetActive(Air_Vehicle.AIbomber, 0)
  DebugOut("Beach Bomber Spawned")
  ClearMessageQueue()
  if GetCurrentMissionCompleted() ~= true or GetTutorialMode() ~= false then
    PhoneMessage(92, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  else
    PhoneMessage(90, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  end
  WaitFor(7.5)
  PauseTutorialTransfer = 1
  if GetCurrentMissionCompleted() == true and GetTutorialMode() == false then
    SetActive(Air_Vehicle.AIbomber, 1)
  end
  WaitFor(2)
  if GetCurrentMissionCompleted() ~= true or GetTutorialMode() ~= false then
    if GetPlayerUnit() == Ground_Vehicle.SEaatank1 then
      PhoneMessage(53, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
    else
      PhoneMessage(98, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
    end
    EndFrame()
  end
  PhoneMessage(93, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until IsDead(Air_Vehicle.AIbomber)
  ClearMessageQueue()
  PhoneMessageWithObjective(97, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE, false, constant.PRIMARY_OBJECTIVE_COMPLETE)
  if IsDead(Building.NavalCannon1) or IsDead(Building.NavalCannon2) then
    SetObjectiveData(Objective.DefendSEcannons1, constant.OBJECTIVE_DATA_STATE, 1)
  else
    SetObjectiveData(Objective.DefendSEcannons, constant.OBJECTIVE_DATA_STATE, 1)
  end
  SetObjectiveData(Objective_Marker.DefendSEcannon1, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.DefendSEcannon2, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 0)
  SetObjectiveData(Objective_Marker.BaseWaypoint01, constant.OBJECTIVE_MARKER_DATA_VISIBLE, 1)
  SetObjectiveData(Objective.RecaptureBase, constant.OBJECTIVE_DATA_VISIBLE, 1)
  EnableControllerItem(constant.CONTROL_TOGGLE_MAP, 0, constant.PLAYER_ONE)
  EnableControllerItem(constant.CONTROL_PAUSE, 0, constant.PLAYER_ONE)
  MidCutsceneDocksSetup = 1
  WaitFor(4)
  ThirdEncounterEnd = true
  WaitFor(3)
  repeat
    if ThirdEncounterEnd == true and GetCurrentMissionAttempted() == true and (ReadControllerState(constant.CONTROL_SKIP_CUTSCENE, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE) or ReadControllerState(constant.CONTROL_SKIP_CUTSCENE_ALT, constant.CONTROL_JUST_PRESSED, constant.PLAYER_ONE)) then
      Kill(MidCutsceneDocks)
      DebugOut("Docks cutscene skipped")
      ClearMessageQueue()
      CameraFade(constant.FADE_OUT, constant.WAIT, 1)
      MidCutsceneEndedDocks = true
    end
    EndFrame()
  until MidCutsceneEndedDocks == true
  EndIntro()
  Kill(MidCutsceneDocks)
  ClearMessageQueue()
  StoreSummaryMessage(1, constant.ARMY_SOLAR, SpriteID.CO_SE_Aqira_Sad)
  StoreSummaryMessage(60, constant.ARMY_ANGLO, SpriteID.CO_AI_Pierce_Happy)
  StoreSummaryMessage(3, constant.ARMY_SOLAR, SpriteID.CO_SE_Aqira_Sad)
  StoreSummaryMessage(46, constant.ARMY_WF, SpriteID.CO_WF_Betty_Sad)
  ExitVehicle(Troop.cutscenegrunt1, Capture_Point.dockCP)
  ExitVehicle(Troop.cutscenegrunt2, Capture_Point.dockCP)
  ExitVehicle(Troop.cutscenegrunt3, Capture_Point.dockCP)
  ExitVehicle(Troop.cutscenegrunt4, Capture_Point.dockCP)
  ExitVehicle(Troop.cutscenegrunt5, Capture_Point.dockCP)
  EndFrame()
  Despawn(Ground_Vehicle.SEHtank1)
  Despawn(Ground_Vehicle.SEHtank2)
  Despawn(Air_Vehicle.cutscenebomber1)
  Despawn(Air_Vehicle.cutscenebomber2)
  Despawn(Air_Vehicle.cutsceneairtransport1)
  Despawn(Air_Vehicle.cutsceneairtransport2)
  Despawn(Building.BombDropTarget)
  Despawn(Troop.cutscenegrunt1)
  Despawn(Troop.cutscenegrunt2)
  Despawn(Troop.cutscenegrunt3)
  Despawn(Troop.cutscenegrunt4)
  Despawn(Troop.cutscenegrunt5)
  Despawn(Troop.cutscenegrunt6)
  Despawn(Troop.cutscenegrunt7)
  Despawn(Troop.cutscenegrunt8)
  Despawn(Troop.cutscenegrunt9)
  Kill(Troop.cutscenegrunt10)
  Kill(Troop.cutscenegrunt11)
  Kill(Troop.cutscenegrunt12)
  Kill(Troop.cutscenegrunt13)
  Kill(Troop.cutscenegrunt14)
  Kill(Troop.cutscenegrunt15)
  Despawn(Water_Vehicle.AItransport1)
  Despawn(Water_Vehicle.AItransport2)
  Despawn(Water_Vehicle.AItransport3)
  Despawn(Water_Vehicle.AItransport4)
  Despawn(Water_Vehicle.AItransport5)
  Despawn(Water_Vehicle.AItransport6)
  Despawn(Water_Vehicle.AItransport7)
  Despawn(Water_Vehicle.AItransport8)
  Despawn(Water_Vehicle.AItransport1target)
  Despawn(Water_Vehicle.AItransport2target)
  Despawn(Water_Vehicle.AItransport3target)
  Despawn(Water_Vehicle.AItransport4target)
  Despawn(Building.BeachGate)
  SetHealthPercent(Troop.WFgrunt1, 100)
  SetHealthPercent(Troop.WFgrunt2, 100)
  SetHealthPercent(Troop.WFgrunt3, 100)
  SetHealthPercent(Troop.WFgrunt4, 100)
  SetHealthPercent(Troop.WFgrunt5, 100)
  SetHealthPercent(Troop.WFgrunt6, 100)
  Spawn(Troop.AIgruntA1)
  Spawn(Troop.AIgruntA2)
  Spawn(Troop.AIgruntA3)
  Spawn(Troop.AIgruntA4)
  SetActive(Troop.AIgruntA1, constant.INACTIVE)
  SetActive(Troop.AIgruntA2, constant.INACTIVE)
  SetActive(Troop.AIgruntA3, constant.INACTIVE)
  SetActive(Troop.AIgruntA4, constant.INACTIVE)
  Spawn(Troop.AIgruntB1)
  Spawn(Troop.AIgruntB2)
  Spawn(Troop.AIgruntB3)
  Spawn(Troop.AIgruntB4)
  Spawn(Troop.AIgruntB5)
  Spawn(Troop.AIgruntB6)
  EnableWeapon(Troop.AIgruntB1, 0)
  EnableWeapon(Troop.AIgruntB2, 0)
  EnableWeapon(Troop.AIgruntB3, 0)
  EnableWeapon(Troop.AIgruntB4, 0)
  EnableWeapon(Troop.AIgruntB5, 0)
  EnableWeapon(Troop.AIgruntB6, 0)
  SetActive(Troop.AIgruntB1, constant.INACTIVE)
  SetActive(Troop.AIgruntB2, constant.INACTIVE)
  SetActive(Troop.AIgruntB3, constant.INACTIVE)
  SetActive(Troop.AIgruntB4, constant.INACTIVE)
  SetActive(Troop.AIgruntB5, constant.INACTIVE)
  SetActive(Troop.AIgruntB6, constant.INACTIVE)
  Spawn(Troop.AIgruntD1)
  Spawn(Troop.AIgruntD2)
  Spawn(Troop.AIgruntD3)
  Spawn(Troop.AIgruntD4)
  Spawn(Troop.AIgruntE1)
  Spawn(Troop.AIgruntE2)
  Spawn(Troop.AIgruntE3)
  Spawn(Troop.AIgruntE4)
  Spawn(Troop.AIgruntF1)
  Spawn(Troop.AIgruntF2)
  Spawn(Troop.AIgruntF3)
  Spawn(Troop.AIgruntF4)
  Spawn(Troop.AIbazooka5)
  Spawn(Troop.AIbazooka6)
  Spawn(Troop.AIbazooka7)
  Spawn(Troop.AIbazooka8)
  Spawn(Ground_Vehicle.AIlighttank3)
  Spawn(Ground_Vehicle.AIlighttank4)
  Spawn(Ground_Vehicle.AIlighttank5)
  Spawn(Ground_Vehicle.AIlighttank6)
  Spawn(Ground_Vehicle.AIlighttank8)
  Spawn(Ground_Vehicle.WFlighttank1)
  SetCapturePointHeight(Capture_Point.dockCP, constant.ARMY_ANGLO, 100)
  SetInstallationOwner(Strategic_Installation.Docks, constant.ARMY_ANGLO)
  EnableControllerItem(constant.CONTROL_TOGGLE_MAP, 1, constant.PLAYER_ONE)
  EnableControllerItem(constant.CONTROL_PAUSE, 1, constant.PLAYER_ONE)
  SetCamera(Camera.player1cam)
  CameraFade(constant.FADE_IN, constant.WAIT, 1)
  WaitFor(UnfreezeDelay)
  UnfreezePlayer(constant.PLAYER_ONE)
  PauseTimerActive = 0
  PlayNoTroopsRemainingString = 1
  SetInvulnerable(flag.TYPE_SOLAR, 0)
  WaitFor(1)
  PhoneMessage(9, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.ShowBaseWaypoint03)
  ClearMessageQueue()
  PhoneMessage(94, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  repeat
    EndFrame()
  until CutsceneHelipadEnd == true
  repeat
    EndFrame()
  until IsInArea(GetPlayerUnit(), Map_Zone.lastbaseattacked)
  ClearMessageQueue()
  PhoneMessage(102, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  WaitFor(4)
  GoToArea(Ground_Vehicle.AIlighttank6, 10, 440, 5)
  GoToArea(Troop.AIgruntE1, 10, 420, 10)
  GoToArea(Troop.AIgruntE2, 10, 420, 10)
  GoToArea(Troop.AIgruntE3, 10, 420, 10)
  GoToArea(Troop.AIgruntE4, 10, 420, 10)
  repeat
    EndFrame()
  until 0 < NumItemsInArea(Map_Zone.docks, flag.TYPE_SOLAR)
  PhoneMessage(30, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  PhoneMessage(31, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  Spawn(Air_Vehicle.AIairtransport3)
  LandAirUnit(Air_Vehicle.AIairtransport3, -51, 479, constant.ORDER_FORCED)
  WaitFor(5)
  Spawn(Air_Vehicle.AIbomber4)
  GoToArea(Air_Vehicle.AIbomber4, -96, 472, 10)
  WaitFor(5)
  Spawn(Air_Vehicle.AIairtransport4)
  LandAirUnit(Air_Vehicle.AIairtransport4, -51, 512, constant.ORDER_FORCED)
  WaitFor(5)
  Spawn(Air_Vehicle.AIairtransport5)
  LandAirUnit(Air_Vehicle.AIairtransport5, -51, 449, constant.ORDER_FORCED)
  WaitFor(5)
  PhoneMessage(100, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
  WaitFor(4.75)
  if IsPassengerInUnit(GetPlayerUnit(), Capture_Point.dockCP) == false or 1 <= GetNumSeatsFree(Capture_Point.dockCP) then
    PauseTutorialJump = 1
    WaitFor(2)
    if GetCurrentMissionCompleted() ~= true or GetTutorialMode() ~= false then
      PhoneMessage(104, constant.ID_NONE, constant.ARMY_SOLAR, 0, SpriteID.CO_SE_Aqira_Happy, constant.PLAYER_ONE)
    end
  end
  RepeatCapturePointStrings = 1
end
