function Startup(owner)
  PlayEffect(Scripted_Effect.Ash, 3, 0, 0, 0)
  Despawn(Troop.CutsceneLegionGrunt01)
  Despawn(Troop.CutsceneLegionGrunt02)
  Despawn(Troop.CutsceneLegionGrunt03)
  Despawn(Troop.CutsceneLegionGrunt04)
  Despawn(Troop.CutsceneLegionGrunt05)
  Despawn(Troop.CutsceneLegionGrunt06)
  Despawn(Troop.CutsceneLegionChainVet01)
  Despawn(Troop.CutsceneLegionChainVet02)
  Despawn(Troop.CutsceneLegionMortarVet01)
  Despawn(Troop.CutsceneLegionMortarVet02)
  Despawn(Troop.CutsceneSolarGrunt01)
  Despawn(Troop.CutsceneSolarGrunt02)
  Despawn(Troop.CutsceneSolarGrunt03)
  Despawn(Troop.CutsceneSolarGrunt04)
  Despawn(Troop.CutsceneSolarAAVet01)
  Despawn(Troop.CutsceneSolarAAVet02)
  Despawn(Troop.CutsceneSolarBazookaVet01)
  Despawn(Troop.CutsceneSolarBazookaVet02)
end
